### ISSUE TITLE
Phobos

### ISSUE THREAD

**Issue by lexxingt0n** [BlesseNtumble/GalaxySpace#1]
Hi there!
Phobos is unreachable for us - we've tried reaching it on a Tier 2, 3 and 4 rocket, but neither works.
Renaming the Dimension ID made the button turn green but it remains non-interactive.
The dimension clearly exists, the blocks show up in NEI, yet the moon itself cannot be reached.

**Comment by BlesseNtumble** [comment]
Change the ID of Phobos on the server and on the client!

**Comment by lexxingt0n** [comment]
Thank you so much! That did work, however, on arrival on Phobos I spawned on block 900something, without the Landing ballons (or my rocket for that matter). It was easy enough to replace, just wanted to let you know this occured.
