### ISSUE TITLE
Краш сборки при добавлении GS1.1.1

### ISSUE THREAD

**Issue by AnDpeY1** [BlesseNtumble/GalaxySpace#100]
![2016-10-15 22-42-45 mods](https://cloud.githubusercontent.com/assets/22859987/19412923/ee789c12-9328-11e6-8004-ed894a8d726d.png)
[crash-2016-10-15_22.13.59-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/531369/crash-2016-10-15_22.13.59-client.txt)

**Comment by BlesseNtumble** [comment]
#101
