### ISSUE TITLE
[Server Crash] entering TcetiE GS 1.1.1/1.1.2

### ISSUE THREAD

**Issue by Dream-Master** [BlesseNtumble/GalaxySpace#105]
We crashing entering the new Planet in 1.1.1 TcetiE
Galacticraft Version 463 and
Modpack:  https://github.com/GTNewHorizons/NewHorizons

Crash log from the server:
https://gist.github.com/Dream-Master/37cdbed22a3a0d03335a1130f196fd2b

https://cdn.discordapp.com/attachments/231156436380549120/240571749761024010/crash-2016-10-25_22.14.23-server.txt

**Comment by Dream-Master** [comment]
@BlesseNtumble Any news or ideas here ?

**Comment by Dream-Master** [comment]
TCeti not have a config option for disabled this dimension so long no fix is available!

**Comment by BlesseNtumble** [comment]
I will add a configuration to disable.
You tried to delete a folder with the dimension?

**Comment by Dream-Master** [comment]
Ok will try it. The decorating error we had version before too if I remember right.

**Comment by Dream-Master** [comment]
@BlesseNtumble Yes still brocken.
When i start a fresh world and try to entering TCeti the games loads for ever get some Terrain gen files and crash but not close the game.

https://gist.github.com/Dream-Master/9da851edbb7a7eb22ea21f300ded1d39

GS 1.1.2
GC 463

Modpack: https://github.com/GTNewHorizons/NewHorizons

**Comment by Dream-Master** [comment]
@BlesseNtumble Any news here. When we can entering this planet without any crash?

**Comment by MeSoLost** [comment]
when entering this planet a runaway reaction occures resulting in EVERY chunk being generated and loaded at the same time.  i had a player go there and just a few minutes later the planet has 20,000 chunks loaded and continued to load more. (version 1.1.1) and i cant use 1.1.2 yet because it's unstable on europa BADLY

Absolutely love the look of this planet too btw ^_^ I wanna make an atlantis base here.

**Comment by Dream-Master** [comment]
@BlessNtumble
Ok I see you release a new version 1.1.3.
Is this issue fixed?

**Comment by BlesseNtumble** [comment]
I can not get a crash.
I is stable. At the other players too.

**Comment by Dream-Master** [comment]
@BlesseNtumble 
Ok i will test it then on my server with version 1.1.3 remove the world/dimesnion folder first.
