### ISSUE TITLE
[Question]Space Suit

### ISSUE THREAD

**Issue by Dream-Master** [BlesseNtumble/GalaxySpace#106]
@BlesseNtumble 
The new Space Suit you add in 1.1.1 did you needed it to wear on every Planet/Moon or only on some?
Did you add a new Potion or Effect if this suit is not detected?

**Comment by BlesseNtumble** [comment]
Fly to Venus and understand everything)

**Comment by Dream-Master** [comment]
Is this a Quiz?

**Comment by Drobac** [comment]
You need the Space Suit starting from venus, but some of the planets need it and some dont. Which of the higher tier ones need it?

**Comment by Dream-Master** [comment]
"Interesting discussion."
@BlesseNtumble So the Questins is not answered we have only a guess how it works.

**Comment by BlesseNtumble** [comment]
Protects from atmospheric pressure

**Comment by Dream-Master** [comment]
Ok but are there other Armors protec you as well like Droconic Evolution armor or Quantum Armor from IC2 or did you add a new type of damage which not supported by these mods?
