### ISSUE TITLE
Player movement check is wrong

### ISSUE THREAD

**Issue by LokeYourC3PH** [BlesseNtumble/GalaxySpace#11]
So, it seems that in the 1.0.7 update, you (BlesseNTumble) changed something about the player movement code or similar. At first, i thought some other mod caused this problem, but now (because of another problem i had, that was my fault) that i backdated to 1.0.6.1, it works fine. Basically, when i move to fast with a Modular Powersuit Armor or any other type of armor or entity or such, i am being stopped mid air, and the console then tells me that i "moved to quickly". I had to backdate GalaxySpace due to this, so it would be nice to have this fixed as soon as possible.

**Comment by BlesseNtumble** [comment]
Full mod list and you use KCauldron or vanilla Forge?

**Comment by LokeYourC3PH** [comment]
Here, the crashlog i previously had when having the same dimension ID for two planets. 

In it should be everything you need.

http://pastebin.com/axeyJGwY

**Comment by BlesseNtumble** [comment]
Redownload build. If again - create a new issue.
