### ISSUE TITLE
Непонятный краш...

### ISSUE THREAD

**Issue by Shurik1236** [BlesseNtumble/GalaxySpace#111]
С последней версией GS появился странный краш, а именно крашится когда ломаешь блок на луне!
Сначала подумал, может cofh core виноват (Сборка для теста генерации. Генерировал руду на луне). Убрал файлы генерации. Вроде ломается нормально, через 10 секунд опят этот же краш.
Без GS этой гадости нет.

http://pastebin.com/8xic1mWw

**Comment by BlesseNtumble** [comment]
Перекачайте билд.
