### ISSUE TITLE
Краш при выборе при выборе планеты для полёта

### ISSUE THREAD

**Issue by ghost** [BlesseNtumble/GalaxySpace#12]
Вылетают клиент и сервер (Cauldron), когда выбираю планету на карте. (GS 1.0.7 stable)
Это не зависит от уровня ракеты.
[crash-2016-02-24_18.39.12-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/144791/crash-2016-02-24_18.39.12-client.txt)
[crash-2016-02-24_14.58.42-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/144803/crash-2016-02-24_14.58.42-server.txt)

**Comment by BlesseNtumble** [comment]
Перекачайте билд.

**Comment by ghost** [comment]
Пробовал 3 раза, ничего не меняется

**Comment by BlesseNtumble** [comment]
Сейчас пробовали перекачать?
