### ISSUE TITLE
Invisible Mars

### ISSUE THREAD

**Issue by Valerik1999** [BlesseNtumble/GalaxySpace#121]
It seems that all blocks on Mars are missing textures since they're all invisible. I assume it's the problem with GalaxySpace. but in case it isn't, I'm gonna attach .minecraft folder for you, with the world that has this bug.
![2016-11-18_23 55 27](https://cloud.githubusercontent.com/assets/23238622/20444582/a70c7acc-ade2-11e6-87f1-82169a95f99e.png)

**Comment by BlesseNtumble** [comment]
Mars is not our content. This content GC3
