### ISSUE TITLE
Надел костюмчик...

### ISSUE THREAD

**Issue by Shurik1236** [BlesseNtumble/GalaxySpace#122]
Надел скафандр (Который от давления защищает), попал на Венеру - краш.
Да вообще на любую планету. Достаточно один элемент скафандра надеть, крашит и в мир не даёт зайти.
http://pastebin.com/cm8abbDt

**Comment by BlesseNtumble** [comment]
Известно. Фикс в 1.1.3

**Comment by SvEgiiVEteR** [comment]
@BlesseNtumble а в 1.1.1 есть такой баг? а то жду 1.1.4

**Comment by BlesseNtumble** [comment]
в 1,1,1 костюма еще нет.
