### ISSUE TITLE
Player Renderer Causes FPS Drops

### ISSUE THREAD

**Issue by nicksavoie** [BlesseNtumble/GalaxySpace#123]
I've realized that there is great fps lag from players and fastcraft/optifine have no effect. Other entities are fine. Players (Including armor stands) even when nude cause fps drops, which get much worse with special armours, backpacks, and weapons.
Example with armour stand: https://gyazo.com/dc2cb55789a54c9a60959d7798bedd28
Other players are able to replicate the issue: https://i.imgur.com/fIbKBor.png

Sampling: https://drive.google.com/file/d/0B4Oxvk4QgzFGbzZjMFlZRTdRdnc/view?usp=sharing
It would appear GalaxySpace is overriding player rendering before using forge, which then keeps reinstancing and parsing Obj models even when no special 3d models are present. This is incorrect, models should be instanced and parsed once then rendered many.

**Comment by m0nkm0nk** [comment]
Can confirm! Its almost unplayable with 1 or more players in your loaded chunk range. Reverted to 1.1.2.
You can also repro this one by placing Armourer's Workshop mannequin/doll. Place one minus 50% fps.
Place like 5/6 and get 10 fps :D

EDIT: seems to appear on older versions as well.. only not as bad as 1.13.

**Comment by SvEgiiVEteR** [comment]
same problem...
returned to the 1.1.1 version 
everything is OK

**Comment by zzApotheosis** [comment]
Yeah, I had issues with it too. I was actually going to post a bug report about misspelling the "Unknown Crystal" block, but then I saw this post and thought this was more important.

I'm going to uninstall this mod until it's fixed in 1.1.4 (hopefully soon). And I really like the way this mod was done, so please make it playable!

**Comment by BlesseNtumble** [comment]
Fixed in 1.1.4
