### ISSUE TITLE
some possible bugs I noticed in the t ceti system

### ISSUE THREAD

**Issue by PlatinumFox** [BlesseNtumble/GalaxySpace#124]
if you walk into a plant that has spawned on the islands bubbles appear and it slows you down as if you are underwater

![2016-12-09_22 38 20](https://cloud.githubusercontent.com/assets/23727270/21071009/104f6362-be61-11e6-8cd7-d315c07b3bcc.png)

going through taller plants on above water islands puts the player underwater

![2016-12-09_22 38 27](https://cloud.githubusercontent.com/assets/23727270/21071011/2e919408-be61-11e6-94c8-304d32bafc48.png)

just a rendering bug

![2016-12-09_22 40 33](https://cloud.githubusercontent.com/assets/23727270/21071012/3551b598-be61-11e6-8eb4-7f6d411e81fa.png)

**Comment by hypraman** [comment]
It seem like the plant blocks share the properties of water, but without being actual water. Think of them like they are different-textured water blocks... for now.
