### ISSUE TITLE
Интеграция Galaxy Space с Enviromine

### ISSUE THREAD

**Issue by Barkovskis** [BlesseNtumble/GalaxySpace#125]
Добрый день.
Возможно ли синхронизировать температуру и воздух Enviromine с теми же показателями GS.
К примеру чтобы одетый термокостюм позволял бы комфортно чувствовать себя в любом биоме. А Т2 термокостюм полностью ликвидировал эффект жары и холода от всех источников жары. Будь, то нахождение рядом с лавой или нахождение в лаве (при одетом зщитном костюме IC2)
Второй вопрос - качество воздуха enviromine.
Если одет Galaxy скафандр и в баллонах есть кислород, тогда раходовать кислород из баллонов как в безвоздушном пространстве.

**Comment by BlesseNtumble** [comment]
Температуру нужно синхронизировать в GC3.
