### ISSUE TITLE
Why doesn't it snow on Venus?!

### ISSUE THREAD

**Issue by basdxz** [BlesseNtumble/GalaxySpace#128]
https://en.wikipedia.org/wiki/Venus_snow
Any chance we can get some heavy metal sulfuric snow on Venus? Would greatly improve my immersion thanks.

**Comment by AndrewRG10** [comment]
Because the temperature is above 450 degrees celsius so sulfuric acid vaporises before it can even reach the ground. There shouldn't even be rain...
