### ISSUE TITLE
recipes not writen using ore dictionary

### ISSUE THREAD

**Issue by bear989** [BlesseNtumble/GalaxySpace#134]
when used with another mod such as Gregtech 5, your recipes using desh ingots arent craftable do to it calling for the Galacticraft desh ingot rather than ore:ingotDesh. the issue can be fixed on our side with a change to unification but if any other mod adds desh as well this will continue to be an issue.

**Comment by BlesseNtumble** [comment]
My addon is not have Desh ingots.
Desh - ingots from Galacticraft. It is necessary to write them.

**Comment by bear989** [comment]
https://imgur.com/a/LKmYA

**Comment by BlesseNtumble** [comment]
ok, i change craft.
