### ISSUE TITLE
Client crash on Moon - cotainer interact event

### ISSUE THREAD

**Issue by Cronosus** [BlesseNtumble/GalaxySpace#138]
Client crashing on moon, when trying to open container (example chest)
Tried on SP/MP 

crash report: http://cronos.wz.cz/mc/crash-2017-03-05_14.03.03-client.txt

**Comment by BlesseNtumble** [comment]
pastebin.com - Upload here your crash report

**Comment by Cronosus** [comment]
http://pastebin.com/5hCMNaTJ

**Comment by BlesseNtumble** [comment]
Update addon.

**Comment by Cronosus** [comment]
which addon?
edit: ah sorry, i downloading from curse, then i not see newest version..

**Comment by BlesseNtumble** [comment]
micdoodle8.com -> forum -> addons
