### ISSUE TITLE
(1.7.10) [GS 1.1.4] Client crash

### ISSUE THREAD

**Issue by Cronosus** [BlesseNtumble/GalaxySpace#139]
Client crashing, when i open map and clicking on planet Fronos from MorePlanets
http://pastebin.com/MSUyiamD
only GS+MP: http://pastebin.com/yYve0ka6

Caused only when i have GS and MP in pack.
incompatibility with Moreplanets?
MJRLegends says is caused by GS
https://github.com/SteveKunG/MorePlanets/issues/25

**Comment by BlesseNtumble** [comment]
Currently, there is no compatibility with the MP
