### ISSUE TITLE
Краш на каллисто

### ISSUE THREAD

**Issue by Shurik1236** [BlesseNtumble/GalaxySpace#14]
Краш если телепортироваться или вообще как то попасть на каллисто.
Краш: http://pastebin.com/Wm3yNWmK

И ещё, баг с ведром метана/неизвестной жидкости так и остался.

**Comment by LokeYourC3PH** [comment]
People could help you even more if you would at least also write it in english. I mean, if you want more universal help, you would be better off. Of course, i can still read the log.

**Comment by BlesseNtumble** [comment]
#15
