### ISSUE TITLE
Amun-Ra Mothership fully broken; thanks new interface.

### ISSUE THREAD

**Issue by AugiteSoul** [BlesseNtumble/GalaxySpace#140]
Your new interface breaks C O M P L E T E L Y those. I'd like to have a config for this. Oh, and i'm gonna remain in 1.1.3 until it's fixed.

**Comment by BlesseNtumble** [comment]
In the config you can disable the new map

**Comment by Kevadro** [comment]
I can't create motherships even if the new map is disabled, ¿other addons conflicts?
