### ISSUE TITLE
Краш игры когда я пытаюсь телепортировался, прилететь на любую планету

### ISSUE THREAD

**Issue by KiraLinux** [BlesseNtumble/GalaxySpace#141]
[crash-2017-03-07_22.56.26-client.zip](https://github.com/BlesseNtumble/GalaxySpace/files/825664/crash-2017-03-07_22.56.26-client.zip)

установленная версия мода GS:
GalaxySpace-1.1.4 STABLE 

GC:
Galacticraft-Planets-1.7-3.0.12.468.jar	
GalacticraftCore-1.7-3.0.12.468.jar	
MicdoodleCore-1.7-3.0.12.468.jar

остальное в архиве

**Comment by KiraLinux** [comment]
[crash-2017-03-07_23.22.52-client.zip](https://github.com/BlesseNtumble/GalaxySpace/files/825722/crash-2017-03-07_23.22.52-client.zip)

попробовал еще раз , и снова

**Comment by BlesseNtumble** [comment]
Перекачайте и отпишитесь, пропала ли ошибка.

**Comment by KiraLinux** [comment]
работает но проблемы со звуком и вроде утечка памяти, вся память заполнилась и в итоге игра зависла 
пришлось ее закрыть ¯ \ _ (ツ) _ / ¯

проблема со звуком мода DynamicSurroundings-1.7.10-1.0.5.9

6 гигов оперативки выделено игре, всего 10 гигов в системе 
вот архив 
[fml-client-latest.zip](https://github.com/BlesseNtumble/GalaxySpace/files/827294/fml-client-latest.zip)

**Comment by BlesseNtumble** [comment]
Ну звуки мы не затрагиваем.
Закрыто.
