### ISSUE TITLE
Краш сервера

### ISSUE THREAD

**Issue by Scrik** [BlesseNtumble/GalaxySpace#143]
Краш сервера,понять из-за чего он, не могу
http://pastebin.com/s8KCGain
KCauldron #201 Forge 1614
Galacticraft 3.0.12.464
GalaxySpace 1.1.3
AE2 rv3 beta 6

Если это было исправлено в новых версиях GC или GS ,то сообщите пожалуйста об этом

**Comment by origamerpro** [comment]
Это Авторы мода не предусмотрели переполнение буфера стола, аплайд сует в стол больше чем он может вместить, заказывал фикс отдельно. Я про эту ошибку уже писал в вк группе.
