### ISSUE TITLE
GS 1.14 New Space biomes have no config options to change ID

### ISSUE THREAD

**Issue by Dream-Master** [BlesseNtumble/GalaxySpace#144]
In GS 1.14 i font have config options for the following Biomes:
``189,SpacePartiallySubmerged,0.5,0.0,0.1,-0.2,0.1,"COLD, DRY, SPOOKY, DEAD, MAGICAL, FOREST",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS
190,SpaceLowIslands,0.5,0.0,0.1,0.2,0.3,"COLD, DRY, SPOOKY, DEAD, MAGICAL",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS
191,SpaceRockyWaters,0.5,0.0,0.1,0.1,0.8,"COLD, DRY, SPOOKY, DEAD, END, MAGICAL",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS
192,SpaceMidHills,0.5,0.0,0.1,1.0,0.5,"COLD, DRY, SPOOKY, DEAD, MAGICAL, FOREST",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS
193,SpaceHighPlateaus,0.5,0.0,0.1,1.5,0.025,"COLD, DRY, SPOOKY, DEAD, MAGICAL, WASTELAND",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS
194,SpaceLowHills,0.5,0.0,0.1,0.45,0.3,"COLD, DRY, SPOOKY, DEAD",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS
195,SpaceMidPlains,0.5,0.0,0.1,0.2,0.2,"COLD, DRY, SPOOKY, DEAD",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS
196,SpaceLowPlains,0.5,0.0,0.1,0.125,0.05,"COLD, DRY, CONIFEROUS, SPOOKY, DEAD, FOREST, SNOWY",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS
197,SpaceDeepOceans,0.5,0.0,0.1,-1.8,0.1,"COLD, DRY, SPOOKY, DEAD",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS
198,SpaceOceans,0.5,0.0,0.1,-1.0,0.1,"COLD, DRY, SPOOKY, DEAD",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS
199,SpaceShallowWaters,0.5,0.0,0.1,-0.5,0.0,"COLD, DRY, SPOOKY, DEAD",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS
200,SpaceDefault,0.5,0.0,0.1,0.1,0.2,"COLD, DRY, SPOOKY, DEAD, RIVER, SNOWY",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS``

I have many mods with different Biome in my pack and some i can't change so please give me a config options for the new Biomes you add in 1.14. The old ones pre 1.13 i can configure well.

Thanks

**Comment by Dream-Master** [comment]
@BlesseNtumble any news here?

**Comment by Dream-Master** [comment]
@BlesseNtumble sadly i can't writen/speak russian to get your attention.

**Comment by SirFell** [comment]
Переведу для Дрима по его просьбе:

"В галактик спейсе 1.14 у меня отсутствуют данные биомы в конфиге:
`189,SpacePartiallySubmerged,0.5,0.0,0.1,-0.2,0.1,"COLD, DRY, SPOOKY, DEAD, MAGICAL, FOREST",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS 190,SpaceLowIslands,0.5,0.0,0.1,0.2,0.3,"COLD, DRY, SPOOKY, DEAD, MAGICAL",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS 191,SpaceRockyWaters,0.5,0.0,0.1,0.1,0.8,"COLD, DRY, SPOOKY, DEAD, END, MAGICAL",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS 192,SpaceMidHills,0.5,0.0,0.1,1.0,0.5,"COLD, DRY, SPOOKY, DEAD, MAGICAL, FOREST",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS 193,SpaceHighPlateaus,0.5,0.0,0.1,1.5,0.025,"COLD, DRY, SPOOKY, DEAD, MAGICAL, WASTELAND",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS 194,SpaceLowHills,0.5,0.0,0.1,0.45,0.3,"COLD, DRY, SPOOKY, DEAD",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS 195,SpaceMidPlains,0.5,0.0,0.1,0.2,0.2,"COLD, DRY, SPOOKY, DEAD",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS 196,SpaceLowPlains,0.5,0.0,0.1,0.125,0.05,"COLD, DRY, CONIFEROUS, SPOOKY, DEAD, FOREST, SNOWY",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS 197,SpaceDeepOceans,0.5,0.0,0.1,-1.8,0.1,"COLD, DRY, SPOOKY, DEAD",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS 198,SpaceOceans,0.5,0.0,0.1,-1.0,0.1,"COLD, DRY, SPOOKY, DEAD",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS 199,SpaceShallowWaters,0.5,0.0,0.1,-0.5,0.0,"COLD, DRY, SPOOKY, DEAD",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS 200,SpaceDefault,0.5,0.0,0.1,0.1,0.2,"COLD, DRY, SPOOKY, DEAD, RIVER, SNOWY",galaxyspace.SolarSystem.core.world.gen.biome.BiomeGenSpaceGS`

У меня много модов с разными биомами в модпаке и некоторые не могут быть изменены, пожалуйста дай мне конфиг для новых биомов ты добавил в 1.14. Все биомы до 1.13 я могу настраивать.

Спасибо."

**Comment by BlesseNtumble** [comment]
The biomes in 1.1.4 were changed and unchanged to the end.

**Comment by Dream-Master** [comment]
Yes i find out that allready (Space Biome ID  -1 till - 12)but adding a new config option for each biome would be much more easy for pack makers.

**Comment by BlesseNtumble** [comment]
Naturally. This will be fixed in 1.1.5

**Comment by Dream-Master** [comment]
cool
