### ISSUE TITLE
GS Spacesuit Jetpack

### ISSUE THREAD

**Issue by kokochicken** [BlesseNtumble/GalaxySpace#146]
The spacesuit jetpack causes me to take massive damage, if i fly up even 1-5 blocks and then fall i take 5hearts+ dmg

**Comment by leptun** [comment]
I can confirm what he said.
It's really annoying that I cannot use this jetpack because i take fall damage.

One way to not take damage is by having a bucket of water with you and placing it down right before you land.

I hope this bug gets fixed in v1.1.5
