### ISSUE TITLE
Новые кислородные баллоны

### ISSUE THREAD

**Issue by Shurik1236** [BlesseNtumble/GalaxySpace#149]
Вообщем в ВК один человек просил добавить более вместительные баллоны, я тут придумал кое что по интереснее...
1. Баллоны увеличенной ёмкости. Вмещающие по 3000, 4000, 5000. Доступны с определённых планет.
2. Баллоны EPP (Environmental Protection Pack). Более продвинутые и дорогие версии баллонов.
Эти баллоны пассивно производят кислород. Если игрок находится в пригодной для дыхания среде, то восстанавливают запас кислорода. В остальных случаях кислород тратится медленнее.
Но в отличии от простых баллонов содержат значительно меньше кислорода.
Уровень:
Первый. 300 ед. кислорода, затраты снижены на 20%
Второй. 450 ед. кислорода, затраты снижены на 40%
Третий. 600 ед. кислорода, затраты снижены на 60%
Четвёртый. 750 ед. кислорода, затраты снижены на 80%
Пятый. 300 ед. кислорода, Кислород не тратится и восстанавливается всегда. Для творческого режима.
Хотя для такого баллона я бы сделал очень сложный рецепт. Как награда за полёт к дальним планетам очень даже хорошо.

Возможно такое реализовать?

**Comment by BlesseNtumble** [comment]
Вполне.
