### ISSUE TITLE
Crash related to using GC3 machines on the moon

### ISSUE THREAD

**Issue by herp21** [BlesseNtumble/GalaxySpace#150]
Good day, it appears that anytime I would open an oxygen collector or an oxygen sealer, the moment I right click either of these blocks, my game will freeze and crash within a couple seconds. I can not confirm that it is with all blocks in GC3 but I will keep trying. Here is the crash report. 

http://pastebin.com/5mbBDehD

Thank you for taking the time to look.

**Comment by herp21** [comment]
Also worthy to note, it appears any block i try to use that is placed on the moon makes me crash with the same report. I crashed this time while trying to install an AE2 quantum bridge singularity.

**Comment by BlesseNtumble** [comment]
Update addon. Fixed in 1.1.3-1.1.4
