### ISSUE TITLE
Crash when update from GS 1.1.3 to 1.1.4 with an existing world.

### ISSUE THREAD

**Issue by Dream-Master** [BlesseNtumble/GalaxySpace#152]
We get issues and crahes  in my Modpack when updating Gs from 1.1.3 to 1.1.4.

Modpack: https://github.com/GTNewHorizons/NewHorizons

Crash Log/Issue: https://github.com/GTNewHorizons/NewHorizons/issues/1256
https://gist.github.com/Dream-Master/cc31bbec6273172cac534915596a9e96

**Comment by SirFell** [comment]
"При обновлении ГС с 1.1.3 до 1.1.4 мы получаем краш репорты.
Модпак: https://github.com/GTNewHorizons/NewHorizons
Ошибка: GTNewHorizons/NewHorizons#1256
Краш лог: https://gist.github.com/Dream-Master/cc31bbec6273172cac534915596a9e96 "

Также дрим попросил тестовую версию мода с дэбаг логами ошибок чтоб найти причину так как мод с закрытым исходным кодом и они не могут ничего поделать с ошибкой без посторонней помощи
