### ISSUE TITLE
client crash (1.7.10) [GS 1.1.4]

### ISSUE THREAD

**Issue by Cronosus** [BlesseNtumble/GalaxySpace#153]
Hello
one of player on my server has this crash:
https://paste.ee/p/nUzxi

caused everytime he make something in his home, not caused to someone alse in the same location

can you please help?
thanks in advance

**Comment by Dream-Master** [comment]
same here
https://github.com/BlesseNtumble/GalaxySpace/issues/152
@BlesseNtumble so we are not the only one get this crash

**Comment by DamnuDen** [comment]
Also have same bug.
Here is crash log if it helps
[crash-2017-06-14_19.07.07-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/1076237/crash-2017-06-14_19.07.07-client.txt)
