### ISSUE TITLE
Краш сервера 1.7.10

### ISSUE THREAD

**Issue by fxusers** [BlesseNtumble/GalaxySpace#155]
[crash-2017-04-10_00.13.44-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/908546/crash-2017-04-10_00.13.44-server.txt)
Установлены моды appliedenergistics2-rv3-beta-6-client, GalaxySpace-1.1.3 STABLE, Galacticraft-Planets-1.7-3.0.12.464, GalacticraftCore-1.7-3.0.12.464
Вылетает при попытке запустить автокрафт "Прочных ракетных стабилизаторов".
Вылетает не всегда, обычно при запуске автокрафта через беспроводной терминал из АЕ.
Подобная ошибка описывалась в этой теме
https://github.com/micdoodle8/Galacticraft/issues/2345

**Comment by BlesseNtumble** [comment]
Обновите GalactiCraft3.
Был фикс в билдах 480+

**Comment by fxusers** [comment]
Поставил билд 485, ошибка осталась
[crash-2017-04-11_21.40.30-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/914101/crash-2017-04-11_21.40.30-server.txt)
