### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TwiRush** [BlesseNtumble/GalaxySpace#16]
---- Minecraft Crash Report ----
// Oops.

Time: 27/02/16 18:08
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
    at codechicken.nei.FastTransferManager.throwAll(FastTransferManager.java:327)
    at codechicken.nei.NEIController.handleSlotClick(NEIController.java:155)
    at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:464)
    at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:581)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at codechicken.nei.FastTransferManager.throwAll(FastTransferManager.java:327)
    at codechicken.nei.NEIController.handleSlotClick(NEIController.java:155)
    at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:464)
    at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:581)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiCrafting

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [GCEntityClientPlayerMP['TwiRush'/46, l='MpServer', x=-201.94, y=65.62, z=449.35]]
    Chunk stats: MultiplayerChunkCache: 289, 298
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (36,64,73), Chunk: (at 4,4,9 in 2,4; contains blocks 32,0,64 to 47,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 128783 game time, 162982 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 50 total; [EntitySkeleton['Skeleton'/65280, l='MpServer', x=-188.50, y=51.00, z=511.50], EntityZombie['Zombie'/65282, l='MpServer', x=-195.88, y=52.00, z=519.69], EntityCreeper['Creeper'/65284, l='MpServer', x=-192.00, y=53.00, z=515.38], EntitySkeleton['Skeleton'/65286, l='MpServer', x=-191.50, y=51.00, z=513.50], EntityCreeper['Creeper'/65288, l='MpServer', x=-193.50, y=53.00, z=518.50], EntityZombie['Zombie'/530, l='MpServer', x=-32.57, y=-46.62, z=-1.33], EntityBat['Bat'/64915, l='MpServer', x=-123.34, y=23.00, z=381.50], EntityBat['Bat'/64916, l='MpServer', x=-124.34, y=23.00, z=380.13], EntityItem['item.item.reeds'/54423, l='MpServer', x=-216.19, y=63.13, z=432.84], EntitySheep['Sheep'/49439, l='MpServer', x=-151.38, y=67.00, z=529.25], EntitySkeleton['Skeleton'/53673, l='MpServer', x=-162.50, y=30.00, z=486.50], EntityCow['Cow'/53421, l='MpServer', x=-228.22, y=67.00, z=412.53], EntitySkeleton['Skeleton'/62385, l='MpServer', x=-184.91, y=19.39, z=468.38], GCEntityClientPlayerMP['TwiRush'/46, l='MpServer', x=-201.94, y=65.62, z=449.35], EntityCreeper['Creeper'/62388, l='MpServer', x=-261.09, y=64.00, z=397.34], EntityCreeper['Creeper'/62389, l='MpServer', x=-245.50, y=64.00, z=395.50], EntityWitch['Witch'/62393, l='MpServer', x=-143.50, y=18.00, z=472.50], EntityWitch['Witch'/62394, l='MpServer', x=-147.50, y=18.00, z=475.50], EntityBat['Bat'/49339, l='MpServer', x=-239.50, y=50.10, z=462.25], EntityCreeper['Creeper'/62395, l='MpServer', x=-130.50, y=75.00, z=429.50], EntitySheep['Sheep'/66, l='MpServer', x=-274.81, y=68.00, z=444.78], EntityCow['Cow'/49346, l='MpServer', x=-225.06, y=74.00, z=512.13], EntitySheep['Sheep'/67, l='MpServer', x=-280.44, y=75.00, z=460.66], EntitySheep['Sheep'/68, l='MpServer', x=-277.81, y=73.00, z=472.44], EntitySheep['Sheep'/69, l='MpServer', x=-285.44, y=75.00, z=456.66], EntitySheep['Sheep'/70, l='MpServer', x=-277.38, y=67.00, z=481.53], EntitySheep['Sheep'/83, l='MpServer', x=-269.66, y=66.00, z=412.53], EntitySheep['Sheep'/84, l='MpServer', x=-277.19, y=75.00, z=456.19], EntityChicken['Chicken'/85, l='MpServer', x=-261.63, y=73.00, z=461.41], EntityMinecartChest['entity.MinecartChest.name'/86, l='MpServer', x=-262.50, y=20.50, z=471.50], EntityMinecartChest['entity.MinecartChest.name'/87, l='MpServer', x=-260.50, y=24.34, z=471.50], EntityCow['Cow'/49751, l='MpServer', x=-229.13, y=67.00, z=401.88], EntityMinecartChest['entity.MinecartChest.name'/88, l='MpServer', x=-269.50, y=22.50, z=486.50], EntitySheep['Sheep'/89, l='MpServer', x=-260.94, y=73.00, z=482.97], EntityZombie['Zombie'/58208, l='MpServer', x=-146.66, y=48.00, z=497.34], EntityCreeper['Creeper'/60896, l='MpServer', x=-154.59, y=63.00, z=484.00], EntityBat['Bat'/60642, l='MpServer', x=-142.00, y=14.00, z=388.44], EntitySheep['Sheep'/99, l='MpServer', x=-248.34, y=64.00, z=396.38], EntitySheep['Sheep'/100, l='MpServer', x=-247.16, y=64.00, z=397.50], EntitySheep['Sheep'/48870, l='MpServer', x=-275.78, y=70.00, z=498.66], EntitySheep['Sheep'/48871, l='MpServer', x=-274.47, y=70.00, z=504.63], EntitySheep['Sheep'/48872, l='MpServer', x=-275.13, y=70.00, z=500.09], EntityCow['Cow'/111, l='MpServer', x=-227.09, y=67.00, z=410.53], EntityCow['Cow'/112, l='MpServer', x=-228.25, y=67.00, z=411.16], EntitySheep['Sheep'/113, l='MpServer', x=-236.44, y=73.00, z=455.53], EntityChicken['Chicken'/49009, l='MpServer', x=-253.53, y=77.00, z=496.75], EntityMinecartChest['entity.MinecartChest.name'/114, l='MpServer', x=-235.50, y=25.50, z=469.50], EntityChicken['Chicken'/116, l='MpServer', x=-243.47, y=71.00, z=485.47], EntityBat['Bat'/57205, l='MpServer', x=-136.91, y=52.06, z=512.75], EntitySlime['Slime'/123, l='MpServer', x=-218.63, y=17.00, z=438.31]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 80917320 bytes (77 MB) / 715530240 bytes (682 MB) up to 3207856128 bytes (3059 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D1 16 mods loaded, 16 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.2.9} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.2.15} [Not Enough Items](NotEnoughItems-1.7.10-1.0.2.15-universal %281%29.jar) 
    UCHIJAAAA   OpenModsCore{0.9.1} [OpenModsCore](minecraft.jar) 
    UCHIJAAAA   adventurebackpack{1.7.10-0.8b} [Adventure Backpack](adventurebackpack-1.7.10-0.8c.jar) 
    UCHIJAAAA   chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCHIJAAAA   eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHIJAAAA   GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.441.jar) 
    UCHIJAAAA   GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.441.jar) 
    UCHIJAAAA   GalaxySpace{1.0.7} [GalaxySpace](GalaxySpace-1.0.7+STABLE.jar) 
    UCHIJAAAA   OpenMods{0.9.1} [OpenMods](OpenModsLib-1.7.10-0.9.1.jar) 
    UCHIJAAAA   OpenBlocks{1.5.1} [OpenBlocks](OpenBlocks-1.7.10-1.5.1.jar) 
    UCHIJAAAA   ReiMinimap{1.7.10} [Rei's Minimap](Reis-Minimap-Mod-1.7.10.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.91' Renderer: 'GeForce 610M/PCIe/SSE2'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    Stencil buffer state: Function set: GL30, pool: disabled, bits: 0
    Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce 610M/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.91, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
OptiFine Version: OptiFine_1.7.10_HD_U_D1
Render Distance Chunks: 8
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
OpenGlVersion: 4.5.0 NVIDIA 358.91
OpenGlRenderer: GeForce 610M/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 2
```

**Comment by BlesseNtumble** [comment]
Are you sure that this is a problem in addon, and not in CodeChikenCore?

**Comment by LokeYourC3PH** [comment]
Update your CodeChickenCore, it is HEAVILY outdated.
