### ISSUE TITLE
spacestations can't be created 

### ISSUE THREAD

**Issue by Fekalista** [BlesseNtumble/GalaxySpace#161]
EN: You are unable to create a new spacestation while this moc is installed. 

CZ: Když chci vytvořit vesmírnou stanici na jakékoliv planetě, tak se nic nestane. Po odinstalaci modu jde vytvořit.

**Comment by BlesseNtumble** [comment]
screenshot and localization in minecraft?

**Comment by Fekalista** [comment]
I have a video. I tried running mc just with forge, galacticraft and galaxyspace. It does't work even if you use spaceship and have items in your inventory. https://www.youtube.com/watch?v=KdcHJPiJVbU&feature=youtu.be

**Comment by CyanideCarrot** [comment]
It works fine if you set `B:enableNewGalaxyMap=` to false, it seems to be related to the planet information

**Comment by BlesseNtumble** [comment]
Will be fixed in 1.1.5
