### ISSUE TITLE
GalaxySpace Rockets/Dimensions don't play nice with the launch controller

### ISSUE THREAD

**Issue by zzApotheosis** [BlesseNtumble/GalaxySpace#164]
Using version 1.1.4. I noticed that the rockets and worlds from GalaxySpace don't properly utilize the launch controller in the base Galacticraft mod. When I tried to launch to Io with a Tier 4 rocket using a launch controller, I ended up landing on the planet with the balloon lander instead of landing regularly with the rocket.

**Comment by BlesseNtumble** [comment]
#162
