### ISSUE TITLE
Galaxy map - Display problem

### ISSUE THREAD

**Issue by fronczek7f** [BlesseNtumble/GalaxySpace#167]
Hi. I have a problem with displaying information about the planets in the galaxy map. I can see the list of planets of each circuit, but when I want to see a planete on the map, I do not display anything. The same is true with the moons.

Images:
http://imgur.com/bJYobeg <- what can i see
http://imgur.com/8fu6W6Z <- nothing display
http://imgur.com/m7TFThc <- nothing display

**Comment by BlesseNtumble** [comment]
GC3 version?

**Comment by fronczek7f** [comment]
GalacticraftCore-1.7-3.0.12.498

**Comment by BlesseNtumble** [comment]
try on 501 version

**Comment by fronczek7f** [comment]
still not working, I noticed that this is only happening when I'm on Earth on the other planets and the moons map is displayed normally

**Comment by fronczek7f** [comment]
I am sorry that after this time I am coming back to this problem, but I did not have time and willingness to check over 170 mods

I found a problem for this "issue", I use Stellar Api and Stellar Sky mod and if this mod is installed my galaxy map shows me information only for stars, other information about planets is not showing, if I switch off this map in config and back to default Galacticraft galaxy map everything works normally, I mean I can travel to other planets, would it be possible to create compatibility with Stellar Api and Stellar Sky?

**Comment by BlesseNtumble** [comment]
Version GS - 1.2.1?

**Comment by fronczek7f** [comment]
yes, and GalacticraftCore-1.7-3.0.12.502

**Comment by BlesseNtumble** [comment]
Is the normal map (GC3) working normally?
