### ISSUE TITLE
GalaxySpace: Virus?

### ISSUE THREAD

**Issue by MadCrafter** [BlesseNtumble/GalaxySpace#168]
Okay, so Google and Ikarus detected the mod as Trojan.Java.Adwind. So please, anyone of you please say that this is a false positive. Can someone maybe show the piece of code that can be detected as a virus please? I'm a little bit scared right now...

**Comment by BlesseNtumble** [comment]
https://www.virustotal.com/ru/file/f6093f593a0769a7a88451e63c60a9a08aa3b82c2b3306141a6363005f7d3f74/analysis/1497630741/
Some antiviruses can swear on obfuscation, because they can not read part of the code.
Therefore, they consider it a virus.
