### ISSUE TITLE
Planet screen error.

### ISSUE THREAD

**Issue by Nekichkekich** [BlesseNtumble/GalaxySpace#176]
When I'm trying to fly to another planet in MULTILAYER, it says that my rocket LvL is too low and all LvL indicators are red, I can't even fly back at earth, [I was using LvL 8 rocket]. But in singleplayer everything works fine. And in LAN game only server host can fly to other planets.

**Comment by BlesseNtumble** [comment]
version?

**Comment by Nekichkekich** [comment]
Galaxy space 1.1.6
Galactic craft 502, but when I used 501 it didn't work too.
Minecraft 1.7.10
