### ISSUE TITLE
I get a crash after I install the latest version of Galaxyspace.

### ISSUE THREAD

**Issue by ghost** [BlesseNtumble/GalaxySpace#177]
Here is the log: https://pastebin.com/S2Q0L8WD
Also my mod list in image: https://imgur.com/a/AGNQw
If you need anything else, just ask.

EDIT: Found my fix in the closed issues. sorry for creating a new issue without checking.

**Comment by ZTWarz** [comment]
I'm sorry. I posted this on the wrong github page. I meant to post it on the Galaxyspace page lol
