### ISSUE TITLE
[Minor Bug] GS Schematic Glitch

### ISSUE THREAD

**Issue by CaveMiner1215** [BlesseNtumble/GalaxySpace#179]
Edit:  You won't have to pay as much attention to this any more.

I encountered a series of problems when I was playing on my singleplayer survival world.

This is what happened:  I decided to add my GalaxySpace schematics to my NASA workbench.  It was going well until I noticed that the schematic for the heavy booster was instead unlocking the recipe for the durable rocket vanes.  I happened to have a second heavy booster schematic, so I tried to input that.  It consumed the schematic, but nothing changed; I still had no recipe for the heavy booster.  I thought that this was a simple bug, and that the durable rocket vane schematic would, in turn, unlock the heavy booster recipe.  So I went back to Ceres and acquired the durable rocket vane schematic from a dungeon.  When I got home and right-clicked the NASA workbench, my game froze, and then crashed.  It may have been because I right clicked it with a draconic sword from draconic evolution, but I don't know.  Here is the crash report: 
[Crash1.txt](https://github.com/BlesseNtumble/GalaxySpace/files/1272541/Crash1.txt)

After this, I reloaded my game, and then my world.  I was able to right click the NASA workbench, but when I tried to scroll over to a GalaxySpace recipe on the workbench, my game crashed immediately.  This crash is more obviously a problem with GalaxySpace:
[Crash2.txt](https://github.com/BlesseNtumble/GalaxySpace/files/1272545/Crash2.txt)

This issue is a major bug and needs to be fixed.

Forge Version Used: 10.13.4.1558
Galacticraft Version Used: 3.0.12.502
GalaxySpace Version Used: 1.1.7

**Comment by CaveMiner1215** [comment]
Well...I tried it again, and this time it didn't crash.  But I was right: the durable rocket vane schematic and the heavy booster schematic are swapped.  This is now just a minor bug.

**Comment by BlesseNtumble** [comment]
You have other addons?

**Comment by CaveMiner1215** [comment]
No Galacticraft addons other that GalaxySpace are installed.
