### ISSUE TITLE
Crash on launching to Mars Space Station on lastest Galaticraft

### ISSUE THREAD

**Issue by SxvxgeUser** [BlesseNtumble/GalaxySpace#18]
See Crash Report: http://pastebin.com/CufPcaAC

Basically, when I updated to lastest Galacticraft build (atm 446), when ever I launch to Mars Space Station, I crash with the log linked above. IDK if this is something with the new build of Galacticraft cause the older builds (like 441 and 442) it works fine. I think 445 and 446 changed some code with Mars and such.

NOTE: I tried this without any mods except GalaxySpace and last Galacticraft build and same thing happens, just if you think it's conflict. Kinda a major issue! -Kody

**Comment by dimion123** [comment]
I confirm Kqdy's crash report. The same happens to me with the latest Galaxy Space on 446. Works fine on 442.

**Comment by LokeYourC3PH** [comment]
Happens to me to, fast fix please!

http://pastebin.com/6Z7sasd1
