### ISSUE TITLE
ocean biomes are replaced by mushroom island

### ISSUE THREAD

**Issue by traso56** [BlesseNtumble/GalaxySpace#183]
after digging this problem i founmd that removing the latest galaxyspace (1.1.8) it solves the issue if you need data of any kind tell me

when i create a world with 1.1.8 the oceans don't generate but instead moshroom islands 
doesn't happen with 1.1.7

tried with galacticraft 501 and 502 for MC 1.7.10

**Comment by BlesseNtumble** [comment]
in Overworld?

**Comment by m0nkm0nk** [comment]
Wondering, you use ONLY galacticraft and Galaxyspace? Or some extra biomes mod like Biomes o plenty?

**Comment by traso56** [comment]
i used BOP but removed it because it crashed yes it is in the OW and using galaxy space 1.1.7 instead of 1.1.8 solved it the only biomes added by mods are the oil biomes by buildcraft i think

**Comment by BlesseNtumble** [comment]
Check you biomes id in configs. They must not coincide.
