### ISSUE TITLE
Random CTD with latest Galaxyspace 1.1.8

### ISSUE THREAD

**Issue by m0nkm0nk** [BlesseNtumble/GalaxySpace#184]
Seems when opening inventory/chests with the latest Galaxyspace, Minecraft starts random crashing to desktop. All the players on my server noticed did. Had to rollback to 1.1.7.

https://pastebin.com/NdcfFnS4

**Comment by m0nkm0nk** [comment]
Question, is this fixed in 1.1.9?

**Comment by BlesseNtumble** [comment]
yes

**Comment by m0nkm0nk** [comment]
Still having the same issue in 1.1.9.

https://pastebin.com/BtdegkTA
