### ISSUE TITLE
"ArrayIndexOutOfBoundsException" crash (1.7.10) gs version = 1.1.8 STABLE

### ISSUE THREAD

**Issue by lAimBotl** [BlesseNtumble/GalaxySpace#187]
[crash-2017-09-30_21.24.14-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/1346851/crash-2017-09-30_21.24.14-client.txt)

Crashed when moving through creative tabs.

**Comment by m0nkm0nk** [comment]
Same goes for 1.1.9 when scrolling in NEI.
https://pastebin.com/BtdegkTA

**Comment by BlesseNtumble** [comment]
Have you tested in the new world?

**Comment by m0nkm0nk** [comment]
Doing that right now. All my server players crash with the same error.

**Comment by m0nkm0nk** [comment]
So, started a new LAN server and let some friends join.
After 5 minutes I searched in NEI for "galaxy" and instant client crash.

Crashlog: https://pastebin.com/DuakruLA
Latestlog: https://pastebin.com/NKyveN0f

**Comment by BlesseNtumble** [comment]
Try this version:
https://yadi.sk/d/Nvu0QfYD3PBJDW

**Comment by m0nkm0nk** [comment]
Thanks, will try tomorrow <3

Edit; still crashing :(

**Comment by robvanbentem** [comment]
The issue still persists with the version you provided: https://pastebin.mozilla.org/9071477

**Comment by m0nkm0nk** [comment]
BlesseNtumble, do you need additional info? Or anything else I can help with. Would be nice to get this fixed 💃

**Comment by BlesseNtumble** [comment]
Try to wipe Proteus
