### ISSUE TITLE
CRASH WHEN MINING RAINBOW CRYSTAL

### ISSUE THREAD

**Issue by tonimark** [BlesseNtumble/GalaxySpace#193]
I was exploring a planet called "bernada c"
reproduce 1.travel to bernada c planet 
2. get a tinker's construction manyully pickaxe and in survival mod mine a rainbow crystal
then I mined a rainbow crystal vie TC manyully pickaxe and then happens here is the crash log:---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 28/10/2017 3:04 μμ
Description: Unexpected error

java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at galaxyspace.BarnardsSystem.planets.barnardaC.blocks.BarnardaCBlockCrystal.func_149745_a(Unknown Source)
	at net.minecraft.block.Block.func_149679_a(Block.java:1000)
	at net.minecraft.block.Block.quantityDropped(Block.java:1462)
	at tconstruct.tools.TActiveOmniMod.autoSmelt(TActiveOmniMod.java:99)
	at tconstruct.tools.TActiveOmniMod.beforeBlockBreak(TActiveOmniMod.java:66)
	at tconstruct.library.tools.ToolCore.onBlockStartBreak(ToolCore.java:571)
	at tconstruct.library.tools.HarvestTool.onBlockStartBreak(HarvestTool.java:43)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78751_a(PlayerControllerMP.java:96)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78759_c(PlayerControllerMP.java:247)
	at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1357)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1967)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassCastException: bootstrap method failed to produce a CallSite
	at java.lang.invoke.CallSite.makeSite(CallSite.java:332)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at galaxyspace.BarnardsSystem.planets.barnardaC.blocks.BarnardaCBlockCrystal.func_149745_a(Unknown Source)
	at net.minecraft.block.Block.func_149679_a(Block.java:1000)
	at net.minecraft.block.Block.quantityDropped(Block.java:1462)
	at tconstruct.tools.TActiveOmniMod.autoSmelt(TActiveOmniMod.java:99)
	at tconstruct.tools.TActiveOmniMod.beforeBlockBreak(TActiveOmniMod.java:66)
	at tconstruct.library.tools.ToolCore.onBlockStartBreak(ToolCore.java:571)
	at tconstruct.library.tools.HarvestTool.onBlockStartBreak(HarvestTool.java:43)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78751_a(PlayerControllerMP.java:96)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78759_c(PlayerControllerMP.java:247)
	at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1357)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [GCEntityClientPlayerMP['tonimark'/306, l='MpServer', x=-82,70, y=73,62, z=234,97], MCH_ViewEntityDummy['McHeliDummyEntity'/387902, l='MpServer', x=0,00, y=-4,00, z=0,00]]
	Chunk stats: MultiplayerChunkCache: 121, 130
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3963702 game time, 5664322 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 44 total; [EntityItem['item.tile.marsMachine.1'/393342, l='MpServer', x=-78,19, y=71,13, z=253,88], EntityVolneskor['Volneskor'/392405, l='MpServer', x=-71,72, y=46,00, z=291,44], EntityCreeper['Creeper'/392404, l='MpServer', x=-89,50, y=27,00, z=299,50], EntityVolneskor['Volneskor'/392407, l='MpServer', x=-68,00, y=46,00, z=296,06], EntityTentacles['Nature Tentacle'/392403, l='MpServer', x=-83,50, y=10,00, z=298,50], EntityTentacles['Nature Tentacle'/392415, l='MpServer', x=-53,50, y=20,00, z=306,50], EntityTentacles['Nature Tentacle'/392409, l='MpServer', x=-67,50, y=46,00, z=291,50], EntityTentacles['Nature Tentacle'/392408, l='MpServer', x=-68,28, y=46,00, z=291,28], EntityTentacles['Nature Tentacle'/392421, l='MpServer', x=-49,50, y=20,00, z=302,50], EntityCreeper['Creeper'/392422, l='MpServer', x=-57,50, y=53,00, z=290,50], EntityCreeper['Creeper'/392418, l='MpServer', x=-137,50, y=36,00, z=294,50], EntityTentacles['Nature Tentacle'/392424, l='MpServer', x=-115,50, y=59,00, z=297,50], EntitySkeleton['Skeleton'/392452, l='MpServer', x=-84,50, y=57,00, z=307,50], EntitySpider['Spider'/391431, l='MpServer', x=-93,06, y=12,00, z=177,66], EntitySkeleton['Skeleton'/391426, l='MpServer', x=-36,16, y=45,00, z=178,41], EntitySkeleton['Skeleton'/392471, l='MpServer', x=-92,50, y=16,00, z=267,50], EntitySkeleton['Skeleton'/392477, l='MpServer', x=-109,50, y=58,00, z=313,50], EntitySkeleton['Skeleton'/392476, l='MpServer', x=-110,50, y=58,00, z=310,50], EntitySkeleton['Skeleton'/392478, l='MpServer', x=-108,50, y=58,00, z=312,50], EntitySkeleton['Skeleton'/392472, l='MpServer', x=-62,69, y=29,00, z=196,09], EntityTentacles['Nature Tentacle'/392483, l='MpServer', x=-114,50, y=46,00, z=178,50], EntitySpider['Spider'/392482, l='MpServer', x=-93,50, y=11,00, z=282,50], EntityTentacles['Nature Tentacle'/393562, l='MpServer', x=-77,50, y=20,00, z=294,50], EntityTentacles['Nature Tentacle'/393576, l='MpServer', x=-79,50, y=20,00, z=296,50], EntityTentacles['Nature Tentacle'/393577, l='MpServer', x=-80,50, y=20,00, z=295,50], EntityCreeper['Creeper'/393716, l='MpServer', x=-71,50, y=45,00, z=305,50], EntityCreeper['Creeper'/393714, l='MpServer', x=-70,50, y=45,00, z=307,50], EntityCreeper['Creeper'/393715, l='MpServer', x=-66,50, y=45,00, z=303,50], EntityCreeper['Creeper'/393712, l='MpServer', x=-72,50, y=45,00, z=308,50], EntityTentacles['Nature Tentacle'/392797, l='MpServer', x=-147,50, y=28,00, z=288,50], EntitySkeleton['Skeleton'/392818, l='MpServer', x=-111,50, y=31,00, z=187,50], EntitySkeleton['Skeleton'/392837, l='MpServer', x=-77,84, y=11,00, z=181,59], EntitySkeleton['Skeleton'/392840, l='MpServer', x=-92,50, y=12,00, z=183,50], EntitySkeleton['Skeleton'/392878, l='MpServer', x=-54,47, y=29,00, z=189,06], EntitySpider['Spider'/392882, l='MpServer', x=-53,34, y=28,00, z=186,28], EntityTentacles['Nature Tentacle'/392916, l='MpServer', x=-116,50, y=22,00, z=172,50], EntityCreeper['Creeper'/392919, l='MpServer', x=-96,50, y=57,00, z=314,50], EntityTentacles['Nature Tentacle'/392915, l='MpServer', x=-118,50, y=23,00, z=173,50], EntityTentacles['Nature Tentacle'/392914, l='MpServer', x=-119,50, y=23,00, z=170,50], EntityVolneskor['Volneskor'/391969, l='MpServer', x=-59,00, y=29,00, z=188,75], GCEntityClientPlayerMP['tonimark'/306, l='MpServer', x=-82,70, y=73,62, z=234,97], MCH_ViewEntityDummy['McHeliDummyEntity'/387902, l='MpServer', x=0,00, y=-4,00, z=0,00], EntitySkeleton['Skeleton'/393100, l='MpServer', x=-66,50, y=16,00, z=156,50], EntityCreeper['Creeper'/393097, l='MpServer', x=-90,00, y=18,00, z=170,53]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 572103040 bytes (545 MB) / 1567240192 bytes (1494 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 11, tcache: 93, allocated: 2, tallocated: 28
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D8 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	psychedelicraftcore{1.4} [Psychedelicraft Core] (minecraft.jar) 
	UCHIJAAAA	debug{1.0} [debug] (Dense-Ores-Mod-1.7.10.jar) 
	UCHIJAAAA	myfit{1.9} [MyFit] (1.7.10-myfit-2.0 (1).jar) 
	UCHIJAAAA	securitycraft{v1.8.2.3} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.2.3.jar) 
	UCHIJAAAA	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCHIJAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1 (1).jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c (1).jar) 
	UCHIJAAAA	AmnesiaDecorations{1.1.1} [Amnesia Decorations] (AmnesiaDecorations-1.7.10-1.1.1.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329 (1).jar) 
	UCHIJAAAA	AmnesiaLights{1.1.1} [Amnesia Lights] (AmnesiaLights-1.7.10-1.1.1.jar) 
	UCHIJAAAA	AmnesiaMonsters{1.1.1} [Amnesia Monsters] (AmnesiaMonsters-1.7.10-1.1.1.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.18} [BuildCraft] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.18} [BC Energy] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.502.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.502.jar) 
	UCHIJAAAA	GalacticraftAmunRa{0.4.8} [Pra's Galacticraft Mod] (AmunRa-GC-0.4.8.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118 (2).jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248 (1).jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.18} [BC Transport] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.18} [BC Silicon] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.18} [BC Factory] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.18} [BC Builders] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.18} [BC Robotics] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10 (1).jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(19jun17).jar) 
	UCHIJAAAA	darkcore{0.3} [Dark Core] (darkcore-0.3-86 (1).jar) 
	UCHIJAAAA	Eln{@VERSION@} [Electrical Age] (ElectricalAge-1.14.2 (1).jar) 
	UCHIJAAAA	EnderTech{1.7.10-0.3.2.405} [EnderTech] (EnderTech-1.7.10-0.3.2.405.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b197.jar) 
	UCHIJAAAA	mcheli{1.0.3} [MC Helicopter] (FOLDER) 
	UCHIJAAAA	Steamcraft{0.29.3} [Flaxbeard's Steam Power] (FSP-1.7.10-0.29.3 (1).jar) 
	UCHIJAAAA	GalaxySpace{1.1.9} [GalaxySpace] (GalaxySpace-1.1.9 STABLE.jar) 
	UCHIJAAAA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.2.0} [Minecraft Comes Alive] (MCA-1.7.10-5.2.0-universal.jar) 
	UCHIJAAAA	millenaire{6.0.0} [MillΓ©naire] (millenaire-6.0.0.jar) 
	UCHIJAAAA	numina{1.7.10} [Numina] (Numina-0.4.1.105.jar) 
	UCHIJAAAA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UCHIJAAAA	powersuits{1.7.10-0.11.1.114} [MachineMuse's Modular Powersuits] (ModularPowersuits-1.7.10-0.11.1.114 (1).jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	psychedelicraft{1.5.2} [Psychedelicraft] (Psychedelicraft-1.5.2.jar) 
	UCHIJAAAA	rafradek_tf2_weapons{0.6.9.4} [TF2 Stuff Mod] (rafradek_tf2_weapons-1.7.10-0.6.9.4.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.2-92.jar) 
	UCHIJAAAA	simplyjetpacks{1.5.3} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.3 (1).jar) 
	UCHIJAAAA	SirenMod{2.2.01} [TheRealMcrafter's Siren Mod (Version 3.0.0)] (SirenMod-3.0.0.jar) 
	UCHIJAAAA	SolarFlux{1.7.10-0.8b} [Solar Flux] (SolarFlux-1.7.10-0.8b.jar) 
	UCHIJAAAA	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCHIJAAAA	TardisMod{0.994} [Tardis Mod] (tardismod-1.7.10-0.994-124-DS (1).jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	TF2Dispenser{1.7.10} [TF2 Dispenser] (TF2Dispenser-1.7.10.jar) 
	UCHIJAAAA	TF2Sentry{1.7.10} [TF2 Sentry] (TF2Sentry-1.7.10.jar) 
	UCHIJAAAA	TF2TeamAddon{1.7.10} [TF2 TeamAddon] (TF2TeamAddon-1.7.10.jar) 
	UCHIJAAAA	TF2Teleporter{1.7.10} [TF2 Teleporter] (TF2Teleporter-1.7.10.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172 (1).jar) 
	UCHIJAAAA	TMechworks{0.2.15.106} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.15.106.jar) 
	UCHIJAAAA	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	denseores{1.0} [Dense Ores] (Dense-Ores-Mod-1.7.10.jar) 
	UCHIJAAAA	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4531' Renderer: 'Intel(R) HD Graphics 4400'
	CoFHCore: -[1.7.10]3.1.4-329
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	RedstoneArsenal: -[1.7.10]1.1.2-92
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.2.1-172
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4531, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D8
	Render Distance Chunks: 5
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4531
	OpenGlRenderer: Intel(R) HD Graphics 4400
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by BlesseNtumble** [comment]
Try this version:
https://yadi.sk/d/Nvu0QfYD3PBJDW

**Comment by tonimark** [comment]
yea I use already 1.1.9-stable i downloaded from curse mods
