### ISSUE TITLE
Can't hit the ¨Create a space station¨ button

### ISSUE THREAD

**Issue by MoonMan420** [BlesseNtumble/GalaxySpace#199]
Hi, im having trouble with the ¨create a space station¨ button or i think that's what its called i don't know because i cant see it i think its here but i cant tell.
I haven't found another place where it could be and i haven't found any videos showing the process of getting the space station in galacticraft 3
![galacticraft 3](https://user-images.githubusercontent.com/34522977/34388531-05d62760-eb2c-11e7-8e33-098d4a8d6362.PNG)
This is the minecraft version 1.7.10 by the way I also have the galaxyspace add-on but i don't know if it's because of it.

As you can see i have all the items required

![galacticraft 3 space station](https://user-images.githubusercontent.com/34522977/34388758-70190bdc-eb2d-11e7-8c48-879a9975fc04.PNG)

Can someone please help me!

**Comment by MoonMan420** [comment]
Please help me i don't want to uninstall this add-on its so cool!

**Comment by BlesseNtumble** [comment]
Wait for version 1.2.0. It fixed this bug.

**Comment by MoonMan420** [comment]
Thanks! i'll do that
