### ISSUE TITLE
crash in NEI

### ISSUE THREAD

**Issue by bear989** [BlesseNtumble/GalaxySpace#204]
I was cycling through NEI and came to the Immersive Engineering chrusher and a missing tesxture was in the input and I crashed with this log
[crash-2018-01-15_18.42.51-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/1633228/crash-2018-01-15_18.42.51-client.txt)

**Comment by m0nkm0nk** [comment]
You are not alone. https://github.com/BlesseNtumble/GalaxySpace/issues/187
