### ISSUE TITLE
(GS 1.2.0) Custom Title Lead to No BGM in game

### ISSUE THREAD

**Issue by jahtim** [BlesseNtumble/GalaxySpace#209]
I have tried a lot of times. I found that:

When I use GS 1.2.0 , with custom title switched on, I entered the title screen, there is BGM. And then I click a button(say single player), the BGM is vanished forever. Exit to title screen again doesn't help.

When I use GS 1.2.0 , with custom title switched off, I entered the title screen, there is BGM. And then I click a button(say single player), the BGM is vanished. Exit to title screen again, and the BGM is revived, thus, played again from start.

But normally,  I entered the title screen, there is BGM. And then I click a button, the BGM does not stop. Exit to title screen again, and the BGM is not stopped, thus, continue playing.

I have other mod which has the function of Custom Title too , and the mod is FossilsAndArcheology.

**Comment by BlesseNtumble** [comment]
BGM?

**Comment by jahtim** [comment]
BGM means BackGround Music. There is 4 music as of Title screen, and much more in game

**Comment by BlesseNtumble** [comment]
It's a mod?
If yes, give me this mod.

**Comment by jahtim** [comment]
no -,- BGM means background music

**Comment by BlesseNtumble** [comment]
I tried to do the same. The music works in normal mode.
