### ISSUE TITLE
Can't join a singleplayer world in 1.0.8

### ISSUE THREAD

**Issue by SxvxgeUser** [BlesseNtumble/GalaxySpace#21]
Whenever I try to go to or make a singleplayer world, I get this crash about some "Exception ticking world", IDK if it's a bug with GalaxySpace or Forge.

Link: http://pastebin.com/aQZd2CR7

**Comment by Dream-Master** [comment]
Yes i have the same error all the time.

If i regenerating new config files some Biome Ids >255.

https://gist.github.com/Dream-Master/51a0e8a4dd019d368add#file-gsgc

**Comment by BlesseNtumble** [comment]
#20 last post.
