### ISSUE TITLE
Black screen with Optifine & Shader's on

### ISSUE THREAD

**Issue by Usverin** [BlesseNtumble/GalaxySpace#212]
Черный экран на 1.7.10, когда включены шейдеры.
![mc-galaxyspace](https://user-images.githubusercontent.com/10797893/37303114-8b3e83f0-263e-11e8-96f2-b151bb6ec4a8.jpg)

моды:
- GalaxySpace-1.2.1+STABLE.jar
- MicdoodleCore-1.7-3.0.12.502.jar
- Galacticraft-Planets-1.7-3.0.12.502.jar
- GalacticraftCore-1.7-3.0.12.502.jar
- OptiFine_1.7.10_HD_U_E3.jar

Последняя версия, в которой все хорошо - GalaxySpace-1.1.4 STABLE.jar

**Comment by BlesseNtumble** [comment]
Отключите небо на Земле в конфиге.

**Comment by Usverin** [comment]
Помогло, спасибо большое!
