### ISSUE TITLE
The problem of this mod with shader

### ISSUE THREAD

**Issue by AustenXiyue** [BlesseNtumble/GalaxySpace#213]
From "Galaxy-space 1.1.5 STABLE", If I'm installing this mod and use some shaders by Optifine, It will make Minecraft window be super dark, I can't even clearly see blocks and mobs, I'm updating my mod version, but the newest version(1.2.1 STABLE) haven't solve this problem.
GalaxySpace-1.2.1+STABLE.jar
MicdoodleCore-1.7-3.0.12.503.jar
Galacticraft-Planets-1.7-3.0.12.503.jar
GalacticraftCore-1.7-3.0.12.503.jar
preview-OptiFine_1.7.10_HD_U_E7_pre.jar
![2018-03-12_18 41 35](https://user-images.githubusercontent.com/25553318/37318003-4e20fe12-2625-11e8-8bf7-bd9866d8bbc2.png)

**Comment by BlesseNtumble** [comment]
Disable Overworld Sky in config.

**Comment by AustenXiyue** [comment]
Wow, the problem was solved, thank you very much @BlesseNtumble
