### ISSUE TITLE
[Worldgen] Bad worldgen cascading on Tau Ceti E

### ISSUE THREAD

**Issue by richardhendricks** [BlesseNtumble/GalaxySpace#214]
Hello,
  We love your mod, and are using it heavily in our 1.7.10 modpack Gregtech:New Horizons.  However, when trying to add support for Tau Ceti, we've discovered it has really bad worldgen cascading. This causes problems with our oregen since it basically locks up the server trying to create thousands of chunks.

It hasn't been much of an issue with the other planets since their surfaces are pretty bare, and a new chunk isn't likely to request a neighboring chunk.  

But on TCE, because of the seaweed decorations, a new chunk will attempt to place blocks on the chunk border, causing a new chunk to be requested. 

Here is a sample picture of the cascading worldgen on Tau Ceti E
![2018-03-14_22 56 39](https://user-images.githubusercontent.com/1214811/37443583-fdf7c8dc-27da-11e8-98ec-5a3c83abe153.png)
![2018-03-14_22 56 50](https://user-images.githubusercontent.com/1214811/37443584-fe093bb2-27da-11e8-84af-038b4c1d35fd.png)

I suggest as a first test, offsetting your worldgen by +8 to X and Z.  In MC, the 3 chunks +X and +Z of the current chunk are already in existence, so placing blocks offset will not cause a cascade of new chunks.

This is a good article on cascading worldgen, and on ways to avoid/stop it.  If you need help, I have changed worldgens before to by-chunk.

https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

**Comment by mitchej123** [comment]
How is this invalid?

**Comment by codewarrior0** [comment]
You didn't specify the GalaxySpace version number?

**Comment by richardhendricks** [comment]
We're using Galaxy Space 1.1.3a, but based on the info on the current page, it looks like Tau Ceti support was dropped, possibly because of this issue.

We'll fix it on our own.

**Comment by Dream-Master** [comment]
Maybe it was fixed in newer version. @richardhendricks  wait with a fix let me update the version first and look at all stuff that changed and  need to be redone before you look for a solution .
