### ISSUE TITLE
GUI is glitching

### ISSUE THREAD

**Issue by ghost** [BlesseNtumble/GalaxySpace#217]
The GUI is glitching with ExtraPlanets (I've only tested it with this addon). Idk if this is also with other addons. (Addons that i use: Extended Planets, extra planets, more planets.)
https://youtu.be/_3JDqQ7IwiE

**Comment by BlesseNtumble** [comment]
Disable our galaxy map or EP galaxy map in config.

**Comment by ghost** [comment]
I've disabled it in ExtraPlanets and it works thanks.

**Comment by ghost** [comment]
And i have a question. Is it normal that i can't place leaves, seeds, gras and water on the moon? And if yes, can i disable it or how can i make that i can place it there?

**Comment by BlesseNtumble** [comment]
Sealed region and add thermal control on Oxygen Sealer.

**Comment by WistarWolf** [comment]
okay
