### ISSUE TITLE
GregTech incompatibility

### ISSUE THREAD

**Issue by DerMilchkarton** [BlesseNtumble/GalaxySpace#218]
I think your mod adds a OreDict-Tag to all the compressed Plates, eg.: Compressed Copper -> plateCopper
this causes progression problems with GregTech 5u
can you maybe add a config option to disable the OreDict-tagging of the compressed plates?
thanks!
PS.: im using your newest release

**Comment by draknyte1** [comment]
Just don't Oredict compressed plates as normal plates, and this fixes all your issues now and in the future.
Should take two second to fix with Find & Replace in your IDE.

**Comment by BlesseNtumble** [comment]
Will added config in 1.2.2
