### ISSUE TITLE
A worldgen problem.

### ISSUE THREAD

**Issue by Sandendaty** [BlesseNtumble/GalaxySpace#221]
Maybe GalaxySpace's Ores (like sapphire ore,mars aluminum ore,mars gold ore and so on...) can not gen on Galacticraft's Planets,I can't find them everywhere.How to solve this problem?
GalaxySpace version 1.2.2
Galacticraft version 3.0.12.503

**Comment by BlesseNtumble** [comment]
Maybe you disable ore gen in config?

**Comment by Sandendaty** [comment]
Well,I reset the Galacticraft config and the GalaxySpace config, but it still can't solve the problem.In my opinion,maybe Galacticraft disable the ores from other mods gen on its planets by default.

**Comment by Sandendaty** [comment]
The problem has been solved.I enabled custom oregen configuration in
`.minecraft\config\Galacticraft\core.conf`
This is a reference:
`S:"Other mods ores for GC to generate on the Moon and planets" <
           GalaxySpace:leadore:2  /UNCOMMON /ONLYMOON
           GalaxySpace:marsoresblocks:0  /RARE /XTRARANDOM /DEEP /ONLYMARS
           GalaxySpace:marsoresblocks:1  /RARE /DEEP /ONLYMARS
           GalaxySpace:marsoresblocks:2  /RARE /SHALLOW /LARGE /ONLYMARS
           GalaxySpace:marsoresblocks:3  /DEEP /ONLYMARS
           GalaxySpace:marsoresblocks:4  /RARE /DEEP /ONLYMARS
           GalaxySpace:marsoresblocks:5  /UNCOMMON /ONLYMARS
     >`
If you think this is reasonable,you can close this issue now.

**Comment by Sandendaty** [comment]
Now the problem has been completely solved in GalaxySpace 2.0.8.
