### ISSUE TITLE
[Big bug] In the world of galaxy planets, I cannot grow and grow all types of trees.

### ISSUE THREAD

**Issue by Twilight-Dream-Of-Magic** [BlesseNtumble/GalaxySpace#222]
# Can you fix it? Otherwise, all of the oxygen machines that need leaves will not work

### I have a level 2 radiation protection suit, and after wearing it, I still can't stop the damage from stellar ### radiation (negative effect).

**Comment by BlesseNtumble** [comment]
It's not bug.

Now Space Suit get protect from radiation.
About grow: Need sealed room for grow or disable Hard Mode in config.

**Comment by Twilight-Dream-Of-Magic** [comment]
No, the method you used to modify the configuration file is correct. 
You can now allow the tree to grow.
However, some of you didn't say it correctly. 
My Level 2 radiation protection suit still did not work.

**Comment by BlesseNtumble** [comment]
Space Suit.
Not Thermal Suit!!!!
