### ISSUE TITLE
Dedicated Server [1.2.1 Stable] java.lang.NoClassDefFoundError: net/minecraft/server/integrated/IntegratedServer

### ISSUE THREAD

**Issue by TigerWalts** [BlesseNtumble/GalaxySpace#225]
The following exception appears in the server log when a player first travels to the moon. The player is kicked as a result.
```
 java.lang.NoClassDefFoundError: net/minecraft/server/integrated/IntegratedServer
    at galaxyspace.core.events.GSEventHandler.sendPlanetList(Unknown Source) ~[GSEventHandler.class:?]
    at galaxyspace.core.events.GSEventHandler.onEntityUpdate(Unknown Source) ~[GSEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_497_GSEventHandler_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
```
**net/minecraft/server/integrated/IntegratedServer** is not available on dedicated servers. The changelog for later versions mentions no fix for this.

**Comment by TigerWalts** [comment]
I updated the Galacticraft and GalaxySpace mods and the error does not happen.

Here are the updates I made:

- GalaxySpace 1.2.1 Stable >> 1.2.3 Stable
- MicdoodleCore 1.7-3.0.12.503 >> 1.7-3.0.12.504
- Galacticraft Core 1.7-3.0.12.503 >> 1.7-3.0.12.504
- Galacticraft Planets 1.7-3.0.12.503 >> 1.7-3.0.12.504

Not sure which one fixed it but you can close this issue now.

**Comment by BlesseNtumble** [comment]
What server core do you use?

**Comment by TigerWalts** [comment]
This was using `forge-1.7.10-10.13.4.1614`

**Comment by BlesseNtumble** [comment]
try on Thermos
