### ISSUE TITLE
[BUG]I can't craft the Tier 2 HeavyBooster.

### ISSUE THREAD

**Issue by Sandendaty** [BlesseNtumble/GalaxySpace#228]
![2018-06-10_21 33 13](https://user-images.githubusercontent.com/39406572/41202179-e9c75384-6cf7-11e8-9a99-9d2fd7bf748d.png)
![2018-06-10_17 14 25](https://user-images.githubusercontent.com/39406572/41202181-f01907e6-6cf7-11e8-9765-8305e44bbbf5.png)

GalaxySpace version 1.2.3
GalactiCraft version 3.0.12.503

**Comment by BlesseNtumble** [comment]
Already fixed. Wait new version.
