### ISSUE TITLE
Some suggestions.

### ISSUE THREAD

**Issue by Sandendaty** [BlesseNtumble/GalaxySpace#232]
Hello BlesseNtumble,your add-on is fantastic,but I have some suggestions.

1.The sun in the sky on Mercury should be white,because Mercury has no atmosphere.
2.I think GS has a better rendering effect on the no-atmosphere-planet's sun in the sky than GC4,so if you can,change the sun from these planets' sky(for example,the moon,the asteroids and the earth-spacestation) to GS's rendering.
![2018-07-29_21 57 11](https://user-images.githubusercontent.com/39406572/43368099-4021e592-938a-11e8-94eb-512ca406e05e.png)
3.Add config option to disable the background-music in GS.

Can you accept my suggestions?Thanks!

**Comment by BlesseNtumble** [comment]
Ok, I'll add a render of the sun to the Moon and Asterodes. So I'll change the render on Mercury and add the config.
