### ISSUE TITLE
A sky-rendering problem.

### ISSUE THREAD

**Issue by Sandendaty** [BlesseNtumble/GalaxySpace#233]
![2018-07-31_01 36 43](https://user-images.githubusercontent.com/39406572/43413952-069b1f16-9464-11e8-99af-3dc1d227e3c3.png)
![2018-07-31_00 49 10](https://user-images.githubusercontent.com/39406572/43413965-0e39cb8c-9464-11e8-9aa4-5c5fb08f14be.png)

The problem is not only consist in Mercury.Maybe all of the GS's planets.

GalactiCraft version 4.0.1.181
GalaxySpace version 2.0.0 STABLE

**Comment by BlesseNtumble** [comment]
give me mc log

**Comment by Sandendaty** [comment]
@BlesseNtumble 
[debug-1(before restart).log](https://github.com/BlesseNtumble/GalaxySpace/files/2245761/debug-1.before.restart.log)
[debug(after restart).log](https://github.com/BlesseNtumble/GalaxySpace/files/2245762/debug.after.restart.log)
[2018-07-31-1(before restart).log](https://github.com/BlesseNtumble/GalaxySpace/files/2245763/2018-07-31-1.before.restart.log)
[latest(after restart).log](https://github.com/BlesseNtumble/GalaxySpace/files/2245764/latest.after.restart.log)

**Comment by Sandendaty** [comment]
Oh,I knew.Your renderer can't compat with Optifine's FastRender.Only 1.12.2 has this problem.My Optifine version is Optifine_1.12.2_HD_U_E1.
