### ISSUE TITLE
[1.12.2] Краш: Космическая карта

### ISSUE THREAD

**Issue by FhtagnHlatk** [BlesseNtumble/GalaxySpace#237]
Краш заключается в том что когда открывается косм. карта игра вылетает
[pastebin.com/UKazpyhR](https://pastebin.com/UKazpyhR)
Версия Minecraft 1.12.2
Версия мода 2.0.0 Стабильный  
Помимо Galacticraft и GS я использую more planets,more planets extras и extra planets

**Comment by BlesseNtumble** [comment]
stevekung.mods.moreplanets.core.event.ClientEventHandler.onRenderCelestialPost(ClientEventHandler.java:483)

moreplanets
