### ISSUE TITLE
[Major] GalaxySpace 1.0.8 - Space Station Loading Crash - java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by LokeYourC3PH** [BlesseNtumble/GalaxySpace#24]
I am referencing from an Issue i opened in Galacticraft. (https://github.com/micdoodle8/Galacticraft/issues/2130)

Basically, once i load a Mars Space Station, and it loads for some seconds, it crashes the server. I had to disable that Space Station for now due to there are many others that still want to play on my server.

This is the log: http://pastebin.com/J0NmKp7Z

It does not happen with my Moon Space Station, only that particular Mars Space Station.

**Comment by BlesseNtumble** [comment]
#20 If the problem continues - create a new question.

**Comment by Yanniclord** [comment]
Why did you reopen it Blesse?

**Comment by LokeYourC3PH** [comment]
@BlesseNtumble Ok i see why, it is NOT fixed. The issue still exists and crashes my server. I have no idea if it helps you or not, but here the new, fresh crashlog from the latest server crash i had: http://pastebin.com/fCX7dNy1

**Comment by BlesseNtumble** [comment]
I know, developers GC3 changed method of obtaining name parent planet at space station.
I don't know what is now name at Mars.

**Comment by LokeYourC3PH** [comment]
Did you try asking them? I know, stupid answer :P
