### ISSUE TITLE
GalaxySpace conflict with hats

### ISSUE THREAD

**Issue by maximcs1** [BlesseNtumble/GalaxySpace#243]
minecraft-1.7.10
GalaxySpace-1.2.5+STABLE
Hats-4.0.1
------------------------------
Шапки работают, но кнопка для открытия gui в hats не работает.
Менял на другую клавишу, тот же результат.
При удалении GalaxySpace, gui открывается.

**Comment by jahtim** [comment]
I also have this problem.
When I press H, the cursor shows up for 1 frame and disappear in the next frame.
Changing keybind to other key is useless.

Reletaive code in Hats:
@Override
    public void openHatsGui()
    {
        FMLClientHandler.instance().displayGuiScreen(Minecraft.getMinecraft().thePlayer, new GuiHatSelection(Minecraft.getMinecraft().thePlayer));
        //		FMLClientHandler.instance().displayGuiScreen(Minecraft.getMinecraft().thePlayer, new GuiTradeWindow("Kihira"));
    }


@SideOnly(Side.CLIENT)
    @SubscribeEvent
    public void onKeyEvent(InputEvent.KeyInputEvent event)
    {
        //if(event.keyBind.isPressed() && event.keyBind == Hats.config.getKeyBind("guiKeyBind"))
        if(Hats.config.getKeyBind("guiKeyBind").isPressed())
        {
            Minecraft mc = Minecraft.getMinecraft();
            if(mc.currentScreen == null && !Hats.proxy.tickHandlerClient.hasScreen)
            {
                if(Hats.config.getSessionInt("playerHatsMode") == 3)
                {
                    PacketHandler.sendToServer(Hats.channels, new PacketPing(0, false));
                }
                else if(Hats.config.getSessionInt("playerHatsMode") == 2)
                {
                    mc.thePlayer.addChatMessage(new ChatComponentTranslation("hats.lockedMode"));
                }
                else if(Hats.config.getSessionInt("playerHatsMode") == 5 && !Hats.config.getSessionString("currentKing").equalsIgnoreCase(mc.thePlayer.getCommandSenderName()))
                {
                    mc.thePlayer.addChatMessage(new ChatComponentTranslation("hats.kingOfTheHat.notKing", Hats.config.getSessionString("currentKing")));
                }
                else
                {
                    Hats.proxy.openHatsGui();
                }
            }
        }
    }
