### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by konsulilya** [BlesseNtumble/GalaxySpace#244]
1. Ver. 1.7.10
2. 1.2.5 + STABLE
3. (Возможно были такие вопросы) При игре с аддоном 4 - space, при открытие галактической карты происходит краш игры. После удаления аддона 4 - space карта открывается, но пропадает планета на Альфа - Центавре и орбитальные полосы на дополнительных солнечных системах (при этом краша нету). 
https://pastebin.com/ugipQBdP - краш репорт

**Comment by BlesseNtumble** [comment]
4Space слишком старый аддон, он не поддерживается в GS

**Comment by konsulilya** [comment]
Спасибо. Вот что я еще заметил, с аддоном More Planets  крашится игра при запуске. Этот аддон тоже не поддерживается или нужна более новая версия?

**Comment by konsulilya** [comment]
Еще заметил, что не хватает солнечных систем

**Comment by BlesseNtumble** [comment]
Нужно менять конфиги в MorePlanets. Там идет конфликт космической станции на Марсе.
Звездные системы, которые были до 1.2.0 на реконструкции.
