### ISSUE TITLE
How to update to a new version of GalaxySpace?

### ISSUE THREAD

**Issue by MadCrafter** [BlesseNtumble/GalaxySpace#245]
Okay, this is not a real issue or something, its just a question. 

My server uses the version 1.1.4 of GalaxySpace and I'm wondering if it is possible to update to the newest version without any problems. I made a whole new copy of my server and tried it out and the mod always errored. Is there some way to make the update work without corrupting anything?

**Comment by BlesseNtumble** [comment]
Upgrade to 1.2.5 version only delete the current world and generate a new.

**Comment by MadCrafter** [comment]
Yeah sure, but is it possible to update the mod in the same world as before? I already built so lot in it and I don't want to lose everything.
Thanks for the response. :)

**Comment by BlesseNtumble** [comment]
Many blocks / items may be lost and you will have to get them again.
You also need to remove all the planets and moons, so they regenerates.
