### ISSUE TITLE
Rocket does not fuel up

### ISSUE THREAD

**Issue by kapusta1234** [BlesseNtumble/GalaxySpace#247]
Ever since I updated to the latest version, I am unable to fuel my rocket. It is a level 6 rocket, I am using the new landing pad 5x5 as well as the advanced fuel loader. The advanced fuel loader has power and is full of fuel; however the rocket's fuel level remains at 0%. I tried to move the rocket to the different location and fuel it there, but the result was the same. Can someone please advise? Thank you.

**Comment by BlesseNtumble** [comment]
for rocket 5 and 6 need Helium-Hydrogen fluid.
It is produced in the separator by combining Helium-3 and Hydrogen

**Comment by kapusta1234** [comment]
Thank you for that. Where can I get Helium-3?

**Comment by BlesseNtumble** [comment]
Universal Recycler and Moon Turf and many planet grunt blocks.
