### ISSUE TITLE
Server Crash with GalaxySpace

### ISSUE THREAD

**Issue by starkimax** [BlesseNtumble/GalaxySpace#248]
Hey, I'm having some trouble with your mod ^^
Need some help.
When I install GalaxySpace on the client everything works fine, but when I try to install your mod on the server side, it crash.
Crash report : [crash-2018-09-02_12.02.13-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/2343184/crash-2018-09-02_12.02.13-server.txt)

**Comment by BlesseNtumble** [comment]
wait 2.0.1 version.
