### ISSUE TITLE
[Minor] GalaxySpace 1.0.8 - Mars Space Station Graphical Glitch

### ISSUE THREAD

**Issue by LokeYourC3PH** [BlesseNtumble/GalaxySpace#25]
So, this is a thing apparently:

![2016-03-08_17 20 33](https://cloud.githubusercontent.com/assets/5807595/13607802/3544fd50-e552-11e5-99e6-d23e48f4c489.png)
![2016-03-08_17 20 43](https://cloud.githubusercontent.com/assets/5807595/13607804/35befdf8-e552-11e5-8882-d49b23ff019c.png)

Mars is on the side of the Space Station, not under/beneath it. I don't know if it is intended, but i am certain it is not.

**Comment by SxvxgeUser** [comment]
I'm confused what I'm looking at.

**Comment by LokeYourC3PH** [comment]
A Space Station from the side? A standard generated Space Station above Mars. Where MARS, the PLANET, is on the SIDE, not BELOW the Space Station. Is that less confusing?

**Comment by SxvxgeUser** [comment]
Well, the last version of GalaxySpace had it already on the side, so I guess it was intended. Could be wrong.

BTW, is that multiplayer, cuz theres a bug in singleplayer were you crash if you load 1.0.8 with "Exception ticking world"

**Comment by BlesseNtumble** [comment]
This is not a bug. Sun also rotates horizontally.

**Comment by LokeYourC3PH** [comment]
@Kqdy Yes Multiplayer, but i also get that crash on an existing Space Station, how odd. @BlesseNtumble Could you investigate please?
