### ISSUE TITLE
[1.12.2]GalaxySpace conflict with BC Silicon.

### ISSUE THREAD

**Issue by Sandendaty** [BlesseNtumble/GalaxySpace#251]
I launched minecraft with buildcraft and this mod,but minecraft crashed.Here is the crash-report.
[crash-2018-09-17_16.57.38-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/2387926/crash-2018-09-17_16.57.38-client.txt)
GalaxySpace version 2.0.1

**Comment by PromanSEW** [comment]
Disable facades in config
In objects.conf, set this:
```
items {
...
    B:plug_facade=false
...
}
```
See https://github.com/BuildCraft/BuildCraft/issues/3937
