### ISSUE TITLE
Crash on GUI Celestial selection

### ISSUE THREAD

**Issue by Kevadroz** [BlesseNtumble/GalaxySpace#253]
Crash Report: [Hastebin](https://paste.dimdev.org/yipemeriwe.mccrash).

When I run a /dimensiontp (just specification) the map zooms in and out quickly and then it crashes.

I think it's a compatibility issue with MJRLegends's addons, [a link to the issue on Planet Progression](https://github.com/MJRLegends/Planet-Progression/issues/33).

Also the issue is from the dependency, AsmodeusCore.

**Comment by BlesseNtumble** [comment]
disable new galaxy map on config. (AsmodeusCore or ExtraPlanets config.)
