### ISSUE TITLE
1.12.2 Bug

### ISSUE THREAD

**Issue by wiqg** [BlesseNtumble/GalaxySpace#255]
So , recently i've downloaded galacticraft and played it for a while until i got interested in some addons for it . I downloaded Extra planets and Galaxy Space , but they both crash . Not exactly crash but , everytime i start the game and i type /dimensiontp nothing happens , i cant type in chat , right click something or anything , just walk around .I cant even quit the game , i have to close it with task manager... Also the Galaxy Space mod doesnt even add new planets or anything ,as if it doesnt even exist, just the default planets, why ? Please help me fix it .

**Comment by BlesseNtumble** [comment]
disable our map in AsmodeusCore or disable map in config Extra Planets.

**Comment by wiqg** [comment]
I disabled the map in AsmodeusCore but now when i tried to open the map i got white screen and then it crashed ... https://pastebin.com/G2WQCj3C
Btw Im playing on 1.12.2 , and using GalaxySpace 2.0.1+ Stable if this matters

**Comment by wiqg** [comment]
So , is there a way to fix it ?

**Comment by BlesseNtumble** [comment]
java.lang.NullPointerException: null
    at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) 
-> try without jorneymap

**Comment by wiqg** [comment]
Ermm nope ... same thing , when i try to open the map i get white screen and minecraft freezes and i have to close it with task manager... But i have almost 80 mods... maybe thats the problem.For example ExtraPlanets had conflict with Flan's mod and i removed it , now it works . But i dont wanna remove any other mods just because of that..

**Comment by BlesseNtumble** [comment]
try with this core: https://yadi.sk/d/q8vRK_axKPfQkQ

**Comment by wiqg** [comment]
https://pastebin.com/KTrbqeDE
https://pastebin.com/xYZBi09a
:/

**Comment by BlesseNtumble** [comment]
try disable Extra Planets map and enable map in AsmodeusCore

**Comment by wiqg** [comment]
When i enabled the custom map i just got my galaxy orbits wider , and when i made it false and enabled galaxy map true i got white screen and the game freezed like before... Can i ask you to help me add my own planets ? Since i have a few mods which work , but most of the others are for 1.7 and this one doesnt work ... but i will use them only for my singleplayer world?

**Comment by wiqg** [comment]
Is it possible to create a planet with a biome generator ? For example creating a planet similiar to the overworld but not the regular vanilla generation , but biome bundle mod , ATG etc. ?

**Comment by BlesseNtumble** [comment]
possible

**Comment by wiqg** [comment]
How can i make it?

**Comment by BlesseNtumble** [comment]
We can't go now. But soon will transfer to our generator in the world.
![example](https://media.discordapp.net/attachments/261150906429472768/496646686165303296/2018-10-02_18.45.34.png)

**Comment by wiqg** [comment]
Nice !
