### ISSUE TITLE
[1.7.10] Suggestion and improvement

### ISSUE THREAD

**Issue by lovesgalacticraft** [BlesseNtumble/GalaxySpace#256]
Hello this is a great add-on and i am loving it. Are you thinking about adding the missing solar system's planets: Jupiter,Neptune,Uranus and Saturn? I would really love if these planets would be added so me and my friends can explore the galaxy even more. I am so glad i found this add-on, you've really done a good job. Please add Saturn,Uranus,Neptune and Jupiter.

 Thank you for reading my post

   Sincerely Lovesgalacticraft

**Comment by BlesseNtumble** [comment]
https://forum.micdoodle8.com/index.php?threads/1-7-10-galaxy-additions-for-galacticraft-3.6558/
