### ISSUE TITLE
[1.12.2] Config to Disable Solar Radiation Mechanic

### ISSUE THREAD

**Issue by CaveMiner1215** [BlesseNtumble/GalaxySpace#258]
Hello,

I do thank you for adding the ability to disable solar radiation in the 1.7.10, and I was wondering when this is coming to the 1.12.2 version.  Do you know?

Thanks,
CaveMiner1215

**Comment by BlesseNtumble** [comment]
on 1.12.2 version - in next build will add this config

on 1.7.10 - core.conf
    # Enable/Disable solar radiation system.
    B:enableSolarRadiationSystem=true

**Comment by CaveMiner1215** [comment]
@BlesseNtumble 
I don't see the config option to disable Solar Radiation in Galaxy Space 2.0.3 for MC 1.12.2 (However, it is there for the 1.7.10 version)
