### ISSUE TITLE
NoBody

### ISSUE THREAD

**Issue by NoBody5865** [BlesseNtumble/GalaxySpace#26]
Не могу войти в Синглплеер. Нажимаю создать мир или играть в выбранном мире. Начинает загружаться, а потом вылетает. Выдает сообщение об ошибке. Длииинное. Все пробовал: лаунчеры менял, компьютеры менял, версии мода и аддона менял. ID измерений менять не получается. Не сохраняются.
Игра:1.7.10
Мод:3.0.12.446
Аддон:1.0.8

**Comment by NoBody5865** [comment]
Краш репорт: https://yadi.sk/i/WkVutFYpq2AHt

**Comment by BlesseNtumble** [comment]
Ждите фикс. В #21 об этой ошибке уже написано.
