### ISSUE TITLE
Game crash when I open the map

### ISSUE THREAD

**Issue by Mugiwaxar** [BlesseNtumble/GalaxySpace#260]
Related to: [366](https://github.com/MJRLegends/ExtraPlanets/issues/366) [355](https://github.com/MJRLegends/ExtraPlanets/issues/355) [253](https://github.com/BlesseNtumble/GalaxySpace/issues/253)

PastBin: [Here](https://pastebin.com/zc4uBUMH)

**Version of Mods:**
GalaxySpace: 2.0.2+STABLE
ExtraPlanet: 1.12.2-0.4.2
Forge: 1.12.2-14.23.5.2772
GalactiCraft: 1.12.2-4.0.1.181

The game crash when I open the galaxy map, any solution work in the related post (And "delete X mod' isn't a solution ...).
Tried to disable custom map on config... Not working

**Comment by MJRLegends** [comment]
Please stop opening new issues for closed issues

**Comment by BlesseNtumble** [comment]
disable EP galaxy map

**Comment by MJRLegends** [comment]
@Mugiwaxar if you actually read the issues you have linked to your solution is right there in just about all of them

**Comment by MJRLegends** [comment]
No need to keep making issue reports we dont need 1000 of them...

**Comment by Mugiwaxar** [comment]
@MJRLegends, If you actually read what I wrote, or what others said in reports you link?
This solution doesn't work!
I have disabled all AsmodeusCore or Extra Planet custom map, the game crash...
Seriously, you have closed my issue so quickly, without know if my problem was solved, and it is still here

Edit 1: This is the log without custom map: [Pastbin](https://pastebin.com/sU82zD7k)
Edit 2:  This is only appening when GalaxySpace and Extra Planet are together

**Comment by Mugiwaxar** [comment]
Actualy, Disabling EP galaxy map doesn't work

**Comment by Mugiwaxar** [comment]
This is the bin without custom map: [Pastbin](https://pastebin.com/sU82zD7k)

**Comment by Mugiwaxar** [comment]
This is only appening when GalaxySpace and Extra Planet are together

**Comment by BlesseNtumble** [comment]
EP config:
```
# Setting this option to false will disable & remove the Custom Galaxies on Celestaial Selection Screen (Note: Will get disabled by the 'Use Custom Galaxy Map/Celestaial Selection Screen' option)
    B:"Custom Galaxies on Celestaial Selection Screen"=false

#Setting this option to false, will change it back to be using the Galacticraft Galaxy Map/Celestaial Selection Screen
    B:"Use Custom Galaxy Map/Celestaial Selection Screen"=false
```
![EP+GS](https://pp.userapi.com/c830709/v830709162/1b659d/o1ukQPDjCWY.jpg)
