### ISSUE TITLE
Update zh_CN.lang, IDK how to use github

### ISSUE THREAD

**Issue by NekoLemon** [BlesseNtumble/GalaxySpace#261]
It is 1.2.6 for minecraft 1.7.10

[zh_CN.zip](https://github.com/BlesseNtumble/GalaxySpace/files/2529344/zh_CN.zip)

**Comment by BlesseNtumble** [comment]
Thanks.
You can write me in Discord and there to send files.
https://discordapp.com/invite/8EHZdFZ
