### ISSUE TITLE
[1.7.10]The sky disappears when I'm in the water./Небо исчезает, когда я в воде.

### ISSUE THREAD

**Issue by dfdfwefvs** [BlesseNtumble/GalaxySpace#267]
### addon 1.2.6 STABLE

![2018-11-19_20 17 48](https://user-images.githubusercontent.com/45236351/48848570-4ce8f880-edb5-11e8-9bbc-690debe3deb8.png)
![2018-11-19_20 17 46](https://user-images.githubusercontent.com/45236351/48848571-4d818f00-edb5-11e8-9989-fe598d789510.png)
![2018-11-19_20 16 28](https://user-images.githubusercontent.com/45236351/48848572-4d818f00-edb5-11e8-8c9f-759de1dbc082.png)
![2018-11-19_20 16 24](https://user-images.githubusercontent.com/45236351/48848573-4d818f00-edb5-11e8-989d-a2cd67e21993.png)
![2018-11-19_20 12 36](https://user-images.githubusercontent.com/45236351/48848574-4d818f00-edb5-11e8-97ff-276bd6ce87d3.png)
![2018-11-19_20 12 32](https://user-images.githubusercontent.com/45236351/48848575-4e1a2580-edb5-11e8-8472-bf82da7099c4.png)
I checked without other mods and resource packs, but the result was the same ... If I jump in the water, sky appears for a second.
Я потом ещё проверила без других модов и ресурспаков, но результат был тот же... Если в воде "прыгать", то оно появляется на секунду.

**Comment by BlesseNtumble** [comment]
Fixed in 1.2.7
