### ISSUE TITLE
Error after updating to 1.2.7 (MC 1.7.10)

### ISSUE THREAD

**Issue by Gartosz** [BlesseNtumble/GalaxySpace#268]
Initializing gamejava.lang.IllegalArgumentException: value already present: net.minecraftforge.fluids.Fluid@1b9cb529
Crash-log: https://pastebin.com/wvkcG71g

**Comment by BlesseNtumble** [comment]
redownload build

**Comment by Gartosz** [comment]
didn't help

**Comment by Gartosz** [comment]
or maybe... xd
