### ISSUE TITLE
[Suggestion] 1.12.2 An config to disable GuiCelestialSelection?

### ISSUE THREAD

**Issue by superhealing** [BlesseNtumble/GalaxySpace#270]
Hi,

I want to say your add-os is fantastic, but one small problem there is GuiCelestialSelection, maybe i want suggest put on config to disable this, will be really helpfully for us.
Thank you.

**Comment by MJRLegends** [comment]
Mesaage for devs:


would be even better if you could please check if planet progression mod is loaded in your open gui event and disable galacy spaces galaxy map as that addon needs its galaxy map to be used or that addon cant function.  

It would mean less bug reports for us and allow both galaxy space and planet progressions to work fine

**Comment by BlesseNtumble** [comment]
@DragonHacker1 you can disable GalaxyMap in configs/AsmodeusCore/core.conf

#Enable/Disable New Galaxy Map.
B:enableNewGalaxyMap=true

@MJRLegends 
I will work on compatibility.
