### ISSUE TITLE
game crashes with flans mod installed 1.12.2

### ISSUE THREAD

**Issue by CanisLRufus** [BlesseNtumble/GalaxySpace#275]
there is an issue when i installed flans mod with galaxy space wich just causes the game to crash

**Comment by BlesseNtumble** [comment]
crash log?

**Comment by CanisLRufus** [comment]
[crash-2019-01-05_16.58.38-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/2730888/crash-2019-01-05_16.58.38-client.txt)

**Comment by BlesseNtumble** [comment]
without Galaxy Space, but with Asmodeus Core worked?

**Comment by CanisLRufus** [comment]
nope i tryed just the core without Galaxy space i get the same issue but with the core and the Galaxy space mod disabled the game started up with out any problems, it seems to be an issue with the core with flans mod but heres the crash report
[crash-2019-01-07_13.31.56-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/2734064/crash-2019-01-07_13.31.56-client.txt)

**Comment by BlesseNtumble** [comment]
Well... I check this problem:
I get crash with full disable AsmodeusCore.

Crash calls this piece of code:
```//Sulphuric acid
		sulphuricAcid = new Fluid("sulphuricAcid", sulphuricAcidStill, sulphuricAcidFlowing).setTemperature(300).setViscosity(800);
		if(FluidRegistry.registerFluid(sulphuricAcid))
		{
			blockSulphuricAcid = new BlockSulphuricAcid(sulphuricAcid, Material.WATER).setTranslationKey("blockSulphuricAcid").setRegistryName("blockSulphuricAcid").setCreativeTab(tabApocalypse);
			sulphuricAcid.setBlock(blockSulphuricAcid);
			sulphuricAcid.setUnlocalizedName(blockSulphuricAcid.getTranslationKey());
			FluidRegistry.addBucketForFluid(sulphuricAcid);
		}
		else
		{
			sulphuricAcid = FluidRegistry.getFluid("sulphuricAcid");
			blockSulphuricAcid = sulphuricAcid.getBlock();
		}
```
https://github.com/FlansMods/FlansMod/blob/1.12.2/src/main/java/com/flansmod/apocalypse/common/FlansModApocalypse.java

SuphuricAcid i dont have in AsmodeusCore, it is in GalacticraftPlanets.
Crash log: https://pastebin.com/Njh2XymV

@radfast, @micdoodle8
