### ISSUE TITLE
Config to Disable Solar Radiation Missing from 1.12.2 GS 2.0.4

### ISSUE THREAD

**Issue by CaveMiner1215** [BlesseNtumble/GalaxySpace#279]
########################################################################
1) Minecraft version: 1.12.2
2) Galacticraft version: N/A
3) GalaxySpace version: 2.0.4
4) AsmodeusCore version (for 2.0.1 version and above): 0.0.5
5) Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): N/A
########################################################################
Description of the issue: My apologies for bothering you again on this subject, though it has been two releases since you said that the config option to disable the solar radiation mechanic would be added in the next release of Galaxy Space for 1.12.2.  As of Galaxy Space 2.0.4, this option is still missing.  I apologize if this is bugging you, but do you know when you plan on implementing this feature to Galaxy Space for 1.12.2?

Thanks,
CaveMiner1215
########################################################################
Screenshot/Video: N/A

########################################################################
Attached log file (or url on pastebin.com): N/A

########################################################################

**Comment by BlesseNtumble** [comment]
Will add in 2.0.5
