### ISSUE TITLE
Exception ticking world with newest 1.0.8fix  Version

### ISSUE THREAD

**Issue by Dream-Master** [BlesseNtumble/GalaxySpace#28]
Ok Version 1.0.8 works for me if I delete all config files from all mods i have in my pack.

If i am only delete Galaxy space and Galacticraft configs or change the configs the game crash with the same error before. (Exception ticking world) I don't have any Id conflicts or Biome id conflicts.

I use my Modpack on a private Server and I can't reset my whole world. I need a solution here because you mod is closed source and I can't do anything. Otherwise we are forced to stay forever with Beta 2.6. or I have to check every config in my mod witch needs weeks or month to check.

FML Log:
https://gist.github.com/Dream-Master/604f33e280b9a3a068c3#file-fml

Configs:
DIM: https://gist.github.com/Dream-Master/fb2d468f587a04ff06c4#file-dim
Biome : https://gist.github.com/Dream-Master/e16e25b2e559ad650035#file-biome

Old Biome dump from GS 2.6
https://gist.github.com/Dream-Master/20908c73bf8e8e2d5c79#file-biome26

Old Dim dump from GS 2.6
https://gist.github.com/Dream-Master/66bc261798efd66c9937#file-dims26

I need help here.

**Comment by Dream-Master** [comment]
With all planets disabled in the config the error changed.

https://gist.github.com/Dream-Master/5fd08a1cfba787b6b37c#file-error

**Comment by Dream-Master** [comment]
I try disabled with menu, delte the asm folder, load an old existing world, remove minetweaker scripts, nothing works i get all the time this error:
https://gist.github.com/Dream-Master/9321fbfc3df8f3719fbb#file-crash

**Comment by Dream-Master** [comment]
So I open up a test setup with only Galaxy space 1.0.8 Galacticraft 446, NEI 1.0.5.120 and Code chick core 1.0.7.47
https://www.dropbox.com/s/rhsszsgzx0i2pg7/Screenshot 2016-03-11 21.31.10.png?dl=0

I using this configs witch are compatible to my modpack with GS 2.6 (i add all ids to the new generated GS config files)
https://www.dropbox.com/s/5g6bv57211d6kgr/config.zip?dl=0

Only with this few mods the game crash and i get the same crash as before.
https://gist.github.com/Dream-Master/7736e22fba6ccd297ffa#file-crash

I sitting here for three evenings to get a the pack running without any success.Could you take a look, please.
Thanks

---

I check today Biome Ids and it seems to be that some biome ids i set via your config not stay at this id. Some Biome ids not have a config (some planets have more than one Biome)
I try to remove biome id cfg and the game start in the minimal setup but inside the pack it crash again.

**Comment by BlesseNtumble** [comment]
#33
