### ISSUE TITLE
Mars crashes 1.12.2

### ISSUE THREAD

**Issue by Nbgreen** [BlesseNtumble/GalaxySpace#280]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
########################################################################
1) Minecraft version: 1.12.2
2) Galacticraft version: 4.0.1.184
3) GalaxySpace version: 2.0.4
4) AsmodeusCore version (for 2.0.1 version and above): 0.0.5
5) Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP
########################################################################
Description of the issue:
Mars crashes still happening on sponge servers 
########################################################################
Attached log file (or url on pastebin.com):
https://paste.dimdev.org/asodemataf.sql
########################################################################

**Comment by BlesseNtumble** [comment]
Fixed in 0.0.6
