### ISSUE TITLE
[1.12.2] [Bug] Galaxy Space Breaks the Color of Grass

### ISSUE THREAD

**Issue by CaveMiner1215** [BlesseNtumble/GalaxySpace#281]
########################################################################
1) Minecraft version: 1.12.2
2) Galacticraft version: 4.0.1.186
3) GalaxySpace version: 2.0.5
4) AsmodeusCore version (for 2.0.1 version and above): 0.0.5
5) Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
########################################################################
Description of the issue:
When Galaxy Space is installed, the color of grass blocks becomes a single shade of green, and does not change color depending on the biome in which the blocks are.  This was tested with only JEI, Galaxy Space, and Galacticraft (was also tested with and without Flan's mod, but the issue persists either way).  Removing Galaxy Space fixes the issue.
########################################################################
Screenshot/Video:
![2019-01-11_17 07 14](https://user-images.githubusercontent.com/30667792/51062135-b3271600-15c3-11e9-9032-370a6b27d4b5.png)
As you can see, the ferns changed their color to match the biome they were in, but the grass blocks did not.
########################################################################
Attached log file (or url on pastebin.com):
[latest-gsbug.log](https://github.com/BlesseNtumble/GalaxySpace/files/2751327/latest-gsbug.log)
########################################################################

**Comment by CaveMiner1215** [comment]
What verification do you need?

**Comment by DoctrinaLudum** [comment]
In that same version when the Galaxy Space is installed where it was to be water in voxelmap everything appears black. I think it's the same problem so I did not open a new post. I did the tests, the previous version of the Galaxy worked well.

**Comment by BlesseNtumble** [comment]
Fixed in 2.0.6
