### ISSUE TITLE
Universal recycler stops producing items when hopper is placed under it and it runs out of items to extract.

### ISSUE THREAD

**Issue by Blayyke** [BlesseNtumble/GalaxySpace#282]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
########################################################################
1) Minecraft version: 1.12.2
2) Galacticraft version: GalacticraftCore-1.12.2-4.0.1.184
3) GalaxySpace version: GalaxySpace-1.12.2-2.0.4
4) AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-0.0.5
5) Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
########################################################################
Description of the issue: If you have a hopper set to extract from a universal recycler, all will work well when there is items for the hopper to take. Once the output slot runs out of items however, the Universal recycler stops making items but continues to consume one item in the input slot. Even after removing the hopper below, the machine continues to not produce anything. Still doesn't make anything even after breaking and replacing the block.

########################################################################
Screenshot/Video:
Can provide video tomorrow.

########################################################################
Attached log file (or url on pastebin.com):
No errors in console.

########################################################################

**Comment by Blayyke** [comment]
It appears that once this happens in a world it does the same thing on every universal recycler that is placed.

**Comment by BlesseNtumble** [comment]
It fixed in 2.0.5
