### ISSUE TITLE
not compatible

### ISSUE THREAD

**Issue by camatthew** [BlesseNtumble/GalaxySpace#283]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
########################################################################
1) Minecraft version:1.12.2
2) Galacticraft version:latest
3) GalaxySpace version:latest
4) AsmodeusCore version (for 2.0.1 version and above): latest
5) Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
########################################################################
Description of the issue:
doesent start
Screenshot/Video:

########################################################################
Attached log file (or url on pastebin.com):

https://paste.dimdev.org/vutoyojisu.mccrash

**Comment by BlesseNtumble** [comment]
ci.micdoodle8.com
Update GC4.
Minimum 184 build.

**Comment by camatthew** [comment]
great job
