### ISSUE TITLE
Galaxy space causing error in rendering Voxel Map

### ISSUE THREAD

**Issue by DoctrinaLudum** [BlesseNtumble/GalaxySpace#284]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
########################################################################
1) Minecraft version: 1.12.2
2) Galacticraft version: 1.12.2-4.0.2.190
3) GalaxySpace version: 1.12.2-2.0.5
4) AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.4
5) Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6) Forge version : 1.12.2-14.23.5.2806
########################################################################
Description of the issue:
Good afternoon!
I've been experiencing this visual bug has 4 versions of Galaxy Space. I did all the tests when I play with all the mods and shot the GalaxySpace the water is correctly weighted on the map. When I put the Galaxy Space happens what is in the screenshot. I did not find anything in the settings that gave me any light.
Help me
########################################################################
Screenshot/Video:
![erro](https://user-images.githubusercontent.com/46344592/51538064-69e28c00-1e37-11e9-96ba-6fe0698aead4.png)

########################################################################
Attached log file (or url on pastebin.com):
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/2782866/latest.log)

########################################################################

**Comment by DoctrinaLudum** [comment]
Good afternoon!
Any progress?

Att,

**Comment by BlesseNtumble** [comment]
Fixed. Wait 2.0.6 build.
