### ISSUE TITLE
[1.12.2] Can't find schematics for Tier 3 Rocket

### ISSUE THREAD

**Issue by VanillaCakePeople** [BlesseNtumble/GalaxySpace#285]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
########################################################################
1) Minecraft version: 1.12.2
2) Galacticraft version: 4.0.1.184
3) GalaxySpace version: 2.0.4
4) AsmodeusCore version (for 2.0.1 version and above): 0.0.5
5) Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP
########################################################################
Description of the issue: Me and my friends have been searching through Mars dungeons constantly to find schematics for the Tier 3 rocket parts but can't seem to find any of them. I don't know if it's because we're looking in the wrong place or what. 

We've only found schematics for the Automatic Cargo Rocket and Astro miner which are apart of Galacticraft and not GalaxySpace. 

########################################################################
Screenshot/Video:

########################################################################
Attached log file (or url on pastebin.com):

########################################################################

**Comment by BlesseNtumble** [comment]
Tier 3 Rocket have new craft. Check Jei.
Need 5 base schematic with Moon.

**Comment by VanillaCakePeople** [comment]
Alright thanks, I'll try finding them on the moon then.
