### ISSUE TITLE
Missing solar wind panel

### ISSUE THREAD

**Issue by MatveyM11** [BlesseNtumble/GalaxySpace#286]
1) Minecraft version: 1.12.2
2) Galacticraft version: 1.12.2 - 4.0.2.190
3) GalaxySpace version: 1.12.2 - 2.0.5
4) AsmodeusCore version:  
5) Side: SSP

Description of the issue:
Missing solar wind panel
I have tried to find it in NEI, in creative search panel,  i tried just craft it, tried delete all mods and lieve only Galaxy Space, GalacticraftCore, Galacticraft Planets, MicdoodleCore, AsmodeusCore,  but there is no panel anywhere.

Screenshot/Video:
![base profile screenshot 2019 02 11 - 11 45 53 67](https://user-images.githubusercontent.com/23504691/52551681-ff4dbc00-2df6-11e9-9a4b-798dceb0cee5.png)

**Comment by BlesseNtumble** [comment]
Added in 2.0.6
