### ISSUE TITLE
Gravity Module CCL Exception

### ISSUE THREAD

**Issue by LokeYourC3PH** [BlesseNtumble/GalaxySpace#287]
1) Minecraft version: 1.12.2
2) Galacticraft version: 4.0.2.190
3) GalaxySpace version: 2.0.5
4) AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.5
5) Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP Server & SSP
########################################################################
Description of the issue:
Error message being thrown on powering the Gravity Module
########################################################################
Screenshot/Video:
![2019-02-13_14 03 20](https://user-images.githubusercontent.com/5807595/52713644-28f21900-2f98-11e9-9dbb-d1045fa8d24b.png)

########################################################################
Attached log file (or url on pastebin.com):
https://pastebin.com/e2JKZ6vu
########################################################################

Also, the Gravity Module doesn't even work at all when powered, it changes nothing and adds no normal gravity within its field.

**Comment by Sairus314** [comment]
Sorry, that is off topic.
But what are the names of these four large energy pipes in your screenshot and from what mod are they?

**Comment by BlesseNtumble** [comment]
Try 2.0.6 version

**Comment by LokeYourLord** [comment]
I can't even start the game now. https://pastebin.com/TQS6gukU

**Comment by LokeYourLord** [comment]
I can't even start the game now @BlesseNtumble https://pastebin.com/TQS6gukU

**Comment by LokeYourC3PH** [comment]
Issue seems fixed.
