### ISSUE TITLE
Dimension ID crash (1.0.8)

### ISSUE THREAD

**Issue by MapperTV** [BlesseNtumble/GalaxySpace#29]
With latest version of Galacticraft (+Planets) and Galaxy Space:

Crash when trying to start a world: http://pastebin.com/GV8Ltkhj

Tried to change the dimension ID with many other numbers (from -5000 to 5000), it always crash.

I tried to remove Galaxy Space configs and all mod configs, started new maps, nothing changed.

**Comment by BlesseNtumble** [comment]
conflict dimension id.
-30 - Asteroids.
