### ISSUE TITLE
Вылет при создании мира 1.12.2

### ISSUE THREAD

**Issue by deboshir228** [BlesseNtumble/GalaxySpace#290]
1.12.2
2. Galacticraft version:148
3. GalaxySpace version:2.0.5
4. AsmodeusCore version 0.0.5
5. Single player 
------------------------------------------------------------------------
Description of the issue:
при создании мира краш, никаких доп. модов не ставил. пробовал менять версии, но безуспешно.

------------------------------------------------------------------------
![default](https://user-images.githubusercontent.com/48103175/53594146-4552a000-3bab-11e9-84ca-e898b92e23ad.PNG)

https://pastebin.com/PXx8S8tS

**Comment by BlesseNtumble** [comment]
Обнови GC.
ci.micdoodle8.com
