### ISSUE TITLE
changing key binds crashes game on relaunch

### ISSUE THREAD

**Issue by Nbgreen** [BlesseNtumble/GalaxySpace#295]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.2.190
3. GalaxySpace version: 1.12.2-2.0.6
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.6
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
all of the above
------------------------------------------------------------------------
Description of the issue:
1. change a key bind
2. restart game
3. game crashes
4. caused by https://paste.dimdev.org/vefilezade.mccrash
Attached log file (or url on pastebin.com):
https://paste.dimdev.org/vefilezade.mccrash

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
#292

**Comment by Nbgreen** [comment]
the version this is happening on is 1.12.2 not 1.7.10
