### ISSUE TITLE
Prepare for Entry!

### ISSUE THREAD

**Issue by Nbgreen** [BlesseNtumble/GalaxySpace#298]
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.2.190
3. GalaxySpace version: 1.12.2-2.0.6
4. Sponge version: 1.12.2-2768-7.1.6-RC3616
5. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.6
6. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
Multiplayer sponge server
------------------------------------------------------------------------
Description of the issue:
any time I change a single galaxy space config on the server and restart it the players get stuck on the Prepare for entry screen and cant do anything till they are forced tped to spawn and  restart their game.
the only way I know to prevent this is to regen the config for the mod but I would like to edit somethings if possible.

**Comment by BlesseNtumble** [comment]
log

**Comment by Nbgreen** [comment]
client side log
https://www.dropbox.com/s/5tuehcq6ivsvmq4/client-latest.log?dl=0
server side log
https://www.dropbox.com/s/lkwfb5r7h9s0w0m/server-latest.log?dl=0

**Comment by BlesseNtumble** [comment]
without GS normal work?

**Comment by Nbgreen** [comment]
The issue only happens when I change GS configs. I have also had players have the same issue when going to Venus when I change GS configs.
