### ISSUE TITLE
Bad Texture

### ISSUE THREAD

**Issue by Notlucky101** [BlesseNtumble/GalaxySpace#300]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.22
2. Galacticraft version:GalacticraftCore-1.12.2-4.0.2.210
3. GalaxySpace version:GalaxySpace-1.12.2-2.0.7
4. AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-0.0.7
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP

------------------------------------------------------------------------
Description of the issue:
I completely started over  and start to implement one mod at a time, but to get to the root of
the problem I load Galacticraft and GalaxySpace first. It all look good until I loaded the following
two mod, Botania, BopAdditions.  Then things go wrong with the textures. 
The previous version of Galaxy Space was not a problem. What do you and Botania do to have
such a conflict?

------------------------------------------------------------------------
Screenshot/Video:

This is before the two mod mentioned above where implemented.
![image](https://user-images.githubusercontent.com/42447191/55675909-c114cc00-587e-11e9-88e8-f3c266053427.png)

And after the two mods this

![image](https://user-images.githubusercontent.com/42447191/55675914-d7bb2300-587e-11e9-9266-e62954ec4052.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
log?
