### ISSUE TITLE
GS + GTCE crash on MC load.

### ISSUE THREAD

**Issue by Sataana** [BlesseNtumble/GalaxySpace#304]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: GalacticraftCore-1.12.2-4.0.2.210
3. GalaxySpace version: GalaxySpace-1.12.2-2.0.7.jar
4. AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-0.0.7.jar
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP (Did not test SMP yet)

------------------------------------------------------------------------
Description of the issue:
There appears to be a crash on loading up MC with GTCE, reverting GS to GalaxySpace-1.12.2-2.0.6.jar seems to resolve the issue.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
Crashlog in Gift form [[HERE](https://gist.github.com/Sataana/e7e3b45e7c98c28c1a188ea4a5c23352)]

------------------------------------------------------------------------

Will [cross post](https://github.com/GregTechCE/GregTech/issues/720) in the GTCE Git.

**Comment by BlesseNtumble** [comment]
you have FoamFix?

**Comment by Sataana** [comment]
> you have FoamFix?

I do yes

**Comment by BlesseNtumble** [comment]
https://github.com/asiekierka/FoamFix/issues/200

**Comment by Sataana** [comment]
That seems to have fixed it, thank you very much!
