### ISSUE TITLE
[1.12] -Startup failure

### ISSUE THREAD

**Issue by RayzFoxx** [BlesseNtumble/GalaxySpace#305]
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.190
3. GalaxySpace version: 2.07
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.7
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

------------------------------------------------------------------------
Description of the issue:

After updating GalaxySpace to version 2.0.7 in my modpack the game with foamFix can't startup, without foamFix game launches fine

foamFix version: 1.10.5

------------------------------------------------------------------------
Screenshot/Video:

none
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

https://pastebin.com/bbUCMHsR 
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
#304
