### ISSUE TITLE
Crash NEI

### ISSUE THREAD

**Issue by NITDroid1995** [BlesseNtumble/GalaxySpace#306]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.7.10
2. Galacticraft version: GalacticraftCore-1.7-3.0.12.502
3. GalaxySpace version: GalaxySpace-1.2.10+STABLE
4. AsmodeusCore version (for 2.0.1 version and above): 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP

------------------------------------------------------------------------
Description of the issue:

Смотрел что можно сделать из лунного камня и клиент закрылся
------------------------------------------------------------------------
Screenshot/Video:

-
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

https://pastebin.com/Kpt5Km9w
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
#303
