### ISSUE TITLE
Keybind toggle for armor is activated even when in a GUI.

### ISSUE THREAD

**Issue by Puppydaze** [BlesseNtumble/GalaxySpace#307]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.190
3. GalaxySpace version: 2.0.6
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.6
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Multiplayer (SMP)

------------------------------------------------------------------------
Description of the issue:
When in a GUI and typing words (Example, ComputerCraft terminal, JEI Search, or Pause Menu (Multiplayer Only), the keybinds will activate for your gear.

------------------------------------------------------------------------
Screenshot/Video:
I have a GIF showing the issue: https://imgur.com/a/6bEljlY
In the GIF, I am using Night Vision upgrade as an example.
You can see in the background that night vision is applied every time I press F, even in the menu or search.

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
No errors.

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
thanks. will add check for gui
