### ISSUE TITLE
crash when connecting to bungeecord server

### ISSUE THREAD

**Issue by Nbgreen** [BlesseNtumble/GalaxySpace#309]
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.2.190
3. GalaxySpace version: 2.0.7
4. AsmodeusCore version (for 2.0.1 version and above): 2.0.7
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Multiplayer
------------------------------------------------------------------------
Description of the issue:
I have a Bungeecord hub set up that does not have galaxy space on it. 
my players use the hub to connect to the server with galaxy space on it.
when trying to connect to the hub with galaxy space 2.0.7 you get this crash https://paste.dimdev.org/califerape.mccrash
you can connect to the bungeecord hub with version 2.0.6 with no issues
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
crash report
https://paste.dimdev.org/califerape.mccrash
client side logs
https://www.dropbox.com/s/rr7jcv4tvfme43a/client.log?dl=0

**Comment by BlesseNtumble** [comment]
```
private void syncCurrentPlayItem()
    {
        int i = this.mc.player.inventory.currentItem;

        if (i != this.currentPlayerItem)
        {
            this.currentPlayerItem = i;
            this.connection.sendPacket(new CPacketHeldItemChange(this.currentPlayerItem));
        }
    }
```
Most likely, null is passed here, and the player should be passed.
This is not a GS error. In any case, there is no mention of GS in the logs.

**Comment by Nbgreen** [comment]
Weird only happens when I update GS

**Comment by Nbgreen** [comment]
found out the issue the mod was conflicting with foamfix
