### ISSUE TITLE
I can not get the blueprint of the Lv2 rocket.

### ISSUE THREAD

**Issue by StarGuardianLulu** [BlesseNtumble/GalaxySpace#314]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.7.10
2. Galacticraft version:1.7-3.0.12.504
3. GalaxySpace version:1.2.11+STABLE
4. AsmodeusCore version (for 2.0.1 version and above): 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
SSP, SMP
------------------------------------------------------------------------
Description of the issue:
私は英語が分かりません、ごめんなさい。Google翻訳です。
I do not understand English, I am sorry. Google translation

私は20個以上の月のダンジョンをクリアしました。
I cleared over 20 moon dances.

しかし、Lv2ロケットの設計図を貰えません。
However, I can not provide a blueprint for the Lv2 rocket.

代わりにSchematic Boxを貰えます。
I'll give you a Schematic Box instead.

私はまだ月にしか行けないのでSchematic Boxを活かせません。
I can only go to the moon so I can not use the Schematic Box.

村人との交換でもLv2ロケットの設計図が貰えません。
Even with the villagers, I can not get the blueprint of the Lv2 rocket.

月のダンジョンのクリア報酬としてLv2ロケットの設計図が手に入りますか？
Can I get a blueprint for the Lv2 rocket as a clear reward for the moon dungeon?

他にLv2ロケットの設計図を入手する方法はありますか？
Is there any other way to get the design of the Lv2 rocket?

------------------------------------------------------------------------
Screenshot/Video:
trade:
https://i.gyazo.com/d9052f30e9630b165aad1cac688f1ecd.png
mods:
https://i.gyazo.com/187d4bd506d3bd59c4e435658a5dc218.png

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Will fix in 1.2.12. Thanks.

**Comment by StarGuardianLulu** [comment]
わかりました。
understood.
回答してくれてありがとうございます。
thank you for your answer.
