### ISSUE TITLE
Triton is not available?

### ISSUE THREAD

**Issue by donqixot** [BlesseNtumble/GalaxySpace#315]
According to curseforge page (https://minecraft.curseforge.com/projects/galaxy-space-addon-for-galacticraft), Triton is highlighted in green, I presume it should be available. Yet, when I try to use Tier 6 rocket, Triton is colored as red (probably means not available). Is curseforge page incorrect or am I doing something wrong?
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.2.210
3. GalaxySpace version: 1.12.2-2.0.7
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.7
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Now triton only on 1.7.10 version.

**Comment by donqixot** [comment]
OK, got it, thank you! And thank you for this mod! Amazing!
