### ISSUE TITLE
Asteroids require tier 4 rocket instead of 3 as in vanilla Galacticraft

### ISSUE THREAD

**Issue by donqixot** [BlesseNtumble/GalaxySpace#316]
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: GalacticraftCore-1.12.2-4.0.2.210
3. GalaxySpace version: GalaxySpace-1.12.2-2.0.7
4. AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-0.0.7
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

------------------------------------------------------------------------
Description of the issue:
I am playing modpack "Lapito's Galacticraft" which has Galacticraft and GalaxySpace (nothing else for space dimensions), I am looking at galaxy map and see Asteroids require Tier 4 rocket (see 1st screenshot), not Tier 3 as in vanilla Galacticraft (see 2nd screenshot). I can't find any changes in config of either mods which could change that, so my question is it hardcoded by GalaxySpace?
------------------------------------------------------------------------
Screenshot/Video:
![2019-05-10_20 27 49](https://user-images.githubusercontent.com/12219588/57562660-a85a7300-7362-11e9-9442-97d16fdf1906.png)
![2019-05-10_20 32 40](https://user-images.githubusercontent.com/12219588/57562683-dc359880-7362-11e9-8f9b-e5cf652a53b9.png)

**Comment by BlesseNtumble** [comment]
You can disable it in configs/GalaxySpace/core.conf
```
# Enable/Disable new tier system for celestial bodies.
 B:enableNewTierSystem=false
```
But, you can fly on Mars and from Mars to Asteroids.

**Comment by donqixot** [comment]
Thank you very much! This is very helpful.
