### ISSUE TITLE
Minecraft does not work at all

### ISSUE THREAD

**Issue by CominSanya** [BlesseNtumble/GalaxySpace#317]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:12.2.2
2. Galacticraft version:4.0.1.181
3. GalaxySpace version:2.0.7
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.7
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):

------------------------------------------------------------------------
Description of the issue:
Minecraft does not work at all.
I dont have any other mods (exclusive of Galacticraft of course)
The solution of this problem didt find on this site
I attached the crash file 

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

[crash-2019-05-11_16.23.03-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/3169085/crash-2019-05-11_16.23.03-client.txt)

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
need above 184 build GC4
