### ISSUE TITLE
[1.7.10] Client crash

### ISSUE THREAD

**Issue by pioski** [BlesseNtumble/GalaxySpace#318]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.7.10
2. Galacticraft version: 3.0.12.504
3. GalaxySpace version: 1.2.11
4. AsmodeusCore version (for 2.0.1 version and above): 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

------------------------------------------------------------------------
Description of the issue:
My game crashes when intalizing 5/7

------------------------------------------------------------------------
Screenshot/Video:
it's a crash

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[crash-2019-05-12_08.22.03-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/3169804/crash-2019-05-12_08.22.03-client.txt)

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Failed to register dimension for id -34, One is already registered.
check your configs.

**Comment by pioski** [comment]
How to check configs


niedz., 12 maj 2019, 12:36 użytkownik BlesseNtumble <
notifications@github.com> napisał:

**Comment by pioski** [comment]
I need to change the caavern world config when i load game without caavern
it works ok

niedz., 12 maj 2019, 12:37 użytkownik PioSki <faraniyt@gmail.com> napisał:
