### ISSUE TITLE
Dimension not found crash

### ISSUE THREAD

**Issue by vagaprime** [BlesseNtumble/GalaxySpace#32]
I have been running into an error where minecraft is unable to locate the Dimesion's added by Galaxy Space.

here are the four crash logs.

http://pastebin.com/1ip2gHH5

http://pastebin.com/m7bmvc1P

http://pastebin.com/bzq0Shtr

http://pastebin.com/fnFjmdqG

I have changed dimension id's as the where causing crashes, Up till the fourth crash

**Comment by BlesseNtumble** [comment]
Conflict ID.

**Comment by vagaprime** [comment]
The only id conflict was with TF, and I changed the twlight forest id to -50. I did a dimension id dumb, and there where no conflicts. If you want to prove me wrong I will send you my whole config folder.

**Comment by BlesseNtumble** [comment]
Change the ID to >150

**Comment by vagaprime** [comment]
The TF or the GS Id's?

**Comment by BlesseNtumble** [comment]
GS
