### ISSUE TITLE
NASA Workbench GUI Crash

### ISSUE THREAD

**Issue by zzApotheosis** [BlesseNtumble/GalaxySpace#321]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.7.10
2. Galacticraft version: 1.7-3.0.12.504
3. GalaxySpace version: 1.2.11
4. AsmodeusCore version (for 2.0.1 version and above): N/A
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

------------------------------------------------------------------------
Description of the issue:

This is a continuation of #227. I figured out how to reproduce the issue.

(1) The game will crash when you load it up from the desktop and click the "Next" button twice in a row without letting the cursor leave the button.

(2) The game will not crash when you let the cursor leave the "Next" button between clicks.

(3) After successfully displaying the Tier 2 Rocket GUI, the game will no longer crash even if the same method in point (1) is used.

I have included a video with timestamps to try and explain how to reproduce the issue.

------------------------------------------------------------------------
Screenshot/Video: https://www.youtube.com/watch?v=hXnGnpc_n-E
Timestamps explanation: https://pastebin.com/bwsZinVq

------------------------------------------------------------------------
Attached log file (or url on pastebin.com): https://pastebin.com/dA5v5Q6U

------------------------------------------------------------------------

**Comment by zzApotheosis** [comment]
I just tried it again... My theory failed. I have no idea what causes it.

**Comment by BlesseNtumble** [comment]
try 1.2.12 version
