### ISSUE TITLE
issue's installing update's 2.0.7 and up

### ISSUE THREAD

**Issue by Batosi001** [BlesseNtumble/GalaxySpace#324]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version: GalacticraftCore-1.12.2-4.0.2.190.jar
3. GalaxySpace version: GalaxySpace-1.12.2-2.0.6.jar
4. AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-0.0.6.jar
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
SMP
------------------------------------------------------------------------
Description of the issue:
trying to install newer updates on GalaxySpace-1.12.2-2.0.7.jar + 2.0.8, both causing game crash. tried each one 1 by with each attempt same result no crash report. 2.0.6 is stable for me. any and all help will be greatly appreciated. Thank you for your valuable time :)

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
update asmodeuscore

**Comment by Batosi001** [comment]
i have updated Asmodeuscore and then updated galaxy space, and server crashed and will not start. Is an update of galacticraftCore needed as well?...EDIT reverting to GalaxySpace-1.12.2-2.0.6.jar server does still start with updated AsmodeusCore-1.12.2-0.0.8.jar
