### ISSUE TITLE
Game crashes when i add the mod

### ISSUE THREAD

**Issue by ericgames234** [BlesseNtumble/GalaxySpace#325]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.7.10
2. Galacticraft version:1.7-3.0.11.333
3. GalaxySpace version:1.2.1
4. AsmodeusCore version (for 2.0.1 version and above): 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):

------------------------------------------------------------------------
Description of the issue: When I add the Galaxy Space mod to my mod folders and launch minecraft from the regular launcher (with forge) it would begin loading and then crash mid way. Some other key information might be that I'm using a mac, it does work without the file and i have tried different versions. could use some help.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
very old version.
Download Galacticraft 503 build and GS 1.2.11 version.
https://minecraft.curseforge.com/projects/galaxy-space-addon-for-galacticraft/files
