### ISSUE TITLE
Titan rain crash 

### ISSUE THREAD

**Issue by Nbgreen** [BlesseNtumble/GalaxySpace#326]
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.210
3. GalaxySpace version: 2.0.8
4. AsmodeusCore version (for 2.0.1 version and above): 2.0.8
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): multiplayer server

------------------------------------------------------------------------
Description of the issue:
Players client crashes when it rains on titan
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

https://paste.dimdev.org/higehicuce.mccrash
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
https://github.com/BlesseNtumble/GalaxySpace/commit/6a0bd2a7304060331c117f9a145c5c514dc96b68
