### ISSUE TITLE
GalaxySpace conflict with FoamFix

### ISSUE THREAD

**Issue by Sandendaty** [BlesseNtumble/GalaxySpace#328]
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.190
3. GalaxySpace version:2.0.8
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.8
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP

------------------------------------------------------------------------
Description of the issue:
If I put either OptiFine or FoamFix into the mods folder that has installed GalaxySpace and launch Minecraft,Minecraft will be normally started.
If I put both OptiFine and FoamFix into the mods folder that has installed GalaxySpace and launch Minecraft,Minecraft will crash.
The problem is also caused in GalaxySpace version 2.0.7.
I wonder if you can solve the problem,because FoamFix is important for Minecraft 1.12.2 which is installed in low distribution computer.Thank you!

**Comment by BlesseNtumble** [comment]
#313
