### ISSUE TITLE
Not configurable Biome ID (Biome ID conflict)

### ISSUE THREAD

**Issue by lex1975** [BlesseNtumble/GalaxySpace#33]
I configure Biome ID manually from 171-199, 244-247. But 216, 227, 228 biomes not configurable. Biomes.csv and biomes.conf in attashed file. It can cause a crash (BiomeID conflict)
[dumps.zip](https://github.com/BlesseNtumble/GalaxySpace/files/172574/dumps.zip)
Sorry my bad english, i am russian http://vk.com/id267747813

**Comment by Dream-Master** [comment]
I have the same problem.
https://github.com/BlesseNtumble/GalaxySpace/issues/28

**Comment by lex1975** [comment]
It is old bug.
In 1.0.7 version same bug - 216 (EnceladusWater) and 225 (BarnardaF) biome ID not configurable
In 1.0.6.1 version same bug - 225 (BarnardaF) biome ID not configurable

**Comment by BlesseNtumble** [comment]
Thanks. Fixed in next build.

**Comment by BlesseNtumble** [comment]
#28

**Comment by lex1975** [comment]
Crash at I create new world and 
[crash-2016-03-16_23.09.05-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/176811/crash-2016-03-16_23.09.05-client.txt)
opening of creative tabs. I think it's a bug modification GalaxySpace. When I deleted it, crash stopped.

**Comment by BlesseNtumble** [comment]
@lex1975 
    at buildcraft.transport.ItemPipe.func_77617_a(ItemPipe.java:135)
    at buildcraft.transport.render.PipeItemRenderer.renderPipeItem(PipeItemRenderer.java:62)
    at buildcraft.transport.render.PipeItemRenderer.renderItem(PipeItemRenderer.java:117)
