### ISSUE TITLE
A bug with fuel generator.

### ISSUE THREAD

**Issue by Sandendaty** [BlesseNtumble/GalaxySpace#331]
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.190
3. GalaxySpace version:2.0.8
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.8
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP

------------------------------------------------------------------------
Description of the issue:
A bucket of fuel can generate infinite electricity with a fuel generator.

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Changed burn time.

**Comment by Sandendaty** [comment]
> Changed burn time.

That's not what I meant.In other words,the fuel is only used for preheating instead of generating electricity.
