### ISSUE TITLE
Sleeping with a bed in GS's planets.

### ISSUE THREAD

**Issue by Sandendaty** [BlesseNtumble/GalaxySpace#332]
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.190
3. GalaxySpace version:2.0.8
4. AsmodeusCore version (for 2.0.1 version and above):0.0.8 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP

------------------------------------------------------------------------
Description of the issue:
I tried sleeping with a bed in GalaxySpace's planets,then the bed exploded.

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Use Cryogenic Chamber.
