### ISSUE TITLE
[1.12.2] Suggestion Fluids freez/vaporize

### ISSUE THREAD

**Issue by Gandalf360one** [BlesseNtumble/GalaxySpace#333]
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.2-215
3. GalaxySpace version: 1.12.2-2.0.8
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.8

Dear Developer,
You have done an amazing work that saplings/plants cannot be placed in an area with no oxygen. 
Can you pleas add that fluids will frezz or vaporize if they are not placed in an area with oxygen and a thermal module ?

**Comment by BlesseNtumble** [comment]
liquids do not need oxygen for placement.
But they are also checked for temperature.
