### ISSUE TITLE
Не присваивается значения ключа

### ISSUE THREAD

**Issue by Romsik788** [BlesseNtumble/GalaxySpace#334]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.211
3. GalaxySpace version:2.0.8
4. AsmodeusCore version (for 2.0.1 version and above):0.0.8
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
SSP, SSP not opened to LAN
------------------------------------------------------------------------
Description of the issue:

Значению ключа "gui.status.nowater.name" не присваивается текст, хотя он присутствует в файлах локализации (356 строка в ru_RU.lang)
------------------------------------------------------------------------
Screenshot/Video:

![2019-07-25_19 06 57](https://user-images.githubusercontent.com/33905242/61890330-e7cf3f00-af0f-11e9-8309-8eb17f403d65.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
https://github.com/BlesseNtumble/GalaxySpace/commit/807962b1b76ea0b638dd3fa08c58c00e38e1914b
