### ISSUE TITLE
Crash with GTCE

### ISSUE THREAD

**Issue by FrostCreeper07** [BlesseNtumble/GalaxySpace#339]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version:1.12.2-4.0.2.219
3. GalaxySpace version:1.12.2-2.0.8
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.8
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Single Player

------------------------------------------------------------------------
Description of the issue: Galaxy Space has a crash with GTCE because when i disabled it in the twitch launcher the game loaded without a problem, I don't have any idea if your planning to make it compatible with GregTech but if you are i'll post a link to the crashlog

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):https://pastebin.com/J2HrLzTH

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
It says that it is the GTCE's error, but notice, that GS 2.0.8 is NOT compatible with GC 4.0.2.219, so downgrade it to 4.0.2.211

**Comment by FrostCreeper07** [comment]
That's alright because i decided not to officially add it to my pack and have thus removed it.

**Comment by BlesseNtumble** [comment]
Disable "optimiseBlockPos" in FoamFix cfg.
