### ISSUE TITLE
Краш на марсианской космической станции

### ISSUE THREAD

**Issue by ghost** [BlesseNtumble/GalaxySpace#34]
Если с космической станции Марса скинуть какой-либо предмет в космос, то игра вылетает, и, чтобы зайти в мир снова приходится удалять её измерение
[crash-2016-03-15_21.34.51-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/174473/crash-2016-03-15_21.34.51-server.txt)

**Comment by BlesseNtumble** [comment]
#24
