### ISSUE TITLE
Crash with Galacticraft 4.0.2.212+

### ISSUE THREAD

**Issue by PromanSEW** [BlesseNtumble/GalaxySpace#340]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.219
3. GalaxySpace version: 2.0.8
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.8
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

------------------------------------------------------------------------
Description of the issue:
Crash while starting with GC 212+
See relevant issues:
https://github.com/micdoodle8/Galacticraft/issues/3743
https://github.com/BuildCraft/BuildCraft/issues/4446

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://gist.github.com/PromanSEW/2d1ed4e41e5c8f5b15275f78abedbb8d

------------------------------------------------------------------------

**Comment by PromanSEW** [comment]
When new version with the fix will be available for download?

**Comment by CaveJohnson376** [comment]
Maybe it will be surprise for you, but GS 2.0.8 currently is not compatible with GC 4.0.2.212+
GS 2.0.9 will be compatible.

**Comment by BlesseNtumble** [comment]
#344
