### ISSUE TITLE
Неправильное отображение ботинков космического костюма

### ISSUE THREAD

**Issue by Romsik788** [BlesseNtumble/GalaxySpace#342]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.211
3. GalaxySpace version:2.0.8
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.8
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
SSP, SSP not opened to LAN
------------------------------------------------------------------------
Description of the issue:
Ботинки космического костюма неправильно отображаются если имеют модуль 
"Высокий прижок"
![2019-07-27_14 27 25](https://user-images.githubusercontent.com/33905242/61993892-6a284200-b07b-11e9-8491-9ab30c2ac79b.png)
"Гравитационная сила"
![2019-07-27_14 28 13](https://user-images.githubusercontent.com/33905242/61993880-2e8d7800-b07b-11e9-8efd-48bb0831ceff.png)
Этот баг проявляется в поножах костюма, если тот имеет модуль
"Ускорители бега"
![2019-07-27_14 44 58](https://user-images.githubusercontent.com/33905242/61993975-1e769800-b07d-11e9-8ba4-246869a7d366.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Не понял сути. Если установлен активный модуль, то он и будет отображаться.

**Comment by Romsik788** [comment]
@BlesseNtumble Понял. Тогда это не баг
