### ISSUE TITLE
Электроинструменты из IC2 разряжают Космический костюм

### ISSUE THREAD

**Issue by QuantumStatement** [BlesseNtumble/GalaxySpace#343]
**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.211
3. GalaxySpace version: 2.0.8
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.8
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

Description of the issue:
------------------------------------------------------------------------
Электроинструменты из IndustrialCraft 2 при использовании разряжают Космический костюм. Скорее всего, это связано с тем, что сам костюм может быть разряжен в энергохранящих блоках (т.е. его можно использовать как аккумулятор)

Версия IC2 2.8.170

Screenshot/Video:
------------------------------------------------------------------------
N/A

Attached log file (or url on pastebin.com):
------------------------------------------------------------------------
N/A

**Comment by CaveJohnson376** [comment]
На баг не похоже, и вообще считай, что это так и должно быть.

**Comment by QuantumStatement** [comment]
> и вообще считай, что это так и должно быть.

Всё бы ничего, но разряженный Космический костюм ломается с одного удара
