### ISSUE TITLE
Absturz beim Start

### ISSUE THREAD

**Issue by Epischer-Mike** [BlesseNtumble/GalaxySpace#344]
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: Newest
3. GalaxySpace version: GalaxySpace-1.12.2-2.0.8.jar
4. AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-0.0.8
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Singleplayer

------------------------------------------------------------------------
Description of the issue:

Jedes mal wenn ich Minecraft mit der Forge Version 1.12.2-14.23.5.2838 starte und damit auch galacticraft und den Zusatz stürtzt mit Minecraft ab bzw. das Fenster verschwindet und ich muss Minecraft über den Task-Manager schließen.
------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

[crash-2019-07-29_17.08.11-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/3442903/crash-2019-07-29_17.08.11-client.txt)
[crash-2019-07-29_17.08.11-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/3442905/crash-2019-07-29_17.08.11-client.txt)
> he game crashed whilst there was a severe problem during mod loading that has caused the game to fail
> Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GalaxySpace (galaxyspace)
> 

------------------------------------------------------------------------

**Comment by Epischer-Mike** [comment]
Übrigens ist das erst seit dem ich Galaxy-Spase und AsmodeusCore hinugefügt habe.

**Comment by Epischer-Mike** [comment]
Galacticraft Version: GalacticraftCore-1.12.2-4.0.2.219
                                 Galacticraft-Planets-1.12.2-4.0.2.219

**Comment by BlesseNtumble** [comment]
Install GC4 211 build.
