### ISSUE TITLE
Изменения настроек не сохраняются после перезапуска игры

### ISSUE THREAD

**Issue by QuantumStatement** [BlesseNtumble/GalaxySpace#345]
**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.211
3. GalaxySpace version: 2.0.8
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.8
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

Description of the issue:
------------------------------------------------------------------------

Настройки мода, изменяемые через внутриигровое меню (`Mods -> GalaxySpace -> Config`), не сохраняются после перезапуска игры

Screenshot/Video:
------------------------------------------------------------------------

N/A

Attached log file (or url on pastebin.com):
------------------------------------------------------------------------

N/A

**Comment by CaveJohnson376** [comment]
Попробуй менять не через это меню, а в конфиг-файле мода.

**Comment by QuantumStatement** [comment]
Уже так и сделал. Но через меню удобнее

**Comment by QuantumStatement** [comment]
В версии 2.0.16 работает
