### ISSUE TITLE
Отключение параметра "enablePlateOreDict" ломает рецепт сжатого сплава "SDHC-120"

### ISSUE THREAD

**Issue by QuantumStatement** [BlesseNtumble/GalaxySpace#346]
**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.211
3. GalaxySpace version: 2.0.8
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.8
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

Description of the issue:
------------------------------------------------------------------------

Отключение параметра `enablePlateOreDict` ломает рецепт сжатого сплава "SDHC-120". Возможно, какие-то другие рецепты также повреждены.

Screenshot/Video:
------------------------------------------------------------------------

![2019-07-30_14 07 07](https://user-images.githubusercontent.com/35406698/62125018-7e1ab080-b2d4-11e9-8cc1-33cdec2859a6.png)

Attached log file (or url on pastebin.com):
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
https://github.com/BlesseNtumble/GalaxySpace/commit/bd2f19373c64edcf416733f76a95c9409358845c
