### ISSUE TITLE
Дуговая печь не удваивает выход слитков с некоторых руд

### ISSUE THREAD

**Issue by QuantumStatement** [BlesseNtumble/GalaxySpace#347]
**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.211
3. GalaxySpace version: 2.0.8
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.8
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

Description of the issue:
------------------------------------------------------------------------

Согласно Galacticraft Wiki, [Электрическая дуговая печь](https://wiki.micdoodle8.com/wiki/Electric_Arc_Furnace) удваивает выход слитков с руд. Но с Кобальтовой, Никелевой и Магниевой рудами это не работает

Screenshot/Video:
------------------------------------------------------------------------

N/A

Attached log file (or url on pastebin.com):
------------------------------------------------------------------------
N/A

**Comment by BlesseNtumble** [comment]
https://github.com/BlesseNtumble/GalaxySpace/commit/484b7a036c700e20b3de5348abec2c41e0a5a617
