### ISSUE TITLE
Crash With Newest Galacticraft (1.12.2)

### ISSUE THREAD

**Issue by KenyMylankca** [BlesseNtumble/GalaxySpace#348]
[crash-2019-08-01_13.37.55-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/3456255/crash-2019-08-01_13.37.55-client.txt)
[debug.log](https://github.com/BlesseNtumble/GalaxySpace/files/3456257/debug.log)
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/3456258/latest.log)

**Comment by CaveJohnson376** [comment]
You forgot to fill form
GS 2.0.8 is NOT compatibe with GC build 212+
Use GC build 211 until GS 2.0.9 is out

**Comment by KenyMylankca** [comment]
ah...didnt know that.

**Comment by KenyMylankca** [comment]
uhm althought, we may keep this issue open to prevent new ones like this... or as you wish, do whatever you want.
