### ISSUE TITLE
Game crash due to MicdoodleCore ?

### ISSUE THREAD

**Issue by xSyphel** [BlesseNtumble/GalaxySpace#349]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.2.224
3. GalaxySpace version: 1.12.2-2.0.8
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.8
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

------------------------------------------------------------------------
Description of the issue: The game crashes straight after the forge loading screen. The only error I find in the crashlog is MicdoodleCore being somehow at fault.

------------------------------------------------------------------------
Screenshot/Video: ~

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[crash-2019-08-04_21.05.10-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/3465221/crash-2019-08-04_21.05.10-client.txt)

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
GS 2.0.8 is not compatible with GC build 212+, please update GS to 2.0.9
