### ISSUE TITLE
Баг во время плавания на Барнарда С

### ISSUE THREAD

**Issue by Romsik788** [BlesseNtumble/GalaxySpace#350]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.224
3. GalaxySpace version:2.0.9
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.9
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
SSP, SSP not opened to LAN
------------------------------------------------------------------------
Description of the issue:
Во время плавания в воде на Барнарда С, на небе исчезают объекты. Это видно на видео

------------------------------------------------------------------------
Screenshot/Video:
https://youtu.be/xRIERwRPtiU
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Поправил проверку позиции, перекачивайте ядро и проверяйте.

**Comment by Romsik788** [comment]
Всё равно исчезают, только теперь когда голова на уровне воды
![2019-08-09_13 47 13](https://user-images.githubusercontent.com/33905242/62773979-42d66980-baac-11e9-971b-cfb81db35777.png)
