### ISSUE TITLE
Client freezes and closes (Зависает и закрывается клиент)

### ISSUE THREAD

**Issue by MongolSpb** [BlesseNtumble/GalaxySpace#353]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.224
3. GalaxySpace version: 2.0.9
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.9
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP/LAN

------------------------------------------------------------------------
Description of the issue:
После обновления 05.08.2019 на версию 2.0.9 при подходе к воде, начало закрывать клиент с ошибкой.
Зависает и закрывается.
С версией 2.0.8 работало хорошо

05.08.2019 after updating to version 2.0.9 in the approach to the water, beginning to close the client with an error.
Hangs and closes.
With version 2.0.8 worked well

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://pastebin.com/kprvAsKw

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
Разработчик русский, можешь не беспокоится.

Насчет ошибки: это скорее всего не связано с водой, только если это не частицы воды, так как ошибка связана с частицами.

**Comment by MongolSpb** [comment]
Бегу, падаю в воду выбрасывает сразу

**Comment by BlesseNtumble** [comment]
Пробуй 2.0.10

**Comment by MongolSpb** [comment]
Всё работает. Спасибо!
