### ISSUE TITLE
Отсутствие изменения цветов дёрна (1.12.2)

### ISSUE THREAD

**Issue by OldieFox** [BlesseNtumble/GalaxySpace#355]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.224
3. GalaxySpace version: 2.0.9
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.9
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):

------------------------------------------------------------------------
Description of the issue:
При установленном Galaxy Space не меняется цвет дёрна в биомах.

------------------------------------------------------------------------
Screenshot/Video:
![1](https://user-images.githubusercontent.com/53820389/62550749-f5cc7a80-b894-11e9-93f6-42593a788679.png)
![2](https://user-images.githubusercontent.com/53820389/62550779-02e96980-b895-11e9-8836-445d43bf3150.png)
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[log.log](https://github.com/BlesseNtumble/GalaxySpace/files/3472883/log.log)
------------------------------------------------------------------------

**Comment by Romsik788** [comment]
Подтверждаю. У меня та же проблема
