### ISSUE TITLE
Latest Version Graphics Glitch

### ISSUE THREAD

**Issue by NihilEntropy** [BlesseNtumble/GalaxySpace#356]
**Do not remove this template, without it your issue will not be considered!**
**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.226
3. GalaxySpace version: 2.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.10
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

------------------------------------------------------------------------
Description of the issue:
Upon installing the new galacticraft and new galaxy space, I saw this really annoying red triangle that changes color depending on where I look. It is mostly prevalent in F1 mode. But also when a world first loads it sometimes appears, maybe due to another mod?

------------------------------------------------------------------------
Screenshot/Video:
![2019-08-08_12 35 00](https://user-images.githubusercontent.com/52515211/62732450-33d2b700-b9d9-11e9-8a5b-0fc9c2294f04.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
Sorry for the large log file, ~130 mods.

[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/3483371/latest.log)

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
If you dont speak russian, don't try to report bug on russian. It makes things even worse.

**Comment by NihilEntropy** [comment]
Got it. Sorry about the bad translation, I tried to save time for people, guess it was unintelligible.

**Comment by BlesseNtumble** [comment]
redownload AsmodeusCore.

**Comment by NihilEntropy** [comment]
That works... Huh, I guess something either went wrong with the download or was asmodeus core patched? It's the same version.

**Comment by BlesseNtumble** [comment]
core
