### ISSUE TITLE
Звёзды резко исчезают на небе на Барнарда С

### ISSUE THREAD

**Issue by Romsik788** [BlesseNtumble/GalaxySpace#357]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.226
3. GalaxySpace version:2.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.10
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
SSP, SSP not opened to lan
------------------------------------------------------------------------
Description of the issue:
Во время рассвета на небе резко, а не плавно, исчезают звёзды. Смотрится не очень

------------------------------------------------------------------------
Screenshot/Video:
https://youtu.be/baq5VhGRznw

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Временно убрал цветные звезды, чем исправил этот баг.
