### ISSUE TITLE
Проблема с новой версией.

### ISSUE THREAD

**Issue by ilya232004** [BlesseNtumble/GalaxySpace#358]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:227
3. GalaxySpace version:2.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.10
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP

------------------------------------------------------------------------
Description of the issue:
После обновления на версию GalaxySpace а 2.0.10 начала глючить миникарта ( в частности луна с включённым описанием), так же при посадке на планеты игра странно глючит ( Появляется загрузка с надписью " Take one giant leap" и зависает , при этом звуки работают и диспетчер задач показывает что игра НЕ зависла), в предыдущей версии аддона GalaxySpace и мода Galacticraft  ничего из этого не было. Скинуть Crashlog не могу из-за того что игра просто не вылетает.

------------------------------------------------------------------------
Screenshot/Video:
![Mods new version](https://user-images.githubusercontent.com/25013658/62819975-c3a56c00-bb65-11e9-8028-bdbdfd75d59b.png)
![Uploading New version 1 problem .png…]()
![New version Moon Problem](https://user-images.githubusercontent.com/25013658/62819981-d029c480-bb65-11e9-8809-2d8ecac0e5dd.png)
![New version problem with planets](https://user-images.githubusercontent.com/25013658/62819982-d15af180-bb65-11e9-869d-bb49a88c3e4f.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by Romsik788** [comment]
GS а точнее AsmodeusCore не совместим с GC 4.0.2.227

**Comment by ilya232004** [comment]
То-есть надо ждать новой версии AsmodeusCore а или новой версии Galacticraft а ?

**Comment by Romsik788** [comment]
Надо ждать новой версии AsmodeusCore

**Comment by ilya232004** [comment]
Всё, спасибо, всё теперь ясно, а то уже 2 дня ломаю голову почему же у меня не идёт.

**Comment by CaveJohnson376** [comment]
Достаточно откатится до билда 226 GC, там таких проблем вроде нет.
И да, удали текущий TL что используешь, так как он является потенциально опасным. И моды там не из проверенных источников. Здесь можно спросить и тебе расскажут больше (где скачать, история о двух TL и многое другое): https://discord.gg/RU2zW9
