### ISSUE TITLE
bad packet

### ISSUE THREAD

**Issue by Nbgreen** [BlesseNtumble/GalaxySpace#359]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.231
3. GalaxySpace version: 0.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.10
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
Multiplayer
------------------------------------------------------------------------
Description of the issue:
I have a player on my server that is getting disconnected from my server after I updated my server/pack to the latest version of gs and Asmodeuscore caused by this error

------------------------------------------------------------------------

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://paste.dimdev.org/ajucunovik.md

------------------------------------------------------------------------

**Comment by Nbgreen** [comment]
turns out I have a few players that have this issue

**Comment by BlesseNtumble** [comment]
SpongeForge?

**Comment by Nbgreen** [comment]
Hey I see you have added the tag that this is fixed in the next version is there anyway I could get you to push out an update early? because currently nun of my players can go to space because of this issue.

**Comment by Nbgreen** [comment]
Yes it’s on a spongeforge server sorry I forgot to mention that
