### ISSUE TITLE
Crash at the opening of creative tabs (1.0.8)

### ISSUE THREAD

**Issue by lex1975** [BlesseNtumble/GalaxySpace#36]
Read this:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2310397-additional-buildcraft-objects-a-plugin-for?comment=164
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2310397-additional-buildcraft-objects-a-plugin-for?comment=170

Crash at the opening of creative tabs.
[crash-2016-03-19_17.28.40-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/180857/crash-2016-03-19_17.28.40-client.txt)

At first I thought it was a mistake mod "GalaxySpace"
I wrote the developer of this mod, but it refers to the error BuildCraft.
When I remove only the modification GalaxySpace-1.0.8+STABLE - crash stop.
When I remove only the modification ABO-MC1.7.10-BC7.1release4.0.8-1 - Crash repeated likewise.
Perhaps it is still incompatible mods Build Craft and Galaxy Space.

My full modlist:
[1.7.10] The Lord of the Rings Mod B27.2.jar
[1.7.10]Treecapitator-universal-2.0.4.jar
ABO-MC1.7.10-BC7.1release4.0.8
advancedgenetics-1.7.10-1.5.9.jar
AdvancedSolarPanel-1.7.10-3.5.1.jar
appliedenergistics2-rv2-stable-10.jar
BiblioCraft[v1.11.4][MC1.7.10].jar
Binnie Patcher 1.6.jar
binnie-mods-2.0-pre14-ru.jar
BiomesOPlenty-1.7.10-2.1.0.1826-universal.jar
buildcraft-7.1.16-ru.jar
buildcraft-compat-7.1.4.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CompactSolars-1.7.10-4.4.39.315-universal.jar
EnchantingPlus-1.7.10-3.0.2-d.jar
ExtraCells-1.7.10-2.3.9b188.jar
forestry_1.7.10-4.2.10.58-ru.jar
GalacticraftCore-1.7-3.0.12.454.jar
Galacticraft-Planets-1.7-3.0.12.454.jar
GraviSuite-1.7.10-2.0.3-ru.jar
Highlands-1.7.2-v-2.2.3.jar
ic2ca-1.7.10-1.14.5.06.jar
IC2NuclearControl-2.3.4a.jar
industrialcraft-2-2.2.817-ru-experimental.jar
ironchest-1.7.10-6.0.62.742-universal.jar
IronChestMinecarts-1.0.4.jar
lookingglass-1.7.10-0.2.0.00.jar
Metallurgy-1.7.10-4.0.8.97.jar
MetallurgyCore-1.7.10-4.0.4.18.jar
MicdoodleCore-1.7-3.0.12.454.jar
MineTweaker3-1.7.10-3.0.10B.jar
ModTweaker2-0.9.5.jar
mystcraft-1.7.10-0.12.3.01.jar
MystNEI-Plugin-1.7.10-02.01.09.jar
neiaddons-1.12.14.40-mc1.7.10.jar
NEIIntegration-MC1.7.10-1.1.2.jar
neiLotr-Alpha 0.4.0.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
OptiFine_1.7.10_HD_U_D1.jar
QuarryPlus-1.7.10-2.1.0.jar
Railcraft_1.7.10-9.9.0.0.jar
Ruins-1.7.10.jar
SpACore-1.7.10-01.05.11.jar
twilightforest-1.7.10-2.3.7.jar
YourRecordsMod[1.7.10][v0.8.1]-ru.jar

**Comment by BlesseNtumble** [comment]
Our add-on has no effect on BC.

**Comment by lex1975** [comment]
GalaxySpace-1.0.7+STABLE works fine with same latest versions BuildCraft and ABO, without crash (I tried open and scroll all the creative tab).

**Comment by da3dsoul** [comment]
Buildcraft makes facades of blocks. I think it's trying to make a facade out of a nonstandard block and crashing. 

FMLInterModComms.sendMessage("BuildCraft|Transport", "blacklist-facade", new ItemStack(block));

Will blacklist facades.
