### ISSUE TITLE
multiple issues

### ISSUE THREAD

**Issue by Nbgreen** [BlesseNtumble/GalaxySpace#361]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.229
3. GalaxySpace version: 0.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.11
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Multiplayer
6. spongeforge version: 1.12.2-2768-7.1.6-RC3616
------------------------------------------------------------------------
Description of the issue:
asteroids spawning in cube chunks
sky box for moon and mars bugged
no launch button for moon
when launching to moon and mars players get stuck on taking one giant leap

------------------------------------------------------------------------
Screenshot/Video:
![2019-08-16_17 52 46](https://user-images.githubusercontent.com/37676381/63202421-2e1b4800-c04f-11e9-8b85-861c16fc03a1.png)
![2019-08-16_17 58 07](https://user-images.githubusercontent.com/37676381/63202476-6f135c80-c04f-11e9-842e-8ffbd2ab9e25.png)
![2019-08-16_17 54 09](https://user-images.githubusercontent.com/37676381/63202417-2bb8ee00-c04f-11e9-8b6d-37ef55ce0a5d.png)
![2019-08-16_17 59 50](https://user-images.githubusercontent.com/37676381/63202845-6d4a9880-c051-11e9-9ad9-452923bd1990.png)
![2019-08-16_18 00 05](https://user-images.githubusercontent.com/37676381/63202847-70458900-c051-11e9-9598-fc2142fe5c0a.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
here is the configs im currently using on the server/client 
[current game configs.zip](https://github.com/BlesseNtumble/GalaxySpace/files/3511370/current.game.configs.zip)

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Try disable venus space station

**Comment by Nbgreen** [comment]
ok then that seems to have fixed all the issues lol
