### ISSUE TITLE
issues crafting

### ISSUE THREAD

**Issue by Nbgreen** [BlesseNtumble/GalaxySpace#362]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.229
3. GalaxySpace version: 0.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.11
5 .Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Multiplayer
6. spongeforge version: 1.12.2-2768-7.1.6-RC3616

------------------------------------------------------------------------
Description of the issue:
cant craft t2 rocket and parts for high tier rockets

------------------------------------------------------------------------
Screenshot/Video:

![unknown](https://user-images.githubusercontent.com/37676381/64547797-05efd380-d2f3-11e9-88c3-1738f0f6411b.png)
![unknown](https://user-images.githubusercontent.com/37676381/64548472-50258480-d2f4-11e9-95a5-063b04522e73.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Update Galacticraft4 build.
It was fix in 233 build.

**Comment by Sandbird** [comment]
Using 1.12.2-4.0.2.244  and i still cant make it
