### ISSUE TITLE
server crashes

### ISSUE THREAD

**Issue by Nbgreen** [BlesseNtumble/GalaxySpace#367]
------------------------------------------------------------------------
1.Minecraft version: 1.12.2
2.Galacticraft version: 4.0.2.237
3.GalaxySpace version: 0.0.10
4.AsmodeusCore version (for 2.0.1 version and above): 0.0.11
5.Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Multiplayer
6.spongeforge version: 1.12.2-2768-7.1.6-RC3616
------------------------------------------------------------------------
Description of the issue:
random server crash
------------------------------------------------------------------------
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://paste.dimdev.org/zokinafeqe.rb
https://paste.dimdev.org/umiqutetim.rb
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Use 236 and below version.
Current version GC4 not support now.
