### ISSUE TITLE
Unplayable bug

### ISSUE THREAD

**Issue by Josh65-2201** [BlesseNtumble/GalaxySpace#368]
------------------------------------------------------------------------
**Versions:**
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.237
3. GalaxySpace version: 2.0.10
4. AsmodeusCore version: 0.0.11 
5. Side: Single player(SSP)

------------------------------------------------------------------------
**Description of the issue:**
When flying in a rocket it will sometimes ether reset the time after 20 seconds or it speeds up/slows down as well as the rocket glitches up and down or the sound cuts out.

But it will always go past the bar and not show the map to launch somewhere and just keeps going until it will crash then reloading gets me stuck in the sky until i open the map a couple times and the launch to the overworld and i can not launch anywhere else.

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/3640202/latest.log)
[debug.log](https://github.com/BlesseNtumble/GalaxySpace/files/3640206/debug.log)
[debug2.log](https://github.com/BlesseNtumble/GalaxySpace/files/3640205/debug2.log)

**Comment by BlesseNtumble** [comment]
#376

**Comment by Josh65-2201** [comment]
i have looked at 376 and have downgraded galaxycraft to 236 and it still happens. Is there anything else i can do.

**Comment by Josh65-2201** [comment]
I found that in the galactic space core config changing "enableSkyOverworld" to false works
