### ISSUE TITLE
Venus bugs

### ISSUE THREAD

**Issue by CyanideCarrot** [BlesseNtumble/GalaxySpace#369]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.237
3. GalaxySpace version: 2.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.11
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

------------------------------------------------------------------------
Description of the issue:
When I try to go to Venus, it crashes then sends me to Enceladus on reload.
If I fall from a Venus Space Station, it sends me to Venus but shows the sky as if I was on one of Saturn's moons.

PS you might want to update the Curseforge page to show Venus is part of Galacticraft 4 now

------------------------------------------------------------------------
Screenshot/Video:
Broken Venus sky: https://imgur.com/a/O5skfbf

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
Directly to Venus, first attempt: https://pastebin.com/3EAhB3Ev
Directly to Venus, after reloading: https://pastebin.com/V46jDcYA
Fall from space station: https://pastebin.com/hiuu9jR0 

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Disable Venus Space Station in config.
