### ISSUE TITLE
Crash when launching Tier 8 rocket

### ISSUE THREAD

**Issue by yannic312** [BlesseNtumble/GalaxySpace#37]
When I place down a Tier 8 rocket, fuel it, get into it and press space to Launch it
after 1 second I get this Crash : http://pastebin.com/LiZu72k5 .
Im using GalaxySpace-1.0.7STABLE, GalacticraftCore-1.7-3.0.12.444 and Galacticraft-Planets-1.7-3.0.12.444.
If you Need more Information just ask :)

I have tried 2 times on one world and then in a new world, both give me the same Crash :/

**Comment by yannic312** [comment]
also, heres the Crash when I try a Tier 3 rocket from galacticraft : http://pastebin.com/dXUqqfRi

**Comment by BlesseNtumble** [comment]
Conflict dimension ID.
configs/GalaxySpace/dimensions.conf
