### ISSUE TITLE
1.7.10-1.2.13 will not boot on a server

### ISSUE THREAD

**Issue by AstroTibs** [BlesseNtumble/GalaxySpace#370]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: **1.7.10, Forge 1614**
2. Galacticraft version: **3.0.12.504**
3. GalaxySpace version: **1.2.13**
4. AsmodeusCore version (for 2.0.1 version and above): _N/A_
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): **SMP**

------------------------------------------------------------------------
Description of the issue:

There is a crash on booting the mod due to a `field not found` error.

------------------------------------------------------------------------
Screenshot/Video:

N/A

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

[https://pastebin.com/TJmRrAMF](https://pastebin.com/TJmRrAMF)

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Redownload build from curse and try again.
