### ISSUE TITLE
При полете на планету происходит бесконечная загрузка

### ISSUE THREAD

**Issue by xthr0** [BlesseNtumble/GalaxySpace#373]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 237
3. GalaxySpace version: 2.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.11
5. Side: Single player

------------------------------------------------------------------------
Description of the issue:
При полете на луну происходит бесконечная загрузка  

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Отключите космическую станцию на Венере в dimensions.conf
