### ISSUE TITLE
No moon launch button

### ISSUE THREAD

**Issue by AstronomyPenguin** [BlesseNtumble/GalaxySpace#374]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2 forge
2. Galacticraft version: GalacticraftCore-1.12.2-4.0.2.237
3. GalaxySpace version: GalaxySpace-1.12.2-2.0.10
4. AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-0.0.11
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Multiplayer

------------------------------------------------------------------------
Description of the issue: Can't go to the moon. There is no Launch button for the moon.

------------------------------------------------------------------------
Screenshot/Video: 
https://drive.google.com/open?id=1-VXz9T-u-6ewFC7xVZ-lsBuxy03HnoB7

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://pastebin.com/ptrF5bMR

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Current build not support 237 GC4 build.
Use below version, ex 236
