### ISSUE TITLE
game can't open

### ISSUE THREAD

**Issue by usta-tr** [BlesseNtumble/GalaxySpace#375]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.211
3. GalaxySpace version:2.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.11
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP

------------------------------------------------------------------------
Description of the issue:

Game crash at loading mods
------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/3746826/latest.log)

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
galacticraftcore    | 4.0.2.211   

Update GC4.
Need min 233 build.
