### ISSUE TITLE
i cant go titan

### ISSUE THREAD

**Issue by usta-tr** [BlesseNtumble/GalaxySpace#376]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.238
3. GalaxySpace version:2.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.11
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP

------------------------------------------------------------------------
Description of the issue:
1. I tryed go to the titan
2.I see titan's sky for 1 seconds
3.Game crashed
------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/3747974/latest.log)

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
2.0.10 build don't support GC4 above 236 version.
Wait new version or install 236 build.
