### ISSUE TITLE
Many Dimensions dont want to load 

### ISSUE THREAD

**Issue by Johnnyboy3148** [BlesseNtumble/GalaxySpace#378]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version:1.12.2-4.0.2.237
3. GalaxySpace version: 1.12.2-2.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.11
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP

------------------------------------------------------------------------
Description of the issue:
Most Dimensions arent loading properly, with one of the more important ones, being the Kuiper Belt, just loading ice cubes, and the moon being orange with the wrong skybox

------------------------------------------------------------------------
Screenshot/Video:
![2019-10-23_16 13 30](https://user-images.githubusercontent.com/53796043/67437818-68591680-f5b7-11e9-91f2-405a74e08c2c.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://pastebin.com/RdmmF0mx

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
disable venus space station in dimensions.conf
