### ISSUE TITLE
Server crashes after flying to new planets

### ISSUE THREAD

**Issue by OceanShadows** [BlesseNtumble/GalaxySpace#379]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.2.238
3. GalaxySpace version: 1.12.2-2.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.11
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP

------------------------------------------------------------------------
Description of the issue:
The Server crashes after selecting and trying to get on every planet. After the Server restarted you get on a completely different planet then the selected. Sorry for bad english.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[crash-2019-10-02_22.15.08-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/3774040/crash-2019-10-02_22.15.08-server.txt)

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
#376
