### ISSUE TITLE
Launch Button Sends to Random Dimension ID? Game Crash on Launch Help!

### ISSUE THREAD

**Issue by Polosolo12** [BlesseNtumble/GalaxySpace#383]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.238
3. GalaxySpace version:2.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.11
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
(Forge version: 14.23.5.2838)

------------------------------------------------------------------------
Description of the issue:

At first I was under the impression that I was choosing planets that were still a WIP (the ones out of the Sol system.) In creative, I launched to Proxima B, only to have the game crash. However, when I relaunched, I was spawned on Callisto, which I only knew by opening the debug screen and looking at the item IDs. Next I tried Barnada C, which caused the same result, except when re-launching I spawned into a very glitched dimension that was seemingly broken. This time I used the /forge tps command to see what dimension I was on, and it showed the dimension ID for mercury. Curious, I teleported to that dimension ID using Mystcraft /tpx command and I just respawned in the same broken dimension. 

At this point, I removed all my mods except for Galacticraft and Galaxy Space to make sure it was not a compatibility issue. I launched to Mercury, and my game once again crashed. This time when I reopened it I respawned on Proxima B. Using forge /tps it said once again I was on a different planet than what I chose-this time it said I was on Callisto. As a final test I launched to Mars, and my game just froze on "taking one small step."

Next I decided to confirm this by doing it again except this time on video. In the video, I launch to Mercury, only for the game to crash. When I respawn, I spawn on Proxima B (Again...)

------------------------
Screenshot/Video:

![Screenshot (1)](https://user-images.githubusercontent.com/54457421/68435980-91f66e00-0171-11ea-9e62-30ab083f680c.png)

![Screenshot (2)](https://user-images.githubusercontent.com/54457421/68435994-9ae73f80-0171-11ea-8895-e80100373ca5.png)

![Screenshot (4)](https://user-images.githubusercontent.com/54457421/68436003-a0dd2080-0171-11ea-97c6-97c79bec2b5e.png)

![Screenshot (5)](https://user-images.githubusercontent.com/54457421/68436016-a76b9800-0171-11ea-85d7-a4f3fe5e1ceb.png)

![Screenshot (6)](https://user-images.githubusercontent.com/54457421/68436044-b7837780-0171-11ea-90ed-edc81f678a15.png)

![Screenshot (7)](https://user-images.githubusercontent.com/54457421/68436051-ba7e6800-0171-11ea-9afd-ae4242b193dc.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

first crash report:

[crash-2019-11-04_20.13.35-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/3812534/crash-2019-11-04_20.13.35-server.txt)

second crash report:
[crash-2019-11-04_20.56.33-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/3812535/crash-2019-11-04_20.56.33-server.txt)

third crash report (the video I took)

[crash-2019-11-05_22.34.23-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/3812538/crash-2019-11-05_22.34.23-server.txt)

log:
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/3822903/latest.log)

And viewing these logs you may see that the dimension I was attempted to tp to was neither the one I selected NOR the one I ended up on....
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
#376 
and disable Venus space station in dimension.conf
