### ISSUE TITLE
[Crash] Crash when you're trying to fly to other dimensions

### ISSUE THREAD

**Issue by slava110** [BlesseNtumble/GalaxySpace#385]
1. Minecraft version: 1.12.2, forge version on pastebin
2. Galacticraft version: 4.0.2.238
3. GalaxySpace version: 2.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.11
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP and LAN at least

------------------------------------------------------------------------
Description of the issue:
Crash sometimes when you're flying to other dimensions. Disabling Venus spacestation doesn't fix it :c
Idk why but... It's not constant. Sometimes it does crash, sometimes it doesn't
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://pastebin.com/SZbcHsmA

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
#376
