### ISSUE TITLE
Crash when Opening World

### ISSUE THREAD

**Issue by jake4832** [BlesseNtumble/GalaxySpace#386]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.238
3. GalaxySpace version: 2.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.11
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

------------------------------------------------------------------------
Description of the issue:
I can launch Minecraft just fine but when I try to open my actual world the game crashes. The first time it crashed I had just placed a modification table and had added battery to my helmet and chest plate. I went to do the same to my spacesuit leggings and the game crashed. I have not been able to open the world since. When the game crashes this message pops up over the launcher "the game crashed while loading nbt data"

Fixed: Ok I found a way to fix it with minimal loss, this took about 6 hours of scientific process to figure out

1. Go into MCEdit and remove the modification table from the world and the spacesuit from your inventory (idk if this is necessary but I did it just in case)
2. Move your player spawn to somewhere far away so that the chunks where all your galacticraft stuff is will be unloaded
3. Save the MCEdit world
4. Remove Galacticraft, Galaxy Space, and their core mods from your mods folder
5. Launch Minecraft and open the world where your spawn point is now moved, as soon as you enter the world click escape and save and exit
6. Move the mods back into your mods folder
7. Re-launch Minecraft and open the world

When you go back to your base all your galacticraft stuff should be there (as the chunks were unloaded when you spawned in with the mods un-installed), the only difference being the modification table gone and spacesuit gone, you can just use creative to get these back if you want. The only damage to the world should be that any galacticraft items (most likely only ores) will be gone in those chunks you spawned into in step 5.

Mods you can remove this post now 

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
Most recent crash report: https://pastebin.com/Ey7D3JUn

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
#376
