### ISSUE TITLE
Сапфир как топливо.

### ISSUE THREAD

**Issue by NicolaiSeven** [BlesseNtumble/GalaxySpace#388]
------------------------------------------------------------------------
1. Minecraft version: 1.7.10
2. Galacticraft version: 3.0.12.504(последний)
3. GalaxySpace version: 1.2.13-pre final
4. AsmodeusCore version (for 2.0.1 version and above): N/A
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP, SMP, LAN

------------------------------------------------------------------------
Description of the issue:
При просмотре через NEI, где используется сапфир, результат показывается, что предмет может быть использован как топливо для печей.
Но он не то, чтобы показывается, а идёт как уголь.
------------------------------------------------------------------------
Screenshot/Video:
https://i.ibb.co/rGzB294/16531.png

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
Можно поинтересоваться, каким лаунчером пользуешься ?(версию тоже укажи)

**Comment by NicolaiSeven** [comment]
> Можно поинтересоваться, каким лаунчером пользуешься ?(версию тоже укажи)

Да пиратка, Rulauncher. У меня раньше была лицензия, но однажды она просто исчезла, пароль, ник, даже redeem код. Спасибо вам моджанг...

**Comment by CaveJohnson376** [comment]
> Да пиратка, Rulauncher. У меня раньше была лицензия, но однажды она просто исчезла, пароль, ник, даже redeem код. Спасибо вам моджанг...

Скорее всего, лицензию украл именно лаунчер, например TL версии 2.х тоже умеет воровать лицензии и не только

**Comment by NicolaiSeven** [comment]
> > Да пиратка, Rulauncher. У меня раньше была лицензия, но однажды она просто исчезла, пароль, ник, даже redeem код. Спасибо вам моджанг...
> 
> Скорее всего, лицензию украл именно лаунчер, например TL версии 2.х тоже умеет воровать лицензии и не только

Хмм, хотя возможно и это, но это всё так давно было. Так что, финансов с размере 2к рэ не имею, буду пиратить. Да и тот исчезнувший аккаунт всё равно был выбит не шибко легитивным способом: то время когда всем давали возможность перейти на Вин10 на халяву раздавали майн, и мои давние знакомые нашли через это способ конвейерного получения аккаунтов официального майна.... Так что, о потере не сильно жалею.

**Comment by NicolaiSeven** [comment]
Вопрос к создателю: будет ли финальная версия этого мода под 1.7.10?
Или уже она не будет поддерживаться?
