### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by chrisfultz** [BlesseNtumble/GalaxySpace#389]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version:1.12.2
3. GalaxySpace version:1.12.2
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):

------------------------------------------------------------------------
Description of the issue: It keeps crashing for an unknown reason. 

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com): 

---- Minecraft Crash Report ----
WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.10-core.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  p455w0rdc0re (p455w0rdslib-1.12.2-2.2.156.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.19.2-release.jar)
  Wizardry Plugin (wizardry-0.10.8.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  Quark Plugin (Quark-r1.5-168.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  RandomPatches (randompatches-1.12.2-1.17.2.1.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.59-core.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  ForgelinPlugin (Forgelin-1.8.3.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.0.381.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.6.0-160-universal.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b165.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 12/16/19 1:12 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GalaxySpace (galaxyspace)
Caused by: java.lang.NoSuchMethodError: asmodeuscore.core.astronomy.BodiesHelper.setNewTierSystem(Z)Z
	at galaxyspace.GalaxySpace.preInit(GalaxySpace.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 345333216 bytes (329 MB) / 4308598784 bytes (4109 MB) up to 9544663040 bytes (9102 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10240m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 316 mods loaded, 316 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                         | Source                                                    | Signature                                |
	|:----- |:--------------------------------- |:------------------------------- |:--------------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2                          | minecraft.jar                                             | None                                     |
	| LCH   | mcp                               | 9.42                            | minecraft.jar                                             | None                                     |
	| LCH   | FML                               | 8.0.99.99                       | forge-1.12.2-14.23.5.2838.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                             | 14.23.5.2838                    | forge-1.12.2-14.23.5.2838.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | advancedrocketrycore              | 1                               | minecraft.jar                                             | None                                     |
	| LCH   | micdoodlecore                     |                                 | minecraft.jar                                             | None                                     |
	| LCH   | openmodscore                      | 0.12.2                          | minecraft.jar                                             | None                                     |
	| LCH   | foamfixcore                       | 7.7.4                           | minecraft.jar                                             | None                                     |
	| LCH   | opencomputers|core                | 1.7.4.153                       | minecraft.jar                                             | None                                     |
	| LCH   | randompatches                     | 1.12.2-1.17.2.1                 | randompatches-1.12.2-1.17.2.1.jar                         | None                                     |
	| LCH   | concheckrmd                       | 1.8.1                           | Modpack Configuration Checker-1.12.2-v1.8.1.jar           | None                                     |
	| LCH   | crafttweaker                      | 4.1.19                          | CraftTweaker2-1.12-4.1.19.jar                             | None                                     |
	| LCH   | mtlib                             | 3.0.6                           | MTLib-3.0.6.jar                                           | None                                     |
	| LCH   | modtweaker                        | 4.0.17                          | modtweaker-4.0.17.jar                                     | None                                     |
	| LCH   | jei                               | 4.15.0.287                      | jei_1.12.2-4.15.0.287.jar                                 | None                                     |
	| LCH   | abyssalcraft                      | 1.9.10                          | AbyssalCraft-1.12.2-1.9.10.jar                            | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | ctm                               | MC1.12.2-0.3.3.22               | CTM-MC1.12.2-0.3.3.22.jar                                 | None                                     |
	| LCH   | roots                             | 1.12.2-3.0.4                    | Roots-1.12.2-3.0.4.jar                                    | None                                     |
	| LCH   | chisel                            | MC1.12.2-0.2.1.35               | Chisel-MC1.12.2-0.2.1.35.jar                              | None                                     |
	| LCH   | baubles                           | 1.5.2                           | Baubles-1.12-1.5.2.jar                                    | None                                     |
	| LCH   | endercore                         | 1.12.2-0.5.59                   | EnderCore-1.12.2-0.5.59.jar                               | None                                     |
	| LCH   | thaumcraft                        | 6.1.BETA26                      | Thaumcraft-1.12.2-6.1.BETA26.jar                          | None                                     |
	| LCH   | codechickenlib                    | 3.2.2.353                       | CodeChickenLib-1.12.2-3.2.2.353-universal.jar             | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux                      | 2.1.0                           | RedstoneFlux-1.12-2.1.0.6-universal.jar                   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cofhcore                          | 4.6.3                           | CoFHCore-1.12.2-4.6.3.27-universal.jar                    | None                                     |
	| LCH   | brandonscore                      | 2.4.17                          | BrandonsCore-1.12.2-2.4.17.208-universal.jar              | None                                     |
	| LCH   | cofhworld                         | 1.3.1                           | CoFHWorld-1.12.2-1.3.1.7-universal.jar                    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | thermalfoundation                 | 2.6.3                           | ThermalFoundation-1.12.2-2.6.3.27-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | draconicevolution                 | 2.3.23                          | Draconic-Evolution-1.12.2-2.3.23.345-universal.jar        | None                                     |
	| LCH   | thermalexpansion                  | 5.5.4                           | ThermalExpansion-1.12.2-5.5.4.43-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | enderio                           | 5.0.46                          | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
	| LCH   | enderiointegrationtic             | 5.0.46                          | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
	| LCH   | mantle                            | 1.12-1.3.3.55                   | Mantle-1.12-1.3.3.55.jar                                  | None                                     |
	| LCH   | twilightforest                    | 3.8.689                         | twilightforest-1.12.2-3.8.689-universal.jar               | None                                     |
	| LCH   | tconstruct                        | 1.12.2-2.12.0.157               | TConstruct-1.12.2-2.12.0.157.jar                          | None                                     |
	| LCH   | acintegration                     | 1.9.0                           | AbyssalCraft Integration-1.12.2-1.9.0.jar                 | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | fastbench                         | 1.7.2                           | FastWorkbench-1.12.2-1.7.2.jar                            | None                                     |
	| LCH   | actuallyadditions                 | 1.12.2-r149                     | ActuallyAdditions-1.12.2-r149.jar                         | None                                     |
	| LCH   | actuallybaubles                   | 1.1                             | ActuallyBaubles-1.12-1.1.jar                              | None                                     |
	| LCH   | additionalbanners                 | 1.1.76                          | AdditionalBanners-1.12.2-1.1.76.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | ic2                               | 2.8.170-ex112                   | industrialcraft-2-2.8.170-ex112.jar                       | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | libvulpes                         | 0.4.1.-60                       | LibVulpes-1.12.2-0.4.1-60-universal.jar                   | None                                     |
	| LCH   | advancedrocketry                  | 1.6.0.-160                      | AdvancedRocketry-1.12.2-1.6.0-160-universal.jar           | None                                     |
	| LCH   | appliedenergistics2               | rv6-stable-7                    | appliedenergistics2-rv6-stable-7.jar                      | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | bdlib                             | 1.14.3.12                       | bdlib-1.14.3.12-mc1.12.2.jar                              | None                                     |
	| LCH   | ae2stuff                          | 0.7.0.4                         | ae2stuff-0.7.0.4-mc1.12.2.jar                             | None                                     |
	| LCH   | p455w0rdslib                      | 2.2.156                         | p455w0rdslib-1.12.2-2.2.156.jar                           | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCH   | ae2wtlib                          | 1.0.30                          | AE2WTLib-1.12.2-1.0.30.jar                                | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCH   | aether_legacy                     | 1.4.4                           | aether_legacy-1.12.2-v1.4.4.jar                           | None                                     |
	| LCH   | aether_legacy_addon               | 1.12.2-v1.2.3                   | aether_continuation-1.12.2-v1.2.3.jar                     | None                                     |
	| LCH   | aiimprovements                    | 0.0.1.1                         | AIImprovements-1.12.1-0.0.1b1.jar                         | None                                     |
	| LCH   | akashictome                       | 1.2-12                          | AkashicTome-1.2-12.jar                                    | None                                     |
	| LCH   | extrautils2                       | 1.0                             | extrautils2-1.12-1.9.9.jar                                | None                                     |
	| LCH   | flyringbaublemod                  | 0.3.1_1.12-d4e654e              | angelRingToBauble-1.12-0.3.1.50+d4e654e.jar               | None                                     |
	| LCH   | applecore                         | 3.2.0                           | AppleCore-mc1.12.2-3.2.0.jar                              | None                                     |
	| LCH   | appleskin                         | 1.0.9                           | AppleSkin-mc1.12-1.0.9.jar                                | None                                     |
	| LCH   | conarm                            | 1.2.4                           | conarm-1.12.2-1.2.4.jar                                   | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCH   | armoryexpansion                   | 1.3.1                           | armoryexpansion-1.3.1.jar                                 | None                                     |
	| LCH   | armoryexpansion-custommaterials   | 1.3.1                           | armoryexpansion-1.3.1.jar                                 | None                                     |
	| LCH   | armoryexpansion-iceandfire        | 1.3.1                           | armoryexpansion-1.3.1.jar                                 | None                                     |
	| LCH   | armoryexpansion-matteroverdrive   | 1.3.1                           | armoryexpansion-1.3.1.jar                                 | None                                     |
	| LCH   | aroma1997core                     | 2.0.0.2.b165                    | Aroma1997Core-1.12.2-2.0.0.2.b165.jar                     | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCH   | aroma1997sdimension               | 2.0.0.2                         | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar           | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCH   | galacticraftcore                  | 4.0.2.220                       | Galacticraft-Mod-1.12.2.jar                               | None                                     |
	| LCH   | galacticraftplanets               | 4.0.2.238                       | Galacticraft-Planets-1.12.2-4.0.2.238.jar                 | None                                     |
	| LCH   | asmodeuscore                      | 0.0.10                          | AsmodeusCore-1.12.2-0.0.11.jar                            | None                                     |
	| LCH   | astralsorcery                     | 1.10.19                         | astralsorcery-1.12.2-1.10.19.jar                          | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCH   | atmtweaks                         | 1.2                             | atmtweaks-1.2.jar                                         | None                                     |
	| LCH   | morphtool                         | 1.2-21                          | Morph-o-Tool-1.2-21.jar                                   | None                                     |
	| LCH   | quark                             | r1.5-168                        | Quark-r1.5-168.jar                                        | None                                     |
	| LCH   | autoreglib                        | 1.3-32                          | AutoRegLib-1.3-32.jar                                     | None                                     |
	| LCH   | badwithernocookiereloaded         | 1.12.2-3.3.16                   | badwithernocookiereloaded-1.12.2-3.3.16.jar               | None                                     |
	| LCH   | betteradvancements                | 0.1.0.77                        | BetterAdvancements-1.12.2-0.1.0.77.jar                    | None                                     |
	| LCH   | betterbuilderswands               | 0.11.1                          | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar           | None                                     |
	| LCH   | bibliocraft                       | 2.4.5                           | BiblioCraft[v2.4.5][MC1.12.2].jar                         | None                                     |
	| LCH   | natura                            | 1.12.2-4.3.2.69                 | natura-1.12.2-4.3.2.69.jar                                | None                                     |
	| LCH   | reborncore                        | 3.14.1.457                      | RebornCore-1.12.2-3.14.1.457-universal.jar                | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCH   | techreborn                        | 2.23.2.1007                     | TechReborn-1.12.2-2.23.2.1007-universal.jar               | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCH   | forestry                          | 5.8.2.387                       | forestry_1.12.2-5.8.2.387.jar                             | None                                     |
	| LCH   | binniecore                        | 2.5.1.188                       | binnie-mods-1.12.2-2.5.1.188.jar                          | None                                     |
	| LCH   | binniedesign                      | 2.5.1.188                       | binnie-mods-1.12.2-2.5.1.188.jar                          | None                                     |
	| LCH   | genetics                          | 2.5.1.188                       | binnie-mods-1.12.2-2.5.1.188.jar                          | None                                     |
	| LCH   | botany                            | 2.5.1.188                       | binnie-mods-1.12.2-2.5.1.188.jar                          | None                                     |
	| LCH   | extrabees                         | 2.5.1.188                       | binnie-mods-1.12.2-2.5.1.188.jar                          | None                                     |
	| LCH   | extratrees                        | 2.5.1.188                       | binnie-mods-1.12.2-2.5.1.188.jar                          | None                                     |
	| LCH   | biomesoplenty                     | 7.0.1.2439                      | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar             | None                                     |
	| LCH   | blockcraftery                     | 1.12.2-1.3.1                    | blockcraftery-1.12.2-1.3.1.jar                            | None                                     |
	| LCH   | cyclicmagic                       | 1.19.13                         | Cyclic-1.12.2-1.19.13.jar                                 | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
	| LCH   | kjlib                             | 1.0.4                           | kjlib-1.0.4.jar                                           | None                                     |
	| LCH   | inventorygenerators               | 1.2.2                           | inventorygenerators-1.2.2.jar                             | None                                     |
	| LCH   | mobtotems                         | 1.12.1-0.3.0                    | mobtotems-1.12.1-0.3.0.jar                                | None                                     |
	| LCH   | guideapi                          | 1.12-2.1.8-63                   | Guide-API-1.12-2.1.8-63.jar                               | None                                     |
	| LCH   | bloodmagic                        | 1.12.2-2.4.1-103                | BloodMagic-1.12.2-2.4.1-103.jar                           | None                                     |
	| LCH   | bookshelf                         | 2.3.585                         | Bookshelf-1.12.2-2.3.585.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | botania                           | r1.10-361                       | Botania r1.10-361.jar                                     | None                                     |
	| LCH   | careerbees                        | 1.0                             | careerbees-0.4.0.jar                                      | None                                     |
	| LCH   | ceramics                          | 1.12-1.3.7                      | Ceramics-1.12-1.3.7.jar                                   | None                                     |
	| LCH   | chameleon                         | 1.12-4.1.3                      | Chameleon-1.12-4.1.3.jar                                  | None                                     |
	| LCH   | chiselsandbits                    | 14.33                           | chiselsandbits-14.33.jar                                  | None                                     |
	| LCH   | cyclopscore                       | 1.4.0                           | CyclopsCore-1.12.2-1.4.0.jar                              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | commoncapabilities                | 2.4.4                           | CommonCapabilities-1.12.2-2.4.4.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | colossalchests                    | 1.7.3                           | ColossalChests-1.12.2-1.7.3.jar                           | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | refinedstorage                    | 1.6.15                          | refinedstorage-1.6.15.jar                                 | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCH   | compactmachines3                  | 3.0.18                          | compactmachines3-1.12.2-3.0.18-b278.jar                   | None                                     |
	| LCH   | compactsolars                     | 1.12.2-5.0.18.341               | CompactSolars-1.12.2-5.0.18.341-universal.jar             | None                                     |
	| LCH   | computercraft                     | 1.80pr1                         | ComputerCraft1.80pr1.jar                                  | None                                     |
	| LCH   | asielib                           | 1.0.0                           | Computronics-1.12.2-1.6.6.jar                             | None                                     |
	| LCH   | flamingo                          | 1.12-1.11                       | Flamingo-1.12-v1.11.jar                                   | None                                     |
	| LCH   | opencomputers                     | 1.7.4.153                       | OpenComputers-MC1.12.2-1.7.4.153.jar                      | None                                     |
	| LCH   | theoneprobe                       | 1.4.28                          | theoneprobe-1.12-1.4.28.jar                               | None                                     |
	| LCH   | computronics                      | 1.6.6                           | Computronics-1.12.2-1.6.6.jar                             | None                                     |
	| LCH   | controlling                       | 3.0.7                           | Controlling-3.0.7.jar                                     | None                                     |
	| LCH   | cookingforblockheads              | 6.4.71                          | CookingForBlockheads_1.12.2-6.4.71.jar                    | None                                     |
	| LCH   | cosmeticarmorreworked             | 1.12.2-v4a                      | CosmeticArmorReworked-1.12.2-v4a.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCH   | craftingtweaks                    | 8.1.9                           | CraftingTweaks_1.12.2-8.1.9.jar                           | None                                     |
	| LCH   | ctgui                             | 1.0.0                           | CraftTweaker2-1.12-4.1.19.jar                             | None                                     |
	| LCH   | crafttweakerjei                   | 2.0.3                           | CraftTweaker2-1.12-4.1.19.jar                             | None                                     |
	| LCH   | cucumber                          | 1.1.3                           | Cucumber-1.12.2-1.1.3.jar                                 | None                                     |
	| LCH   | custombackgrounds                 | 1.0                             | CustomBackgrounds-MC1.12-1.1.1.jar                        | None                                     |
	| LCH   | custommainmenu                    | 2.0.9                           | CustomMainMenu-MC1.12.2-2.0.9.jar                         | None                                     |
	| LCH   | darkutils                         | 1.8.226                         | DarkUtils-1.12.2-1.8.226.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | journeymap                        | 1.12.2-5.5.5b9                  | journeymap-1.12.2-5.5.5b9.jar                             | None                                     |
	| LCH   | defaultoptions                    | 9.2.8                           | DefaultOptions_1.12.2-9.2.8.jar                           | None                                     |
	| LCH   | defaultworldgenerator-port        | 1.12-2.3                        | DefaultWorldGenerator-port-1.12-2.3.jar                   | None                                     |
	| LCH   | diethopper                        | 1.1                             | diethopper-1.1.jar                                        | None                                     |
	| LCH   | ding                              | 1.0.1                           | Ding-1.12.1-1.0.1.jar                                     | None                                     |
	| LCH   | discordsuite                      | 2.2.4                           | DiscordSuite-2.2.4.jar                                    | None                                     |
	| LCH   | dldungeonsjbg                     | 1.12.5                          | DoomlikeDungeons-1.12.5-MC1.12.2.jar                      | None                                     |
	| LCH   | gottschcore                       | 1.9.0                           | GottschCore-mc1.12.2-f14.23.5.2768-v1.9.0.jar             | None                                     |
	| LCH   | dungeons2                         | 1.7.1                           | Dungeons2-mc1.12.2-f14.23.5.2768-v1.7.1.jar               | None                                     |
	| LCH   | dungeontactics                    | DT-0.16.6                       | DungeonTactics-1.12.2-0.16.6.jar                          | None                                     |
	| LCH   | embers                            | 1.13-hotfix2                    | EmbersRekindled-1.13-hotfix2.jar                          | None                                     |
	| LCH   | enderiobase                       | 5.0.46                          | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
	| LCH   | enderioconduits                   | 5.0.46                          | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
	| LCH   | enderioconduitsappliedenergistics | 5.0.46                          | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
	| LCH   | enderioconduitsopencomputers      | 5.0.46                          | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
	| LCH   | enderioconduitsrefinedstorage     | 5.0.46                          | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
	| LCH   | enderiointegrationforestry        | 5.0.46                          | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
	| LCH   | enderiointegrationticlate         | 5.0.46                          | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
	| LCH   | ftblib                            | 5.4.3.130                       | FTBLib-5.4.3.130.jar                                      | None                                     |
	| LCH   | enderiomachines                   | 5.0.46                          | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
	| LCH   | enderiopowertools                 | 5.0.46                          | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
	| LCH   | enderstorage                      | 2.4.5.135                       | EnderStorage-1.12.2-2.4.5.135-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | valkyrielib                       | 1.12.2-2.0.20.1                 | valkyrielib-1.12.2-2.0.20.1.jar                           | None                                     |
	| LCH   | environmentaltech                 | 1.12.2-2.0.20.1                 | environmentaltech-1.12.2-2.0.20.1.jar                     | None                                     |
	| LCH   | mcmultipart                       | 2.5.3                           | MCMultiPart-2.5.3.jar                                     | None                                     |
	| LCH   | mekanism                          | 1.12.2-9.8.0.381                | Mekanism-1.12.2-9.8.0.381.jar                             | None                                     |
	| LCH   | immersiveengineering              | 0.12-89                         | ImmersiveEngineering-0.12-89.jar                          | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCH   | exchangers                        | 1.12.2-2.8                      | Exchangers-1.12.2-2.8.jar                                 | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCH   | excore                            | 2.0.0-beta19-1.12.2             | EXCore-2.0.0-beta19-1.12.2.jar                            | None                                     |
	| LCH   | extracells                        | 2.6.2                           | ExtraCells-1.12.2-2.6.2a.jar                              | None                                     |
	| LCH   | shadowmc                          | 3.8.0                           | ShadowMC-1.12-3.8.0.jar                                   | None                                     |
	| LCH   | extrarails                        | 1.3.0                           | ExtraRails-1.12-1.3.0.jar                                 | None                                     |
	| LCH   | zerocore                          | 1.12.2-0.1.2.8                  | zerocore-1.12.2-0.1.2.8.jar                               | None                                     |
	| LCH   | bigreactors                       | 1.12.2-0.4.5.67                 | ExtremeReactors-1.12.2-0.4.5.67.jar                       | None                                     |
	| LCH   | fairylights                       | 2.1.9                           | fairylights-2.1.9-1.12.2.jar                              | None                                     |
	| LCH   | fencejumper                       | 1.0.5                           | fencejumper-1.12-1.0.5.jar                                | None                                     |
	| LCH   | flatcoloredblocks                 | mc1.12-6.8                      | flatcoloredblocks-mc1.12-6.8.jar                          | None                                     |
	| LCH   | foamfix                           | 0.10.5-1.12.2                   | foamfix-0.10.5-1.12.2.jar                                 | None                                     |
	| LCH   | forgelin                          | 1.8.3                           | Forgelin-1.8.3.jar                                        | None                                     |
	| LCH   | forgemultipartcbe                 | 2.6.1.81                        | ForgeMultipart-1.12.2-2.6.1.81-universal.jar              | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | microblockcbe                     | 2.6.1.81                        | ForgeMultipart-1.12.2-2.6.1.81-universal.jar              | None                                     |
	| LCH   | minecraftmultipartcbe             | 2.6.1.81                        | ForgeMultipart-1.12.2-2.6.1.81-universal.jar              | None                                     |
	| LCH   | ftbutilities                      | 5.4.0.100                       | FTBUtilities-5.4.0.100.jar                                | None                                     |
	| LCH   | ftbbackups                        | 0.0.0.ftbbackups                | FTBUtilitiesBackups-1.0.0.5.jar                           | None                                     |
	| LCH   | funkylocomotion                   | 1.0                             | funky-locomotion-1.12.2-1.1.2.jar                         | None                                     |
	| LCH   | galacticrafttweaker               | 1.12.2-1.0.3                    | GalacticraftTweaker-1.12.2-1.0.3.jar                      | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCE   | galaxyspace                       | 2.0.6                           | Galaxy-Space-Mod-1.12.2.jar                               | None       

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
> Galacticraft version:1.12.2
> GalaxySpace version:1.12.2
> AsmodeusCore version (for 2.0.1 version and above): 1.12.2
Tell the MOD version, not GAME version mod designed for

**Comment by chrisfultz** [comment]
Sorry about that, the Galacticraft version is 4.0.2.238. The GalaxySpace version is 2.0.10 and the AsmodeusCore version is 0.0.11. If these are not it just know I am using the most up-to-date versions of these mods.

**Comment by CaveJohnson376** [comment]
Where did you downloaded the mods?

**Comment by chrisfultz** [comment]
Curse Forge

**Comment by CaveJohnson376** [comment]
What launcher are you using?

**Comment by chrisfultz** [comment]
Twitch

**Comment by CaveJohnson376** [comment]
Try updating all the mods to their latest versions

**Comment by chrisfultz** [comment]
I believe most if not all of these mods are updated, the only one that is crashing is the Galaxy Space but I really don't know why.

**Comment by CaveJohnson376** [comment]
Just try updating 'em all

**Comment by CaveJohnson376** [comment]
So, issue is resolved?
