### ISSUE TITLE
Can't fly to moon / Не работает полет на луну

### ISSUE THREAD

**Issue by coldfeudal** [BlesseNtumble/GalaxySpace#390]
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 237
3. GalaxySpace version: 2.0.10
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.11
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP & SMP

------------------------------------------------------------------------
Description of the issue:
При попытке полета на луну нет кнопки запуска. Если нажать Disable info, появляется, но после самого запуска карта начинает меняться местами с текстом "Takin one giant leap", в таком состоянии и остается

No start button after launch. When "Disable info pressed" enables, but after clicking it start per-fps switching between map and "Taking one giant leap"

------------------------------------------------------------------------
Screenshot/Video:

[proof.zip](https://github.com/BlesseNtumble/GalaxySpace/files/3978588/proof.zip)
Sorry for phone recording

**Comment by BlesseNtumble** [comment]
Try new version.
