### ISSUE TITLE
Unable to Launch with newest update

### ISSUE THREAD

**Issue by ROMVoid95** [BlesseNtumble/GalaxySpace#391]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: **1.12.2**
2. Galacticraft version: **1.12.2-4.0.2.239**
3. GalaxySpace version: **1.12.2-2.0.11**
4. AsmodeusCore version (for 2.0.1 version and above): **1.12.2-0.0.12**
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
Not Applicable
------------------------------------------------------------------------
Description of the issue:
Fails to load during game launch, LaunchWrapper is not able to launch, no window appears
i stated GC version .239 above, this was tried starting with .237 and .238 also

------------------------------------------------------------------------
Screenshot/Video:
N/A

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

[latest.log](https://hasteb.in/fabedene.css)
[debug.log](https://hasteb.in/edobeqib.md)
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
redownload AsmodeusCore and GalaxySpace
