### ISSUE TITLE
Контроллер запуска не распознает Улучшенную взлётную площадку

### ISSUE THREAD

**Issue by QuantumStatement** [BlesseNtumble/GalaxySpace#392]
**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.239
3. GalaxySpace version: 2.0.11
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.12
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

Description of the issue:
------------------------------------------------------------------------
Контроллер запуска не распознаёт Улучшенную взлётную площадку, что не позволяет осуществлять автоматический запуск на ракетах 5 и 6 уровней

Screenshot/Video:
------------------------------------------------------------------------
N/A

Attached log file (or url on pastebin.com):
------------------------------------------------------------------------
N/A

**Comment by BlesseNtumble** [comment]
Контроллер запуска учитывает только стандартную площадку из GC. Ждите нашу версию контроллера.
