### ISSUE TITLE
Шлем космического костюма неправильно отображается на стойке для брони

### ISSUE THREAD

**Issue by QuantumStatement** [BlesseNtumble/GalaxySpace#394]
**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.239
3. GalaxySpace version: 2.0.11
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.12
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

Description of the issue:
------------------------------------------------------------------------
Шлем космического костюма на стойке для брони всегда смотрит на юг вне зависимости от угла поворота стойки

Screenshot/Video:
------------------------------------------------------------------------
![2019-12-06_21 30 14](https://user-images.githubusercontent.com/35406698/71313610-2e3bb200-244c-11ea-8c2f-85f62ae662f5.png)

Attached log file (or url on pastebin.com):
------------------------------------------------------------------------
N/A

**Comment by CaveJohnson376** [comment]
Багоискатель, блен :D
