### ISSUE TITLE
Шлем космического костюма странно подсвечивает мобов в броне

### ISSUE THREAD

**Issue by QuantumStatement** [BlesseNtumble/GalaxySpace#395]
**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.239
3. GalaxySpace version: 2.0.11
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.12
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

Description of the issue:
------------------------------------------------------------------------
Надетый космический шлем дает подсветку мобов. Но броня и оружие, особенно зачарованные, отображаются при этом несколько странно

Screenshot/Video:
------------------------------------------------------------------------
Без шлема
![2019-11-09_17 02 20](https://user-images.githubusercontent.com/35406698/71313678-2597ab80-244d-11ea-8872-94b68c8ec750.png)
С шлемом
![2019-11-09_17 02 27](https://user-images.githubusercontent.com/35406698/71313681-2defe680-244d-11ea-8879-80e92d1dbcd9.png)
Еще с шлемом
![2019-11-09_16 55 33](https://user-images.githubusercontent.com/35406698/71313683-33e5c780-244d-11ea-865b-1927147afb92.png)
![2019-11-09_16 57 49](https://user-images.githubusercontent.com/35406698/71313684-36482180-244d-11ea-9612-372b8f5f74b7.png)

Attached log file (or url on pastebin.com):
------------------------------------------------------------------------
N/A

**Comment by BlesseNtumble** [comment]
Проверьте, актуальна ли ошибка в версии 2.0.13

**Comment by QuantumStatement** [comment]
Да, актуальна

**Comment by BlesseNtumble** [comment]
Проверьте работу сенсорных очков из Galacticraft.

**Comment by QuantumStatement** [comment]
Нда...
![2020-05-04_15 53 57](https://user-images.githubusercontent.com/35406698/81178031-430a8380-8fb0-11ea-8e84-1ed13e2f0590.png)

**Comment by BlesseNtumble** [comment]
Мод лист предоставьте.

**Comment by QuantumStatement** [comment]
Galacticraft 4.0.2.272
AsmodeusCore 0.0.14
GalaxySpace 2.0.13
Smooth Font 2.1.2
OptiFine 1.12.2 HD U F5

<details><summary>мысли</summary>Что-то мне начинает казаться, что виноват сам Galacticraft</details>

**Comment by BlesseNtumble** [comment]
Проверьте без GS

**Comment by Romsik788** [comment]
В GC без GS. 
![2020-06-10_17 04 49](https://user-images.githubusercontent.com/33905242/84277780-9d14e080-ab3c-11ea-8074-20e857e4a403.png)

**Comment by QuantumStatement** [comment]
Без Galaxyspace проблема тоже присутствует. Пошел писать разработчикам Galacticraft.
