### ISSUE TITLE
Looking at Lilypad on Barnada C crashes player

### ISSUE THREAD

**Issue by CommanderLouiz** [BlesseNtumble/GalaxySpace#397]
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.2.239
3. GalaxySpace version: 1.12.2-2.0.11
4. AsmodeusCore version (for 2.0.1 version and above):  1.12.2-0.0.12
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
SMP (Lapitos Galacticraft Modpack)
------------------------------------------------------------------------
Description of the issue:
When looking at a Lillypad on Barnada C, you crash.

Specifically, when you are looking at it with the mod OneProbe installed. According to the log, when OneProbe tries to access the localization files to display the lilypads name, there's an IndexOutOfBounds error that causes the crash.

OneProbe version: 1.12-1.4.28

------------------------------------------------------------------------
Screenshot/Video:
Should be pretty easy to replicate but if requested, I can get one.

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://paste.dimdev.org/kikuhefegu.mccrash

------------------------------------------------------------------------

**Comment by ScienceDrummer** [comment]
I believe this crash is similar, I picked up the item instead. https://paste.dimdev.org/ukexizusuw.mccrash

**Comment by fatcatgamer123** [comment]
this issue still occurs even on 2.0.11, when you pick block
