### ISSUE TITLE
Cofhcore Oregen

### ISSUE THREAD

**Issue by adamcirillo** [BlesseNtumble/GalaxySpace#4]
Can you add cofhcore oregen support the normal galacticraft has support for it I can gen ores on the moon, mars or asteroids no problem but you planets it never works

**Comment by BlesseNtumble** [comment]
Config " S:"Other mods ores for GC to generate on GS planets" <>" tried?

**Comment by adamcirillo** [comment]
Sorry to take so long to get back to you been busy. I was referring to this option in galacticraft config if you could add this to your mod.

 # If generate other mods features is disabled as recommended, this setting can whitelist CoFHCore custom worldgen on planets.
    B:"Whitelist CoFHCore worldgen to generate its ores and lakes on planets"=true

**Comment by adamcirillo** [comment]
I just checked on this today still can't get it to work for some reason can you show me the json code you used for the world gen cause I can get it to work on mars no problems but triton and Pluto no ore gen here is the code I used for mars

"Osmium": {
            "template": "uniform",
            "block": "Mekanism:OreBlock",
            "material": "minecraft:stone",
            "clusterSize": 10,
            "numClusters": 30,
            "minHeight": 5,
            "maxHeight": 80,
            "retrogen": "true",
            "biomeRestriction": "none",
            "biomes": [],
            "dimensionRestriction": "whitelist",
            "dimensions": [
                -29  
            ]
    }

if I change dimensions to -20 triton ore won't spwan.

also used version 1.0.9 of galaxyspace
galaicticraft build 460
cofhcore 3.1.2-325

**Comment by adamcirillo** [comment]
I managed to finally get this working I had to use "material": { "name" :"GalaxySpace:plutoblocks", "metadata" : 4 }, with the block of the planet I wanted to get the ores spawn so it was just bad config I wish I realised this sooner
