### ISSUE TITLE
Новая планета...

### ISSUE THREAD

**Issue by Shurik1236** [BlesseNtumble/GalaxySpace#40]
Я знаю, вы в группе писали, что не будете пока добавлять планеты, но такое на заметку взять стоит.
Итак, мне кажется стоит добавить планету идентичную земле.
То есть вообще идентичную. Те же мобы, генерация и так далее.
Но это не всё. Надо добавить для этой планеты продвинутую конфигурацию.
1. Планета по умолчанию будет отключена. И будет базой для мод-паков.
2. Руды. Генерация руды зависима от овера, что ванила/моды добавляют на землю, будет на этой планете. Но в конфиге можно будет отключить руду вообще. И разрешить генерировать руды только через конфиг в аддоне, либо через CoFH Core.
3. Данжи. Все структуры которые добавлены в овер будут спавнится и тут.
   Метеориты из AE2... Тотемы, алтари и так далее из таума... Всё можно будет найти.
   Но вот тут есть проблема, если выключить данжи в овере из таума, они вообще не будут спавнится. Придётся как то подхватывать и спавнить структуры обходя конфиги модов.
4. Возможность выбора отдельного генератора мира.
   Например, землю генерирует Wasteland mod (Генератор овера выбирается при создании мира). Земля - безжизненная пустыня.
   Игрок улетает с земли, и добыв нужное количество ресурсов прилетает на эту планету...
   А там мир генерирует не Wasteland mod, а скажем BiomesOPlenty!
   Или ExtrabiomesXL, ATG, RTG и так далее.
   То есть можно поставить вообще два разных мода на биомы, один для Земли, второй для планеты X.

Вот нагородил... Даже не знаю, можно ли это реализовать...

**Comment by BlesseNtumble** [comment]
Зачем?
На сервере банально можно сгененрировать новый мир и через плагин прыгать между этими мирами.

**Comment by Shurik1236** [comment]
А если это сингл? И как через плагин можно заставить игроков попадать туда ракетой определённого уровня? Ну и вообще разве можно плагином добавить планету на галактическую карту?
Мир отдельный сделать и телепортироваться туда командой это ерунда.
А вот сделать так что бы туда можно было попасть на ракете из мода это уже круто.
