### ISSUE TITLE
Weird things then launching to another planet

### ISSUE THREAD

**Issue by MorePortal** [BlesseNtumble/GalaxySpace#400]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 238 or 243
3. GalaxySpace version: 2.0.11
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.12
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

------------------------------------------------------------------------
Description of the issue:
When I launch to random planet, it freezes. After reloading, I'm ending on an another (random) planet. For example, I'm launching to Moon, then (after reloading) I'm on Ganymede with surface of
Koentus (MorePlanets Planet).

I don't know if it's a GalaxySpace or MorePlanets issue

------------------------------------------------------------------------
Screenshot/Video:
![2020-01-13_19 19 21](https://user-images.githubusercontent.com/19516422/72272553-df8fcb00-3639-11ea-8f0c-033a6ab2a908.png)
![2020-01-13_19 20 28](https://user-images.githubusercontent.com/19516422/72272554-df8fcb00-3639-11ea-9a92-3e375bed59a9.png)
![2020-01-13_19 20 57](https://user-images.githubusercontent.com/19516422/72272555-df8fcb00-3639-11ea-968c-d7c3a50e0abd.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/4054531/latest.log)

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
Send a crash-report pls (latest created file in `.minecraft/crash-reports`), because it has some more info about the crash.

**Comment by MorePortal** [comment]
It doesn't crash, but "Taking one small step" won't disappear until I manually close the game.

**Comment by CaveJohnson376** [comment]
I need full mod list (including "hidden" mods, mods that appears in the game without putting it into mods folder)

**Comment by MorePortal** [comment]
MCP
FML
Forge
Micdoodle8 Core
GC Core & Planets
AsmodeusCore & GalaxySpace
SteveKunG's Lib & More Planets

Thats all

**Comment by BlesseNtumble** [comment]
delete file configs/GalaxySpace/dimensions.conf and try

**Comment by MorePortal** [comment]
Now it works
The error was caused by enableVenusSpaceStation=false which I used to fix #361
Thanks!
