### ISSUE TITLE
Вылет игры на барнаде С

### ISSUE THREAD

**Issue by KiraLinux** [BlesseNtumble/GalaxySpace#401]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1.12.2
GalacticraftCore-1.12.2-4.0.2.239.jar
Galacticraft-Planets-1.12.2-4.0.2.239.jar 
GalaxySpace-1.12.2-2.0.11.jar  
AsmodeusCore-1.12.2-0.0.12.jar 
Single player

------------------------------------------------------------------------
Description of the issue: вылет игры когда я посмотрел на траву Lillypad 

[crash-2020-01-15_23.39.07-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/4067443/crash-2020-01-15_23.39.07-client.txt)
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/4067445/latest.log)

**Comment by CaveJohnson376** [comment]
ToP не может нормально отобразить сей блок, сейчас гляну, имеется ли конфиг на отключение рендера...

UPD: К сожалению такой настройки нету :(

**Comment by BlesseNtumble** [comment]
#397
