### ISSUE TITLE
Tier 3 Rocket Schematics

### ISSUE THREAD

**Issue by Gandalf360one** [BlesseNtumble/GalaxySpace#407]
Where can I find the tier 3 rocket schematics ?

**Comment by BlesseNtumble** [comment]
Removed.
Check new recipe for Tier 3 Rocket in NEI/JEI.

**Comment by Gandalf360one** [comment]
I know but where can I find the new schmatics for the rocket parts ?

**Comment by BlesseNtumble** [comment]
Schematic Box on Moon

**Comment by Gandalf360one** [comment]
And where can I find the Schematic Box on the Moon ?

**Comment by BlesseNtumble** [comment]
Dungeon
