### ISSUE TITLE
Server crashed on moon

### ISSUE THREAD

**Issue by mMONTAGEe** [BlesseNtumble/GalaxySpace#417]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0
3. GalaxySpace version:2.0.12
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.13
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SMP

------------------------------------------------------------------------
Description of the issue:
server and minecraft crashed after launching to moon

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://pastebin.com/ABvxsDn4
https://pastebin.com/ibMKT7TS

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Redownload AsmodeusCore
