### ISSUE TITLE
Strange entity from Barnarda C crashing my server

### ISSUE THREAD

**Issue by DRPHONICS** [BlesseNtumble/GalaxySpace#418]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.2.244
3. GalaxySpace version: 1.12.2-2.0.11
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.12
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP

------------------------------------------------------------------------
Description of the issue:

A mysterious water mob from barnarda C causing the crash of my server
------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

https://pastebin.com/HMhEiJRu
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
| LCHIJA | asmodeuscore        | 0.0.13            | AsmodeusCore-1.12.2-0.0.13.jar                      | None 

you use 0.0.13 version with old GS 2.0.11 version

**Comment by DRPHONICS** [comment]
i already changed the 0.0.13 to 0.0.12 and it still says that the 0.0.13 is in there
