### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by DRPHONICS** [BlesseNtumble/GalaxySpace#419]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version: 1.12.2 - 4.0.2.244
3. GalaxySpace version: 1.12.2-2.0.11
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.12 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
SMP
------------------------------------------------------------------------
Description of the issue:
server crash i dont know why

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://pastebin.com/DcyG0b2U

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Not GS issue.
