### ISSUE TITLE
Suggestion for 1.0.9

### ISSUE THREAD

**Issue by sexyasianboy** [BlesseNtumble/GalaxySpace#42]
Suggestion for 1.0.9:

Is it able to add sandstorms on mars, which would do damage and decrease the sight. So it is some special equipment needed to not getting those dmg.

**Comment by Dream-Master** [comment]
Yes and add fog and clouds back on Venus.

**Comment by Dream-Master** [comment]
"not a GalaxySpace issue"?  This was an suggestion and i remember Venus have fog before.

**Comment by BlesseNtumble** [comment]
Fog I returned, and Mars does not belong to us.

**Comment by Dream-Master** [comment]
Cool thanks.
