### ISSUE TITLE
GalaxySpace-2.0.12 does not work

### ISSUE THREAD

**Issue by TeiBri** [BlesseNtumble/GalaxySpace#421]
------------------------------------------------------------------------
1. Minecraft version: 1.12.2-forge1.12.2-14.23.5.2847
2. Galacticraft version:  GalacticraftCore-1.12.2-4.0.2.244
3. GalaxySpace version:   2.0.12
4. AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-0.0.13.jar
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):  SSP

------------------------------------------------------------------------
Description of the issue:
Nejde mi to spustit!

------------------------------------------------------------------------
Screenshot/Video:

![](https://www.thomasvdbulk.nl/minecraft/background5.png)

Tenhle obrázek je na mé obrazovce furt!
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
Žádný problém to nehlásí! :( Nenačítá se to!

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
use pastebin

**Comment by TeiBri** [comment]
Omlovám se ale problém je v tom že mi to problém nehlásí prostě je tam jen ta obrazovka. :/

**Comment by BlesseNtumble** [comment]
logs/latest.log

**Comment by TeiBri** [comment]
https://pastebin.com/CRYJ5it8

:)

**Comment by BlesseNtumble** [comment]
Redownload GS and AC from Curse.

**Comment by TeiBri** [comment]
Thank you! Are you best! :D And your addon is the best! :)

![2020-04-10_13 48 55](https://user-images.githubusercontent.com/62265168/78988786-2a828700-7b32-11ea-89bc-c783430e3ef9.png)

**Comment by BlesseNtumble** [comment]
Np. all fo you.
