### ISSUE TITLE
Краш сервера

### ISSUE THREAD

**Issue by Whylfoff** [BlesseNtumble/GalaxySpace#425]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4 0 2 244
3. GalaxySpace version:2 0 12
4. AsmodeusCore version (for 2.0.1 version and above): 0 0 13
5. Multiplayer (SMP)
------------------------------------------------------------------------
Description of the issue:
Получается я лечу на ракету долетаю в итоге должна открыться космическая карта но вдруг серв выключается и все.

------------------------------------------------------------------------
Screenshot/Video:
https://yadi.sk/i/UJdsVQVcxltYYA

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

https://yadi.sk/d/VokJ4wbWqasXsg
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Перекачайте GS и AC с curse.
