### ISSUE TITLE
Плуто крашится из-за какой-то странной несовместимости с Extra Planets.

### ISSUE THREAD

**Issue by DanielAntony201** [BlesseNtumble/GalaxySpace#426]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.7.10
2. Galacticraft version:7-3.0.12.504
3. GalaxySpace version:1.2.13
4. AsmodeusCore version (for 2.0.1 version and above): Что за Асмодеус Кор? У меня без этого работает. Стоит её установить? Я что-то неправильно делаю?
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):

SSP
------------------------------------------------------------------------
Description of the issue:

Когда ты Спавнишься в  Плуто, то игра либо крашится сразу, либо после нескольких минут прогулок по Плуто. Я эту проблему доложил MJRLegends, но он сказал, что проблема не в Extra Planets. Не поможешь?
Название краша такое.
java.lang.ClassCastException: com.mjr.extraplanets.planets.Kepler22b.worldgen.biome.BiomeGenKepler22bDiamondPlains cannot be cast to galaxyspace.core.world.gen.GSBiomeGenBase

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

Вот ссылка на Краш-Репорт.

https://pastebin.com/0RZMfYNP
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Ну так у вас 2 планеты одновременно включены. Отключите одну из них в конфиге аддона.

**Comment by CaveJohnson376** [comment]
Можно еще поинтересоваться информацией о используемом лаунчере?

**Comment by DanielAntony201** [comment]
Стандартный официальный Майнкрафт Лаунчер.
 Насчёт выключения планеты проверю, хотя MJRLegends уже добавил опцию совместимости. Когда её включаешь, то обычная Плуто вырубается и включается новая Pluto 2.0. Ладно, всё равно проверю. Но мне MJRLegends сказал, что проблема именно в вашем моде, в коде, и что при её создании вы не учитывали существование других измерений из других модов.
 К тому же,BlesseNtumble.
 проблема была не в существовании двух одинаковых Плуто. Краш Репорт же сказал, что Биом Kepler 22b почему-то хотел появляться в Плуто вашего мода. Прочитайте Краш-Репорт внимательно. MJRLegends сказал, что проблема в вашем моде, а не в Extra Planets. Я же поставил ссылку на Pastebin с Краш Репортом, Проверьте, пожалуйста.

**Comment by DanielAntony201** [comment]
BlesseNtumble Ты уверен, что проблема в двух одинаковых Плуто? Так было написано в краш Репорте?

**Comment by DanielAntony201** [comment]
BlesseNtumble
Уже попытался. Я выключил Плуто из Extra Planets и Pluto 2.0 исчезла из карты, как и полагалось. После этого я снова пошёл на Плуто Galaxy Space. После 2 минут она крашнула. Та же самая проблема.
java.lang.ClassCastException: com.mjr.extraplanets.planets.Kepler22b.worldgen.biome.BiomeGenKepler22bDiamondPlains cannot be cast to galaxyspace.core.world.gen.GSBiomeGenBase

Надеюсь вы не проигнорируйте эту проблему.

**Comment by BlesseNtumble** [comment]
проверяйте ID Kepler22b и Плутона из GS

**Comment by DanielAntony201** [comment]
А как мне это проверить? Их ID можно как-то поменять? Или это вы должны поменять?

**Comment by DanielAntony201** [comment]
Окей, я нашёл это в конфигах, проблема в спавне биомов. Но на какое число мне стоит поменять  ID некоторых биомов? Любое рандомное сойдёт?

**Comment by BlesseNtumble** [comment]
пойдет.
