### ISSUE TITLE
Buildcraft and galaxyspace

### ISSUE THREAD

**Issue by mMONTAGEe** [BlesseNtumble/GalaxySpace#427]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:
2. Galacticraft version:
3. GalaxySpace version:
4. AsmodeusCore version (for 2.0.1 version and above): 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):

------------------------------------------------------------------------
Description of the issue:
in creative menu game crashes on page 3

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

https://pastebin.com/HYH48ZPz
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Update GC (250 build and above).
