### ISSUE TITLE
Визуальный и физически ограждающий и мешающий баг.

### ISSUE THREAD

**Issue by DanielAntony201** [BlesseNtumble/GalaxySpace#429]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.7.10
2. Galacticraft version:7-3.0.12.504
3. GalaxySpace version:1.2.13
4. AsmodeusCore version (for 2.0.1 version and above): 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):

------------------------------------------------------------------------
Description of the issue:

Неправильное отображение Требуемого уровня ракет для Планет. Это мешает путешествию по планетам. Иногда показывает слишком высокие требования тиров и из-за этого нельзя спуститься к низкоуровневым планетам.
------------------------------------------------------------------------
Screenshot/Video:

![2020-04-17_17 53 33](https://user-images.githubusercontent.com/60870366/79576996-18c25600-80d5-11ea-9ff9-e524fe59fb65.png)
![2020-04-17_17 53 38](https://user-images.githubusercontent.com/60870366/79577002-19f38300-80d5-11ea-8d76-0fa6d1222b09.png)
![2020-04-17_17 54 08](https://user-images.githubusercontent.com/60870366/79577007-1b24b000-80d5-11ea-8e3f-92aeeaa3c116.png)
![2020-04-17_17 54 22](https://user-images.githubusercontent.com/60870366/79577011-1bbd4680-80d5-11ea-97d6-c3771ec4edc5.png)
![2020-04-17_17 54 48](https://user-images.githubusercontent.com/60870366/79577202-65a62c80-80d5-11ea-928c-757425c756bf.png)
![2020-04-17_17 54 41](https://user-images.githubusercontent.com/60870366/79577206-66d75980-80d5-11ea-8172-b52b2969edf3.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by DanielAntony201** [comment]
Так это исправить никак нельзя что-ли? Блин.

**Comment by DanielAntony201** [comment]
А с этим вообще нельзя ничего делать?

**Comment by BlesseNtumble** [comment]
Это не баг. Это улучшенная система уровней.
Синхронизация расстояний.
