### ISSUE TITLE
java.lang.IllegalArgumentException: Could not get provider type for dimension -N, does not exist (N - число) 

### ISSUE THREAD

**Issue by AleksStar** [BlesseNtumble/GalaxySpace#43]
Galaxy Space 1.08 и Applied Energistics 2 stable-10 вызывает следующую ошибку

java.lang.IllegalArgumentException: Could not get provider type for dimension -N, does not exist (N - число) 
Замена ID в Galaxy Space не помогает. Вылетает ошибка того id что было заменено, если отключать планету ID которой вызывает ошибку то данную ошибку вызывает следующие id планеты
Заменить ID в Applied Energistics 2 не вижу способа. 
Подозреваю что большинство проблем с крашем адона именно из за конфликтов с этим распространенным и необходимым индустриальным модом.
[2016-04-08-6.log.gz](https://github.com/BlesseNtumble/GalaxySpace/files/209816/2016-04-08-6.log.gz)

**Comment by BlesseNtumble** [comment]
На сервере все это?

**Comment by AleksStar** [comment]
нет это клиент крашится, убираю спейс мод и все работает без ошибок.

**Comment by BlesseNtumble** [comment]
Это явный конфликт ID измерений.
Проверим GS и AE2 rev10.

**Comment by BlesseNtumble** [comment]
Вы уверены, что конфликтов нет?
У нас на сервере стоит 10 рева и GS 1.0.8.
Вылетов нет.
Возьмите конфиги с нашего сервера.

Если поможет - закройте тему.
Если не поможет - отпишитесь тут.

**Comment by AleksStar** [comment]
Хорошо я могу получить ссылку на ваши конфиги? Из Вашего ответа я не могу понять откуда мне их взять.

**Comment by BlesseNtumble** [comment]
http://galaxytechnology.myarena.ru
