### ISSUE TITLE
buildcraft and galaxy space crash

### ISSUE THREAD

**Issue by mMONTAGEe** [BlesseNtumble/GalaxySpace#430]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0
3. GalaxySpace version: latest one
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.13
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):

------------------------------------------------------------------------
Description of the issue:
when i try to open creative page 3 or write in search. En,Engine,pa.pad,oil minecraft crashes

------------------------------------------------------------------------
Screenshot/Video:
https://drive.google.com/file/d/19KeWr2d0KpUA97D2r57b3bLESERNeEdF/view?usp=sharing
https://drive.google.com/file/d/1inpTdfJfmfA6oT77SRoQHc9oxJ3u_8hv/view?usp=sharing
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
Minecraft Crash log - https://pastebin.com/hf46C8By
gALAXY SPACE - https://pastebin.com/N9Wws303
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
#427
