### ISSUE TITLE
Cant land on planets with buildcraft

### ISSUE THREAD

**Issue by mMONTAGEe** [BlesseNtumble/GalaxySpace#431]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0
3. GalaxySpace version:1.0.12
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.13
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP

------------------------------------------------------------------------
Description of the issue:
i cant fly to planets!

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://pastebin.com/wDUmBkEs

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
#437
