### ISSUE TITLE
Это так должно быть?

### ISSUE THREAD

**Issue by DanielAntony201** [BlesseNtumble/GalaxySpace#433]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.7.10
2. Galacticraft version:3.0.12.504
3. GalaxySpace version:1.2.13.
4. AsmodeusCore version (for 2.0.1 version and above): 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):

------------------------------------------------------------------------
Description of the issue:

Я полетел на Меркурий на Тир 3 ракете и мне почему-то показывает, что для полёта на Марс нужна Тир 4 ракета. Это так должно быть? И это не единственная проблема. Церес и пояс Астеройдов вообще показывает, что нужна тир 6 ракета, хотя должно было быть тир 4. И я подозреваю, что это не единственные проблемы с этой проблемой.
------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

![2020-04-19_12 43 01](https://user-images.githubusercontent.com/60870366/79683743-2561be00-823d-11ea-9fb8-faf4a3592cdf.png)
![2020-04-19_12 38 12](https://user-images.githubusercontent.com/60870366/79683745-272b8180-823d-11ea-81eb-9958d3ebb13b.png)
![2020-04-19_12 38 39](https://user-images.githubusercontent.com/60870366/79683746-272b8180-823d-11ea-86d4-fdafe7dc50a6.png)
![2020-04-19_12 40 38](https://user-images.githubusercontent.com/60870366/79683747-27c41800-823d-11ea-8089-776adb49d681.png)

------------------------------------------------------------------------

**Comment by mMONTAGEe** [comment]
это так задумыволос

**Comment by DanielAntony201** [comment]
Сомневаюсь. Ты моё описание читал вообще? Планеты требуют больше должного. Почему Марс требует тир 4, если у меня тир 3, а Марс вообще должен быть тир 2?

**Comment by mMONTAGEe** [comment]
чем дольше отдолаеша тем больше уровня

**Comment by DanielAntony201** [comment]
Всмылсе? то-есть ты хочешь сказать, что от Меркурия к Марсу так далеко?

**Comment by CaveJohnson376** [comment]
Все именно так, в GalaxySpace имеется механика расстояния между планетами: чем дальше лететь, тем выше должен быть уровень ракеты
