### ISSUE TITLE
Spacesuit on armour stands cause memory leaks and FPS Drops.

### ISSUE THREAD

**Issue by Josh65-2201** [BlesseNtumble/GalaxySpace#434]
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.244
3. GalaxySpace version: 2.0.12
4. AsmodeusCore version : 0.0.13
5. Single player, Multiplayer, opened to LAN: All

------------------------------------------------------------------------
Description of the issue:
When having the spacesuit armor on a armor stand the frame rate drops by at least half and then uses all my memory and crashes.

------------------------------------------------------------------------
Screenshot/Video:
None

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/4499429/latest.log)

------------------------------------------------------------------------

**Comment by Josh65-2201** [comment]
Update: The memory doesn't seem to be an issues in 2.0.13 but FPS drops still happens.

[2020-05-02-4.txt](https://github.com/BlesseNtumble/GalaxySpace/files/4569137/2020-05-02-4.txt)

**Comment by Romsik788** [comment]
I can confirm. This is also visible in the video. https://youtu.be/DgpE2O9CJ7M I also want to add that the shoes do not appear on a armor stand

**Comment by Josh65-2201** [comment]
the video is private

**Comment by Romsik788** [comment]
@josh-65 Give me a sec... Video not uploaded yet
EDIT: Done.

**Comment by Romsik788** [comment]
FPS also drops when you press f5
![2020-07-13_19 03 15](https://user-images.githubusercontent.com/33905242/87326794-e68d8c80-c53b-11ea-9008-514078428fea.png)
![2020-07-13_19 03 23](https://user-images.githubusercontent.com/33905242/87326801-e8575000-c53b-11ea-9ff4-eb66e928bfc8.png)

**Comment by BlesseNtumble** [comment]
Check in 2.0.15
