### ISSUE TITLE
Штото сломалось 

### ISSUE THREAD

**Issue by mMONTAGEe** [BlesseNtumble/GalaxySpace#435]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.254
3. GalaxySpace version: 2.0.12
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.13
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP

------------------------------------------------------------------------
Description of the issue:
minecraft ломается после полёта на планеты но после удаления оно заработало даже с  buildcraft

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://pastebin.com/q30ALM5r heres latest log 

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
GS не поддерживает GC выше 247 билда (там изменили некоторые методы).
Скачивайте 247 билд GC.
