### ISSUE TITLE
Can't load world

### ISSUE THREAD

**Issue by Josh65-2201** [BlesseNtumble/GalaxySpace#436]
Versions:
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.254
3. GalaxySpace version: 2.0.12
4. AsmodeusCore version: 0.0.13 
5. Side : Single player

------------------------------------------------------------------------
Description of the issue:
When loading a world it crashes without debug mode on. but will always crash when trying to reload the world.

------------------------------------------------------------------------
Screenshot/Video:
None

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/4503506/latest.log)

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
GS now don't work with GC above 247 build.
Downgrade GC.

**Comment by Josh65-2201** [comment]
It still happends on 244 and 247.

**Comment by BlesseNtumble** [comment]
#437
