### ISSUE TITLE
Crashing everytime someone tries to land on a planet

### ISSUE THREAD

**Issue by BestAardvark** [BlesseNtumble/GalaxySpace#437]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.256
3. GalaxySpace version: 2.0.12
4. AsmodeusCore version (for 2.0.1 version and above):  0.0.13
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP

------------------------------------------------------------------------
Description of the issue:
When anyone on the server tries to go to any planets they get stuck in the loading screen then crash.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://pastebin.com/LDUAemmJ

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Try 2.0.13 build.
