### ISSUE TITLE
Сломанные текстуры у некоторых блоков

### ISSUE THREAD

**Issue by QuantumStatement** [BlesseNtumble/GalaxySpace#438]
Please fill in the form below:
---
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.272
3. GalaxySpace version: 2.0.12
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.14
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

Description of the issue:
---
У Улучшенного корпуса машин, Кислородного массива, Улучшенного электрического компрессора и Улучшенного производителя микросхем отсутствуют текстуры для некоторых сторон

Screenshot/Video
---
![2020-04-28_01 18 51](https://user-images.githubusercontent.com/35406698/80427214-e8a65e80-88ef-11ea-92b6-09cd88d43948.png)

![2020-04-28_01 28 07](https://user-images.githubusercontent.com/35406698/80427224-ee03a900-88ef-11ea-8237-a121cbc968bb.png)

Attached log file (or url on pastebin.com):
---
N/A

**Comment by MaxwellYe0815** [comment]
galaxyspace:oxygen_storage_module_1
galaxyspace:machineframes
galaxyspace:adv_electric_compressor
galaxyspace:adv_circuit_fabricator

**Comment by MaxwellYe0815** [comment]
I checked the model files of GC and GS. The reason for this problem is probably because the author of GS used the texture file of GC, and the author of GC moved some of the texture from "Galacticraft-Planets" to "Galacticraftcore". Among them are those used by GS authors.

**Comment by YlimazYe** [comment]
![屏幕截图(79)](https://user-images.githubusercontent.com/64358442/80553746-7de34900-89fd-11ea-899b-72bcf576b35b.png)
![屏幕截图(80)](https://user-images.githubusercontent.com/64358442/80553753-8045a300-89fd-11ea-9202-1e348e3f328a.png)

**Comment by MaxwellYe0815** [comment]
![1](https://user-images.githubusercontent.com/64358442/80553788-a4a17f80-89fd-11ea-8f6d-e996a7aa7874.png)
![2](https://user-images.githubusercontent.com/64358442/80553793-a5d2ac80-89fd-11ea-9e90-6880b155fa13.png)

**Comment by MaxwellYe0815** [comment]
I successfully fixed this bug, but I am just a player and not the author. So I can't update the mod

**Comment by YlimazYe** [comment]
![3](https://user-images.githubusercontent.com/64358442/80559359-dae7fa80-8a0f-11ea-8663-aefacbe68251.png)

**Comment by YlimazYe** [comment]
![3](https://user-images.githubusercontent.com/64358442/80559567-842ef080-8a10-11ea-930a-53b680d810f4.png)
![4](https://user-images.githubusercontent.com/64358442/80559572-85f8b400-8a10-11ea-8859-6eb2bf78ae33.png)

**Comment by MaxwellYe0815** [comment]
![3](https://user-images.githubusercontent.com/64358442/80560118-619dd700-8a12-11ea-9330-04531dcd0131.png)
![4](https://user-images.githubusercontent.com/64358442/80560120-62cf0400-8a12-11ea-8e88-7a5f015e455c.png)

**Comment by sergey-byte** [comment]
YlimazYe can you throw off the mod fix?

**Comment by MaxwellYe0815** [comment]
> YlimazYe can you throw off the mod fix?

why do you ask me to give it up?
or 'throw off' means "upload"?
If it ’s ‘upload’,here you are.
i can't upload a jar file so you should change File extension from .zip to ,jar
[[星系附属][Fixed]GalaxySpace-1.12.2-2.0.12.zip](https://github.com/BlesseNtumble/GalaxySpace/files/4550914/Fixed.GalaxySpace-1.12.2-2.0.12.zip)

**Comment by sergey-byte** [comment]
I'm sorry I don't know English very well so I use a translator

**Comment by sergey-byte** [comment]
> > YlimazYe можешь скинуть мод исправления?
> 
> почему ты просишь меня отказаться от этого?
> или «сбросить» означает «загрузить»?
> Если это «загрузить», вот вы здесь.
> Я не могу загрузить файл jar, поэтому вы должны изменить расширение файла с .zip на jar
> [[星系 附属] [Исправлено] GalaxySpace-1.12.2-2.0.12.zip](https://github.com/BlesseNtumble/GalaxySpace/files/4550914/Fixed.GalaxySpace-1.12.2-2.0.12.zip)

thank you very much!

**Comment by BlesseNtumble** [comment]
Try 2.0.13 build.
