### ISSUE TITLE
Oxygen Sealer showing Thermal control status N/A 

### ISSUE THREAD

**Issue by CargoGen** [BlesseNtumble/GalaxySpace#439]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.272
3. GalaxySpace version: 2.0.13
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.1.4
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

------------------------------------------------------------------------
Description of the issue: All oxygen sealers show thermal control status as N/A with an thermal ambient controller. It occurred after updating asmodeus, galacticraft core and galaxy space to their latest versions. 

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Need check without AsmodeusCore and GalaxySpace.
