### ISSUE TITLE
Triton crash (Asmodeuscore)

### ISSUE THREAD

**Issue by melody-rs** [BlesseNtumble/GalaxySpace#441]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: Latest (4.0.2.272)
3. GalaxySpace version: Latest (2.0.3)
4. AsmodeusCore version (for 2.0.1 version and above): 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP, SMP, LAN

------------------------------------------------------------------------
Description of the issue:
Asmodeus core causes the game to crash when landing on Proxima B.
This issue has been reported to asmodeus core's curseforge but has gotten no response.
As asmodeus core is a dependency of galaxy space, and is made by the developer of GS, I shall report it here.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[crash-2020-05-06_18.13.33-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/4590213/crash-2020-05-06_18.13.33-client.txt)
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/4590214/latest.log)

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
what is your AsmodeusCore version?

**Comment by melody-rs** [comment]
Latest, 0.0.14

**Comment by BlesseNtumble** [comment]
you have any mods for custom chunks?

**Comment by melody-rs** [comment]
No. No cubic chunks, if that’s what you mean.
I don’t think it’s the mod list since other people on completely different mod packs are having similar issues.

**Comment by BlesseNtumble** [comment]
https://www.curseforge.com/minecraft/mc-mods/asmodeuscore/files/2950369
Try it build

**Comment by melody-rs** [comment]
Ok, I’ll see if it fixes it

**Comment by melody-rs** [comment]
It fixed it

**Comment by melody-rs** [comment]
Thanks!

**Comment by melody-rs** [comment]
Tried to land on triton, and Asmodeus core caused another crash, this time with screen rendering. After entering the atmosphere Minecraft turned white and crashed.
I think this may be related, but I'm not sure.
[crash-2020-05-06_23.17.57-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/4591033/crash-2020-05-06_23.17.57-client.txt)
