### ISSUE TITLE
Barnards system crash

### ISSUE THREAD

**Issue by BlueCreeper160** [BlesseNtumble/GalaxySpace#442]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.277
3. GalaxySpace version: 2.0.13
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.16
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

------------------------------------------------------------------------
Description of the issue:
A crash happens when I start minecraft, some of the details are the asmodeus core solar system register and the barnards system bodies. I'm using the exoplanets and Extra planets addons.

------------------------------------------------------------------------
Screenshot/Video:
None

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[crash-2020-05-10_12.08.30-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/4606266/crash-2020-05-10_12.08.30-client.txt)

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Use 0.0.15 AsmodeusCore or wait update GalaxySpace
