### ISSUE TITLE
Crash On Start-Up

### ISSUE THREAD

**Issue by TheOnlySmeme** [BlesseNtumble/GalaxySpace#443]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.278
3. GalaxySpace version: 2.0.13
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.16
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP and LAN

------------------------------------------------------------------------
Description of the issue:
When I load up my game with GalaxySpace installed it gives me an error message telling me that the cause is GalaxySpace. I've also tried this with the previous 2 versions of GalaxySpace and the same thing happens, I have no clue what is causing this. I also can't get a link of the crash report as it just says failed when I attempt it.

------------------------------------------------------------------------
Screenshot/Video:
![image](https://user-images.githubusercontent.com/62208329/81829827-3b5c5900-9533-11ea-966c-8c97915db03c.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Download 0.0.15 AsmodeusCore.
