### ISSUE TITLE
Galaxy Space failed to load

### ISSUE THREAD

**Issue by Starslinger909** [BlesseNtumble/GalaxySpace#444]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: Latest (4.0.2.208)
3. GalaxySpace version: Latest 2.0.13
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.16
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Doesnt matter cant load but SSP

------------------------------------------------------------------------
Description of the issue:
The game fails to load galaxy space. Log attached

------------------------------------------------------------------------
Screenshot/Video:
![Screenshot (8)](https://user-images.githubusercontent.com/36279460/82249613-1ba0a880-9918-11ea-90e8-9c34cae136d8.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[crash-2020-05-18_14.26.34-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/4646020/crash-2020-05-18_14.26.34-client.txt)

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
#443
