### ISSUE TITLE
Crash On Launch Of Pack

### ISSUE THREAD

**Issue by jonplaysgames** [BlesseNtumble/GalaxySpace#445]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version: 2.0.13
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.16
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

------------------------------------------------------------------------
Description of the issue:
I updated to the newest versions and now the pack crashes during startup every time it reaches initializing Galaxy Space.

------------------------------------------------------------------------
Screenshot/Video:
![wpcrash](https://user-images.githubusercontent.com/65702395/82531014-87e3fd80-9b0c-11ea-93ae-37c3e3301800.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://pastebin.com/RRScGyQi

------------------------------------------------------------------------

**Comment by ROMVoid95** [comment]
use AsmodeusCore 0.0.15

**Comment by mMONTAGEe** [comment]
Asmodeuscore 0.0.15 or 14

**Comment by jonplaysgames** [comment]
Thanks, you're lifesavers!
