### ISSUE TITLE
Крашит при заходе в игру

### ISSUE THREAD

**Issue by rhherhre** [BlesseNtumble/GalaxySpace#446]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.2.280
3. GalaxySpace version: 1.12.2-2.0.13
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.16
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): одиночная игра

------------------------------------------------------------------------
Description of the issue:
Краш при заходе в игру

------------------------------------------------------------------------
Screenshot/Video:
https://imgur.com/a/sl5NRfO

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

https://pastebin.com/zCU2cw0P
------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
Во-первых, проблема в AsmodeusCore, поставь версию 0.0.15
Во-вторых, ты используешь фейковый TL, который насильно добавляет моды и меняет код игры без твоего ведома. И не только игры...

**Comment by rhherhre** [comment]
> Во-первых, проблема в AsmodeusCore, поставь версию 0.0.15
> Во-вторых, ты используешь фейковый TL, который насильно добавляет моды и меняет код игры без твоего ведома. И не только игры...

**Comment by rhherhre** [comment]
> Во-первых, проблема в AsmodeusCore, поставь версию 0.0.15
> Во-вторых, ты используешь фейковый TL, который насильно добавляет моды и меняет код игры без твоего ведома. И не только игры...

Где мне взять 0.0.15 версию? TL оригинальный, моды не добавляет, и у меня все нормально с ним

**Comment by CaveJohnson376** [comment]
1. На курсфорже
2. У тебя там стоит мод, который насильно добавляется только фейковым TL
![image](https://user-images.githubusercontent.com/33164023/83176712-57691880-a137-11ea-8c9a-862130396814.png)

Вот так выглядит оригинальный TL:
![image](https://user-images.githubusercontent.com/33164023/83176751-6f409c80-a137-11ea-8fc4-fd7cbcd124ab.png)

**Comment by rhherhre** [comment]
> 1. На курсфорже
> 2. У тебя там стоит мод, который насильно добавляется только фейковым TL
>    ![image](https://user-images.githubusercontent.com/33164023/83176712-57691880-a137-11ea-8c9a-862130396814.png)
> 
> Вот так выглядит оригинальный TL:
> ![image](https://user-images.githubusercontent.com/33164023/83176751-6f409c80-a137-11ea-8fc4-fd7cbcd124ab.png)

Спасибо, Какой лаунчер тогда лучше использовать?

**Comment by CaveJohnson376** [comment]
Либо лицензионный от моянгов, либо MultiMC, либо [оригинальный TL](https://tlauncher.ru)
