### ISSUE TITLE
Hook error when launching

### ISSUE THREAD

**Issue by SSkankhunt42** [BlesseNtumble/GalaxySpace#447]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version:  4.0.2.280
3. GalaxySpace version: 2.0.13
4. AsmodeusCore version (for 2.0.1 version and above):  0.0.15
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP

------------------------------------------------------------------------
Description of the issue:
As soon as I launch Minecraft it instantly crashes and from checking the logs it seems the issue is with this mod. It's probably a problem on my end however I hope this report helps!

------------------------------------------------------------------------
Screenshot/Video:

N/A
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[Crash Log](https://pastebin.com/xTsLD9nb)
------------------------------------------------------------------------

**Comment by SSkankhunt42** [comment]
[Modlist.txt](https://github.com/BlesseNtumble/GalaxySpace/files/4732915/Modlist.txt)
^ List of all the mods I tried to launch with if it is of any use to you

**Comment by SSkankhunt42** [comment]
[New Crash Log](https://pastebin.com/MkhvpZiV)
After trying to launch without the twitch mod launcher I got this crash log instead

**Comment by CaveJohnson376** [comment]
you have asmodeuscore 0.0.16, but you need 0.0.15 one

**Comment by SSkankhunt42** [comment]
Huh, strange. When I tried it with asmodeuscore 0.0.15 it didn't work before but now it does? Anyways Thank you!
