### ISSUE TITLE
Crash caused by Galaxy Space

### ISSUE THREAD

**Issue by TopCraft** [BlesseNtumble/GalaxySpace#449]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: GalacticraftCore-1.12.2-4.0.2.280
3. GalaxySpace version: GalaxySpace-1.12.2-2.0.13.jar
4. AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-0.0.16
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue: Crash caused by Galaxy Space

------------------------------------------------------------------------
Screenshot/Video: 

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

[lastest.zip.zip](https://github.com/BlesseNtumble/GalaxySpace/files/4706828/lastest.zip.zip)

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
Downgrade AsmodeusCore to 0.0.15
