### ISSUE TITLE
New Server, cannot access Vega B

### ISSUE THREAD

**Issue by LokeYourC3PH** [BlesseNtumble/GalaxySpace#45]
So i recently reset the map on my server, and i remember i had this problem before. However, it was said to be fixed in the last version (1.0.8+), which it was, the first time (it seems). Now that i made a completely new map, clicking the Vega B "LAUNCH" button, does nothing, absolutely nothing. Every other planet works, not Vega B. Any idea?

Galacticraft version 454
GalaxySpace version 1.0.8+

**Comment by LokeYourC3PH** [comment]
I am referring to this: https://github.com/BlesseNtumble/GalaxySpace/issues/20

Besides that, i tried deleting the biomeconf file, it didn't fix anything.

**Comment by BlesseNtumble** [comment]
Change ID?

**Comment by LokeYourC3PH** [comment]
Hmm, i will try it, but i can't imagine it to fix anything.
