### ISSUE TITLE
Crash while trying to load the mod

### ISSUE THREAD

**Issue by varappdev** [BlesseNtumble/GalaxySpace#459]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version: 2.0.13
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.16
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: None
------------------------------------------------------------------------
Description of the issue:
I tried simply loading GalaxySpace with my set of mods and it keeps crashing. I really do not know how to read crash reports.

------------------------------------------------------------------------
Screenshot/Video:
https://prnt.sc/swpeus
https://prnt.sc/swpf97

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[crash-2020-06-09_18.03.25-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/4753605/crash-2020-06-09_18.03.25-client.txt)

------------------------------------------------------------------------

**Comment by Romsik788** [comment]
Install AsmodeusCore version 0.0.15 for fix.
