### ISSUE TITLE
(Not really an issue) GalaxySpace main menu background. 

### ISSUE THREAD

**Issue by TopCraft** [BlesseNtumble/GalaxySpace#462]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: GalacticraftCore-1.12.2-4.0.2.280
3. GalaxySpace version: GalaxySpace-1.12.2-2.0.13
4. AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-0.0.15
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue: I just wanna ask how do I turn off the galaxy space main menu background and make it default main menu.

------------------------------------------------------------------------
Screenshot/Video:
![image](https://user-images.githubusercontent.com/34287494/84231605-5cb55400-aaa3-11ea-8c9c-3dcde2a33ab3.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
check configs

**Comment by BlesseNtumble** [comment]
configs/GalaxySpace/core.conf
