### ISSUE TITLE
GalaxySpace crashes

### ISSUE THREAD

**Issue by Talvas** [BlesseNtumble/GalaxySpace#464]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version: 2.0.13
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.16
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): LAN
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:
https://pastebin.com/qaCYSAFF

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
1. you are using fake TL, redownload from https://tlaun.ch/latest/exe
2. downgrade AsmodeusCore to 0.0.15
