### ISSUE TITLE
always another ID

### ISSUE THREAD

**Issue by PercyJames** [BlesseNtumble/GalaxySpace#465]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.1.2.2
2. Galacticraft version: 1.12.2-4.0.2.272
3. GalaxySpace version: 1.12.2-2.0.13
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.14
5. Side (SSP)
6. Other add-ons: more planets, extra planets, Zollern Galaxy
------------------------------------------------------------------------
Description of the issue: when i try to join these crashes keep happening. i tried changing the id but when i do it just says that another space station with that id already exists.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com): 

https://pastebin.com/UNjfHYQk

https://pastebin.com/gKiBV0sd

https://pastebin.com/fNSQDgtm

------------------------------------------------------------------------

oh and if you say "downgrade AsmodeusCore to .14" then i know you haven't read the issue

**Comment by CaveJohnson376** [comment]
disable Venus space station (or what one i didn't remember)

**Comment by PercyJames** [comment]
thank you!
