### ISSUE TITLE
the screen turns white and that ain't right

### ISSUE THREAD

**Issue by PercyJames** [BlesseNtumble/GalaxySpace#466]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.1.2.2
2. Galacticraft version: 1.12.2-4.0.2.272
3. GalaxySpace version: 1.12.2-2.0.13
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.14
5. Side (SSP)
6. Other add-ons: more planets, extra planets, Zollern Galaxy
------------------------------------------------------------------------
Description of the issue: the first time i tried to open the galaxy map i crashed. i fixed it by turning off the new galaxy map. the second time i tried to open the galaxy map the screen turned white then i crashed. below is the crash report

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com): 

https://pastebin.com/pPNVKsaJ

------------------------------------------------------------------------

oh and if you say "downgrade AsmodeusCore to .14" then i know you haven't read the issue

**Comment by mMONTAGEe** [comment]
You have mod that open map on M button or do something?

**Comment by mMONTAGEe** [comment]
Have you disable venus space station?

**Comment by PercyJames** [comment]
i have it mapped to the no i don't have another map mod

**Comment by PercyJames** [comment]
yes

**Comment by mMONTAGEe** [comment]
try disabling i mean deleting extra planets for while or more planets

**Comment by PercyJames** [comment]
no?

**Comment by PercyJames** [comment]
i don't think that will help

**Comment by mMONTAGEe** [comment]
one of these mods cause problem :/

**Comment by PercyJames** [comment]
the problem started when i downloaded this mod

**Comment by mMONTAGEe** [comment]
which one?
galaxy space?

**Comment by PercyJames** [comment]
yes

**Comment by mMONTAGEe** [comment]
try upgrading galacticraft to 280

**Comment by PercyJames** [comment]
ok!

**Comment by mMONTAGEe** [comment]
always use latest versions

**Comment by mMONTAGEe** [comment]
That helped?

**Comment by PercyJames** [comment]
i'm loading minecraft right now. and may just say that i have not had a conversation on github like this before

**Comment by mMONTAGEe** [comment]
if you could record video with debug mode on. that would help a lot

**Comment by PercyJames** [comment]
debug mode?

**Comment by mMONTAGEe** [comment]
i think its in config file or in Mods menu in minecraft

**Comment by mMONTAGEe** [comment]
it says some sciencific java things to help developers

**Comment by PercyJames** [comment]
oh. well, i don't have OBS or any other recording software

**Comment by mMONTAGEe** [comment]
Xbox gamebar?

**Comment by PercyJames** [comment]
i have no idea what that is

**Comment by mMONTAGEe** [comment]
nvm.

**Comment by mMONTAGEe** [comment]
Also upgrade asmodeuscore to 15 it also maybe could help

**Comment by PercyJames** [comment]
i'm confused. a lot of people have problems with any version of asmodeuscore above .14

**Comment by mMONTAGEe** [comment]
the 16 one have 1 line code that not compatible with galaxy space 13.

**Comment by mMONTAGEe** [comment]
its for future plans

**Comment by PercyJames** [comment]
ok then

**Comment by mMONTAGEe** [comment]
So it helped?

**Comment by PercyJames** [comment]
so, there's this weird thing i need to do before i join my world. i need to close my computer (not turn it off) for a few minutes and then i can join. don't know why but it works. so i'm going to need to take a break

**Comment by mMONTAGEe** [comment]
Also after upgrading galacticraft and asmodeuscore get the latest extra planets you have 6.2 new one 6.4

**Comment by PercyJames** [comment]
ok

**Comment by PercyJames** [comment]
ok so, i can access the galaxy map. but, the places GS claims to add are still red. like the Kuiper Belt.
