### ISSUE TITLE
can't go to Kuiper Belt or Haumea

### ISSUE THREAD

**Issue by PercyJames** [BlesseNtumble/GalaxySpace#467]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.1.2.2
2. Galacticraft version: 1.12.2-4.0.2.280
3. GalaxySpace version:  1.12.2-2.0.13
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.15
5. Side (SSP)
6. Other add-ons: more planets, extra planets, Zollern Galaxy
------------------------------------------------------------------------
Description of the issue:
Kuiper Belt and Haumea despite being completed are not loading as travelable places in my game.

------------------------------------------------------------------------
Screenshot/Video:

![2020-06-22_17 15 45](https://user-images.githubusercontent.com/65469481/85340713-31236800-b4ac-11ea-9cfd-218ad045eaaf.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------
oh and if you say "downgrade AsmodeusCore to .14" then i know you haven't read the issue

**Comment by BlesseNtumble** [comment]
Configure configs of other add-ons.
