### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by PercyJames** [BlesseNtumble/GalaxySpace#468]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.1.2.2
2. Galacticraft version: 1.12.2-4.0.2.280
3. GalaxySpace version:  1.12.2-2.0.13
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.15
5. Side (SSP)
6. Other add-ons: more planets, extra planets, Zollern Galaxy
------------------------------------------------------------------------
Description of the issue: can't join a world created after downloading the mod

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

https://pastebin.com/2naAx4gh
------------------------------------------------------------------------
oh and if you say "downgrade AsmodeusCore to .14/.15" then i know you haven't read the issue

**Comment by BlesseNtumble** [comment]
Reopen if relevant.
