### ISSUE TITLE
[Suggestion] Use tier 1 thermal suit parts for tier 2 crafting

### ISSUE THREAD

**Issue by MapperTV** [BlesseNtumble/GalaxySpace#47]
Currently tier 2 thermal suit needs  tier 2 thermal cloth to be crafted. When it's done, the tier 1 thermal suit becomes obsolete, without any use. And mining all that cobaltum on Phobos is long because the moon doesn't have caves.

So I suggest to modify the recipe by replacing one of the tier 2 thermal cloth by the tier 1 part. For example: 
![image](https://cloud.githubusercontent.com/assets/11135018/14743335/5f0e619a-08a1-11e6-8f67-4fe84ec08750.png)

Only the boots will still need its 4 thermal clothes, and put the tier 1 boots between them:
![image](https://cloud.githubusercontent.com/assets/11135018/14743350/7bd52c3c-08a1-11e6-882c-f13d06a523b3.png)

For me it makes more sense since:
- tier 1 is useless when you get tier 2, and will just take space in chests. So with this craft we won't drop it in chests.
- it looks more like an upgrade tier 1 -> tier 2
- less cobaltum mining, but still need all the ressources from tier 1

Hope you'll like it :)

**Comment by BlesseNtumble** [comment]
Ok, added.
