### ISSUE TITLE
Minecraft with galaxy space does not start

### ISSUE THREAD

**Issue by number947** [BlesseNtumble/GalaxySpace#471]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: GalacticraftCore-1.12.2-4.0.2.280
3. GalaxySpace version: 1.12.2-2.0.13
4. AsmodeusCore version: 1.12.2-0.0.16
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: no addons
------------------------------------------------------------------------
Description of the issue:
I cannot start minecraft with enabled galaxy space addon. Disabling it allows to start minecraft

------------------------------------------------------------------------
Screenshot/Video:
![Снимок экрана (92)](https://user-images.githubusercontent.com/44410578/85927100-34e82d80-b8a4-11ea-9a81-022f9f12797d.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[crash-2020-06-27_18.29.10-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/4840901/crash-2020-06-27_18.29.10-client.txt)

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
1. you are using fake TL
2. downgrade AsmodeusCore 0.0.15

**Comment by number947** [comment]
@CaveJohnson376 Thank you for your response. It helped me a lot!

**Comment by mMONTAGEe** [comment]
Note download original TL or buy license
