### ISSUE TITLE
Не могу слетать на Энцелад и Титан

### ISSUE THREAD

**Issue by Romsik788** [BlesseNtumble/GalaxySpace#478]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.280
3. GalaxySpace version:2.0.13
4. AsmodeusCore version (for 2.0.1 version and above):0.0.15
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP
6. Other add-ons:
![modlist](https://user-images.githubusercontent.com/33905242/87317191-59443b00-c52f-11ea-9b32-43fefd076c52.png)

------------------------------------------------------------------------
Description of the issue:

Майнкрафт вылетает при выборе спутников Сатурна. Также нету кнопки запуска при выборе Энцелада или Титана

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

https://pastebin.com/9hDDjm7y
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Small Mode на карте включен?

**Comment by Romsik788** [comment]
Да, переключил на Normal Mode - вроде всё норм

**Comment by BlesseNtumble** [comment]
#500
