### ISSUE TITLE
Server Crash when trying to generate dungeon on Io

### ISSUE THREAD

**Issue by CommanderLouiz** [BlesseNtumble/GalaxySpace#479]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. GalacticraftCore version: 4.0.2.280
3. GalaxySpace version: 2.0.13
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.15
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP Lapito's Galacticraft Modpack

6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:

Suddenly, server crash. Logs point to trying to generate components for the bosses room on Io.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[debug-1.log.gz](https://github.com/BlesseNtumble/GalaxySpace/files/4935772/debug-1.log.gz)
[crash-2020-07-17_04.29.42-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/4935760/crash-2020-07-17_04.29.42-server.txt)

------------------------------------------------------------------------

**Comment by CommanderLouiz** [comment]
A member of the server moved into the chunkloading range and the server crashed. I reset them, and teleported to where they were in spectator, under the ground so I could see it coming. Upon seeing one of the hallways load in, the server crashed again. 

Same error as before.

**Comment by ryanzhoudev** [comment]
Currently, what I'm doing to avoid the problem is to delete all chunks without my builds from my nbt data, disable dungeon generation in config, then generate the majority of the world, then re-enable. Might be useful to know until fixed.
- Bug also exists with AsmodeusCore 0.0.17 and GalaxySpace 2.0.14.

**Comment by BlesseNtumble** [comment]
Try 2.0.15
