### ISSUE TITLE
I crashed :/

### ISSUE THREAD

**Issue by cgiigc** [BlesseNtumble/GalaxySpace#480]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version: 2.0.13
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.17
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: More Planets
------------------------------------------------------------------------
Description of the issue:
Soo I loaded up my Twitch modpack, with some space mods in, and it just crashed! I have Ambience, Music Player, and Buildcraft.

------------------------------------------------------------------------
Screenshot/Video:
https://prnt.sc/to4xpk

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
latest.log: https://pastebin.com/NCjceFHG

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
downgrade AsmodeusCore to 0.0.15

**Comment by cgiigc** [comment]
> downgrade AsmodeusCore to 0.0.15

Thank you so much! It worked!
