### ISSUE TITLE
Info Pad Crash

### ISSUE THREAD

**Issue by TheMCSpacePro** [BlesseNtumble/GalaxySpace#483]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version: 2.0.14
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.17
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: Galacticraft-Planets-1.12.2-4.0.2.280
------------------------------------------------------------------------
Description of the issue:
In the Info pad, selecting Mars results in the game crashing.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://haste.romvoid.dev/ujizataxat.yml

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
Why didn't you mentioned asmodeuscore version?

**Comment by ROMVoid95** [comment]
@CaveJohnson376 while i have to agree, its easily find-able  in the log link

**Comment by CaveJohnson376** [comment]
Also galacticraft-planets is not an addon, it's an optional part of mod

**Comment by CaveJohnson376** [comment]
Try disabling custom map in GS/AC config files
