### ISSUE TITLE
barnarda c sand breaks in instant

### ISSUE THREAD

**Issue by galacticrafthuman** [BlesseNtumble/GalaxySpace#486]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 280
3. GalaxySpace version: 2.0.14
4. AsmodeusCore version (for 2.0.1 version and above):  0.0.17
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): any of them
6. Other add-ons: none
------------------------------------------------------------------------
Description of the issue:
when on the planet barnarda c, there is this greenish sand, in survival you can mine it instantly, and super fast

------------------------------------------------------------------------
Screenshot/Video:
i couldnt get a video because minecraft hates recording for me so heres a screenshot of that sand
![2020-08-07_18 56 04](https://user-images.githubusercontent.com/69351520/89664700-3adc2000-d8e0-11ea-8ae1-e365e6ab9167.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Try 2.0.15
