### ISSUE TITLE
Баги с универсальным переработчиком

### ISSUE THREAD

**Issue by ghost** [BlesseNtumble/GalaxySpace#488]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2 
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version: 2.0.14
4. AsmodeusCore version (for 2.0.1 version and above): 2.0.17 (curseforge) 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue: иногда из 64 блоков лунного камня получается 64 лунного сапфира, хотя шанс получения из одного блока камня - 5%.
Если забрать из УП предметы на выходе с зажатым шифтом, то их количество удваивается

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
1) Сколько не пихал стаки, не получается 100%.
2) https://github.com/BlesseNtumble/GalaxySpace/commit/ddffa84468894c4c98a9a5107bffe5c73efce3ea

**Comment by ghost** [comment]
1. Сам хз как так получилось, в этот момент вроде были перебои с поставляемой энергией.
2. Спасибо
