### ISSUE TITLE
Add ES_es Lang

### ISSUE THREAD

**Issue by Kevadroz** [BlesseNtumble/GalaxySpace#49]
Can you add more lang files? example: Spanish from Spain (ES_es)

**Comment by BlesseNtumble** [comment]
If you make a translation - will add.

**Comment by Kevadroz** [comment]
Im not interested on making it :(

**Comment by BlesseNtumble** [comment]
Well, I'm Russian, and Spanish I do not know.
So I will wait for the translation from the Spanish.
