### ISSUE TITLE
travelling issue: I'm not getting to the planet I selected.

### ISSUE THREAD

**Issue by Gigiboys** [BlesseNtumble/GalaxySpace#492]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.2.280
3. GalaxySpace version: 1.12.2-2.0.14
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.18
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:
when selecting a planet to launch myself to, I always get to one different from the one selected (moon>Titan, Venus>Callisto) except for Mars apparently. strangely enough I disabled the venus space stations, the Mars one to be sure and even changed the dimension's coordinates.
by the way, I don't know how hard it could be to maintain this version stable along with galacticraft, so thanks a lot for your hard work !

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
a txt of the dimensions config
[dimensions.conf.txt](https://github.com/BlesseNtumble/GalaxySpace/files/5079112/dimensions.conf.txt)

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
server?

**Comment by BlesseNtumble** [comment]
clear all configs and try

**Comment by Gigiboys** [comment]
thanks, that worked perfectly ! I guess I didn't updated my configs for a while, now they're different.
