### ISSUE TITLE
GUI compatibility problem with ExtraPlanets

### ISSUE THREAD

**Issue by AC102** [BlesseNtumble/GalaxySpace#493]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version: 2.0.14
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.17
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: 
     ExtraPlanets: 0.6.9
------------------------------------------------------------------------
Description of the issue:
GUI of ExtraPlanets and GalaxySpace have a display problem when you are on a planet with radiations/pressure activated with ExtraPlanets 

------------------------------------------------------------------------
Screenshot/Video:
https://cdn.discordapp.com/attachments/293007125515468800/744329279147606087/unknown.png

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Update to version 0.0.20. There added configs for panel displacement by X \ Y.
