### ISSUE TITLE
Random crash while exploring the moon IO on a server

### ISSUE THREAD

**Issue by knoxhack** [BlesseNtumble/GalaxySpace#494]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: GalacticraftCore-1.12.2-4.0.2.280
3. GalaxySpace version: GalaxySpace-1.12.2-2.0.14
4. AsmodeusCore version (for 2.0.1 version and above):  AsmodeusCore-1.12.2-0.0.18
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Server
6. Other add-ons: 
- ExtraPlanets-1.12.2-0.7.0
- GalacticTweaks-1.1.0
- GalacticraftTweaker-1.12.2-1.0.3
- PlanetProgression-1.12.2-0.4.5

------------------------------------------------------------------------
Description of the issue:
Random crash while exploring the moon IO on a server

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[https://gist.github.com/knoxhack/a44277b89c32e1c396b3597978986fe3](https://gist.github.com/knoxhack/a44277b89c32e1c396b3597978986fe3)

------------------------------------------------------------------------

**Comment by MBfromOK** [comment]
Same issue: https://pastebin.com/q5W2jSxT

Was fine at first, this time I had the compass out looking for a dungeon, flying over terrain I had already mapped, game has crashed 8x so far (full shutdown & relaunch required)

**Comment by MetagamerDotJpg** [comment]
IO is a mess of corrupted chunks

**Comment by realPiecemaker** [comment]
Same issue: https://pastebin.com/kwgRJAXw

First i could explore IO without problem. 

Now it crash frequently. 
It started the second time i went to IO.

After several reconnects it works but only if i go in the opposite direction. 

Maybe it helps to find the issue.

**Comment by MetagamerDotJpg** [comment]
Once you get stuck in a chunk, getting out can be troublesome. Sometimes you get lucky and find your dungeon before the server explodes ;P

**Comment by BlesseNtumble** [comment]
Try 2.0.15
