### ISSUE TITLE
Хвоя меняет цвет в разных биомах

### ISSUE THREAD

**Issue by QuantumStatement** [BlesseNtumble/GalaxySpace#499]
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version: 2.0.14
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.19
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: none

------------------------------------------------------------------------
Description of the issue:
Хвоя меняет цвет в зависимости от биома, хотя не должна этого делать

------------------------------------------------------------------------
Screenshot/Video:
![2020-09-18_00 46 26](https://user-images.githubusercontent.com/35406698/93531810-7c80d180-f948-11ea-8a57-3e26c0abbb30.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
N/A

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
#500
