### ISSUE TITLE
Баг в 1.0.9 и небольшое предложение

### ISSUE THREAD

**Issue by Shurik1236** [BlesseNtumble/GalaxySpace#50]
Во первых, грунт фобоса теперь такой:
<a target="_blank" href="http://radikal.ru/big/2fffd60f15774eb289e8af8ad4672302"><img src="http://s011.radikal.ru/i317/1605/23/e69df454653a.png" ></a>
Во вторых, думаю надо уменьшить твёрдость и уровень добычи блоков.
Их просто невозможно нормально добывать, мало того что они требуют алмазную кирку, так ещё и добываются медленно. Паровой бур из Flaxbeard's Steam Power даже с наконечником из алмаза вообще еле еле копает (Раскрутить его естественно не забыл). Хотя камень земли, марса сносит на раз. Тёмная кирка из Ender IO со всеми улучшениями и то ужасно медленная.
Не, ну ладно они добываются медленнее чем простой камень, но не на столько же!
И зачарования упоминать не надо. Сейчас в модах много инструментов которые нельзя зачаровывать.

**Comment by BlesseNtumble** [comment]
Это только на Фобосе или грунт на всех планетах\спутниках?

**Comment by Shurik1236** [comment]
Только на Фобосе. Грунт и подповерхностный грунт.
И кстати, порода Фобоса добывается с нормальной скоростью.
Вообще надо уменьшить уровень добычи породы (Не руды) планет до каменной, ну или на некоторых до железной кирки. На Энцеладе так вообще алмазная кирка как каменная добывает. Издевательство просто.
