### ISSUE TITLE
Не отображается шкала солнечной радиации.

### ISSUE THREAD

**Issue by xLuchok** [BlesseNtumble/GalaxySpace#500]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.280
3. GalaxySpace version:2.0.14
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.19
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
6. Other add-ons:none
------------------------------------------------------------------------
Description of the issue: Когда игрок находится не на Земле, то не отображается шкала солнечной радиации. Но при этом солнечная радиация есть и она убивает.

------------------------------------------------------------------------
Screenshot/Video:
![2020-09-19_16 29 41](https://user-images.githubusercontent.com/71549799/93665110-d0e59780-fa95-11ea-9d6d-df6e7321d9eb.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Попробуйте 0.0.20 версию.
