### ISSUE TITLE
ExtraPlanets crash due to this mod.

### ISSUE THREAD

**Issue by MagmaSlime123** [BlesseNtumble/GalaxySpace#501]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2.
2. Galacticraft version: GalacticraftCore-1.12.2-4.0.2.280, Galacticraft-Planets-1.12.2-4.0.2.280
3. GalaxySpace version: GalaxySpace-1.12.2-2.0.14
4. AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-0.0.19
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Singleplayer.
6. Other add-ons: MorePlanets, ExtraPlanets and PlanetProgression.
------------------------------------------------------------------------
Description of the issue:
Game crashes mentioning that I have a space station on one of this mod's planets, when in reality I don't. I can't even start my game so.

------------------------------------------------------------------------
Screenshot/Video:
![image](https://user-images.githubusercontent.com/51277766/93781198-fa113f80-fbdd-11ea-9320-8928dc18054d.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[crash-2020-09-21_07.35.57-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/5256062/crash-2020-09-21_07.35.57-client.txt)

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
Disable mars (i'm not sure there tbh) space station in config

**Comment by MagmaSlime123** [comment]
In what config.

This mod? MorePlanets? ExtraPlanets?

Not really sure.

**Comment by CaveJohnson376** [comment]
Either GS or EP

**Comment by MagmaSlime123** [comment]
I don't see any option for space stations in GS.

**Comment by CaveJohnson376** [comment]
check config files

**Comment by MagmaSlime123** [comment]
Where in what file.

I did actually notice that ExtraPlanets does have a compat option for MorePlanets as well, but theres no options that it wants you to toggle off.

**Comment by CaveJohnson376** [comment]
i've looked up somewhere and found out, that you have to disable venus space station, not the mars one

config files are located at `.minecraft/config`

**Comment by MagmaSlime123** [comment]
What config file though. Gal? MP? EP? GS?

**Comment by CaveJohnson376** [comment]
as i said, either EP or GS

**Comment by CaveJohnson376** [comment]
read this https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/ for more info (link found in your crash report)

**Comment by MagmaSlime123** [comment]
Oh.

I did actually notice that ExtraPlanets does have a compat option for MorePlanets as well, but theres no options that it wants you to toggle off in the MorePlanets config.

**Comment by CaveJohnson376** [comment]
there's no problem with MP, i think

**Comment by MagmaSlime123** [comment]
![image](https://user-images.githubusercontent.com/51277766/93798300-4b2b2e80-fbf2-11ea-970a-66ba571f0411.png)

This section its mentioning doesnt exist in MP's config. Unless there's a 2nd file I'm not finding.

**Comment by CaveJohnson376** [comment]
just disable venus space station in EP config and it should work fine

**Comment by MagmaSlime123** [comment]
Hang on.

Sorry for being an ass with this stuff.

Have you tested these all together and know what the conflict is?

**Comment by CaveJohnson376** [comment]
there was a bunch of crashes similar to your, that's why i know where's the problem and what to do

**Comment by MagmaSlime123** [comment]
Oh. Good. Will test this and hand you a new report if it crashes again. I'm just unsure about the MP compat issue. Cause MP has nothing in its config related to GS, so unsure why GS says you need to disable stuff in MP's config when there's no GS stuff in that config.

**Comment by CaveJohnson376** [comment]
MP has nothing to do with your crash

**Comment by MagmaSlime123** [comment]
Ik. MP has nothing in its config related to GS, so unsure why GS says you need to disable stuff in MP's config to add compat.

**Comment by CaveJohnson376** [comment]
idk about MP, i'm pretty sure there will be no problems with it without changing config

**Comment by MagmaSlime123** [comment]
GS says you have to.
![image](https://user-images.githubusercontent.com/51277766/93800052-dc9ba000-fbf4-11ea-8fd5-bcd34c78b90f.png)

**Comment by CaveJohnson376** [comment]
you can ignore this

**Comment by MagmaSlime123** [comment]
Oh, alright. Starting game, hang on

Sorry for being an ass about this, not very smart when it comes to modding, so yeah

EDIT: Game loaded but just a few questions: MP, GS and EP all have Tier 4-10 rockets so, what can I do with those to prevent conflicts

**Comment by CaveJohnson376** [comment]
disable rockets in EP and MP, leaving only GS rockets

**Comment by MagmaSlime123** [comment]
Will that allow those rockets to travel to both EP and MP planets though?

**Comment by CaveJohnson376** [comment]
GS rockets can get to any place by doing planet hopping

**Comment by MagmaSlime123** [comment]
Oh. 1second.
