### ISSUE TITLE
Mars' Atmosphere, Gas Liquefier and Methane Synthesizer

### ISSUE THREAD

**Issue by QuantumBeef** [BlesseNtumble/GalaxySpace#503]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version: 2.0.14
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.20
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: None
------------------------------------------------------------------------
Description of the issue:
When on Mars, using an Atmospheric Valve in the Carbon Dioxide tank slot of the Methane Synthesizer doesn't fill it with anything. With the Gas Liquefier, in Mars the two gases being liquefied aren't Argon and Nitrogen, but Nitrogen and Oxygen as if the Atmosphere was Earth's

------------------------------------------------------------------------
Screenshot/Video:
https://streamable.com/4iqyn6 (With GalaxySpace)

https://streamable.com/i7suqo (Without GalaxySpace)
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Fixed in 2.0.15
