### ISSUE TITLE
Visual issue with Buildcraft Engines in Galacticraft Asteroids dimension

### ISSUE THREAD

**Issue by TakeABao23** [BlesseNtumble/GalaxySpace#504]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2
3. GalaxySpace version: 2.0.14
4. AsmodeusCore version (for 2.0.1 version and above):  0.0.19
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
Single player
6. Other add-ons:
Optifine
----------------------------------------------------------------------------
--------------------------------------------------------------------------
Description of the issue:

When any buildcraft engine is placed in the Galacticraft asteroids, the screen is immediately covered in blackness whenever the engine is within the field of view, even if it is hidden by blocks. Have confirmed it is a compatibility issue between GalaxySpace and Optifine. Issue only persists when GalaxySpace and Optifine are running at the same time.

------------------------------------------------------------------------
Screenshot/Video:
[Minecraft.1.12.2.2020-09-30.13-25-00_Trim.zip](https://github.com/BlesseNtumble/GalaxySpace/files/5324793/Minecraft.1.12.2.2020-09-30.13-25-00_Trim.zip)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
none

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
This issue is impossible to fix - Optifine has closed source code. Only solution to this problem is to remove Optifine

**Comment by TakeABao23** [comment]
Darn
