### ISSUE TITLE
Error: java.lang.NullPointerException: Tesselating block model

### ISSUE THREAD

**Issue by killerkalamari** [BlesseNtumble/GalaxySpace#505]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2-forge-14.23.5.2854
2. Galacticraft version: 1.12.2-4.0.2.280
3. GalaxySpace version: 1.12.2-2.0.14
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.20
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Multiplayer (client crashes)
6. Other add-ons: None 
------------------------------------------------------------------------
Description of the issue:

- Server side is fine. Client loads. However, about 1-2 seconds after joining the server, the client crashes. Seems to be related to "leaves2", variant "dark_oak". Seed: 3926758518314452153. 
- I regenerated the world several times, and finally on an island spawn without trees it didn't crash (didn't note that seed). I also didn't explore to find out if looking at a dark oak tree would cause a crash. 
- There was no crash when removing only GalaxySpace-1.12.2-2.0.14.jar (leaving AsmodeusCore-1.12.2-0.0.20.jar, GalacticraftCore-1.12.2-4.0.2.280.jar, Galacticraft-Planets-1.12.2-4.0.2.280.jar, MicdoodleCore-1.12.2-4.0.2.280.jar), and regenerating with the above seed 3926758518314452153.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[crash-2020-10-28_16.48.16-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/5455390/crash-2020-10-28_16.48.16-client.txt)

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
Known bug, maybe try other seed?

**Comment by killerkalamari** [comment]
This seed works (or at least doesn't crash at spawn): -3462035780234417933

**Comment by BlesseNtumble** [comment]
Try AsmodeusCore 0.0.21
