### ISSUE TITLE
TileEntityAssembler crash

### ISSUE THREAD

**Issue by bigenergy** [BlesseNtumble/GalaxySpace#508]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.2.281
3. GalaxySpace version:1.12.2-2.0.14
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.21
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Multiplayer
6. Other add-ons: MorePlanets
------------------------------------------------------------------------
Description of the issue:
Crash server on start

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[crash-2020-12-12_21.50.30-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/5683628/crash-2020-12-12_21.50.30-server.txt)

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
minor incompatability bug between GS and mekanism

**Comment by bigenergy** [comment]
![image](https://user-images.githubusercontent.com/17977139/102007217-171a6200-3d38-11eb-9776-79fb84f26bf7.png)
this construct crashes the server

**Comment by bigenergy** [comment]
@BlesseNtumble pls fix)

**Comment by erishiamu** [comment]
Just curious if there's a workaround for this? We made the mistake of not adding aroma to a laptio's galacticraft standalone server, and when we connected the assembler we had a hard crash / persistent crash on reload.

**Comment by BlesseNtumble** [comment]
https://github.com/BlesseNtumble/GalaxySpace/commit/7c79d7a8172cf71b82c5381bd53ad2678a2aaa8e#diff-e20cef833043358dad2d7d9d3f1d08feb6731fb631d0ca98a1e8c4ca47b8d1cb

**Comment by BlesseNtumble** [comment]
Try 2.0.15
