### ISSUE TITLE
Fix cobalt ore name in upgrade modules recipe

### ISSUE THREAD

**Issue by onyn** [BlesseNtumble/GalaxySpace#509]
There is no such item with ore name "ingotCobaltum":

https://github.com/BlesseNtumble/GalaxySpace/blob/5cc5b5d1a9a84e83fbece503e68eafd5466d2474/src/main/java/galaxyspace/systems/SolarSystem/planets/overworld/recipes/CraftingRecipesOverworld.java#L188-L191

But there is "ingotCobalt":

https://github.com/BlesseNtumble/GalaxySpace/blob/5cc5b5d1a9a84e83fbece503e68eafd5466d2474/src/main/java/galaxyspace/core/GSItems.java#L192

**Comment by BlesseNtumble** [comment]
Fixed in 2.0.15
