### ISSUE TITLE
Can not place leaves/crops on the moon to generate oxygen

### ISSUE THREAD

**Issue by mrB3AN** [BlesseNtumble/GalaxySpace#510]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 281
3. GalaxySpace version: 2.0.14
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.23
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP, not sure about SMP
6. Other add-ons: More Planets Mod 
------------------------------------------------------------------------
Description of the issue:
When I try to place leaves on the moon I get an error message. The base galaticraft mod does not do this messsage and places the leaves. 

------------------------------------------------------------------------
Screenshot/Video:
![2021-01-06_12 14 55](https://user-images.githubusercontent.com/73447781/103800255-2b413e80-501a-11eb-8575-98ed101cbce6.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Need oxygen room.
