### ISSUE TITLE
[Dev environment] issue when trying to build mod

### ISSUE THREAD

**Issue by gatoborrachon** [BlesseNtumble/GalaxySpace#511]
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: GalacticraftCore-Dev-1.12.2-4.0.2.261
3. GalaxySpace version: latest from github
4. AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-0.0.23
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): gradlew build
6. Other add-ons: 
------------------------------------------------------------------------
Description of the issue:
i get a LOT of these issues when i try to compile the mod:

```
C:\Users\Usuario\Documents\Minecraft-Modding\Mods\GalaxySpace-1.12.2\build\sources\main\java\galaxyspace\core\hooklib\asm\Hook.java:50: error: unmappable character for encoding Cp1252
     * ð╝ð¥ð│ÐâÐé ð▓Ð?ÐéÐÇðÁÐéð©ÐéÐîÐ?Ð? (ð¢ð░ð┐ÐÇð©ð╝ðÁÐÇ, Ð?Ðéð¥ ð╝ð¥ðÂð¢ð¥ Ð?ð┤ðÁð╗ð░ÐéÐî ð┐ÐÇð© ð¥ð▒ÐäÐâÐ?ð║ð░Ðåð©ð© ÐçðÁÐÇðÁðÀ ProGuard)
```

**Comment by gatoborrachon** [comment]
i get more issues related to asmodeus core i guess, please release a new build because it fixes a crash

**Comment by ROMVoid95** [comment]
because you need to set the text file encoding for the project to UTF-8

**Comment by BlesseNtumble** [comment]
it's warnings. not error/bugs.

**Comment by gatoborrachon** [comment]
> because you need to set the text file encoding for the project to UTF-8

and how can i do that?

also, where can i get the 0.0.23 dev version of AsmodeusCore? i get the following issues:
https://pastebin.com/4FprwBJj

**Comment by ROMVoid95** [comment]
looks to be changes to asmodeuscore that are not released yet in a new version.
