### ISSUE TITLE
Server crash with AsmodeusCore

### ISSUE THREAD

**Issue by Josh65-2201** [BlesseNtumble/GalaxySpace#512]
**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version: 2.0.15
4. AsmodeusCore version: 0.0.24 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP
------------------------------------------------------------------------
Description of the issue:
AsmodeusCore causes a crash when running on a server.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[crash-2021-02-09_11.01.16-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/5951152/crash-2021-02-09_11.01.16-server.txt)

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
lmaooo first issue after update

**Comment by BlesseNtumble** [comment]
redownload from curseforge GalaxySpace 2.0.15 and try again.
