### ISSUE TITLE
Make tier 4 rocket is impossible without tier 4 rocket.

### ISSUE THREAD

**Issue by MisileLab** [BlesseNtumble/GalaxySpace#514]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.281
3. GalaxySpace version: 2.0.15
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.24
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): LAN
6. Other add-ons: NO
------------------------------------------------------------------------
Description of the issue:
Tier 4 rocket need magnesium but, Magnesium can't get without 
tier 4 rocket.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
You can reach Ganymede with a tier 3 rocket.
Overworld - Mars - Ceres - Ganymede
