### ISSUE TITLE
Issue with Solar Panels

### ISSUE THREAD

**Issue by mMONTAGEe** [BlesseNtumble/GalaxySpace#516]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version:1.12.2-4.0.2.281
3. GalaxySpace version: 2.0.15
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.24
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: MorePlanets,Interstellar Exoplanets,Zollern Galaxy
------------------------------------------------------------------------
Description of the issue:
The Solar Panels dont work on Tau Ceti F. they seems see the sun but dont know what to do lol

------------------------------------------------------------------------
Screenshot/Video:

https://cdn.discordapp.com/attachments/449966345665249292/810146444627410954/unknown.png
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
![image](https://user-images.githubusercontent.com/8407547/107870075-d1654b80-6ed8-11eb-8584-7c0ee92e4de1.png)
set boost = 0.0% (default generation)

**Comment by mMONTAGEe** [comment]
Thanka for the fix 😅
