### ISSUE TITLE
impossible to make tier 3 rocket ваще

### ISSUE THREAD

**Issue by liopard** [BlesseNtumble/GalaxySpace#519]
GalaxySpace-1.12.2-2.0.15
ракету 3-го уровня не сделать
никак
ваще, вам нужны тестеры с чек-листом ))

**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:
2. Galacticraft version:
3. GalaxySpace version:
4. AsmodeusCore version (for 2.0.1 version and above): 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Fixed in 2.0.16
