### ISSUE TITLE
Launch Controllers Are Broken

### ISSUE THREAD

**Issue by Luisxcaliber** [BlesseNtumble/GalaxySpace#521]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.280
3. GalaxySpace version:2.0.15
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.24
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP
6. Other add-ons:None
------------------------------------------------------------------------
Description of the issue: I notice that when using launch controllers there were a few issues I ran in to, the main one being was when using a launch controller in the Overworld it couldn't detect the frequency of one that was in another dimension like the Moon or a space station. I kept making test worlds to see if it would always be the same and it always was. Also sometimes I would run in to some crashes but I couldn't constantly repeat this.

------------------------------------------------------------------------
Screenshot/Video: https://www.youtube.com/watch?v=YY0_o_RAZGs

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/6096865/latest.log)
Crash Report from the crashes I sometimes got.
[crash-2021-03-07_03.26.11-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/6096867/crash-2021-03-07_03.26.11-server.txt)

------------------------------------------------------------------------

**Comment by v1993** [comment]
Launch Controllers come from Galacticraft Planets, are you sure it's an issue with GalaxySpace?

**Comment by Luisxcaliber** [comment]
Yes it was a issue with GalaxySpace because the problem would only happen with it install and no other mods beside Galacticraft. Although Launch Controllers are from Galacticraft Planets, the GalaxySpace mod effects and changes few things in Galacticraft but I believe this issue is now fixed in GalaxySpace version 2.0.16.
