### ISSUE TITLE
Makemake does not appear on the celestial map and only in the options (1.12.2)

### ISSUE THREAD

**Issue by MIGUel670XX** [BlesseNtumble/GalaxySpace#524]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.280
3. GalaxySpace version:2.0.16
4. AsmodeusCore version (for 2.0.1 version and above): 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):any
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:Makemake It is by default in the galaxy space options (that is, in the config.cfg file of the mod) but when the option is activated it does not appear in the celestial map not even the blocks but in 1.7.10 it does appear when it is activated

------------------------------------------------------------------------
Screenshot/Video:

1.7,10 screenshots
![2021-04-12_11 09 09](https://user-images.githubusercontent.com/82398540/114427444-b46b9280-9b80-11eb-901f-fd43a65c9ddf.png)
Makemake terrain

![2021-04-12_11 10 06](https://user-images.githubusercontent.com/82398540/114427566-d1a06100-9b80-11eb-82b7-be7ca0006c60.png)
Makemake blocks 1

![2021-04-12_11 10 08](https://user-images.githubusercontent.com/82398540/114427591-d9600580-9b80-11eb-9b42-ef77acd83c94.png)
Makemake blocks 2

![2021-04-12_11 10 13](https://user-images.githubusercontent.com/82398540/114427608-dd8c2300-9b80-11eb-8c36-81f03c70d039.png)
Makemake blocks 3

![2021-04-12_11 10 18](https://user-images.githubusercontent.com/82398540/114427641-e7ae2180-9b80-11eb-9346-93e8ed92feae.png)
Ice blazes

1.12.2 screenshots
![image](https://user-images.githubusercontent.com/82398540/114428373-bb46d500-9b81-11eb-9d0b-888eac9a6c29.png)
Options of the mod (galaxy space)

![image](https://user-images.githubusercontent.com/82398540/114430354-f6e29e80-9b83-11eb-9163-a8d4ac85f2ca.png)
Makemake does not apear

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by ROMVoid95** [comment]
its not actually implemented

**Comment by ghost** [comment]
I wana land on Makemake

**Comment by ghost** [comment]
> its not actually implemented

I don't think it is ether?
ps: Please unblock me from Issues.
