### ISSUE TITLE
(Suggestion)Option to disable sky mapping

### ISSUE THREAD

**Issue by Realittttty** [BlesseNtumble/GalaxySpace#527]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.280
3. GalaxySpace version:2.0.16
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.25
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:
It is suggested to add the option of disable sky mapping. Although the sky at night is beautiful,But I prefer the sky of custom resource package.
Note: there is no such problem in GS version 2.0.14, which only appears after 2.0.16
------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by Realittttty** [comment]
Not long after I made this suggestion, I found a new problem. The sky map of 2.0.16 will make the shader sky error.
2.0.16：https://ftp.rss.ink/imgs/2021/05/28f05f57c574a4d3.png
2.0.14：https://ftp.bmp.ovh/imgs/2021/05/1db49a4cad1b5e97.png
So it's necessary to add the option to disable sky mapping.
In addition, my English is very poor, the above are machine translation, please forgive me. XD

**Comment by BlesseNtumble** [comment]
configs/AsmodeusCore/core.conf

    # Enable/Disable Advanced Sky Provider on Overworld (Not support shaders).
    B:enableSkyOverworld=true

**Comment by Realittttty** [comment]
oh! i found it. i only looked at the GS configuration file before, but I didn't expect that it was in the Asmodeus core configuration file. thx!
