### ISSUE TITLE
Mars dungeon does not generate drawing box(火星地牢没有图纸盒子)

### ISSUE THREAD

**Issue by lp20010415** [BlesseNtumble/GalaxySpace#528]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:1.12.2-4.0.2.280
3. GalaxySpace version:1.12.2-2.0.16
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.25
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP
6. Other add-ons:Avaritia-1.12.2-3.3.0.33-universal
------------------------------------------------------------------------
Description of the issue:
我总共开了10个二阶宝箱，但是都没有图纸盒子，不会爆率这么低吧？
Translate:
I opened a total of 10 second-order treasure boxes, but there are no drawing boxes. Won't the explosion rate be so low?

------------------------------------------------------------------------
Screenshot/Video:
我没有录，如果需要的话，我可以录下视频来！
Translate:
I forget,if you need,i will make

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
none

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Schematic box on Moon dungeons and Moon Villagers

**Comment by lp20010415** [comment]
> 月球地牢和月球村民的示意图框
什么意思？
What"s mean?

**Comment by lp20010415** [comment]
> Schematic box on Moon dungeons and Moon Villagers

Ok,I'll take a look

**Comment by lp20010415** [comment]
我找到了，不过好像找了6-8个箱子，脸黑，哈哈。不过总算知道了哪里生成了，哈哈。感谢作者！
I found it, but it seems that I found 6-8 boxes, black face, ha ha. But I finally know where to generate, ha ha. Thank the author!
