### ISSUE TITLE
Spanish Localization for GalaxySpace!

### ISSUE THREAD

**Issue by CreeperCristo** [BlesseNtumble/GalaxySpace#532]
I just found the mod didn't have a spanish translation, so I decided to create a .lang file by myself and upload it here.
I hope this gets into the next Galaxyspace update very soon.
Most of the texts in the file are manually translated into spanish, except for the Info-Pad texts (those are WIP anyway, won't be used properly until completed i guess) plus a little easter egg related to the Titan ores (has to do with someone we know who's frome Titan) ;)
[es_ES.txt](https://github.com/BlesseNtumble/GalaxySpace/files/6745713/es_ES.txt)

**Comment by CaveJohnson376** [comment]
you could fork GS repo, add that lang file to your fork, and then open pull request

**Comment by CreeperCristo** [comment]
Im new to GitHub. Not sure how to "fork" a repo.

**Comment by CaveJohnson376** [comment]
there's a button for that
![image](https://user-images.githubusercontent.com/33164023/124076319-87cc6600-da5f-11eb-8ba7-59151d540290.png)
