### ISSUE TITLE
Game crashes when opening the star rmap

### ISSUE THREAD

**Issue by Creet1724** [BlesseNtumble/GalaxySpace#537]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.2.280
3. GalaxySpace version: 1.12.2-2.0.16
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.26
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Singleplayer
6. Other add-ons: ExtraPlanets-1.12.2-0.7.3, More-Planets-1.12.2-2.2.1-GC280
------------------------------------------------------------------------
Description of the issue:
I disabled some of the planets in ExtraPlanets, then I launched the game, entered a world, then when I open the star map, it crashed the game.
------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://pastebin.com/re8VH9f6
------------------------------------------------------------------------

**Comment by Frostiocean** [comment]
try removing more planets it caused me more erros than it did content
