### ISSUE TITLE
Некоторые проблемы с рецептами при нестандартных параметрах

### ISSUE THREAD

**Issue by QuantumStatement** [BlesseNtumble/GalaxySpace#543]
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.281
3. GalaxySpace version: 2.0.16.1
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.26
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: none
------------------------------------------------------------------------
Description of the issue:

1. При отключенном параметре `enablePlateOredict` Декоративный медный блок не крафтится.
2. При отключенном параметре `enableAdvancedRocketCraft` в JEI для ракеты 3 уровня рецепт не отображается, а для ракеты 2 уровня отображается продвинутый рецепт вместо стандартного.
JEI 4.16.1.302

------------------------------------------------------------------------
Screenshot/Video:
N/A

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
N/A

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
https://github.com/BlesseNtumble/GalaxySpace/commit/9356c3f9168cb0dd651bbf1af5385d988f3efbb3
