### ISSUE TITLE
Game crashes when opening the Galaxy Map

### ISSUE THREAD

**Issue by Lewyfcb9pro** [BlesseNtumble/GalaxySpace#547]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.280
3. GalaxySpace version:2.0.16.1
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.26
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP,SMP,LAN
6. Other add-ons:Extra Planets, galacticraft Planets, InterStellar Exoplanets, More Planets and More Planets Extras
------------------------------------------------------------------------
Description of the issue:
Both of the Config files (Extra Planets and Galaxy Space) are set to use the Extra Planets Galaxy Map but when I try opening the Galaxy Map the game crashes and yes I set the enableNewGalaxyMap to false and saved. If you want to see all the mods I'm using they are in the Crash Log.

------------------------------------------------------------------------
Screenshot/Video:
I don't have andy

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://pastebin.pl/view/83e5be10

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Redownload AsmodeusCore

**Comment by Lewyfcb9pro** [comment]
Downloaded the fixedcfg version and it works.
Thanks
