### ISSUE TITLE
Краш на Ио.

### ISSUE THREAD

**Issue by LeoonWi** [BlesseNtumble/GalaxySpace#549]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version: 2.0.16.1
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.26
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP
6. Other add-ons: Без них тоже вылетает
------------------------------------------------------------------------
Description of the issue:
Крашится мир, скорее всего, при генерации данжа на спутнике Ио. После чего зайти на мир я уже не могу.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/7071229/latest.log)
[crash-2021-08-28_20.45.35-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/7071231/crash-2021-08-28_20.45.35-server.txt)

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Try 2.0.17 version
