### ISSUE TITLE
Проблемы при создании космических станций

### ISSUE THREAD

**Issue by PompomAndHula** [BlesseNtumble/GalaxySpace#55]
Ни над Марсом, ни над Землёй не удаётся создать станцию. Все ресурсы, которые требуются для создании имеются, но при нажатии кнопки "создать" карта просто отдаляет солнечную систему. Пытался создать в креативе и без - не помогло.
Что вы можете мне посоветовать?
Заранее благодарен.

**Comment by BlesseNtumble** [comment]
Это баг в GC3, нужно приземлится на планету и снова взлететь.
