### ISSUE TITLE
Crash After The Last Update of Asmodeus Core(0.0.27)

### ISSUE THREAD

**Issue by KenyMylankca** [BlesseNtumble/GalaxySpace#551]
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.281
3. GalaxySpace version: 2.0.16
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.27
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): game startup
6. Other add-ons:none
------------------------------------------------------------------------
Description of the issue:
game wont start(Crash)

Attached log file (or url on pastebin.com):

[crash-2021-10-18_19.05.13-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/7366888/crash-2021-10-18_19.05.13-client.txt)
-

i just updated asmodeus core from 0.0.26 to 0.0.27 and this happens.

**Comment by CaveJohnson376** [comment]
asmodeuscore 0.0.27 is NOT compatible with GS 2.0.16. downgrade asmodeus core and wait for GS 2.0.17 to release

**Comment by KenyMylankca** [comment]
oh, thx for the information.
