### ISSUE TITLE
2.0.16 crashes every time i launch it      [A commenter helped me, please close it]

### ISSUE THREAD

**Issue by imadethisaccounttoreportbugs** [BlesseNtumble/GalaxySpace#553]
------------------------------------------------------------------------
1. Minecraft version: 1.12.2 tried both 14.23.5.2855 and 14.23.5.2854 forge

2. Galacticraft version: Newest

3. GalaxySpace version: 2.0.16

4. AsmodeusCore version (for 2.0.1 version and above): 0.0.27

5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP (can test using SSP)

6. Other add-ons: Apple skin 1.0.14, Galacticraft rpc (shows where you are and puts on Discord), HBM's Nuclear Tech 1.6.4a-Gv1 (classified as to why I put it on this mod pack), journey map 5.7.1, More Planets, its extras mod and core. (main: 2.2.1 core: 1.1.10 extras: 1.0), ExtraPlanets (core: 1.2.1  main: 0.7.3 ) (Tried EVERYTHING on MJR's compatibility support), and thats it.

_**Mod list if i missed anything**_
![modlist](https://user-images.githubusercontent.com/82173052/138577794-0c903166-1c76-4778-942d-3e3153d00d2a.PNG)

------------------------------------------------------------------------
Description of the issue:
a few months ago it worked perfectly fine, and it didn't crash, but now it does crash unexpectedly when I try to launch it. In stage 2/7 for mod loading, when it hits the GalaxySpace portion of loading, it crashes.

------------------------------------------------------------------------
Screenshot/Video:

![crashed](https://user-images.githubusercontent.com/82173052/138577728-1a91c02b-06ea-45db-9bd0-706a65ea6131.PNG)

------------------------------------------------------------------------
Attached log file (or URL on pastebin.com):

[crash-2021-10-23_22.21.53-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/7403961/crash-2021-10-23_22.21.53-client.txt)

------------------------------------------------------------------------

**Comment by kicekkic** [comment]
I have the same problem

**Comment by CaveJohnson376** [comment]
from ViTold's (BlesseNtumble's) discord server
![image](https://user-images.githubusercontent.com/33164023/138592335-7cfdabb0-efc6-4b56-8a3b-071804630914.png)

**Comment by imadethisaccounttoreportbugs** [comment]
> from ViTold's (BlesseNtumble's) discord server ![image](https://user-images.githubusercontent.com/33164023/138592335-7cfdabb0-efc6-4b56-8a3b-071804630914.png)

Thank you
