### ISSUE TITLE
Crashing while trying to jump in Earth Space Station

### ISSUE THREAD

**Issue by MinecraftModEnjoyer** [BlesseNtumble/GalaxySpace#554]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.281
3. GalaxySpace version: 2.0.17
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.27
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: Techguns, Better FPS, Damage Indicator, Grapple Mod, NaturesCompass, Reap, Sit.
------------------------------------------------------------------------
Description of the issue:
I tried to jump in Earth Space Station, Minecraft crashed. I can't return to the world, because Minecraft crashes while I'm trying to open the world.

------------------------------------------------------------------------
Screenshot/Video:
Can't upload media because I can't open the world. 

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/7464290/latest.log)

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Update AsmodeusCore to 0.0.28 version and try again

**Comment by MinecraftModEnjoyer** [comment]
Not worked. Still the same error.

**Comment by MinecraftModEnjoyer** [comment]
hold up, maybe i need update galacticraft?
Edit1: Damn it, still not working.
Edit2: Some assistance, please!

**Comment by BlesseNtumble** [comment]
last log please

**Comment by MinecraftModEnjoyer** [comment]
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/7470237/latest.log)

**Comment by BlesseNtumble** [comment]
Ok, redownload 0.0.28 build frm curseforge. Should fix.

**Comment by MinecraftModEnjoyer** [comment]
It worked!
