### ISSUE TITLE
Updated Spanish Translation for 1.12.2!!

### ISSUE THREAD

**Issue by CreeperCristo** [BlesseNtumble/GalaxySpace#558]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: I don't know-- Ok, I checked out: Galacticraft Core: 1.12.2-4.0.2.280, Galacticraft Planets: 1.12.2-4.0.2.281
3. GalaxySpace version: 1.12.2-2.0.17
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.28
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): All of them.
6. Other add-ons: None I'm aware of.
------------------------------------------------------------------------
Description of the issue:
Hey Blesse, remember me? It's been a long time since I don't play on my 1.12 modpack. I've recently moved to 1.16.5 with Mekanism, Quark, and Ice & Fire stuff mixed together. But I still visit Galaxy Space's Curseforge page. It's good to see the addon is still alive after 4 years of development! Even when everybody it's just talking about things like the coming 1.18 and 1.19 updates, with the Warden and the Allay and the Deep Dark Cities and stuff.

Straight to the point, I've just downloaded the new update a few days ago. It's surprising it has the spanish lang file I made (I feel famous lol!). So, I've made a new updated and revised language file. It only took me half afternoon. I just had to modify the old ES_es.lang file to add the new item names and fixed some spelling errors (The new spacesuit descriptions messed me up a bit.)  I've also removed the Infinity Stones pun on the names of Titan's ores (I know it was something stupid), but they are still under the corrected ore names in case you actually wanted to keep them.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
Here it is:
[es_ES.txt](https://github.com/BlesseNtumble/GalaxySpace/files/7575443/es_ES.txt)
And also the Pastebin URL just in case:
https://pastebin.com/cykG4mE6

**Comment by BlesseNtumble** [comment]
https://github.com/BlesseNtumble/GalaxySpace/commit/bb4126262a9686baa5357b2640207a9f5d4bc1b7
