### ISSUE TITLE
Galaxy Space rendering 2D Overworld above y=190 

### ISSUE THREAD

**Issue by XcelOrbit** [BlesseNtumble/GalaxySpace#563]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version: 2.0.17
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.28
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Client Visual Bug
6. Other add-ons: None
------------------------------------------------------------------------
Description of the issue:
I was developing a modpack for 1.12.2 with a whole ton of mods, one of which adds very tall mountains. Upon reaching the top of the mountain, I see the 2D Overworld render below my feet as if I were launching into space. I created a test instance to recreate the issue, and upon loading nothing but Galacticraft and its core mods along with Galaxy Space and its core mods I see that if I fly above y 190 the 2D Overworld appears. Disabling Galaxy Space gets rid of the issue. I see that there is no way to disable this or raise the level at which the 2D render appears, nor is there a way to disable the sky that Galaxy Space adds. I've also noticed that the 2D Overworld starts to flash with Astral Sorcery installed. Is there any way to raise the y level that the 2D Overworld appears so that it will only appear much past the build height limit?

------------------------------------------------------------------------
Screenshot/Video:
(https://imgur.com/Jy0GCL2)
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
Visual Bug, no crash logs
------------------------------------------------------------------------

**Comment by QuantumStatement** [comment]
You can change the `renderBodyPosY` parameter in `config\AsmodeusCore\core.conf` config file
