### ISSUE TITLE
Sharing Repo / Forking GTNH's custom version of GS

### ISSUE THREAD

**Issue by Houstonruss** [BlesseNtumble/GalaxySpace#565]
------------------------------------------------------------------------
1. Minecraft version: Forge 7.10.99.99 for MC 1.7.10
2. Galacticraft version: 3.0.13 (GTNH version)
3. GalaxySpace version: 1.1.7c (GTNH version)
4. AsmodeusCore version (for 2.0.1 version and above): Micdoodlecore iirc no version.
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): NA
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:
Hello! Myself and some friends have created a hard fork of GT: New Horizons and we would like permission to use their custom version in our pack GTMEGA, and since we'd end up distributing modified versions we want your go-ahead.

Ideally all of our dev work will be in our private repo, which will be forked from GTNH's private repo.
Bugs and Issues will be sent to GTMEGA's issue tracker, not here.

GTNH devs are ok with GTMEGA using their fork so long as they can potentially use GTMEGA's modifications to GS.
Currently we are a "private" modpack as we seek out mod permissions for our use.
------------------------------------------------------------------------
Links for reference.
https://github.com/BlesseNtumble/GalaxySpace/issues/485
GTNH Discord: https://discord.gg/gtnh
GTMEGA Discord: https://discord.gg/gtmega
------------------------------------------------------------------------
Thanks for your time. -Houston

**Comment by BlesseNtumble** [comment]
If you plan to distribute a modified version of GS, then the following is required:
1) Your version of GS should only work in your modpack. (Preferred)
2) The source code of GS is still closed. It is also impossible to distribute the source code of the modified version.
3) When developing your version of GS, you cannot use resources and code from the original version of GS.
4) It is forbidden to sell the modified version.
5) Be sure to indicate the author of the addon in the modified version and a note that the version is not original.
