### ISSUE TITLE
Nature Gas Flowing Up

### ISSUE THREAD

**Issue by jake4832** [BlesseNtumble/GalaxySpace#576]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.2.280
3. GalaxySpace version: 1.12.2-2.0.18
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.30
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: None
------------------------------------------------------------------------
Description of the issue:

While I get that the nature gas flows upward, like actual natural gas, this means that any time it gets to a place with no ceiling, it will flow endlessly into the sky, creating quite an ugly picture. The screenshot attached shows what this looks like when there's a gas pocket in a ravine. It just creates a massive blob of gas that takes up the skyline

------------------------------------------------------------------------
Screenshot/Video:
![2022-03-06_04 21 48](https://user-images.githubusercontent.com/44510921/156917080-d67f1ef0-8969-4e88-98ab-c87a445b5092.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by v1993** [comment]
Yeah, it would be nice to at least have an option to disable gas generation for now. It ruins naturally generated landscapes.
