### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Shazuli** [BlesseNtumble/GalaxySpace#58]
Hi!

I'm currently making my own private modpack with a few friends, it works fine until I install your mod (I just want to say that your mod looks amazing just by looking at the pictures!) and my game crashes on startup. Here is the mod list and the crash report:

Alternate Terrain generation, Buildcraft, Buildcraft Compat, Chisel 2, CodeChickenCore, DragonAPI, ElectricCraft, EnderCore, Logistics Pipes, MineTweaker 3, ModTweaker 2, NotEnoughtItems, OpenComputers, ProjectRed Compatibility, ProjectRed Core, ProjectRed Illumination, ProjectRed Transmission, ReactorCraft. RotaryCraft, Waila, WAILA Plugins, WorldEdit, GalaxySpace, GalacyCraft, Galacticraft Planets, MicdoodleCore.

[crash-2016-05-28_18.39.45-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/287805/crash-2016-05-28_18.39.45-client.txt)

**Comment by BlesseNtumble** [comment]
ci.micdoodle8.com
Download >454 build
