### ISSUE TITLE
Remove Proxima C and D. They have no textures, cannot be travelled to, and have no config for disabling them.

### ISSUE THREAD

**Issue by MagmaSlime123** [BlesseNtumble/GalaxySpace#584]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version: 2.0.18
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.30
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Singleplayer.
6. Other add-ons: MorePlanets/Extras.
------------------------------------------------------------------------
Description of the issue:
See title.

------------------------------------------------------------------------
Screenshot/Video:
![2022-05-15_22 21 37](https://user-images.githubusercontent.com/51277766/168519316-31b57654-0e94-4e0f-9b19-65eb781a4681.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
N/A

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Fixed in 2.0.19
