### ISSUE TITLE
No gravity at all on asteroids

### ISSUE THREAD

**Issue by AlexLikeFoxes** [BlesseNtumble/GalaxySpace#588]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.284
3. GalaxySpace version: 2.0.18
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.30
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: More planet, More planet extra and star maker
------------------------------------------------------------------------
Description of the issue: There is no gravity at all on asteroid and its
impossible to move

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
config/GalaxySpace/core.conf
# Enable/Disable zero gravity (like Kuiper Belt) on Astreroids.
    B:enableZeroGravityOnAsteroids=true
    
set false
