### ISSUE TITLE
Тяжёлая космическая броня отображается не правильно

### ISSUE THREAD

**Issue by FibrousBadger65** [BlesseNtumble/GalaxySpace#590]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.281
3. GalaxySpace version: 2.0.18
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.30
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP and SMP
6. Other add-ons: more planets 2.2.2-GC280
------------------------------------------------------------------------
Description of the issue:
Этот баг у меня был ещё на прошлых версиях если не ошибаюсь на 2.0.16 тоже такой баг был но тогда я играл в одиночную игру, а сейчас в Многопользовательскую.

------------------------------------------------------------------------
Screenshot/Video:

https://user-images.githubusercontent.com/107522055/173719394-fabe2984-7a32-407c-94f4-3ee84549b78c.mp4

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
броня зачарована?

**Comment by FibrousBadger65** [comment]
Да зачарованна, но она была такой до зачарования

**Comment by FibrousBadger65** [comment]
думаю обновлю драйвера на видеокарту, и скажу помогло ли

**Comment by BlesseNtumble** [comment]
Не, это в коде дело)

**Comment by FibrousBadger65** [comment]
мм, значит то что я качаю драйвера не поможет :/

**Comment by FibrousBadger65** [comment]
буду значит ждать обновы мода

**Comment by BlesseNtumble** [comment]
Тестовый фикс в 2.0.19, ожидайте
