### ISSUE TITLE
Game crashes after updating to latest 1.7.10 version

### ISSUE THREAD

**Issue by Lewyfcb9pro** [BlesseNtumble/GalaxySpace#591]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:     1.7.10
2. Galacticraft version:  1.7-3.0.12.504
3. GalaxySpace version:1.2.15
4. AsmodeusCore version (for 2.0.1 version and above):   not available for 1.7.10
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):   Game startup
6. Other add-ons:   beyond space (1.0.0), extra planets (2.1.4), GC-planets (3.0.12.504), zollern-galaxy (1.4.4)
------------------------------------------------------------------------
Description of the issue:
after updating the mod from 1.2.14 to 1.2.15 (I didn't expect any mods to be updated for 1.7.10) the game doesn't finish loading

------------------------------------------------------------------------
Screenshot/Video:
https://www.youtube.com/watch?v=Tn2XXb8AzFo

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
log: https://pastebin.com/9MRzZW5g
crash-report: https://pastebin.com/Xxz5n1TZ
------------------------------------------------------------------------

**Comment by GalacitCity** [comment]
The cause of the crash is java.lang.NullPointerException

**Comment by GalacitCity** [comment]
Why not try increasing your initiator memory?

**Comment by BlesseNtumble** [comment]
Remove BeyondSpace

**Comment by GalacitCity** [comment]
> 移除超越空间

So the beyond space mod is useless for ever?

**Comment by Lewyfcb9pro** [comment]
Oh thanks it just showed me will test it shortly
