### ISSUE TITLE
Latest 1.7.10 Version(1.2.15) Bug:No Vega B and Tau Ceti System On galaxy map

### ISSUE THREAD

**Issue by Oldmemory1** [BlesseNtumble/GalaxySpace#592]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.7.10
2. Galacticraft version:3.0.12.504
3. GalaxySpace version:1.2.15
4. AsmodeusCore version (for 2.0.1 version and above): None
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP
6. Other add-ons:None
------------------------------------------------------------------------
Description of the issue:
I have seen the changelog info of 1.2.15 on curseforge:
1) Many fixes

2) Added Tau Ceti system

3) Added Vega B system

I lanuch the game successfully and press M to open the galaxy map,however I do not found any new galaxy system added,I can not see Vega B and Tau Ceti.
I am sorry that my English is so poor.
Modlists:
![0UWY2DYWTD~TSVKUYBSEB5X](https://user-images.githubusercontent.com/94025104/175749198-0ab51fc4-fb2b-4591-aed2-4a2bb5312e30.png)

------------------------------------------------------------------------
Screenshot/Video:

![20220625073848](https://user-images.githubusercontent.com/94025104/175749156-4f635095-0761-4d92-b153-e988e7820add.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
config/GalaxySpace/core.conf

B:enableOldSystems=true
