### ISSUE TITLE
Two missing systems

### ISSUE THREAD

**Issue by GalacitCity** [BlesseNtumble/GalaxySpace#593]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.7.10
2. Galacticraft version:3.0.12.504(1.7)
3. GalaxySpace version:1.12.15
4. AsmodeusCore version (for 2.0.1 version and above): none
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):ssp
6. Other add-ons:none
------------------------------------------------------------------------
Description of the issue:
Vega and tau ceti have been added to the changelog of forge, but these two systems are not included in the 1.2.15 version of the galaxy space (the latest 1.7.10 version).

------------------------------------------------------------------------
Screenshot/Video:
![1656113948_31111_pNIu](https://user-images.githubusercontent.com/108249398/175855579-c326391f-1f55-49a3-a5b7-90700c03b9bd.png)
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

(Sorry, I can't find this file)
------------------------------------------------------------------------

**Comment by GalacitCity** [comment]
Note: this screenshot is in Chinese, not English

**Comment by BlesseNtumble** [comment]
#592
