### ISSUE TITLE
Stars on Proxima B do not render, just their flares

### ISSUE THREAD

**Issue by CheetahCyberBoi** [BlesseNtumble/GalaxySpace#599]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.284
3. GalaxySpace version: 2.0.18
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.30
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: GC RPC, More planets, more planets extras, interstellar exoplanets
------------------------------------------------------------------------
Description of the issue:
When on Proxima B, Alpha Centauri A/B and Proxima Centauri are not visible, yet the background flares (the little spikes and things) are still visible. Interestingly, when descending to Proxima B, at the start you can see only Proxima Centauri (and tiny blips as the other stars), but when you are on the surface, nothing is visible star-wise. 

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------
![2022-07-05_14 14 39](https://user-images.githubusercontent.com/81482606/177417930-ddd2558c-404e-4fcb-bc98-7fef06999909.png)
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/9049743/latest.log)

**Comment by BlesseNtumble** [comment]
Fog
