### ISSUE TITLE
2.0.19 Crash when startup

### ISSUE THREAD

**Issue by SinusoidalC** [BlesseNtumble/GalaxySpace#600]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.284
3. GalaxySpace version:2.0.19
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.30
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP、SMP
6. Other add-ons:none
------------------------------------------------------------------------
Description of the issue:

Crash when startup
------------------------------------------------------------------------
Screenshot/Video:

none
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

https://paste.ubuntu.com/p/9qjw55y7gc/
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Update AsmodeusCore
