### ISSUE TITLE
Crash To Desktop During Pre-Init 2.0.19

### ISSUE THREAD

**Issue by CharlesWedge** [BlesseNtumble/GalaxySpace#601]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version: 2.0.19
4. AsmodeusCore version (for 2.0.1 version and above): 0.31
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: JEI only
------------------------------------------------------------------------
Description of the issue:
Upon attempting to load Minecraft with Galaxy Space loaded, minecraft will crash when attempting to Pre-Initialize. After moving files around in my mods folder I confirmed it was not just the case of a corrupted file or some new incompatibility with an existing mod on my instance. Included is log file, hopefully this can be fixed quickly.
------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

[crash-2022-07-13_18.35.07-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/9106760/crash-2022-07-13_18.35.07-client.txt)

------------------------------------------------------------------------

**Comment by seasonedcurlys** [comment]
got the same error too

**Comment by BlesseNtumble** [comment]
https://www.curseforge.com/minecraft/mc-mods/galaxy-space-addon-for-galacticraft/files/3873672
