### ISSUE TITLE
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GalaxySpace (galaxyspace)

### ISSUE THREAD

**Issue by LostGameDev** [BlesseNtumble/GalaxySpace#604]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.2.280
3. GalaxySpace version:2.0.19
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.31
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons:galacticraft-rpc, GalacticraftTweaker, PlanetProgression, SpaceAmbient, ZollernGalaxy, GalacticComputers
------------------------------------------------------------------------
Description of the issue: when loading the game with galaxy space installed it crashes

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):https://pastebin.com/S1cMq2X1

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
#601 
or update GC from CurseForge to 284 build
