### ISSUE TITLE
takeoff and crash

### ISSUE THREAD

**Issue by sergey-byte** [BlesseNtumble/GalaxySpace#607]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: Galacticraft-1.12.2-4.0.2.284
3. GalaxySpace version: GalaxySpace-1.12.2-2.0.19_Comp_280_GC
4. AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-0.0.31
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: 
------------------------------------------------------------------------
Description of the issue:
after takeoff, the game crashes in a couple of seconds

------------------------------------------------------------------------
Screenshot/Video:
![Безымянный](https://user-images.githubusercontent.com/64485141/181268911-80e701cd-e080-4b52-b864-d6376551976c.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/9199840/latest.log)

[crash-2022-07-27_18.10.32-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/9199842/crash-2022-07-27_18.10.32-client.txt)

**Comment by CaveJohnson376** [comment]
time4tfc TFC addon seems to tamper with GC/AC code when it shouldn't

side note: you seem to use fake TL. more info on that at https://minecraftmain.ru/2018/02/tlauncher-story

**Comment by BlesseNtumble** [comment]
disable Overworld sky in AsmodeusCore config file
