### ISSUE TITLE
Newer version kept crashing

### ISSUE THREAD

**Issue by some525242** [BlesseNtumble/GalaxySpace#608]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:
2. Galacticraft version:
3. GalaxySpace version:
4. AsmodeusCore version (for 2.0.1 version and above): 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:
So, I got the GalactiCraft and everything, but it kept crashing

-------------------

-----------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

[crash-2022-07-29_00.07.01-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/9216750/crash-2022-07-29_00.07.01-client.txt)

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
#600

**Comment by some525242** [comment]
i just did

**Comment by some525242** [comment]
thanks
