### ISSUE TITLE
Server crashes after updating GS to 2.0.19

### ISSUE THREAD

**Issue by dvdcorsair** [BlesseNtumble/GalaxySpace#611]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version 1.12.2 forge 2860:
2. Galacticraft version 1.12.2-4.0.2.280:
3. GalaxySpace version 1.12.2-2.0.19:
4. AsmodeusCore version 1.12.2-0.0.31: 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP
6. Other add-ons:
![изображение](https://user-images.githubusercontent.com/93685067/182413315-6f0a434b-ee90-4a9e-be23-9fdb0edff949.png)
![изображение](https://user-images.githubusercontent.com/93685067/182413430-cfc3bb1c-7fb0-442a-a752-a5bfe1071f7b.png)
![изображение](https://user-images.githubusercontent.com/93685067/182413495-c66f2c77-6bb1-4c91-83c3-555659162782.png)

------------------------------------------------------------------------
Description of the issue: Server stops

------------------------------------------------------------------------
Screenshot/Video: There is no any of it
 

------------------------------------------------------------------------
Attached log file (or url on pastebin.com): 
[debug.log](https://github.com/BlesseNtumble/GalaxySpace/files/9243580/debug.log)

[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/9243581/latest.log)
Crash report
[crash-2022-08-02_16.22.58-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/9243586/crash-2022-08-02_16.22.58-server.txt)

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
newer versions of GS require GC patch 284 or newer

**Comment by dvdcorsair** [comment]
where it can be downloaded?

**Comment by dvdcorsair** [comment]
> newer versions of GS require GC patch 284 or newer
that one? https://www.curseforge.com/minecraft/mc-mods/galacticraft-legacy/files/3648807

**Comment by CaveJohnson376** [comment]
on CurseForge
