### ISSUE TITLE
Кислородные баллоны быстро опустошаются под водой

### ISSUE THREAD

**Issue by QuantumStatement** [BlesseNtumble/GalaxySpace#613]
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.284
3. GalaxySpace version: 2.0.19
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.31
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:

Я не знаю, баг это или так задумано, но при нахождении под водой кислородные баллоны очень быстро опустошаются. Например, большого кислородного баллона из Galacticraft хватает приблизительно на две минуты. В космосе же его хватало более чем на 20 минут.
Тестировались оба космических костюма с улучшением "Подводное дыхание".

------------------------------------------------------------------------
Screenshot/Video:

N/A

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

N/A

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Не баг. Баллоны фиксировано за 1 единицу прочности пополняют 300 ед. воздуха.
