### ISSUE TITLE
Missing entries after opening a world

### ISSUE THREAD

**Issue by Lupa13** [BlesseNtumble/GalaxySpace#620]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: Galacticraft-1.12.2-4.0.3
3. GalaxySpace version: GalaxySpace-1.12.2-2.0.19
4. AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-0.0.31
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Single player (SSP)
6. Other add-ons: See screenshot down here
<img width="660" alt="image" src="https://user-images.githubusercontent.com/64890347/184862515-463c2eb6-afda-44d7-99b9-6d8c10a30213.png">

------------------------------------------------------------------------
Description of the issue:
After downloading the latest GalaxySpace version and a few other addons, I opened a world and the game showed this error:

"Forge Mod Loader detected missing registry entries.
There are 1 missing entries in this save.
If you continue the missing entries will get removed.
A world backup will be automatically created in your saves directory.
Missing minecraft:blocks:galaxyspace:block_naturegas

------------------------------------------------------------------------
Screenshot/Video:
![Immagine 2022-08-16 123858](https://user-images.githubusercontent.com/64890347/184862645-fdf2c69f-64ee-4117-ac5f-6a1483529dfb.jpg)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by GalacitCity** [comment]
I don't think you need to worry. It's normal

**Comment by GalacitCity** [comment]
This is not a problem with other mods

**Comment by GalacitCity** [comment]
You can still play

**Comment by Lupa13** [comment]
@GalacitCity thank you for your answer!!
I agree with you, I can still play, but I fear that I won't be able to find natural gas in the world (if "block_naturegas" means natural gas) because there is not the information needed for the world to generate it...I'm not an expert so I don't know exactly how it works but I hope I won't need to switch to creative mode to get natural gas, you know😂...
Thanks!

**Comment by GalacitCity** [comment]
You don't have to worry about this problem, it won't affect the generation of naturel gas,In fact, it is possible that nature gas will not be generated only in your chuck(I mean, this may affect the generation of some chucks, but not all)in other words,You can still play

**Comment by Lupa13** [comment]
@GalacitCity Ok, thank you!!
