### ISSUE TITLE
Mars SS Crash

### ISSUE THREAD

**Issue by kaguyahimeinthemoon** [BlesseNtumble/GalaxySpace#622]
MC 1.12.2
Galaxy Space 2.0.19
Galacticraft 4.0.3
AsmodeusCore: 0.0.31

1. /dimensiontp
2. Create a Mars Space Station
3. Select and Launch
4. Place a basic/advanced solar panel from GC

The crash makes the world unplayable unless you remove the spacestation dimension folder

**Comment by BlesseNtumble** [comment]
please attach log file

**Comment by BlesseNtumble** [comment]
fixed in next build
