### ISSUE TITLE
minecraft crashing 

### ISSUE THREAD

**Issue by ghost** [BlesseNtumble/GalaxySpace#629]
q

**Comment by Czechoslovakia2** [comment]
Update AsmodeusCore: https://www.curseforge.com/minecraft/mc-mods/asmodeuscore/files/3873588
Get the GC .280 compatible version of GalaxySpace 2.0.19 if you really need it: https://www.curseforge.com/minecraft/mc-mods/galaxy-space-addon-for-galacticraft/files/3873672

If confused about "there's more than .280???", look at: https://www.curseforge.com/minecraft/mc-mods/galacticraft-legacy

**Comment by aadsasd435t** [comment]
this fixed my issue, thank  you so so much!
