### ISSUE TITLE
Вылет майнкрафта.

### ISSUE THREAD

**Issue by ghost** [BlesseNtumble/GalaxySpace#63]
Баг репорты (2):[bug report.zip](https://github.com/BlesseNtumble/GalaxySpace/files/300338/bug.report.zip)
Я выяснил,что причиной для вылета становится мод applied energystics.Первый вылет происходит при первом запуске мира.При последующих запусках все стабильно,но при запуске любой ракеты на 18 секунде обратного отсчёта вылетает майн.
Список модов (102):[Список модов.zip](https://github.com/BlesseNtumble/GalaxySpace/files/300352/default.zip)

**Comment by BlesseNtumble** [comment]
java.lang.IllegalArgumentException: Could not get provider type for dimension -30, does not exist

Конфликт ID измерений.
- 30 - это Астероиды.
