### ISSUE TITLE
Moon Renders Glitched

### ISSUE THREAD

**Issue by jredfox** [BlesseNtumble/GalaxySpace#64]
Version: 1.09 Stable
Images: http://imgur.com/5GJLgLy

galacticraft vanilla Moon Renders Glitched. I go to the moon and I am upsidedown so is the spacecraft. I took your mod out and it was fixed.

**Comment by BlesseNtumble** [comment]
Galacticraft version?

**Comment by jredfox** [comment]
Versions = recommended versions
GalacticraftCore-1.7-3.0.12.442
Galacticraft-Planets-1.7-3.0.12.442
MicdoodleCore-1.7-3.0.12.442

**Comment by jredfox** [comment]
I updated to the latest that seemed to fix the issue.
