### ISSUE TITLE
How to find or craft dolomite crystal???

### ISSUE THREAD

**Issue by Kkelos** [BlesseNtumble/GalaxySpace#644]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:4.0.4
3. GalaxySpace version:2.0.19
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.31
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP
6. Other add-ons:Jei
------------------------------------------------------------------------
Description of the issue:
I know, this is stupid question, but:
How to craft, or find dolomite crystal???
I try to find it, but i can't.

------------------------------------------------------------------------
Screenshot/Video:
None

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
None

------------------------------------------------------------------------

**Comment by weeJman** [comment]
Go to Ceres.

**Comment by Kkelos** [comment]
> Go to Ceres.

Oh, thanks!
