### ISSUE TITLE
[Suggestion] Config setting to enable/disable Sublight Engine requirement

### ISSUE THREAD

**Issue by KingColton1** [BlesseNtumble/GalaxySpace#653]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.05
3. GalaxySpace version: 2.0.19
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.31
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP
6. Other add-ons: Extra Planets, More Planets, More Planets Extras, GalacticTweaks, Space Ambient, and Zollern Galaxy
------------------------------------------------------------------------
Description of the issue:
I noticed there is no way to disable Sublight Engine requirement to be able to use other add-on rockets like Extra Planets. Yes I'm aware that I could simply disable the galaxy map to use Extra Planets' map to bypass this requirement but my server prefer AsmodeusCore's map because it's just way better design.

------------------------------------------------------------------------
This change would have the following benefits:
It would provide more flexibility on how you like with your game without being hindered by this requirement. Getting a sublight engine is pretty difficult and high risk to lose one. I've been hearing other people's issues with this item such as losing sublight engine when landing on another planet, can't use it with fully fueled rocket, etc. While it is buggy, but I think it is better to give us a option of this to lessen frustrations. It also help with compatibility to work with another addons' rockets. It can have a new line in GalaxySpace's or AsmodeusCore's config like this; "RequireSublightEngine = true" to enable or disable the use of sublight engine to travel outside of the Sol system in the galaxy map.

**Comment by BlesseNtumble** [comment]
Will add in AsmodeusCore 1.0.2
