### ISSUE TITLE
Crash IC2Classic

### ISSUE THREAD

**Issue by ghost** [BlesseNtumble/GalaxySpace#656]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.5
3. GalaxySpace version: 2.0.19
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.31
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: More-Planets-1.12.2-2.3.2-GC4.0.5
------------------------------------------------------------------------
Description of the issue:
Вылет игры при надевании квантовой брони IC2Classic
Убрав остальные моды (кроме AsmodeusCore, GC, GS, IC2) вылет остался. Убрав только GS вылета нет.
С остальной бронёй из IC2 или других модов ошибки нет.
------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------
[crash-2023-05-14_19.52.24-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/11472500/crash-2023-05-14_19.52.24-client.txt)

**Comment by BlesseNtumble** [comment]
Проблема в аудио системе IC2Classic.
ic2/core/audio/AudioSourceClient.updateVolume

Вам необходимо написать разработчику IC2Classic. Мы не затрагиваем какую либо аудио систему.
