### ISSUE TITLE
Crash Gaz Owerworld

### ISSUE THREAD

**Issue by ghost** [BlesseNtumble/GalaxySpace#660]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.5
3. GalaxySpace version: 2.0.19
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.31
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP
6. Other add-ons: More-Planets-1.12.2-2.3.2-GC4.0.5
------------------------------------------------------------------------
Description of the issue:

Вылет при заходе в газ несколько раз, даже при попытке зайти в игру. После друг ко мне tp и вылетел он, а я остался на месте. После друг зашел в игру и нечего не произошло.
------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinBooter (!mixinbooter-7.1.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  Aqua Acrobatics Transformer (AquaAcrobatics-1.15.3.jar)
  MicdoodlePlugin (Galacticraft-1.12.2-4.0.5.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.19.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-mc1.12.2-v1.3.0.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
  CoreModLoader (Sound-Physics-1.12.2-1.0.10-1.jar)
  BetterFontsCore (TTFR-1.12.1-1.9.1.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 7/2/23 9:27 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:2373)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1646)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

(MixinBooter) Mixins in Stacktrace:
	net.minecraft.client.renderer.EntityRenderer:
		stevekung.mods.stevekunglib.mixin.EntityRendererMixin (mixins.stevekung's_lib.json)
		com.fuzs.aquaacrobatics.core.mixin.client.EntityRendererMixin (META-INF/mixins.aquaacrobatics.json)
		com.mamiyaotaru.voxelmap.forgemod.mixins.MixinEntityRenderer (mixins.voxelmap.json)
		stevekung.mods.moreplanets.core.mixin.client.MixinEntityRenderer (mixins.more_planets.json)
	net.minecraft.client.Minecraft:
		me.jellysquid.mods.phosphor.mixins.lighting.client.MixinMinecraft (mixins.phosphor.json)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:2373)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1646)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [GCEntityClientPlayerMP['Rio192AL'/335, l='MpServer', x=1366.93, y=41.64, z=196.99], GCEntityOtherPlayerMP['Prorok_Griboboy'/495, l='MpServer', x=1366.90, y=41.82, z=196.97]]
	Chunk stats: MultiplayerChunkCache: 280, 280
	Level seed: 0
	Level generator: ID 09 - lostcities_bop, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-113,64,224), Chunk: (at 15,4,0 in -8,14; contains blocks -128,0,224 to -113,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1997739 game time, 2750068 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 60 total; [EntitySkeleton['Skeleton'/513, l='MpServer', x=1394.50, y=25.00, z=237.50], EntitySkeleton['Skeleton'/514, l='MpServer', x=1392.50, y=18.00, z=232.50], EntityBat['Bat'/515, l='MpServer', x=1395.55, y=40.83, z=229.29], EntitySpider['Spider'/523, l='MpServer', x=1408.07, y=16.00, z=195.30], EntityBat['Bat'/524, l='MpServer', x=1406.48, y=36.98, z=220.16], EntitySquid['Squid'/525, l='MpServer', x=1399.50, y=60.64, z=214.99], EntityCreeper['Creeper'/526, l='MpServer', x=1388.84, y=19.00, z=228.53], EntityZombieVillager['Zombie Villager'/527, l='MpServer', x=1388.53, y=27.00, z=228.80], GCEntityOtherPlayerMP['Prorok_Griboboy'/495, l='MpServer', x=1366.90, y=41.82, z=196.97], EntityLatchedRenderer['unknown'/3093, l='MpServer', x=1366.90, y=41.82, z=196.97], EntityItem['item.tile.stone.granite'/563, l='MpServer', x=1398.13, y=32.00, z=205.13], EntityItem['item.ic2.resource.lead_ore'/564, l='MpServer', x=1397.12, y=32.00, z=205.88], EntitySkeleton['Skeleton'/565, l='MpServer', x=1378.44, y=29.00, z=213.12], EntityZombie['Zombie'/566, l='MpServer', x=1364.32, y=27.00, z=234.08], EntityItem['item.tile.stone.granite'/567, l='MpServer', x=1385.00, y=32.00, z=205.64], EntityBat['Bat'/568, l='MpServer', x=1365.83, y=29.10, z=219.79], EntityZombie['Zombie'/569, l='MpServer', x=1338.50, y=41.00, z=242.50], EntitySpider['Spider'/571, l='MpServer', x=1402.50, y=42.00, z=170.50], EntitySkeleton['Skeleton'/572, l='MpServer', x=1384.43, y=24.00, z=190.99], EntityEnderman['Enderman'/573, l='MpServer', x=1384.75, y=29.00, z=190.44], EntityCreeper['Creeper'/574, l='MpServer', x=1342.66, y=13.00, z=227.50], EntityBat['Bat'/575, l='MpServer', x=1388.31, y=12.10, z=169.37], EntitySquid['Squid'/576, l='MpServer', x=1378.90, y=53.72, z=173.43], EntityCreeper['Creeper'/449, l='MpServer', x=1650.80, y=25.00, z=288.56], EntityCreeper['Creeper'/577, l='MpServer', x=1362.18, y=21.00, z=191.60], EntitySkeleton['Skeleton'/578, l='MpServer', x=1358.52, y=20.00, z=177.10], EntityZombie['Zombie'/579, l='MpServer', x=1336.50, y=18.00, z=198.78], EntityZombie['Zombie'/453, l='MpServer', x=1637.78, y=21.00, z=303.56], EntitySkeleton['Skeleton'/581, l='MpServer', x=1322.50, y=17.00, z=166.92], EntityCreeper['Creeper'/454, l='MpServer', x=1617.50, y=19.00, z=306.50], EntityCreeper['Creeper'/455, l='MpServer', x=1604.50, y=27.00, z=332.50], EntityZombie['Zombie'/460, l='MpServer', x=1639.50, y=25.00, z=283.50], EntityZombie['Zombie'/461, l='MpServer', x=1638.50, y=25.00, z=283.50], EntityZombie['Zombie'/462, l='MpServer', x=1640.21, y=25.00, z=281.87], EntityZombie['Zombie'/463, l='MpServer', x=1641.49, y=26.00, z=279.93], EntityZombie['Zombie'/336, l='MpServer', x=1624.78, y=22.00, z=297.30], EntitySkeleton['Skeleton'/464, l='MpServer', x=1639.30, y=25.00, z=281.45], EntitySpider['Spider'/337, l='MpServer', x=1624.70, y=24.10, z=298.48], EntitySkeleton['Skeleton'/465, l='MpServer', x=1615.43, y=24.00, z=310.89], EntityCreeper['Creeper'/338, l='MpServer', x=1627.60, y=21.00, z=292.40], EntityCreeper['Creeper'/339, l='MpServer', x=1625.50, y=22.00, z=300.50], EntitySkeleton['Skeleton'/467, l='MpServer', x=1616.50, y=15.00, z=280.50], EntityCreeper['Creeper'/340, l='MpServer', x=1620.18, y=20.00, z=294.44], EntitySkeleton['Skeleton'/468, l='MpServer', x=1627.50, y=24.00, z=277.25], EntitySkeleton['Skeleton'/341, l='MpServer', x=1619.70, y=16.00, z=288.70], EntityCreeper['Creeper'/469, l='MpServer', x=1613.50, y=14.00, z=289.50], EntityZombie['Zombie'/342, l='MpServer', x=1619.07, y=16.00, z=288.70], EntityEnderman['Enderman'/472, l='MpServer', x=1623.51, y=15.00, z=271.46], GCEntityOtherPlayerMP['Prorok_Griboboy'/495, l='MpServer', x=1366.90, y=41.82, z=196.97], EntityItem['item.item.sulphur'/496, l='MpServer', x=1364.13, y=15.41, z=194.13], EntityItem['item.ic2.resource.copper_ore'/497, l='MpServer', x=1367.88, y=15.40, z=194.13], EntityItem['item.tile.stonebrick'/498, l='MpServer', x=1367.88, y=15.18, z=194.13], EntityItem['item.tile.asteroids_block.asteroid_rock_0'/499, l='MpServer', x=1367.88, y=15.22, z=194.13], EntitySkeleton['Skeleton'/500, l='MpServer', x=1368.30, y=16.00, z=193.50], EntityItem['item.tile.stonebrick'/501, l='MpServer', x=1367.88, y=16.00, z=198.78], EntityTippedArrow['Arrow'/502, l='MpServer', x=1367.47, y=28.91, z=196.72], EntityTippedArrow['Arrow'/503, l='MpServer', x=1367.96, y=35.76, z=198.00], EntityZombie['Zombie'/506, l='MpServer', x=1396.50, y=35.00, z=241.50], GCEntityClientPlayerMP['Rio192AL'/335, l='MpServer', x=1366.93, y=41.64, z=196.99], EntityLatchedRenderer['unknown'/3070, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 22 total; [EntityCreeper['Creeper'/449, l='MpServer', x=1650.80, y=25.00, z=288.56], EntityZombie['Zombie'/453, l='MpServer', x=1637.78, y=21.00, z=303.56], EntityCreeper['Creeper'/454, l='MpServer', x=1617.50, y=19.00, z=306.50], EntityCreeper['Creeper'/455, l='MpServer', x=1604.50, y=27.00, z=332.50], EntityZombie['Zombie'/460, l='MpServer', x=1639.50, y=25.00, z=283.50], EntityZombie['Zombie'/461, l='MpServer', x=1638.50, y=25.00, z=283.50], EntityZombie['Zombie'/462, l='MpServer', x=1640.21, y=25.00, z=281.87], EntityZombie['Zombie'/463, l='MpServer', x=1641.49, y=26.00, z=279.93], EntityZombie['Zombie'/336, l='MpServer', x=1624.78, y=22.00, z=297.30], EntitySkeleton['Skeleton'/464, l='MpServer', x=1639.30, y=25.00, z=281.45], EntitySkeleton['Skeleton'/465, l='MpServer', x=1615.43, y=24.00, z=310.89], EntitySpider['Spider'/337, l='MpServer', x=1624.70, y=24.10, z=298.48], EntityCreeper['Creeper'/338, l='MpServer', x=1627.60, y=21.00, z=292.40], EntitySkeleton['Skeleton'/467, l='MpServer', x=1616.50, y=15.00, z=280.50], EntityCreeper['Creeper'/339, l='MpServer', x=1625.50, y=22.00, z=300.50], EntitySkeleton['Skeleton'/468, l='MpServer', x=1627.50, y=24.00, z=277.25], EntityCreeper['Creeper'/340, l='MpServer', x=1620.18, y=20.00, z=294.44], EntityCreeper['Creeper'/469, l='MpServer', x=1613.50, y=14.00, z=289.50], EntitySkeleton['Skeleton'/341, l='MpServer', x=1619.70, y=16.00, z=288.70], EntityZombie['Zombie'/342, l='MpServer', x=1619.07, y=16.00, z=288.70], EntityEnderman['Enderman'/472, l='MpServer', x=1623.51, y=15.00, z=271.46], EntityLatchedRenderer['unknown'/3070, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: Magma
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_361, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1376350712 bytes (1312 MB) / 3178758144 bytes (3031 MB) up to 7639400448 bytes (7285 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8196m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 77 mods loaded, 77 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version           | Source                                        | Signature                                |
	|:------ |:------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                 | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2860-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2860      | forge-1.12.2-14.23.5.2860-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       | 4.0.5             | minecraft.jar                                 | None                                     |
	| LCHIJA | betterfonts         | 1.9.1             | minecraft.jar                                 | None                                     |
	| LCHIJA | mixinbooter         | 7.1               | minecraft.jar                                 | None                                     |
	| LCHIJA | foamfixcore         | 7.7.4             | minecraft.jar                                 | None                                     |
	| LCHIJA | voxelmap            | 1.9.25            | forgemod_VoxelMap-1.9.28_for_1.12.2.jar       | None                                     |
	| LCHIJA | deconstruction      | 3.0.4             | [MC1.12.2]DeconTable-3.0.4.jar                | None                                     |
	| LCHIJA | acslib              | 1.1.0-5           | ACsGuis-1.2.1-3-all.jar                       | None                                     |
	| LCHIJA | aether_legacy       | 1.5.3.2           | aether-1.12.2-v1.5.3.2.jar                    | None                                     |
	| LCHIJA | aiimprovements      | 0.0.1.3           | AIImprovements-1.12-0.0.1b3.jar               | None                                     |
	| LCHIJA | aquaacrobatics      | 1.15.3            | AquaAcrobatics-1.15.3.jar                     | None                                     |
	| LCHIJA | arcademod           | 2.1.5             | arcademod-2.1.5-1.12.2.jar                    | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.5             | Galacticraft-1.12.2-4.0.5.jar                 | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.5             | Galacticraft-1.12.2-4.0.5.jar                 | None                                     |
	| LCHIJA | asmodeuscore        | 0.0.30            | AsmodeusCore-1.12.2-0.0.31.jar                | None                                     |
	| LCHIJA | backpack            | 3.0.2             | backpack-3.0.2-1.12.2.jar                     | None                                     |
	| LCHIJA | bedrockbreaks       | 1.0               | bedrockbreaks-1.0.1.jar                       | None                                     |
	| LCHIJA | betterf3            | 1.12.2-1.0        | betterf3-1.12.2-1.0.jar                       | None                                     |
	| LCHIJA | betterpingdisplay   | 1.0               | BetterPingDisplay-1.12.2-1.0.jar              | None                                     |
	| LCHIJA | biomesoplenty       | 7.0.1.2445        | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar | None                                     |
	| LCHIJA | buildcraftlib       | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftcore      | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftbuilders  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcrafttransport | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftsilicon   | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | ic2                 | 2.8.222-ex112     | industrialcraft-2-2.8.222-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | buildcraftcompat    | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftenergy    | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftfactory   | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftrobotics  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | codechickenlib      | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chickenchunks       | 2.4.2.74          | ChickenChunks-1.12.2-2.4.2.74-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | classiccombat       | 1.0.1             | ClassicCombat-1.0.1.jar                       | None                                     |
	| LCHIJA | craftingstation     | @VERSION@         | craftingstation-0.1.8a.jar                    | None                                     |
	| LCHIJA | ctm                 | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LCHIJA | endermail           | 1.1.3             | EnderMail-1.12.2-1.1.3.jar                    | None                                     |
	| LCHIJA | experienceore       | 1.0.1             | experienceore-1.0.2.jar                       | None                                     |
	| LCHIJA | falling_tree        | 2.4.0             | FallingTree-1.12.2-2.4.0.jar                  | None                                     |
	| LCHIJA | fastleafdecay       | v14               | FastLeafDecay-v14.jar                         | None                                     |
	| LCHIJA | flansmod            | 5.10.0            | Flan's+Mod-1.12.2-5.10.0.jar                  | None                                     |
	| LCHIJA | foamfix             | @VERSION@         | foamfix-0.10.15-1.12.2.jar                    | None                                     |
	| LCHIJA | forgivingvoid       | 1.1.0             | ForgivingVoid_1.12.2-1.1.0.jar                | None                                     |
	| LCHIJA | fpsreducer          | mc1.12.2-1.20     | FpsReducer-mc1.12.2-1.20.jar                  | None                                     |
	| LCHIJA | fw                  | 1.6.0             | FullscreenWindowed-1.12-1.6.0.jar             | None                                     |
	| LCHIJA | cfm                 | 6.3.0             | furniture-6.3.2-1.12.2.jar                    | None                                     |
	| LCHIJA | galaxyspace         | 2.0.19            | GalaxySpace-1.12.2-2.0.19.jar                 | None                                     |
	| LCHIJA | glassdoors          | 1.0.0             | glassdoors-1.12.2-1.0.0.jar                   | None                                     |
	| LCHIJA | gravisuite          | 3.1.1             | Gravitation+Suite-3.1.1.jar                   | None                                     |
	| LCHIJA | ichunutil           | 7.2.2             | iChunUtil-1.12.2-7.2.2.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | gravitygun          | 7.1.0             | GravityGun-1.12.2-7.1.0.jar                   | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | hunterillager       | 1.2               | hunterillager-1.12.2-1.2.jar                  | None                                     |
	| LCHIJA | waila               | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCHIJA | ikwid               | 1.0.2             | ikwid-1.0.2.jar                               | None                                     |
	| LCHIJA | ironchest           | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LCHIJA | jei                 | 4.16.1.1001       | jei_1.12.2-4.16.1.1001.jar                    | None                                     |
	| LCHIJA | jeiintegration      | 1.6.0             | jeiintegration_1.12.2-1.6.0.jar               | None                                     |
	| LCHIJA | keepinginventory    | 2.4               | KeepingInventory-1.12.2-2.4.jar               | None                                     |
	| LCHIJA | libraryex           | 1.2.2             | LibraryEx-1.12.2-1.2.2.jar                    | None                                     |
	| LCHIJA | lost_aether         | 1.0.2             | lost-aether-content-1.12.2-1.0.2.jar          | None                                     |
	| LCHIJA | lostcities          | 2.0.22            | lostcities-1.12-2.0.22.jar                    | None                                     |
	| LCHIJA | stevekung's_lib     | 1.3.0             | SteveKunG's-Lib-mc1.12.2-v1.3.0.jar           | None                                     |
	| LCHIJA | moreplanets         | 2.3.2             | More-Planets-1.12.2-2.3.2-GC4.0.5.jar         | None                                     |
	| LCHIJA | netherex            | 2.2.5             | NetherEx-1.12.2-2.2.5.jar                     | None                                     |
	| LCHIJA | nopotionshift       | 1.2.0             | nopotionshift_1.12.2-1.2.0.jar                | None                                     |
	| LCHIJA | norecipebook        | 1.2.1             | noRecipeBook_v1.2.2formc1.12.2.jar            | None                                     |
	| LCHIJA | notes               | 1.1.1             | Notes-1.12-1.1.1.jar                          | None                                     |
	| LCHIJA | packingtape         | 0.7.6             | PackingTape-1.12.2-0.7.6.jar                  | None                                     |
	| LCHIJA | portalgun           | 7.1.0             | PortalGun-1.12.2-7.1.0.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | storagenetwork      | 1.8.3             | SimpleStorageNetwork-1.12.2-1.8.3.jar         | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LCHIJA | soundphysics        | 1.0.10-1          | Sound-Physics-1.12.2-1.0.10-1.jar             | None                                     |
	| LCHIJA | surge               | 2.0.79            | Surge-1.12.2-2.0.79.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | toxicrain           | 2.2.0             | ToxicRain-1.12.2-2.2.0.jar                    | None                                     |
	| LCHIJA | twilightforest      | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LCHIJA | phosphor-lighting   | 1.12.2-0.2.6      | phosphor-1.12.2-0.2.6+build50-universal.jar   | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
MixinBooter (!mixinbooter-7.1.jar)
  
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Aqua Acrobatics Transformer (AquaAcrobatics-1.15.3.jar)
  
MicdoodlePlugin (Galacticraft-1.12.2-4.0.5.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
GSHooksLoader (GalaxySpace-1.12.2-2.0.19.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
SteveKunGLibPlugin (SteveKunG's-Lib-mc1.12.2-v1.3.0.jar)
  
SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
  
CoreModLoader (Sound-Physics-1.12.2-1.0.10-1.jar)
  com.sonicether.soundphysics.CoreModInjector
BetterFontsCore (TTFR-1.12.1-1.9.1.jar)
  cubex2.ttfr.BFClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 536.40' Renderer: 'NVIDIA GeForce RTX 3070/PCIe/SSE2'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.40, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 536.40
	OpenGlRenderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
не похоже на проблему GS. потенциальные виновники:
- Aqua Acrobatics
- VoxelMap
- MorePlanets
- Phosphor

**Comment by BlesseNtumble** [comment]
#662
