### ISSUE TITLE
Config Option to disable Natural Gas

### ISSUE THREAD

**Issue by TFCAliarcy** [BlesseNtumble/GalaxySpace#661]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:1.12.2-4.0.5
3. GalaxySpace version:1.12.2-2.0.19
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.31
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: None
------------------------------------------------------------------------
Description of the issue:
There is does not seem to be an option in the config to disable natural gas.

------------------------------------------------------------------------
Screenshot/Video:
![image](https://github.com/BlesseNtumble/GalaxySpace/assets/95112949/76ad091b-c022-4cb1-9920-90791bd6bd22)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
In next build
