### ISSUE TITLE
crash with natural gas

### ISSUE THREAD

**Issue by javiburatos** [BlesseNtumble/GalaxySpace#662]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.5
3. GalaxySpace version: 2.0.19
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.31
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: Planet progresion, more planets, extraplanets, Zollern Galaxy, Interestellar: exoplanets.
------------------------------------------------------------------------
Description of the issue:
When i touch the natural gas, sometimes my game crash.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://pastebin.com/Q5Vfwaii

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Will fix in next build
