### ISSUE TITLE
Вылетает при заходе в Сборочный цех / Assembly machine crash

### ISSUE THREAD

**Issue by Oltich** [BlesseNtumble/GalaxySpace#663]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.6
3. GalaxySpace version: 2.0.19
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.31
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: -
------------------------------------------------------------------------
Description of the issue:
Вылетает каждый раз при попытке открыть сборочный цех

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

java.lang.IllegalAccessError: tried to access field net.minecraft.inventory.InventoryCrafting.field_70465_c from class galaxyspace.systems.SolarSystem.planets.overworld.inventory.ContainerAssembler
	at galaxyspace.systems.SolarSystem.planets.overworld.inventory.ContainerAssembler.<init>(ContainerAssembler.java:24)
	at galaxyspace.systems.SolarSystem.planets.overworld.gui.GuiAssembler.<init>(GuiAssembler.java:29)
	at galaxyspace.core.handler.GSGuiHandler.getClientGuiElement(GSGuiHandler.java:201)
	at galaxyspace.core.handler.GSGuiHandler.getClientGuiElement(GSGuiHandler.java:178)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:276)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:111)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
	at galaxyspace.systems.SolarSystem.planets.overworld.blocks.machines.BlockAssembler.onMachineActivated(BlockAssembler.java:48)
	at micdoodle8.mods.galacticraft.core.blocks.BlockAdvanced.func_180639_a(BlockAdvanced.java:65)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at galaxyspace.systems.SolarSystem.planets.overworld.inventory.ContainerAssembler.<init>(ContainerAssembler.java:24)
	at galaxyspace.systems.SolarSystem.planets.overworld.gui.GuiAssembler.<init>(GuiAssembler.java:29)
	at galaxyspace.core.handler.GSGuiHandler.getClientGuiElement(GSGuiHandler.java:201)
	at galaxyspace.core.handler.GSGuiHandler.getClientGuiElement(GSGuiHandler.java:178)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:276)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:111)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
	at galaxyspace.systems.SolarSystem.planets.overworld.blocks.machines.BlockAssembler.onMachineActivated(BlockAssembler.java:48)
	at micdoodle8.mods.galacticraft.core.blocks.BlockAdvanced.func_180639_a(BlockAdvanced.java:65)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Oltich'/2245, l='MpServer', x=-199.50, y=63.00, z=230.50]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-196,64,232), Chunk: (at 12,4,8 in -13,14; contains blocks -208,0,224 to -193,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 198 game time, 198 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 67 total; [EntityBat['Летучая мышь'/4110, l='MpServer', x=-270.84, y=18.69, z=287.31], EntityBat['Летучая мышь'/4111, l='MpServer', x=-275.25, y=18.07, z=291.34], EntityBat['Летучая мышь'/4112, l='MpServer', x=-274.29, y=18.78, z=290.60], EntityBat['Летучая мышь'/4113, l='MpServer', x=-267.74, y=18.03, z=291.63], EntityBat['Летучая мышь'/4120, l='MpServer', x=-255.96, y=33.70, z=243.44], EntityBat['Летучая мышь'/4163, l='MpServer', x=-254.25, y=35.95, z=248.25], EntityPig['Свинья'/75, l='MpServer', x=-263.01, y=68.00, z=271.25], EntityPig['Свинья'/76, l='MpServer', x=-263.30, y=68.00, z=272.20], EntityPig['Свинья'/77, l='MpServer', x=-264.50, y=68.00, z=266.50], EntityPig['Свинья'/78, l='MpServer', x=-265.50, y=68.00, z=268.50], EntityPig['Свинья'/84, l='MpServer', x=-251.50, y=64.00, z=198.50], EntityPig['Свинья'/85, l='MpServer', x=-257.50, y=64.00, z=190.76], EntityPig['Свинья'/86, l='MpServer', x=-253.50, y=64.00, z=195.50], EntityPig['Свинья'/87, l='MpServer', x=-253.50, y=64.00, z=194.50], EntityPig['Свинья'/88, l='MpServer', x=-252.50, y=69.00, z=213.50], EntityPig['Свинья'/89, l='MpServer', x=-252.50, y=68.00, z=211.50], EntityPig['Свинья'/90, l='MpServer', x=-250.50, y=69.00, z=212.50], EntityPig['Свинья'/91, l='MpServer', x=-250.50, y=70.00, z=215.50], EntitySheep['Овца'/92, l='MpServer', x=-251.50, y=68.00, z=278.50], EntitySheep['Овца'/93, l='MpServer', x=-258.46, y=69.00, z=278.72], EntitySheep['Овца'/94, l='MpServer', x=-252.50, y=68.00, z=277.50], EntitySheep['Овца'/95, l='MpServer', x=-254.50, y=68.00, z=277.50], EntityPig['Свинья'/100, l='MpServer', x=-216.50, y=67.00, z=168.50], EntityPig['Свинья'/101, l='MpServer', x=-218.50, y=67.00, z=168.50], EntityPig['Свинья'/102, l='MpServer', x=-213.76, y=64.00, z=180.22], EntityPig['Свинья'/103, l='MpServer', x=-217.50, y=66.00, z=172.50], EntitySheep['Овца'/104, l='MpServer', x=-216.71, y=66.00, z=251.70], EntitySheep['Овца'/105, l='MpServer', x=-215.50, y=68.00, z=257.66], EntitySheep['Овца'/106, l='MpServer', x=-211.50, y=69.00, z=257.50], EntitySheep['Овца'/107, l='MpServer', x=-215.50, y=68.00, z=258.55], EntitySheep['Овца'/120, l='MpServer', x=-183.76, y=70.00, z=179.49], EntitySheep['Овца'/121, l='MpServer', x=-197.19, y=68.00, z=173.63], EntitySheep['Овца'/122, l='MpServer', x=-193.50, y=68.00, z=174.50], EntitySheep['Овца'/123, l='MpServer', x=-196.22, y=68.00, z=175.75], EntityChicken['Курица'/144, l='MpServer', x=-145.50, y=66.00, z=223.50], EntityChicken['Курица'/145, l='MpServer', x=-141.90, y=67.00, z=220.62], EntityChicken['Курица'/146, l='MpServer', x=-143.65, y=66.00, z=221.50], EntityChicken['Курица'/147, l='MpServer', x=-144.50, y=66.00, z=221.50], GCEntityClientPlayerMP['Oltich'/2245, l='MpServer', x=-199.50, y=63.00, z=230.50], EntityItem['item.tile.flower2.tulipOrange'/4643, l='MpServer', x=-199.88, y=64.00, z=254.56], EntityItem['item.tile.flower2.tulipWhite'/4644, l='MpServer', x=-200.19, y=64.00, z=255.88], EntityItem['item.tile.flower2.tulipOrange'/4645, l='MpServer', x=-198.63, y=63.00, z=253.16], EntityItem['item.tile.flower2.tulipWhite'/4646, l='MpServer', x=-198.38, y=64.00, z=255.38], EntityCreeper['Крипер'/4655, l='MpServer', x=-263.50, y=19.00, z=281.50], EntityCreeper['Крипер'/4656, l='MpServer', x=-272.09, y=18.00, z=286.51], EntityCreeper['Крипер'/4657, l='MpServer', x=-265.50, y=19.00, z=286.50], EntityCreeper['Крипер'/4658, l='MpServer', x=-269.23, y=18.00, z=287.53], EntityItem['item.tile.flower2.tulipOrange'/4793, l='MpServer', x=-201.01, y=64.00, z=252.44], EntityBat['Летучая мышь'/4807, l='MpServer', x=-243.46, y=15.03, z=256.87], EntitySkeleton['Скелет'/2760, l='MpServer', x=-269.50, y=20.00, z=277.50], EntityZombie['Зомби'/4819, l='MpServer', x=-255.50, y=17.00, z=249.50], EntitySkeleton['Скелет'/4830, l='MpServer', x=-275.50, y=38.00, z=277.50], EntityZombie['Зомби'/4836, l='MpServer', x=-267.50, y=20.00, z=305.50], EntityCreeper['Крипер'/4837, l='MpServer', x=-268.50, y=20.00, z=305.50], EntitySkeleton['Скелет'/4838, l='MpServer', x=-273.50, y=18.00, z=288.50], EntityCreeper['Крипер'/4849, l='MpServer', x=-270.50, y=18.00, z=289.50], EntityCreeper['Крипер'/4850, l='MpServer', x=-272.83, y=18.00, z=286.50], EntityCreeper['Крипер'/4851, l='MpServer', x=-268.50, y=18.00, z=289.50], EntityCreeper['Крипер'/3915, l='MpServer', x=-277.50, y=18.00, z=220.50], EntityBat['Летучая мышь'/4004, l='MpServer', x=-275.97, y=21.17, z=279.03], EntityZombie['Зомби'/4066, l='MpServer', x=-276.50, y=48.00, z=161.50], EntityBat['Летучая мышь'/4067, l='MpServer', x=-255.56, y=27.96, z=248.75], EntitySquid['Спрут'/4068, l='MpServer', x=-260.49, y=60.60, z=178.45], EntityBat['Летучая мышь'/4071, l='MpServer', x=-254.56, y=25.07, z=243.75], EntitySquid['Спрут'/4073, l='MpServer', x=-264.35, y=61.04, z=176.04], EntitySquid['Спрут'/4074, l='MpServer', x=-256.41, y=60.38, z=175.40], EntityEnderman['Эндермен'/4078, l='MpServer', x=-271.50, y=18.00, z=288.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 850815544 bytes (811 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2048M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                         | Version                  | Source                              | Signature                                |
	|:------ |:-------------------------- |:------------------------ |:----------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                  | 1.12.2                   | minecraft.jar                       | None                                     |
	| LCHIJA | mcp                        | 9.42                     | minecraft.jar                       | None                                     |
	| LCHIJA | FML                        | 8.0.99.99                | forge-1.12.2-14.23.5.2860.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                      | 14.23.5.2860             | forge-1.12.2-14.23.5.2860.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore              | 4.0.6                    | minecraft.jar                       | None                                     |
	| LCHIJA | ClientFixer                | 1.12.2-1.9               | minecraft.jar                       | None                                     |
	| LCHIJA | galacticraftcore           | 4.0.6                    | Galacticraft-1.12.2-4.0.6.jar       | None                                     |
	| LCHIJA | galacticraftplanets        | 4.0.6                    | Galacticraft-1.12.2-4.0.6.jar       | None                                     |
	| LCHIJA | asmodeuscore               | 1.0.0                    | asmodeuscore-1.12.2-1.0.0.jar       | None                                     |
	| LCHIJA | backpack                   | 3.0.2                    | backpack-3.0.2-1.12.2.jar           | None                                     |
	| LCHIJA | bookshelf                  | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | buildcraftlib              | 7.99.24.8                | buildcraft_all_7.99.24.8_1.12.2.jar | None                                     |
	| LCHIJA | buildcraftcore             | 7.99.24.8                | buildcraft_all_7.99.24.8_1.12.2.jar | None                                     |
	| LCHIJA | buildcraftbuilders         | 7.99.24.8                | buildcraft_all_7.99.24.8_1.12.2.jar | None                                     |
	| LCHIJA | buildcrafttransport        | 7.99.24.8                | buildcraft_all_7.99.24.8_1.12.2.jar | None                                     |
	| LCHIJA | buildcraftsilicon          | 7.99.24.8                | buildcraft_all_7.99.24.8_1.12.2.jar | None                                     |
	| LCHIJA | buildcraftcompat           | 7.99.24.8                | buildcraft_all_7.99.24.8_1.12.2.jar | None                                     |
	| LCHIJA | buildcraftenergy           | 7.99.24.8                | buildcraft_all_7.99.24.8_1.12.2.jar | None                                     |
	| LCHIJA | buildcraftfactory          | 7.99.24.8                | buildcraft_all_7.99.24.8_1.12.2.jar | None                                     |
	| LCHIJA | buildcraftrobotics         | 7.99.24.8                | buildcraft_all_7.99.24.8_1.12.2.jar | None                                     |
	| LCHIJA | eplus                      | 5.0.179                  | EnchantingPlus-1.12.2-5.0.179.jar   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | galaxyspace                | 2.0.19                   | GalaxySpace-1.12.2-2.0.19.jar       | None                                     |
	| LCHIJA | inventorytweaks            | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest                  | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar     | None                                     |
	| LCHIJA | jei                        | 4.16.1.1003              | jei_1.12.2-4.16.1.1003.jar          | None                                     |
	| LCHIJA | journeymap                 | 1.12.2-5.7.1             | journeymap_1.12.2_5.7.1.jar         | None                                     |
	| LCHIJA | mousetweaks                | 2.10.1                   | MouseTweaks-2.10.1-mc1.12.2.jar     | None                                     |
	| LCHIJA | neat                       | 1.4-17                   | Neat_1.12.2_1.4_17.jar              | None                                     |
	| LCHIJA | tlauncher_custom_cape_skin | 1.4                      | tlskincape_1.12.2-1.4.jar           | None                                     |

	Loaded coremods (and transformers): 
ClientFixer (clientfixer-1.12.2-1.9.jar)
  com.gamerforea.clientfixer.asm.ASMTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MicdoodlePlugin (Galacticraft-1.12.2-4.0.6.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
GSHooksLoader (GalaxySpace-1.12.2-2.0.19.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Try GC Legacy 4.0.4 version

**Comment by svElder** [comment]
Это из-за новой версии GC (4.0.6).
Используй версию 4.0.4

**Comment by Oltich** [comment]
> Try GC Legacy 4.0.4 version

thank you very much

**Comment by Oltich** [comment]
> Это из-за новой версии GC (4.0.6). Используй версию 4.0.4

Большое спасибо, помогло

**Comment by Amir82607** [comment]
Guys i downloaded 4.0.4 ver. But it crashes with addons and without 
What can i do?
