### ISSUE TITLE
I cant spawn in the overworld only the moon

### ISSUE THREAD

**Issue by Lhama0** [BlesseNtumble/GalaxySpace#664]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.7.10
2. Galacticraft version:Galacticraft-1.7-3.0.12.504
3. GalaxySpace version:GalaxySpace-1.7.10-1.2.15
4. AsmodeusCore version (for 2.0.1 version and above): 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP
6. Other add-ons:More planets,Galaxy space,galactic ores
------------------------------------------------------------------------
Description of the issue:
i keep spawning on the moon and i dont know why

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Not bug. Change parameter in config/Galacticraft/core.conf
