### ISSUE TITLE
Crash when loading into Tau Ceti F

### ISSUE THREAD

**Issue by Toadbean** [BlesseNtumble/GalaxySpace#665]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: Galacticraft Legacy 4.0.6
3. GalaxySpace version: 2.0.1.9
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.0
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:
When loading into Tau Ceti F, your game will crash and the world will not be able to be loaded again

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

https://pastebin.com/mhzJetf1
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Use AsmodeusCore 0.0.31 version for GS 2.0.19
