### ISSUE TITLE
game crashes when opeping assembly machine

### ISSUE THREAD

**Issue by Tvojemotther** [BlesseNtumble/GalaxySpace#666]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.6
3. GalaxySpace version: 2.0.19
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.31
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP with friends through essential mod
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:
Game just crashes when opening assembly machine

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

[2023-08-01-7.log.gz](https://github.com/BlesseNtumble/GalaxySpace/files/12229690/2023-08-01-7.log.gz)

[crash-2023-08-01_15.10.47-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/12229692/crash-2023-08-01_15.10.47-client.txt)

------------------------------------------------------------------------

**Comment by Astr0Master** [comment]
Install galacticraft 4.0.4

**Comment by Tvojemotther** [comment]
i forgot to mention that i had more planets installed, so when i downloaded gc 4.0.4 i had to downgrade more planets (currently i have version 2.3.1 - GC 4.0.4) and it doesnt load bcs i gotta have gc 4.0.5
[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/12229851/latest.log)

**Comment by CafDad** [comment]
I am in the same boat. After trying to downgrade everything broke and I cannot get the game to load back up. Any word on when this issue will be fixed?

**Comment by CafDad** [comment]
> i forgot to mention that i had more planets installed, so when i downloaded gc 4.0.4 i had to downgrade more planets (currently i have version 2.3.1 - GC 4.0.4) and it doesnt load bcs i gotta have gc 4.0.5 [latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/12229851/latest.log)

For you and for anyone else reading this, downgrading Galacticraft to version 4.0.5 also fixes the issue and you do not have to change any other mods (to my knowledge).

**Comment by willis1030** [comment]
GalaxySpace-1.12.2-2.1.1 with Galacticraft-1.12.2-4.0.6 crashed when right-click assembly machine.
Downgrade to Galacticraft-1.12.2-4.0.5 solved it.

**Comment by BlesseNtumble** [comment]
#678
