### ISSUE TITLE
Game Crashes upon travelling to Barnarda C

### ISSUE THREAD

**Issue by CafDad** [BlesseNtumble/GalaxySpace#667]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.5
3. GalaxySpace version: 2.0.19
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.0
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP, SMP
6. Other add-ons: More Planets, Zollern Galaxy, mod pack can be found [here](https://legacy.curseforge.com/minecraft/modpacks/cosmic-horizon) for full list of mods and such
------------------------------------------------------------------------
Description of the issue:
When attempting to travel to Barnarda C with a tier 6 sublight engine, the game crashes (however this does not make a crash report as it registers as "not enough ram" or "this issue can be solved by allocating more ram"). I do not need to allocate more RAM because I have 16 GB of RAM allocated to my game. 

------------------------------------------------------------------------
Screenshot/Video:
[Youtube Video](https://youtu.be/vAAC6kuyXUU)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/12263900/latest.log)

------------------------------------------------------------------------

**Comment by CafDad** [comment]
Update/Addon for this issue. This version of Asmodeus Core also crashes your game when going to most other planets such as Mars. I downgraded Asmodeus core to the previous version and that appears to have fixed the issue with both Barnarda C crashing the game as well as loading into Mars crashing the game. We have no problem loading in to the moon however so I am not sure if it is just planets or what.

**Comment by BlesseNtumble** [comment]
Galaxy Space has not been updated for the new version of AsmodeusCore yet, please use 0.0.31
