### ISSUE TITLE
Not compatible with Beyond Space mod

### ISSUE THREAD

**Issue by KINGSUNofSolarDynasty** [BlesseNtumble/GalaxySpace#668]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.7.10
2. Galacticraft version:1.7-3.0.12.504
3. GalaxySpace version:1.2.15
4. AsmodeusCore version (for 2.0.1 version and above): none
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):Side
6. Other add-ons:Beyond Space
------------------------------------------------------------------------
Description of the issue:
the newest version of GS broke the Beyond Space, but it didn't update for it. I wonder how to make them compatible.

------------------------------------------------------------------------
Screenshot/Video:
none

------------------------------------------------------------------------
Attached log file (or url o
[minecraft-exported-logs-2023-08-08T16-48-21.log](https://github.com/BlesseNtumble/GalaxySpace/files/12289388/minecraft-exported-logs-2023-08-08T16-48-21.log)
n pastebin.com):

------------------------------------------------------------------------

**Comment by ghost** [comment]
SOMEBODY RESPOND TO THIS GUY! NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by BlesseNtumble** [comment]
use older version galaxy space
