### ISSUE TITLE
Galaxyspace removes changes buildcraft oil to gc

### ISSUE THREAD

**Issue by Chachavo** [BlesseNtumble/GalaxySpace#674]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.6
3. GalaxySpace version: 2.1.1
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.0
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP, SMP and LAN
6. Other add-ons: None
------------------------------------------------------------------------
Description of the issue:
When installed alongside buildcraft, it replaces all buildcraft's oil with gc's oil, however buildcraft still generates its own different oil in the world, it isn't a problem since it works just fine, but I find it strange since galacticraft normally works with buidlcraft's oil if it is installed, but it seems galaxyspace changes it back to gc oil.
So probably a minor unintended behavior

------------------------------------------------------------------------
Screenshot/Video:
![2023-09-07_22 43 37](https://github.com/BlesseNtumble/GalaxySpace/assets/131740687/0790ab70-79c7-46ed-9380-37d4e4b524f8)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
GalaxySpace does not change oil generation

**Comment by xJon** [comment]
@BlesseNtumble AsmodeusCore affects BuildCraft oil. See in your Discord server: https://discord.com/channels/309283659935121409/1211589774092275713/1211589774092275713

**Comment by xJon** [comment]
Changing Galacticraft's registration config appears to be a workaround:
```
    # Set to true to make Galacticraft oil register as oilgc, for backwards compatibility with previously generated worlds.
    B:"Use legacy oilgc fluid registration"=true

    # Set to true to make Galacticraft fuel register as fuelgc, for backwards compatibility with previously generated worlds.
    B:"Use legacy fuelgc fluid registration"=true
```
