### ISSUE TITLE
game crashes when opening galacticraft map

### ISSUE THREAD

**Issue by qwertymash** [BlesseNtumble/GalaxySpace#675]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.06
3. GalaxySpace version: 2.1.1
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.0
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): ssp
6. Other add-ons: galactic research and space ambient
------------------------------------------------------------------------
Description of the issue:

when i open the galaxy map, screen goes white for a few seconds then the game crashes
------------------------------------------------------------------------
Screenshot/Video:

https://youtu.be/oGMELRPKS7c
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

---- Minecraft Crash Report ----

WARNING: coremods are present:
  GSHooksLoader (GalaxySpace-1.12.2-2.1.1.jar)
  LoadingPlugin (AdPother-1.12.2-1.2.25.0-build.0673.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.6.1-build.0648.jar)
  MicdoodlePlugin (Galacticraft-1.12.2-4.0.6.jar)
  ReflectorsPlugin (GalacticResearch-1.0.6.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  LoadingPlugin (AdChimneys-1.12.2-3.5.16.0-build.0654.jar)
  SuperMartijn642's Core Lib Plugin (_supermartijn642corelib-1.1.13-forge-mc1.12.jar)
  Moving Elevators Plugin (movingelevators-1.4.4-forge-mc1.12.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.7.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 9/29/23 10:24 PM
Description: Rendering screen

java.lang.NoSuchMethodError: asmodeuscore.core.astronomy.BodiesData.getStarClass()Lasmodeuscore/api/dimension/IAdvancedSpace$StarClass;
	at igentuman.galacticresearch.client.gui.GRGuiCelestialSelectionGalaxySpace.drawVortex(GRGuiCelestialSelectionGalaxySpace.java:1068)
	at igentuman.galacticresearch.client.gui.GRGuiCelestialSelectionGalaxySpace.func_73863_a(GRGuiCelestialSelectionGalaxySpace.java:548)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at igentuman.galacticresearch.client.gui.GRGuiCelestialSelectionGalaxySpace.drawVortex(GRGuiCelestialSelectionGalaxySpace.java:1068)
	at igentuman.galacticresearch.client.gui.GRGuiCelestialSelectionGalaxySpace.func_73863_a(GRGuiCelestialSelectionGalaxySpace.java:548)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: igentuman.galacticresearch.client.gui.GRGuiCelestialSelectionGalaxySpace
	Mouse location: Scaled: (365, 49). Absolute: (731, 911)
	Screen size: Scaled: (960, 505). Absolute: (1920, 1009). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['samzking'/193, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [GCEntityClientPlayerMP['samzking'/193, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1947829168 bytes (1857 MB) / 3924295680 bytes (3742 MB) up to 7397179392 bytes (7054 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7936m -Xms256m
	IntCache: cache: 5, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version                   | Source                                          | Signature                                |
	|:------ |:------------------------ |:------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                | 1.12.2                    | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                      | 9.42                      | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                      | 8.0.99.99                 | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                    | 14.23.5.2859              | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore            | 4.0.6                     | minecraft.jar                                   | None                                     |
	| LCHIJA | obfuscate                | 0.4.2                     | minecraft.jar                                   | None                                     |
	| LCHIJA | securitycraft            | v1.9.7                    | [1.12.2] SecurityCraft v1.9.7.jar               | None                                     |
	| LCHIJA | supermartijn642corelib   | 1.1.13                    | _supermartijn642corelib-1.1.13-forge-mc1.12.jar | None                                     |
	| LCHIJA | forgeendertech           | 1.12.2-4.5.6.1            | ForgeEndertech-1.12.2-4.5.6.1-build.0648.jar    | None                                     |
	| LCHIJA | adpother                 | 1.12.2-1.2.25.0           | AdPother-1.12.2-1.2.25.0-build.0673.jar         | None                                     |
	| LCHIJA | aquaculture              | 1.6.8                     | Aquaculture-1.12.2-1.6.8.jar                    | None                                     |
	| LCHIJA | galacticraftcore         | 4.0.6                     | Galacticraft-1.12.2-4.0.6.jar                   | None                                     |
	| LCHIJA | galacticraftplanets      | 4.0.6                     | Galacticraft-1.12.2-4.0.6.jar                   | None                                     |
	| LCHIJA | asmodeuscore             | 1.0.0                     | AsmodeusCore-1.12.2-1.0.0.jar                   | None                                     |
	| LCHIJA | bookworm                 | 1.12.2-2.5.2.1            | bookworm-1.12.2-2.5.2.1.jar                     | None                                     |
	| LCHIJA | buildinggadgets          | 2.8.4                     | BuildingGadgets-2.8.4.jar                       | None                                     |
	| LCHIJA | cctweaked                | 1.89.2                    | cc-tweaked-1.12.2-1.89.2.jar                    | None                                     |
	| LCHIJA | computercraft            | 1.89.2                    | cc-tweaked-1.12.2-1.89.2.jar                    | None                                     |
	| LCHIJA | chameleon                | 1.12-4.1.3                | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| LCHIJA | comforts                 | 1.4.1.3                   | comforts-1.12.2-1.4.1.3.jar                     | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | firstaid                 | 1.6.22                    | firstaid-1.6.22.jar                             | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCHIJA | galacticresearch         | 1.0.0                     | GalacticResearch-1.0.6.jar                      | None                                     |
	| LCHIJA | galaxyspace              | 2.1.1                     | GalaxySpace-1.12.2-2.1.1.jar                    | None                                     |
	| LCHIJA | gravestone               | 1.10.3                    | gravestone-1.10.3.jar                           | None                                     |
	| LCHIJA | cgm                      | 0.15.3                    | guns-0.15.3-1.12.2.jar                          | None                                     |
	| LCHIJA | ironchest                | 1.12.2-7.0.67.844         | ironchest-1.12.2-7.0.72.847.jar                 | None                                     |
	| LCHIJA | ironfurnaces             | 1.3.5                     | ironfurnaces-1.3.5.jar                          | None                                     |
	| LCHIJA | jei                      | 4.16.1.301                | jei_1.12.2-4.16.1.301.jar                       | None                                     |
	| LCHIJA | jeresources              | 0.9.2.60                  | JustEnoughResources-1.12.2-0.9.2.60.jar         | None                                     |
	| LCHIJA | mekanism                 | 1.12.2-9.8.3.390          | Mekanism-1.12.2-9.8.3.390.jar                   | None                                     |
	| LCHIJA | mekanismgenerators       | 1.12.2-9.8.3.390          | MekanismGenerators-1.12.2-9.8.3.390.jar         | None                                     |
	| LCHIJA | mekanismtools            | 1.12.2-9.8.3.390          | MekanismTools-1.12.2-9.8.3.390.jar              | None                                     |
	| LCHIJA | mousetweaks              | 2.10                      | MouseTweaks-2.10-mc1.12.2.jar                   | None                                     |
	| LCHIJA | supermartijn642configlib | 1.1.6                     | supermartijn642configlib-1.1.8-forge-mc1.12.jar | None                                     |
	| LCHIJA | movingelevators          | 1.4.4                     | movingelevators-1.4.4-forge-mc1.12.jar          | None                                     |
	| LCHIJA | hbm                      | NTM-Extended-1.12.2-1.9.8 | NTM-Extended-1.12.2-1.9.8.jar                   | None                                     |
	| LCHIJA | sereneseasons            | 1.2.18                    | SereneSeasons-1.12.2-1.2.18-universal.jar       | None                                     |
	| LCHIJA | spaceambient             | 0.0.1                     | SpaceAmbient-1.12.2-0.0.1.jar                   | None                                     |
	| LCHIJA | storagedrawers           | 5.5.0                     | StorageDrawers-1.12.2-5.5.0.jar                 | None                                     |
	| LCHIJA | trashcans                | 1.0.18                    | trashcans-1.0.18-forge-mc1.12.jar               | None                                     |
	| LCHIJA | vehicle                  | 0.44.1                    | vehicle-mod-0.44.1-1.12.2.jar                   | None                                     |
	| LCHIJA | zawa                     | 1.12.2-2.1.3              | zawa-1.12.2-2.1.3.jar                           | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| LCHIJA | adchimneys               | 1.12.2-3.5.16.0           | AdChimneys-1.12.2-3.5.16.0-build.0654.jar       | None                                     |

	Loaded coremods (and transformers): 
GSHooksLoader (GalaxySpace-1.12.2-2.1.1.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
LoadingPlugin (AdPother-1.12.2-1.2.25.0-build.0673.jar)
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Vanilla
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$DynamicSurroundings
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Weather2$Mesh
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Weather2$Render
  com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$FurnaceDouble
  com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$CoalGenerator
  com.endertech.minecraft.mods.adpother.transformers.AdvancedRocketry$Rocket
  com.endertech.minecraft.mods.adpother.transformers.BetterWithMods$Furnace
  com.endertech.minecraft.mods.adpother.transformers.Campfire$Cooking
  com.endertech.minecraft.mods.adpother.transformers.ControlledBurn$Fire
  com.endertech.minecraft.mods.adpother.transformers.CookingForBlockheads$Oven
  com.endertech.minecraft.mods.adpother.transformers.DraconicEvolution$Generator
  com.endertech.minecraft.mods.adpother.transformers.EmbersRekindled$EmberBore
  com.endertech.minecraft.mods.adpother.transformers.EmbersRekindled$SteamEngine
  com.endertech.minecraft.mods.adpother.transformers.EnderIO$CombustionGenerator
  com.endertech.minecraft.mods.adpother.transformers.EnderIO$StirlingGenerator
  com.endertech.minecraft.mods.adpother.transformers.EngineersDecor$DecorFurnace
  com.endertech.minecraft.mods.adpother.transformers.Factory0Resources$BurnerDrill
  com.endertech.minecraft.mods.adpother.transformers.FastFurnace$Burning
  com.endertech.minecraft.mods.adpother.transformers.FastFurnace$Smelting
  com.endertech.minecraft.mods.adpother.transformers.FurnaceOverhaul$Burning
  com.endertech.minecraft.mods.adpother.transformers.FurnaceOverhaul$Smelting
  com.endertech.minecraft.mods.adpother.transformers.FutureMC$AdvancedFurnace$Burning
  com.endertech.minecraft.mods.adpother.transformers.FutureMC$AdvancedFurnace$Smelting
  com.endertech.minecraft.mods.adpother.transformers.FloodLights$CarbonFloodlight
  com.endertech.minecraft.mods.adpother.transformers.Galacticraft$AutoRocket
  com.endertech.minecraft.mods.adpother.transformers.Galacticraft$Buggy
  com.endertech.minecraft.mods.adpother.transformers.Gregicality$PrimitiveBlastFurnace
  com.endertech.minecraft.mods.adpother.transformers.Gregtech$CokeOven
  com.endertech.minecraft.mods.adpother.transformers.Gregtech$LargeBoilerLiquidFuel
  com.endertech.minecraft.mods.adpother.transformers.Gregtech$LargeBoilerSolidFuel
  com.endertech.minecraft.mods.adpother.transformers.Gregtech$BoilerRecipeLogic
  com.endertech.minecraft.mods.adpother.transformers.Gregtech$FuelRecipeLogic
  com.endertech.minecraft.mods.adpother.transformers.Gregtech$PrimitiveBlastFurnace
  com.endertech.minecraft.mods.adpother.transformers.Gregtech$SteamCoalBoiler
  com.endertech.minecraft.mods.adpother.transformers.Gregtech$SteamLavaBoiler
  com.endertech.minecraft.mods.adpother.transformers.HBMsNuclearTech$Boiler
  com.endertech.minecraft.mods.adpother.transformers.HBMsNuclearTech$BurnerPress
  com.endertech.minecraft.mods.adpother.transformers.HBMsNuclearTech$CombustionGenerator
  com.endertech.minecraft.mods.adpother.transformers.HBMsNuclearTech$DieselGenerator
  com.endertech.minecraft.mods.adpother.transformers.HBMsNuclearTech$GasFlare
  com.endertech.minecraft.mods.adpother.transformers.HBMsNuclearTech$IndustrialGeneratorSolid
  com.endertech.minecraft.mods.adpother.transformers.HBMsNuclearTech$IndustrialGeneratorLiquid
  com.endertech.minecraft.mods.adpother.transformers.HBMsNuclearTech$Turbofan
  com.endertech.minecraft.mods.adpother.transformers.HBMsNuclearTech$RadialEngine
  com.endertech.minecraft.mods.adpother.transformers.HBMsNuclearTech$Extended$Firebox
  com.endertech.minecraft.mods.adpother.transformers.HBMsNuclearTech$Extended$GasFlare
  com.endertech.minecraft.mods.adpother.transformers.HBMsNuclearTech$Extended$IronFurnace
  com.endertech.minecraft.mods.adpother.transformers.HBMsNuclearTech$Extended$HeaterOilburner
  com.endertech.minecraft.mods.adpother.transformers.HBMsNuclearTech$Extended$SteelFurnace
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveCraft$FurnaceTE
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$AllowSmelter
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$BlastFurnace
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$CokeOven
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$DieselGenerator
  com.endertech.minecraft.mods.adpother.transformers.ImmersivePetroleum$Motorboat
  com.endertech.minecraft.mods.adpother.transformers.ImmersivePetroleum$PortableGenerator
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveRailroading$LocomotiveDiesel
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveRailroading$LocomotiveSteam
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveTechnology$Boiler
  com.endertech.minecraft.mods.adpother.transformers.IndustrialForegoing$FuelGenerator
  com.endertech.minecraft.mods.adpother.transformers.IndustrialForegoing$ReactorGenerator
  com.endertech.minecraft.mods.adpother.transformers.IndustrialRenewal$FluidGenerator
  com.endertech.minecraft.mods.adpother.transformers.IndustrialRenewal$SteamBoiler$LiquidFuel
  com.endertech.minecraft.mods.adpother.transformers.IndustrialRenewal$SteamBoiler$SolidFuel
  com.endertech.minecraft.mods.adpother.transformers.Magneticraft$CombustionChamber
  com.endertech.minecraft.mods.adpother.transformers.Magneticraft$BigChamberSolidFuel
  com.endertech.minecraft.mods.adpother.transformers.Magneticraft$BigChamberLiquidFuel
  com.endertech.minecraft.mods.adpother.transformers.Mekanism$FuelwoodHeater
  com.endertech.minecraft.mods.adpother.transformers.MekanismGenerators$BioGenerator
  com.endertech.minecraft.mods.adpother.transformers.MekanismGenerators$GasGenerator
  com.endertech.minecraft.mods.adpother.transformers.MekanismGenerators$HeatGenerator
  com.endertech.minecraft.mods.adpother.transformers.Metallurgy$Alloyer
  com.endertech.minecraft.mods.adpother.transformers.Metallurgy$Crusher
  com.endertech.minecraft.mods.adpother.transformers.Minecraft$AnimalFeeding
  com.endertech.minecraft.mods.adpother.transformers.Minecraft$FurnaceSmelting
  com.endertech.minecraft.mods.adpother.transformers.MoreFurnaces$IronFurnace
  com.endertech.minecraft.mods.adpother.transformers.MrCrayfish$Vehicle
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$InferiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$IntermediumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$PrudentiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SuperiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SupremiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$UltimateFurnace
  com.endertech.minecraft.mods.adpother.transformers.Natura$NetherrackFurnace
  com.endertech.minecraft.mods.adpother.transformers.PneumaticCraft$AirCompressor
  com.endertech.minecraft.mods.adpother.transformers.PrimalCore$RecipeHelper
  com.endertech.minecraft.mods.adpother.transformers.Pyrotech$TileCombustion
  com.endertech.minecraft.mods.adpother.transformers.RealisticBlockPhysics$FallingBlock
  com.endertech.minecraft.mods.adpother.transformers.RealisticTorches$BlockTorch
  com.endertech.minecraft.mods.adpother.transformers.RFTools$CoalGenerator
  com.endertech.minecraft.mods.adpother.transformers.SRParasites$BlockInfestedStain
  com.endertech.minecraft.mods.adpother.transformers.StevesCarts$ModuleCoal
  com.endertech.minecraft.mods.adpother.transformers.Techguns$MachineSlot
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronAlloyFurnace
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronFurnace
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileSolidFuelGenerator
  com.endertech.minecraft.mods.adpother.transformers.TerraFirmaCraft$CharcoalForge
  com.endertech.minecraft.mods.adpother.transformers.TerraFirmaCraft$FirePit
  com.endertech.minecraft.mods.adpother.transformers.TerraFirmaCraft$LogPile
  com.endertech.minecraft.mods.adpother.transformers.TinkersComplement$HighOven
  com.endertech.minecraft.mods.adpother.transformers.TinkersConstruct$HeatingStructure
  com.endertech.minecraft.mods.adpother.transformers.TinkersConstruct$SmelteryAlloys
  com.endertech.minecraft.mods.adpother.transformers.SimpleGrinder$CoalGrinder
  com.endertech.minecraft.mods.adpother.transformers.UltimateCarMod$Car
  com.endertech.minecraft.mods.adpother.transformers.ViesCraft$AirShip
  com.endertech.minecraft.mods.adpother.renders.AerometerRender
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockCaughtFire
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockUpdateTick
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockExploded
  com.endertech.minecraft.mods.adpother.pollution.WorldData$GetSkyColor
  com.endertech.minecraft.mods.adpother.pollution.WorldData$FurnaceFuelBurned
  com.endertech.minecraft.mods.adpother.pollution.WorldData$LavaTouchesWater
  com.endertech.minecraft.mods.adpother.transformers.ZenFoundry$BurnerHeater
  com.endertech.minecraft.mods.adpother.transformers.ZenFoundry$MoldStation
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
CorePlugin (ForgeEndertech-1.12.2-4.5.6.1-build.0648.jar)
  
MicdoodlePlugin (Galacticraft-1.12.2-4.0.6.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ReflectorsPlugin (GalacticResearch-1.0.6.jar)
  igentuman.galacticresearch.reflection.ReflectorsPlugin
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
LoadingPlugin (AdChimneys-1.12.2-3.5.16.0-build.0654.jar)
  com.endertech.minecraft.mods.adchimneys.world.WorldData$BlockRandomTick
SuperMartijn642's Core Lib Plugin (_supermartijn642corelib-1.1.13-forge-mc1.12.jar)
  
Moving Elevators Plugin (movingelevators-1.4.4-forge-mc1.12.jar)
  
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.7.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 537.13' Renderer: 'NVIDIA GeForce GTX 1650/PCIe/SSE2'
	Launched Version: forge-14.23.5.2859
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 537.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 5800HS with Radeon Graphics 
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
igentuman.galacticresearch.client.gui.GRGuiCelestialSelectionGalaxySpace
write igentuman to fix
