### ISSUE TITLE
The Assembly Machine is not working

### ISSUE THREAD

**Issue by CrAlex20** [BlesseNtumble/GalaxySpace#678]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.6
3. GalaxySpace version: 2.1.1
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.0
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP and SMP
6. Other add-ons: More Planet
------------------------------------------------------------------------
Description of the issue: I have created the Assembly Machine but at the moment of placing the items nothing happens and the machine crashes in "Status: Idle". This happened in a server, but when I open a singleplayer world the problem persists even placing the upgrade modules in the machine.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by 6ItsYaBoi9** [comment]
I am having this exact same issue rn and i cant find anything online on how to fix it or what to do

Edit; i have fixed the issue by using galacticraft legacy version 4.0.5

**Comment by BlesseNtumble** [comment]
try 2.1.3 version
