### ISSUE TITLE
Crash when ticking a block

### ISSUE THREAD

**Issue by MossCG** [BlesseNtumble/GalaxySpace#679]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2 CatServer (Server Side)
2. Galacticraft version: Galacticraft-1.12.2-4.0.6
3. GalaxySpace version: GalaxySpace-1.12.2-2.1.2
4. AsmodeusCore version (for 2.0.1 version and above): AsmodeusCore-1.12.2-1.0.1
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SMP
6. Other add-ons: ExtraPlanets-1.12.2-0.7.7
------------------------------------------------------------------------
Description of the issue:
Run  Server and server crash after done
but i change GS version back to GalaxySpace-1.12.2-2.0.19 it wont happen
tested:
remove EP: crashed
remove GS: fixed
rollback GS version: fixed
------------------------------------------------------------------------
Screenshot/Video:
//

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

https://pastebin.com/gg4sQtn4
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
On 2.1.1 still crash?

**Comment by D-9341** [comment]
It doesn`t crash on 2.1.1, но проблема может перерасти в ticking world, по факту уничтожая мир. Я проверял один и тот же мир на сервере и на своём пк, и проблема наблюдалась только на сервере. Все версии идентичны версиям MossCG, только нет extraplanets

**Comment by BlesseNtumble** [comment]
try 2.1.3 build
