### ISSUE TITLE
Config for Planetary Tiers

### ISSUE THREAD

**Issue by TFCAliarcy** [BlesseNtumble/GalaxySpace#682]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version:4.0.5
3. GalaxySpace version:2.1.3
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.1
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:
Would like there to be config option for rocket tiers assigned to planets so we can rearrange progression. For example assigning asteroid belt as tier 3 and Mercury as 4.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Will add in AsmodeusCore 1.0.2
