### ISSUE TITLE
Unusual / repetitive terrain generation on Barnarda C

### ISSUE THREAD

**Issue by dkluin** [BlesseNtumble/GalaxySpace#686]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.6
3. GalaxySpace version: 2.1.3
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.1
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP/SMP/SSP on LAN
6. Other add-ons: N/A
------------------------------------------------------------------------
Description of the issue:

The terrain generation on Barnarda C is very repetitive, consisting of thin bands of "biomes", separated by large lakes. These thin bands always contain a strip of forest and a very tall cliff with little to no variation. I've created several worlds but this didn't make much of a difference.

I've noticed similar issues in the past on other worlds, namely Mars, which I managed to fix by disabling the custom world engine. However, I tried visiting Mars and it seems to have been fixed there by now. I haven't checked out other worlds, but chances are there's another planet/moon which has similar terrain generation issues.

------------------------------------------------------------------------
Screenshot/Video:

https://imgur.com/a/fsMtSD4

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

N/A

------------------------------------------------------------------------

**Comment by ghost** [comment]
That's not a bug it's a feture.
