### ISSUE TITLE
The configuration files are slightly outdated / in need of a cleanup

### ISSUE THREAD

**Issue by dkluin** [BlesseNtumble/GalaxySpace#687]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.6
3. GalaxySpace version: 2.1.3
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.1
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP/SMP/SSP on LAN
6. Other add-ons: N/A
------------------------------------------------------------------------
Description of the issue:

A few years ago GalaxySpace had additional dimensions which are now removed. However, the generated dimensions.conf file (and other files possibly as well) still reference these dimensions. I don't know if these are still read (I haven't tried to force an ID conflict on any of them), but it might be best to clean up the generated config file.

I've done a bit of searching and this should be all of the removed planets/moons:
- Deimos
- The Jupiter space station dimension
- Makemake
- Oberon
- Proteus
- Proxima C
- Proxima D
- Barnarda C1
- Barnarda C2

Another thing I noticed is that it is currently impossible to change Tau Ceti A's dimension ID, as no dimensions.conf file exists in the tau_ceti folder.

------------------------------------------------------------------------
Screenshot/Video:

N/A

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

N/A

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Barnarda C1 and Barnarda C2 - wip content
