### ISSUE TITLE
Краш на integrated-server (singleplayer)

### ISSUE THREAD

**Issue by Maks2103** [BlesseNtumble/GalaxySpace#69]
crash-2016-06-26_17.27.06-server: http://pastebin.com/GiD3MTKG
crash-2016-06-26_17.27.21-client: http://pastebin.com/GtU9miKZ
оба crash-report'а сгенерировались одновременно
на выделенном сервере всё работает нормально

**Comment by Maks2103** [comment]
поясняю для тупых: выделенный сервер = обычный сервер, отдельный от клиента

**Comment by BlesseNtumble** [comment]
Could not get provider type for dimension -22, does not exist - Конфликт ID
Краш со стороны клиента не относится к GS. cofh у нас никак не задействован.
