### ISSUE TITLE
Kuiper Belt Unplayable

### ISSUE THREAD

**Issue by ShionWayne** [BlesseNtumble/GalaxySpace#695]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.6
3. GalaxySpace version: 2.1.3
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.0
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: ExtraPlanets, More Planets, More Planets Extra, Zollern Galaxy
------------------------------------------------------------------------
Description of the issue:
Kuiper Belt is highly malfunctioning. I was wearing modular powersuits from MPS and Electric Flight Ring from More Electric Tools. Unlike in the Asteroids which has gravity, I was floating around and could barely control myself. So I tried using Travel function from Ender IO, and grapple hook from GC. In either way, I got to move at the desired direction at first, but after touching something (hit a block from its side or below) I started to be teleported at random like crazy, and there was no way to get control. In creative mode you don't get teleported but you still can't experience creative flight. I'm not sure if this dimension is meant to be different from Asteroids, because while I cannot feel gravity the monsters still do. But the teleporting thing cannot be normal. 

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Use the grappling hook
