### ISSUE TITLE
Persistent rendering of Oxygen Gears and Thermal Padding between worlds

### ISSUE THREAD

**Issue by EzerArch** [BlesseNtumble/GalaxySpace#70]
The Oxygen Gears and Thermal Padding (GC's or GS's) are being rendered between worlds, even if you have no 

How to reproduce it in Single Player:
1. Create a new world:
   ![2016-06-26_20 48 51](https://cloud.githubusercontent.com/assets/6743303/16365746/f6eb7414-3bdf-11e6-8a93-2b0ae5d49be0.png)
2. Put oxygen gears and GS thermal padding on:
   ![2016-06-26_20 49 42](https://cloud.githubusercontent.com/assets/6743303/16365747/fa9788f0-3bdf-11e6-8814-2bdb96d55146.png)
3. Close the world (not the game), and open or create another world.
4. The game will render the same oxygen gears and GS thermal padding on from the 1st world:
   ![2016-06-26_20 51 41](https://cloud.githubusercontent.com/assets/6743303/16365753/0c952f8a-3be0-11e6-9cb0-4ff788d6f307.png)
5. Even if the space player inventory is empty:
   ![2016-06-26_20 53 56](https://cloud.githubusercontent.com/assets/6743303/16365758/23476d74-3be0-11e6-87e9-d454096f8c60.png)
6. Kill yourself, it will drop nothing:
   ![2016-06-26_20 56 49](https://cloud.githubusercontent.com/assets/6743303/16365777/85892b8a-3be0-11e6-8012-dbbf5b41e91b.png)

**Note:** This bug does not happen without GS installed.

**Mods being used (Forge 1614):**
- CodeChickenCore-1.7.10-1.0.7.47-universal.jar
- NotEnoughItems-1.7.10-1.0.5.120-universal.jar
- MicdoodleCore-1.7-3.0.12.460.jar
- GalacticraftCore-1.7-3.0.12.460.jar
- Galacticraft-Planets-1.7-3.0.12.460.jar
- GalaxySpace-1.0.9 STABLE.jar

**Comment by MeSoLost** [comment]
I've seen this issue too now that I'm at the point I'm setting death drop conditions. (hadn't died before)  Would you like screenshots or should I make a short video to demonstrate the problem?  (problem is semi corrected for me because I scripted in a Galacticraft keep-inventory-on-death fix since that appears to have broken. (game setting of keep inventory on death fails to keep GC inv - bug known))

**Comment by BlesseNtumble** [comment]
Well...
Render thermal armor comes in GC3.

**Comment by EzerArch** [comment]
>  Render thermal armor comes in GC3.

Sorry, could you please elaborate?

I don't have this issue when I'm playing only with Galacticraft, **only if** GS is also installed: I die, whole armor set still renders even if the player inventory is empty and all items are scattered on the floor at the death point.
