### ISSUE TITLE
Beyond Space, keeps crashing on startup.

### ISSUE THREAD

**Issue by ghost** [BlesseNtumble/GalaxySpace#712]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.7.10
2. Galacticraft version:
3. GalaxySpace version:
4. AsmodeusCore version (for 2.0.1 version and above): 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
6. Other add-ons: Beyond Space
------------------------------------------------------------------------
Description of the issue:

------------------------------------------------------------------------
Screenshot/Video:
![Screenshot 2024-05-04 112304](https://github.com/BlesseNtumble/GalaxySpace/assets/166317640/d801d4a5-478c-41a2-8b83-9983a374a373)
![Screenshot 2024-03-15 203431](https://github.com/BlesseNtumble/GalaxySpace/assets/166317640/74d024c4-2901-4812-b0ab-759270833bd9)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
this has been told numerous times - the 1.7.10 branch

**Comment by CaveJohnson376** [comment]
this has been told numerous times - the 1.7.10 branch of the mod is deprecated and therefore, no longer maintained. please move on and stop spamming with same issues all over again.
