### ISSUE TITLE
[SUGGESTION] Add Gas Giants

### ISSUE THREAD

**Issue by ghost** [BlesseNtumble/GalaxySpace#717]
**Do not remove this template, without it your issue will not be considered!**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.6
3. GalaxySpace version: 2.1.4
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.2
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Single Player
6. Other add-ons: None
------------------------------------------------------------------------
Description of the issue: I love exploring new planets especially Gas Giants.
In Galaxy Space Jupiter and the other Gas Giants are all unreachable. You could add a ring dimension to them or one made only of clouds and fog, with a liquid hydrogen helium surface. Can you make the Gas Giants not have a surface but be launchable? 🚀
------------------------------------------------------------------------
Screenshot/Video: 
![Screenshot 2024-07-17 103930](https://github.com/user-attachments/assets/8c3f3927-6193-4820-a84c-b8c4043a2d0f)

This may be inspiring.

![Screenshot 2024-07-16 204604](https://github.com/user-attachments/assets/e8ec35f0-ac7d-46ef-afd0-cd2bc05906b1)

Can you also add all the moons.
------------------------------------------------------------------------
Attached log file (or url on pastebin.com): None

------------------------------------------------------------------------

**Comment by ghost** [comment]
Here is more inspiration.

![Buqti_yqvaI](https://github.com/user-attachments/assets/ded8447c-5ebd-411d-973d-7d2d05f57a6c)

![iLo0DsX7ZHk](https://github.com/user-attachments/assets/09de2012-3a40-42db-b7a6-9a4eead7aca3)

![RiTQcxsl4Sc](https://github.com/user-attachments/assets/c43ad4ab-8f08-40b2-bcf4-5a2ee24b70f9)

![u_0G6MxNXaY](https://github.com/user-attachments/assets/f261e165-12eb-4d17-89ec-15d41792efcd)

![A3uhgpZVRhg](https://github.com/user-attachments/assets/8e14f84a-e7f3-43b7-becc-ac1a0ae2eb6f)

**Comment by CaveJohnson376** [comment]
developer has stated numorous times that they will NOT implement gas giants as landable destinations.

**Comment by syzygy2896** [comment]
> developer has stated numorous times that they will NOT implement gas giants as landable destinations.

But the Beyond Space addon was supposed to add them, and it broke. They don't have to have a surface.

**Comment by syzygy2896** [comment]
> developer has stated numorous times that they will NOT implement gas giants as landable destinations.

Not landable, just travilable.

**Comment by syzygy2896** [comment]
I just like exploring Gas planets

**Comment by syzygy2896** [comment]
Why is nobody els commenting on this?

**Comment by ghost** [comment]
> developer has stated numorous times that they will NOT implement gas giants as landable destinations.

The Beyond Space mod that adds the Gas Giants causes an EPPTank crash. Can you please tell the author of the Beyond Space mod to remove the EPPTank?

**Comment by CaveJohnson376** [comment]
developer has abandoned older versions of game, and moved on to developing new content for newer versions. GS for 1.7.10 and BeyondSpace will NOT be getting any new updates, both bugfixes and new content. spamming github issues with requests to continue support and/or add gas giants will not help, and will only get you banned from posting any more issues and commenting on existing ones.

**Comment by ghost** [comment]
> developer has abandoned older versions of game, and moved on to developing new content for newer versions. GS for 1.7.10 and BeyondSpace will NOT be getting any new updates, both bugfixes and new content. spamming github issues with requests to continue support and/or add gas giants will not help, and will only get you banned from posting any more issues and commenting on existing ones.
