### ISSUE TITLE
Крашится при запуске

### ISSUE THREAD

**Issue by axtew** [BlesseNtumble/GalaxySpace#72]
[crash-2016-07-04_10.08.00-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/345759/crash-2016-07-04_10.08.00-client.txt)

**Comment by BlesseNtumble** [comment]
(GalacticraftCore-1.7-3.0.12.375.jar) 
Читать то не умеем?
Минимальный билд 454, а у вас 375
