### ISSUE TITLE
IndexOutOfBoundsException when loading into Main Menu

### ISSUE THREAD

**Issue by Flimsy-Fox** [BlesseNtumble/GalaxySpace#720]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.6
3. GalaxySpace version: 2.1.4
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.2
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): N/A
6. Other add-ons: SpaceCraftX
------------------------------------------------------------------------
Description of the issue:
GSGuiMainMenu.drawScreen crashes with an IndexOutOfBoundsException

------------------------------------------------------------------------
Screenshot/Video:

![minecraft-crash](https://github.com/user-attachments/assets/ba9f70a5-0155-43bc-a608-885267fa983c)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://pastebin.com/SVPyishJ

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Will try fix in 2.1.5
