### ISSUE TITLE
Hydroponic Farm's growing animation is in reverse

### ISSUE THREAD

**Issue by GalaxinTM** [BlesseNtumble/GalaxySpace#721]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.6
3. GalaxySpace version: 2.1.4
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.2
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: MorePlanets, GalacticraftTweaker
------------------------------------------------------------------------
Description of the issue: the crop(s) are visualized to be growing but in reverse

------------------------------------------------------------------------
Screenshot/Video:

https://github.com/user-attachments/assets/094334b4-438e-4b2e-a3d6-239ea4011d33

------------------------------------------------------------------------
Attached log file (or url on pastebin.com): Not required

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Will fix in 2.1.5
