### ISSUE TITLE
Hydroponic Farm uses 3x more resources regardless of how many farms are attached

### ISSUE THREAD

**Issue by GalaxinTM** [BlesseNtumble/GalaxySpace#722]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.6
3. GalaxySpace version: 2.1.4
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.2
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: MorePlanets, GalacticraftTweaker
------------------------------------------------------------------------
Description of the issue: Hydroponic farm uses 3 bone meals regardless of how many farms are attached.
It should only use 1 bone meal if there's 1 farm attached, the same goes if there are 2 farms attached.

------------------------------------------------------------------------
Screenshot/Video:

https://github.com/user-attachments/assets/e67b3cd7-439f-49cb-ae21-95402aeb32ed

https://github.com/user-attachments/assets/7d7ffb6c-4df0-4fcc-aebf-32fcd64d8512

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Will fix in 2.1.5
