### ISSUE TITLE
EPO Tank schematic incorrectly unlocks tier 3 rocket recipe

### ISSUE THREAD

**Issue by GalaxinTM** [BlesseNtumble/GalaxySpace#723]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.6
3. GalaxySpace version: 2.1.4
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.2
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SMP
6. Other add-ons: MorePlanets, GalacticraftTweaker
------------------------------------------------------------------------
Description of the issue:
Trying to use the EPO tank's schematic in a NASA workbench unlocks the recipe for the Tier 3 rocket.
Advanced rocket craft is disabled in the config btw.
The attached video shows that the Tier 3 rocket gets unlocked, and the EPO tank's recipe is nowhere to be seen.

Попытка использовать схему бака EPO в верстаке NASA разблокирует рецепт для ракеты Tier 3.
Кстати, Advanced rocket craft отключен в конфигурации.
Прикрепленное видео показывает, что ракета Tier 3 разблокируется, а рецепт бака EPO нигде не виден.

------------------------------------------------------------------------
Screenshot/Video:

https://github.com/user-attachments/assets/de2054ff-2bfe-4979-8cbe-9b9107f70dc6

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Will fix in 2.1.5
