### ISSUE TITLE
Thermal Control not Protecting Against Atmospheric Pressure

### ISSUE THREAD

**Issue by TFCAliarcy** [BlesseNtumble/GalaxySpace#727]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.12.2
2. Galacticraft version:1.12.2-4.0.6
3. GalaxySpace version:1.12.2-2.1.4
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-1.0.2
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):SSP
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:
Putting an Ambient Thermal Controller in and oxygen sealer will protect against temperature but not against pressure.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Use Gravity Module and Stabilization module.
