### ISSUE TITLE
(1.12.2) World Lighting Visual Bug When Entering Galaxy Space Rockets 

### ISSUE THREAD

**Issue by ghost** [BlesseNtumble/GalaxySpace#733]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.6
3. GalaxySpace version: 2.1.4
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.2
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue: When a player enters any rocket tier from Galaxy Space, the world lighting suddenly changes, creating dark block shadows and rendering the world lighting as if smooth lighting was off. 

The video attachment shows what happens when a player enters rocket tiers 4-6. The visual bug also occurs in other dimensions like Venus.

------------------------------------------------------------------------
Screenshot/Video:
https://github.com/user-attachments/assets/c5586be1-049d-4850-a2ff-2deda513d899

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Will fix in 2.1.5
