### ISSUE TITLE
[1.12.2] Large and Small Triton Geysers Don't Work

### ISSUE THREAD

**Issue by ghost** [BlesseNtumble/GalaxySpace#735]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.6
3. GalaxySpace version: 2.1.4
4. AsmodeusCore version (for 2.0.1 version and above):  1.0.2
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:

Triton's geysers do not seem to work when performing a clean installation of Galaxy Space and related mods to run the addon. 

Doing a test shows that both the small and large Triton geysers spew particles when a water source block is below both geyser types.

However, small geysers on the actual moon, Triton, do not generate with any water source block below it. I also found that water on Triton freezes; this is problematic because the large geysers don't spew particles into the sky.

It appears that with the temperature system of Galaxy Space, water is instantly turned into ice under certain temperatures; however, Triton doesn't have that exception, resulting in geysers not working as intended.

------------------------------------------------------------------------
Screenshot/Video:
https://github.com/user-attachments/assets/404fb9ac-2c59-4e84-ab6e-f99c6179ab4f

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
https://github.com/BlesseNtumble/GalaxySpace/commit/60a6072a358873e59892f4f7e159163407ad82a4
