### ISSUE TITLE
crash - fuel generator (MP)

### ISSUE THREAD

**Issue by Cronosus** [BlesseNtumble/GalaxySpace#79]
hello
We have crash on server, when player insert Canister with fuel inside Fuel Generator
Server: Thermos, 1.7.10
crash report: http://pastebin.com/t8GEt6mF

thanks in advance

**Comment by Miraun** [comment]
I'd like to verify the above bug.  We were able to replicate it fairly consistently when a fuel generator ran out of fuel.  Unfortunately, it happened to a generator array on the server (like, 10 generators powering a mining laser), near simultaneously, so it ended up taking MANY REBOOTS to fix once we noticed that the act of running out of fuel was causing the crash, and getting new block IDs each crash.

[crash-2016-07-28_21.23.07-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/391036/crash-2016-07-28_21.23.07-server.txt)

**Comment by Miraun** [comment]
Note:  This also happened in creative single player, where we verified the conditions for the crash/etc

**Comment by rlemish** [comment]
Подтверждаю баг!

[crash-2016-10-03_17.36.31-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/506479/crash-2016-10-03_17.36.31-server.txt)

**Comment by Egorpom** [comment]
Краш происходит при помещении неполной канистры с топливом в генератор. При помещении полной канистры краша не происходит.

**Comment by BlesseNtumble** [comment]
Fixed in next version.
