### ISSUE TITLE
Crash singleplayer.

### ISSUE THREAD

**Issue by kostay99** [BlesseNtumble/GalaxySpace#81]
Здравствуйте, столкнулся с такой проблемой: после недавнего обновления GalactiCraft решил поставить и  GalaxySpace и как бы проблем не было, т.к. я играю на своем сервере, но решив зайти в творческий сингл собственно краш. 
По итогу: убираешь GalaxySpace не крашиться, id измерений я уже менял на новые(которых в принципе нет), крашлогов много, но вот последний, перед которым были снесены конфиги http://pastebin.com/wKghQUSz

З.Ы.: краш происходит не сразу, а через 20-30 сек после захода в мир, а теперь и вовсе не заходит:(
Версия GalaxySpace 1.1.0(также пробовал 1.0.9 без результатно), GalactiCraft 454 сборки.

**Comment by KiraLinux** [comment]
Could not get provider type for dimension -1022 
У меня тоже так же
