### ISSUE TITLE
[VENUS] Server is having MEGA Lags

### ISSUE THREAD

**Issue by LokeYourC3PH** [BlesseNtumble/GalaxySpace#83]
Having a problem on Venus since the last update. When i mine surface blocks or sub-surface blocks, they do not drop as items. Not just that, but the Venus dimensions causes HUGE TPS drops, from 20 down to 3-7 TPS (which is probably due to all the lava if i should guess). Any fix for both?

**Comment by dimon22220** [comment]
Схожая проблема

**Comment by LokeYourC3PH** [comment]
@dimon22220 God damn it speak english, most people won't understand you, even if the developer speaks russian, others that may want to help won't understand you.

**Comment by dimon22220** [comment]
Sorry, i wrote: a similar problem
