### ISSUE TITLE
Barnarda C terrain generation error/failure

### ISSUE THREAD

**Issue by MeSoLost** [BlesseNtumble/GalaxySpace#91]
Title and pictures say it all.  I had 1.0.9 installed and never visited this planet and the landing spot was ok.  I start to make my way to 0, 0 and ran into this. (after updateing to 1.1.0) 
edit: (dark places are just stone without lighting update, all surface dirt and trees is whats missing from the chunks)
![_mods](https://cloud.githubusercontent.com/assets/20606168/18155553/667a0dd8-6fc3-11e6-9b8e-28483342b3f3.jpg)
![2016-08-31_21 26 00](https://cloud.githubusercontent.com/assets/20606168/18155561/8adbbdb6-6fc3-11e6-9d1c-99ce796b79a1.png)
![2016-08-31_21 26 44](https://cloud.githubusercontent.com/assets/20606168/18155562/8adf127c-6fc3-11e6-888b-d85cad42fb8d.png)

**Comment by MeSoLost** [comment]
I do not believe

**Comment by MeSoLost** [comment]
I don't believe you meant for there to be "oceans of rock" and WorldEdit //regen does correct ground level but as you can see it remains an ocean of stone -.-
![2016-08-31_21 54 24](https://cloud.githubusercontent.com/assets/20606168/18155959/2b7a559a-6fc7-11e6-9991-f3c697b2d3c8.png)
![2016-08-31_21 55 44](https://cloud.githubusercontent.com/assets/20606168/18155960/2b7b0cec-6fc7-11e6-8b87-f413c0074cb4.png)
![2016-08-31_22 00 01](https://cloud.githubusercontent.com/assets/20606168/18155962/2b82f9e8-6fc7-11e6-8cf1-3fa4120e39cd.png)
![2016-08-31_22 00 09](https://cloud.githubusercontent.com/assets/20606168/18155961/2b7dc158-6fc7-11e6-9318-609bffda1ac2.png)
More pictures so you can see some of the terrain is actually generating WAY up high at y256 (last picture) in the ocean biome. Looking for any other variations of the error.

**Comment by MeSoLost** [comment]
Hills generate as plains, plains generate as forests. Any hills that generate as actual hills have the missing dirt error. Shores have the missing top layers errors. Found an "Ocean" generated as mountains with floating dirt at y256.
![2016-08-31_22 06 56](https://cloud.githubusercontent.com/assets/20606168/18156421/fef48884-6fca-11e6-8add-96259b2171c7.png)
![2016-08-31_22 07 07](https://cloud.githubusercontent.com/assets/20606168/18156422/fef6de72-6fca-11e6-9518-15cd1320539c.png)
![2016-08-31_22 10 23](https://cloud.githubusercontent.com/assets/20606168/18156423/fef6f8bc-6fca-11e6-8976-63ff72d3171e.png)
![2016-08-31_22 11 21](https://cloud.githubusercontent.com/assets/20606168/18156424/fefd8326-6fca-11e6-8a40-72bf50577232.png)
![2016-08-31_22 16 06](https://cloud.githubusercontent.com/assets/20606168/18156425/ff0068a2-6fca-11e6-9179-cee75e27a181.png)
![2016-08-31_22 16 24](https://cloud.githubusercontent.com/assets/20606168/18156426/ff08ea54-6fca-11e6-812a-9a0336752183.png)
![2016-08-31_22 18 27](https://cloud.githubusercontent.com/assets/20606168/18156427/ff0c86e6-6fca-11e6-812f-668138c39e9e.png)
![2016-08-31_22 18 43](https://cloud.githubusercontent.com/assets/20606168/18156428/ff25b512-6fca-11e6-8dca-76bd948db792.png)
![2016-08-31_22 19 39](https://cloud.githubusercontent.com/assets/20606168/18156429/ff2973a0-6fca-11e6-9e9c-35ad3dada103.png)
![2016-08-31_22 25 30](https://cloud.githubusercontent.com/assets/20606168/18156430/ff2aa126-6fca-11e6-8294-376132bdd5ff.png)
![2016-08-31_22 25 41](https://cloud.githubusercontent.com/assets/20606168/18156432/ff365e76-6fca-11e6-8948-d8989f31cfcd.png)
![2016-08-31_22 27 47](https://cloud.githubusercontent.com/assets/20606168/18156431/ff2f8808-6fca-11e6-9c51-a9505244b5f9.png)
![2016-08-31_22 27 52](https://cloud.githubusercontent.com/assets/20606168/18156433/ff3912f6-6fca-11e6-84cc-3940e563a4e9.png)
![2016-08-31_22 28 02](https://cloud.githubusercontent.com/assets/20606168/18156434/ff42b4aa-6fca-11e6-8288-71359d5aae87.png)

If you want to see this for yourself it is on my server.

**Comment by BlesseNtumble** [comment]
In the pure world did not try?

**Comment by MeSoLost** [comment]
I do not understand what you are asking there.

**Comment by BlesseNtumble** [comment]
Try in new world.

**Comment by MeSoLost** [comment]
I'm preparing to setup my worlds to have re-spawning bosses so after I reset them all in the next week I'll let you know. 

i deleted all my extra planets to let them all regen and the oceans didnt regen properly again. no square chunk errors found but where there should be an ocean the ground is again stone and dirt layers are present at layer 252-255 (regenerated with KCauldron jar, i've since changed to Thermos and I'll try and regen the world again and let you know)

Ok after the update (mod update to 1.1.1, NOT my server update, that still generated oddly) the regeneration is ok now although there are no ocean biomes (just really big shores biomes) Dunno if that was intended but I flew around for a half an hour and only saw 1 thing weird.

These guys supposed to generate floating over UnknownLiquid ?

![2016-10-15_18 04 13](https://cloud.githubusercontent.com/assets/20606168/19414794/e309583c-930d-11e6-9f71-f0d6b409a961.png)

**Comment by MeSoLost** [comment]
i deleted all my extra planets to let them all regen and the oceans didnt regen properly again.  no square chunk errors found but where there should be an ocean the ground is again stone and dirt layers are present at layer 252-255 (regenerated with KCauldron jar, i've since changed to Thermos and I'll try and regen the world again and let you know)

**Comment by BlesseNtumble** [comment]
Yes. This "guys" generate floating over UnknownLiquid
