### ISSUE TITLE
ошибка при запуске лаунчера 

### ISSUE THREAD

**Issue by Mrdemon123** [BlesseNtumble/GalaxySpace#96]
выдаёт crash при запуске лаунчера с модом Galaxy Space 
[crash-2016-09-12_18.04.49-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/467250/crash-2016-09-12_18.04.49-client.txt) других модов нет только 
galacticraft  и Galaxy Space

**Comment by BlesseNtumble** [comment]
Обновите Galacticraft3

**Comment by Mrdemon123** [comment]
я и так обновил
