### ISSUE TITLE
Crash upon loading GS dimension

### ISSUE THREAD

**Issue by EzerArch** [BlesseNtumble/GalaxySpace#97]
My game crashed once I entered a GS dimension, and now it crashes every time I try to load the save.

```
Description: Ticking player

java.lang.ClassCastException: net.minecraft.item.ItemArmor cannot be cast to galaxyspace.SolarSystem.core.registers.items.IItemPressurized
at galaxyspace.SolarSystem.core.handler.GSEventHandler.onEntityUpdate(GSEventHandler.java:224)
```

Full log: https://gist.github.com/EzerArch/d7fb6806fc25b710ad75126b20596dcc

EDIT: It looks like the dimension crashes if I try to use a vanilla armor.

**Comment by BlesseNtumble** [comment]
redownload 1.1.1 version
