### ISSUE TITLE
Крашится игра при залёте на деймос.

### ISSUE THREAD

**Issue by Nicrisild22** [BlesseNtumble/GalaxySpace#98]
Почему когда я в выживании у себя залетаю на Деймос, то вылетает игра?, что происходит?, Деймос спутник Марса, не давно создал ракету 2 лвл, вот краш-репорт.

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 05.10.16 16:53
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: 4
    at galaxyspace.SolarSystem.core.coremod.gui.GSGuiMainMenu.func_73863_a(GSGuiMainMenu.java:560)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at galaxyspace.SolarSystem.core.coremod.gui.GSGuiMainMenu.func_73863_a(GSGuiMainMenu.java:560)

-- Screen render details --
Details:
    Screen name: galaxyspace.SolarSystem.core.coremod.gui.GSGuiMainMenu
    Mouse location: Scaled: (417, 181). Absolute: (835, 267)
    Screen size: Scaled: (463, 315). Absolute: (925, 630). Scale factor of 2
Stacktrace:
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_66, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 548376392 bytes (522 MB) / 1321017344 bytes (1259 MB) up to 3207856128 bytes (3059 MB)
    Mod Pack: Unknown / None
    LiteLoader Mods: 3 loaded mod(s)
          - WorldEditWrapper version 1.2.0
          - MAtmos version r28 for 1.7.10
          - VoxelMap version 1.5.13
    LaunchWrapper: 38 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: atomicstryker.dynamiclights.common.DLTransformer
          - Transformer: mrtjp.relocation.asm.Transformer
          - Transformer: com.creativemd.itemphysic.ItemTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: shadersmodcore.transform.SMCClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.JoinGamePacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerChatPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderCallbackInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LoginSuccessPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CustomPayloadPacketTransformer
          - Transformer: com.mumfrey.worldeditwrapper.asm.InteractionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerCustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ChatPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
    JVM Flags: 5 total; -Xmx3072M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 15, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 84 mods loaded, 84 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   itemphysic{0.8.3} [ItemPhysic](minecraft.jar) 
    UCHIJAAAA   Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.111} [Not Enough Items](NotEnoughItems-client.jar) 
    UCHIJAAAA   seasonsmod{pre-3.0beta4} [The Seasons Mod](1.7.10-TheSeasonsMod-pre-3.0beta4.jar) 
    UCHIJAAAA   seasonsmodac{1.0} [Additional Seasons Content](1.7.10-TheSeasonsMod-pre-3.0beta4.jar) 
    UCHIJAAAA   wputil{1.4} [WeatherPony Utilities](1.7.10-TheSeasonsMod-pre-3.0beta4.jar) 
    UCHIJAAAA   IMSM{100.0.2} [IMSM](1.7.10InstantMassiveStructuresMod.jar) 
    UCHIJAAAA   MedicineCraft{V4.0} [MedicineCraft](2043_MedicineCraft-M.jar) 
    UCHIJAAAA   BuildCraft|Core{7.1.14} [BuildCraft](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.1.14} [BC Transport](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.1.14} [BC Silicon](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.1.14} [BC Factory](buildcraft-7.1.14.jar) 
    UCHIJAAAA   additionalpipes{4.7.0} [Additional Pipes](additionalpipes-4.7.0.jar) 
    UCHIJAAAA   IC2{2.2.810-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.810-experimental.jar) 
    UCHIJAAAA   AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels](AdvancedSolarPanels-3.5.1.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.1.14} [BC Energy](buildcraft-7.1.14.jar) 
    UCHIJAAAA   GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.463.jar) 
    UCHIJAAAA   GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.463.jar) 
    UCHIJAAAA   GalacticraftAmunRa{0.0.2} [Pra's Galacticraft Mod](AmunRa-GC-0.1.0 %281%29.jar) 
    UCHIJAAAA   animalsPlus{1.2} [Animals+](animalsPlus-1.2.jar) 
    UCHIJAAAA   BiblioCraft{1.11.2} [BiblioCraft](Bibliocraft.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.1.14} [BC Builders](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.1.14} [BC Robotics](buildcraft-7.1.14.jar) 
    UCHIJAAAA   Forestry{3.6.10.1} [Forestry for Minecraft](forestry-3.6.10.1.jar) 
    UCHIJAAAA   BuildCraft|Compat{7.1.3} [BuildCraft Compat](buildcraft-compat-7.1.3.jar) 
    UCHIJAAAA   CarpentersBlocks{3.3.7} [Carpenter's Blocks](CarpentersBlocks-3.3.7.jar) 
    UCHIJAAAA   colourfulportalsmod{1.4.1} [Colourful Portals](Colourful-Portals-Mod-1.7.10.jar) 
    UCHIJAAAA   BuildMod{v1.0} [Build Mod](coroutil-1.1.3 for MC v1.7.10.jar) 
    UCHIJAAAA   CoroPets{v1.0} [CoroPets](coroutil-1.1.3 for MC v1.7.10.jar) 
    UCHIJAAAA   CoroAI{v1.0} [CoroAI](coroutil-1.1.3 for MC v1.7.10.jar) 
    UCHIJAAAA   ExtendedRenderer{v1.0} [Extended Renderer](coroutil-1.1.3 for MC v1.7.10.jar) 
    UCHIJAAAA   ConfigMod{v1.0} [Extended Mod Config](coroutil-1.1.3 for MC v1.7.10.jar) 
    UCHIJAAAA   customnpcs{1.7.10} [CustomNpcs](Custom-NPCs-Mod-1.7.10.jar) 
    UCHIJAAAA   DamageIndicatorsMod{3.2.0} [Damage Indicators](damage_indicators_mod_1.7.10.jar) 
    UCHIJAAAA   DynamicLights{1.3.5} [Dynamic Lights](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_mobEquipment{1.0.5} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   extvil{1.7.10-1.3} [Extended_Villages](extended_villages_mod_1.7.10.jar) 
    UCHIJAAAA   flashlight{???{version}} [Flashlight Mod](Flashlight_1.7.10_1.0.jar) 
    UCHIJAAAA   GalaxySpace{1.1.1} [GalaxySpace](GalaxySpace-1.1.1 STABLE.jar) 
    UCHIJAAAA   GraviSuite{1.7.10-2.0.3} [Graviation Suite](GravitationSuite-client.jar) 
    UCHIJAAAA   IC2NuclearControl{2.3.3a-Exist} [Nuclear Control 2](IC2NuclearControl-2.3.3a-Exist.jar) 
    UCHIJAAAA   iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCHIJAAAA   IronChest{6.0.62.742} [Iron Chest](ironchest-6.0.62.742.jar) 
    UCHIJAAAA   LotsOfFood{1.7.10} [Lots of Food](lots_of_food_1.7.10_v4.jar) 
    UCHIJAAAA   MCEF{0.6} [Minecraft Chromium Embedded Framework](mcef-1.7.10.jar) 
    UCHIJAAAA   millenaire{6.0.0} [MillГ©naire](millenaire-6.0.0.jar) 
    UCHIJAAAA   MineChess{1.3.8} [MineChess](MineChess-Mod-1.7.10.jar) 
    UCHIJAAAA   movillages{1.2.1} [Mo' Villages](mo-villages-mod-1.7.10-by-pigs_ftw.jar) 
    UCHIJAAAA   Morph{0.9.2} [Morph](Morph-Beta-0.9.2.jar) 
    UCHIJAAAA   cfm{3.4.8} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.81.7.10.jar) 
    UCHIJAAAA   Oceancraft{1.4.1} [Oceancraft](oceancraft_1.7.10_1.4.1.jar) 
    UCHIJAAAA   Portals{1.0.8} [Portals](Portals.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   MrTJPCoreMod{1.1.0.32} [MrTJPCore](MrTJPCore-1.7.10-1.1.0.32-universal.jar) 
    UCHIJAAAA   ProjRed|Core{4.7.0pre10.93} [ProjectRed Core](ProjectRed-1.7.10-4.7.0pre10.93-Base.jar) 
    UCHIJAAAA   ProjRed|Transmission{4.7.0pre10.93} [ProjectRed Transmission](ProjectRed-1.7.10-4.7.0pre10.93-Integration.jar) 
    UCHIJAAAA   ProjRed|Transportation{4.7.0pre10.93} [ProjectRed Transportation](ProjectRed-1.7.10-4.7.0pre10.93-Mechanical.jar) 
    UCHIJAAAA   ProjRed|Exploration{4.7.0pre10.93} [ProjectRed Exploration](ProjectRed-1.7.10-4.7.0pre10.93-World.jar) 
    UCHIJAAAA   ProjRed|Compatibility{4.7.0pre10.93} [ProjectRed Compatibility](ProjectRed-1.7.10-4.7.0pre10.93-Compat.jar) 
    UCHIJAAAA   ProjRed|Integration{4.7.0pre10.93} [ProjectRed Integration](ProjectRed-1.7.10-4.7.0pre10.93-Integration.jar) 
    UCHIJAAAA   ProjRed|Illumination{4.7.0pre10.93} [ProjectRed Illumination](ProjectRed-1.7.10-4.7.0pre10.93-Lighting.jar) 
    UCHIJAAAA   ProjRed|Expansion{4.7.0pre10.93} [ProjectRed Expansion](ProjectRed-1.7.10-4.7.0pre10.93-Mechanical.jar) 
    UCHIJAAAA   Railcraft{9.8.0.0} [Railcraft](Railcraft-9.8.0.0-client.jar) 
    UCHIJAAAA   bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    UCHIJAAAA   Treecapitator{1.7.10} [Treecapitator](Treecapitator-2.0.4.jar) 
    UCHIJAAAA   AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.10.jar) 
    UCHIJAAAA   worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   ForgeRelocation{0.0.1.4} [ForgeRelocation](ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
    UCHIJAAAA   MCFrames{1.0} [MCFrames](ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
    UCHIJAAAA   RelocationFMP{0.0.1.2} [RelocationFMP](ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    Launched Version: Forge 1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GT 640/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: Русский (Россия)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: On (2)
```

Исправьте эту штуку, с чем это связано?, я не хочу терять свой мир выживания.

**Comment by BlesseNtumble** [comment]
Перекачайте билд.
